// Reconstructed from the licensed GOG macOS 1.0.30000 captured Metal programs.
// Generated by tools/shader_reconstruction/shaderlab_generator.py.
// Original serialized Shader SHA256: d1248e723ee96ea85f49084a00b1edcfc591696a5bfab40b9ec0d766f61c6c31
// Properties, render states, texture samplers, and retained variants come from the original data.
// Extra keyword combinations select a captured variant; see batch-generation-manifest.json.
Shader "TextMeshPro/Sprite"
{
    Properties
    {
        _MainTex ("Sprite Texture", 2D) = "white" {}
        _Color ("Tint", Color) = (1, 1, 1, 1)
        _StencilComp ("Stencil Comparison", Float) = 8
        _Stencil ("Stencil ID", Float) = 0
        _StencilOp ("Stencil Operation", Float) = 0
        _StencilWriteMask ("Stencil Write Mask", Float) = 255
        _StencilReadMask ("Stencil Read Mask", Float) = 255
        _ColorMask ("Color Mask", Float) = 15
        _ClipRect ("Clip Rect", Vector) = (-10000, -10000, 10000, 10000)
        [Toggle(UNITY_UI_ALPHACLIP)] _UseUIAlphaClip ("Use Alpha Clip", Float) = 0
    }
    SubShader
    {
        Tags { "CanUseSpriteAtlas"="true" "IGNOREPROJECTOR"="true" "PreviewType"="Plane" "QUEUE"="Transparent" "RenderType"="Transparent" }
        Pass
        {
            Tags { "CanUseSpriteAtlas"="true" "IGNOREPROJECTOR"="true" "PreviewType"="Plane" "QUEUE"="Transparent" "RenderType"="Transparent" }
            Cull Off
            ZClip On
            ZTest [unity_GUIZTestMode]
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend SrcAlpha OneMinusSrcAlpha
            BlendOp Add
            ColorMask [_ColorMask]
            Stencil
            {
                Ref [_Stencil]
                ReadMask [_StencilReadMask]
                WriteMask [_StencilWriteMask]
                Comp [_StencilComp]
                Pass [_StencilOp]
                Fail Keep
                ZFail Keep
            }
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#pragma multi_compile __ UNITY_UI_ALPHACLIP
#if (defined(UNITY_UI_ALPHACLIP))
            // Original Metal program SHA256: vertex 790220c993b3154aacbeba524fe76ff798430a44d51e7b7d4d212c7f35f3893f; fragment 6249ce706e58b84788b012bf793e1d8b3898d8148e2e3b7c74d9ab630a460cf8.
#include "UnityCG.cginc"

float4 _ClipRect;

float4 _Color;

Texture2D<float4> _MainTex;

float4 _TextureSampleAdd;

SamplerState sampler_MainTex;



struct RV_790220c993b3_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_790220c993b3_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_790220c993b3_Output RecoveryVertex(RV_790220c993b3_Input input)
{
    RV_790220c993b3_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.COLOR0 = input.COLOR0 * _Color;
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    output.TEXCOORD1 = input.POSITION0;
    return output;
}



struct RF_6249ce706e58_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_6249ce706e58_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_6249ce706e58_Output RecoveryFragment(RF_6249ce706e58_Input input)
{
    RF_6249ce706e58_Output output;
    float4 u_xlat0;
    bool4 u_xlatb0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlatb0.xy = (input.TEXCOORD1.xy>=_ClipRect.xy);
    u_xlatb0.zw = (_ClipRect.zw>=input.TEXCOORD1.xy);
    u_xlat0 = ((((bool4)(u_xlatb0))) ? (float4(1.0, 1.0, 1.0, 1.0)) : (float4(0.0, 0.0, 0.0, 0.0)));
    u_xlat0.xy = u_xlat0.zw * u_xlat0.xy;
    u_xlat0.x = u_xlat0.y * u_xlat0.x;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat1 = u_xlat1 + _TextureSampleAdd;
    u_xlat1 = u_xlat1 * input.COLOR0;
    u_xlat2 = mad(u_xlat1.w, u_xlat0.x, -0.00100000005);
    u_xlat0.x = u_xlat0.x * u_xlat1.w;
    output.SV_Target0.xyz = u_xlat1.xyz;
    output.SV_Target0.w = u_xlat0.x;
    u_xlatb0.x = u_xlat2<0.0;
    if(((int(u_xlatb0.x) * int(0xffffffffu)))!=0){discard;}
    return output;
}

#else
            // Original Metal program SHA256: vertex 790220c993b3154aacbeba524fe76ff798430a44d51e7b7d4d212c7f35f3893f; fragment f83dc109d498e77d2d9a96301dc7deb0ea5b317e11885266d210c30a8528c27b.
#include "UnityCG.cginc"

float4 _ClipRect;

float4 _Color;

Texture2D<float4> _MainTex;

float4 _TextureSampleAdd;

SamplerState sampler_MainTex;



struct RV_790220c993b3_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_790220c993b3_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_790220c993b3_Output RecoveryVertex(RV_790220c993b3_Input input)
{
    RV_790220c993b3_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.COLOR0 = input.COLOR0 * _Color;
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    output.TEXCOORD1 = input.POSITION0;
    return output;
}



struct RF_f83dc109d498_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_f83dc109d498_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_f83dc109d498_Output RecoveryFragment(RF_f83dc109d498_Input input)
{
    RF_f83dc109d498_Output output;
    float4 u_xlat0;
    bool4 u_xlatb0;
    float4 u_xlat1;
    u_xlatb0.xy = (input.TEXCOORD1.xy>=_ClipRect.xy);
    u_xlatb0.zw = (_ClipRect.zw>=input.TEXCOORD1.xy);
    u_xlat0 = ((((bool4)(u_xlatb0))) ? (float4(1.0, 1.0, 1.0, 1.0)) : (float4(0.0, 0.0, 0.0, 0.0)));
    u_xlat0.xy = u_xlat0.zw * u_xlat0.xy;
    u_xlat0.x = u_xlat0.y * u_xlat0.x;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat1 = u_xlat1 + _TextureSampleAdd;
    u_xlat1 = u_xlat1 * input.COLOR0;
    output.SV_Target0.w = u_xlat0.x * u_xlat1.w;
    output.SV_Target0.xyz = u_xlat1.xyz;
    return output;
}

#endif
            ENDHLSL
        }
    }
}
