// Reconstructed from the licensed GOG macOS 1.0.30000 captured Metal programs.
// Generated by tools/shader_reconstruction/shaderlab_generator.py.
// Original serialized Shader SHA256: 788f62199de2449e7b8b863fe00f2a1b9d0341458f76e899b360587c267f6a6f
// Properties, render states, texture samplers, and retained variants come from the original data.
// Extra keyword combinations select a captured variant; see batch-generation-manifest.json.
Shader "TextMeshPro/Mobile/Distance Field Overlay"
{
    Properties
    {
        _FaceColor ("Face Color", Color) = (1, 1, 1, 1)
        _FaceDilate ("Face Dilate", Range(-1, 1)) = 0
        _OutlineColor ("Outline Color", Color) = (0, 0, 0, 1)
        _OutlineWidth ("Outline Thickness", Range(0, 1)) = 0
        _OutlineSoftness ("Outline Softness", Range(0, 1)) = 0
        _UnderlayColor ("Border Color", Color) = (0, 0, 0, 0.5)
        _UnderlayOffsetX ("Border OffsetX", Range(-1, 1)) = 0
        _UnderlayOffsetY ("Border OffsetY", Range(-1, 1)) = 0
        _UnderlayDilate ("Border Dilate", Range(-1, 1)) = 0
        _UnderlaySoftness ("Border Softness", Range(0, 1)) = 0
        _WeightNormal ("Weight Normal", Float) = 0
        _WeightBold ("Weight Bold", Float) = 0.5
        _ShaderFlags ("Flags", Float) = 0
        _ScaleRatioA ("Scale RatioA", Float) = 1
        _ScaleRatioB ("Scale RatioB", Float) = 1
        _ScaleRatioC ("Scale RatioC", Float) = 1
        _MainTex ("Font Atlas", 2D) = "white" {}
        _TextureWidth ("Texture Width", Float) = 512
        _TextureHeight ("Texture Height", Float) = 512
        _GradientScale ("Gradient Scale", Float) = 5
        _ScaleX ("Scale X", Float) = 1
        _ScaleY ("Scale Y", Float) = 1
        _PerspectiveFilter ("Perspective Correction", Range(0, 1)) = 0.875
        _VertexOffsetX ("Vertex OffsetX", Float) = 0
        _VertexOffsetY ("Vertex OffsetY", Float) = 0
        _ClipRect ("Clip Rect", Vector) = (-10000, -10000, 10000, 10000)
        _MaskSoftnessX ("Mask SoftnessX", Float) = 0
        _MaskSoftnessY ("Mask SoftnessY", Float) = 0
        _StencilComp ("Stencil Comparison", Float) = 8
        _Stencil ("Stencil ID", Float) = 0
        _StencilOp ("Stencil Operation", Float) = 0
        _StencilWriteMask ("Stencil Write Mask", Float) = 255
        _StencilReadMask ("Stencil Read Mask", Float) = 255
        _ColorMask ("Color Mask", Float) = 15
    }
    SubShader
    {
        Tags { "IGNOREPROJECTOR"="true" "QUEUE"="Overlay" "RenderType"="Transparent" }
        Pass
        {
            Tags { "IGNOREPROJECTOR"="true" "QUEUE"="Overlay" "RenderType"="Transparent" }
            Cull [_CullMode]
            ZClip On
            ZTest Always
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend One OneMinusSrcAlpha
            BlendOp Add
            ColorMask [_ColorMask]
            Stencil
            {
                Ref [_Stencil]
                ReadMask [_StencilReadMask]
                WriteMask [_StencilWriteMask]
                Comp [_StencilComp]
                Pass [_StencilOp]
                Fail Keep
                ZFail Keep
            }
            Fog { Mode Off }
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#if (1)
            // Original Metal program SHA256: vertex 3614bdafcdb4808f6cee878ac7b8c8a1d631fcff3fe3f7612fd6bd3ab4ca10b9; fragment 3b2266366c118d352e6b61c8e1d0d8e3bd107832ee4b7cce4cb42b4e66711c29.
#include "UnityCG.cginc"

float4 _ClipRect;

float4 _FaceColor;

float _FaceDilate;

float _GradientScale;

Texture2D<float4> _MainTex;

float _MaskSoftnessX;

float _MaskSoftnessY;

float4 _OutlineColor;

float _OutlineSoftness;

float _OutlineWidth;

float _PerspectiveFilter;

float _ScaleRatioA;

float _ScaleX;

float _ScaleY;

float _VertexOffsetX;

float _VertexOffsetY;

float _WeightBold;

float _WeightNormal;

SamplerState sampler_MainTex;



struct RV_3614bdafcdb4_Input
{
    float4 POSITION0 : POSITION0;
    float3 NORMAL0 : NORMAL0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RV_3614bdafcdb4_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float4 COLOR1 : COLOR1;
    float4 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
    float4 TEXCOORD2 : TEXCOORD2;
};

RV_3614bdafcdb4_Output RecoveryVertex(RV_3614bdafcdb4_Input input)
{
    RV_3614bdafcdb4_Output output;
    float2 u_xlat0;
    bool u_xlatb0;
    float4 u_xlat1;
    float4 u_xlat2;
    float4 u_xlat3;
    float4 u_xlat4;
    float u_xlat5;
    float2 u_xlat6;
    float u_xlat10;
    float u_xlat15;
    bool u_xlatb15;
    u_xlat0.xy = input.POSITION0.xy + float2(_VertexOffsetX, _VertexOffsetY);
    u_xlat1 = u_xlat0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat1 = mad(transpose(unity_ObjectToWorld)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat1);
    u_xlat2 = u_xlat1 + transpose(unity_ObjectToWorld)[3];
    u_xlat1.xyz = mad(transpose(unity_ObjectToWorld)[3].xyz, input.POSITION0.www, u_xlat1.xyz);
    u_xlat1.xyz = (-u_xlat1.xyz) + _WorldSpaceCameraPos.xyzx.xyz;
    u_xlat3 = u_xlat2.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat3 = mad(transpose(unity_MatrixVP)[0], u_xlat2.xxxx, u_xlat3);
    u_xlat3 = mad(transpose(unity_MatrixVP)[2], u_xlat2.zzzz, u_xlat3);
    u_xlat2 = mad(transpose(unity_MatrixVP)[3], u_xlat2.wwww, u_xlat3);
    output.mtl_Position = u_xlat2;
    u_xlat3 = input.COLOR0 * _FaceColor;
    u_xlat3.xyz = u_xlat3.www * u_xlat3.xyz;
    output.COLOR0 = u_xlat3;
    u_xlat10 = dot(u_xlat1.xyz, u_xlat1.xyz);
    u_xlat10 = rsqrt(u_xlat10);
    u_xlat1.xyz = ((float3)(u_xlat10)) * u_xlat1.xyz;
    u_xlat2.x = dot(input.NORMAL0.xyz, transpose(unity_WorldToObject)[0].xyz);
    u_xlat2.y = dot(input.NORMAL0.xyz, transpose(unity_WorldToObject)[1].xyz);
    u_xlat2.z = dot(input.NORMAL0.xyz, transpose(unity_WorldToObject)[2].xyz);
    u_xlat10 = dot(u_xlat2.xyz, u_xlat2.xyz);
    u_xlat10 = rsqrt(u_xlat10);
    u_xlat2.xyz = ((float3)(u_xlat10)) * u_xlat2.xyz;
    u_xlat10 = dot(u_xlat2.xyz, u_xlat1.xyz);
    u_xlat1.xy = _ScreenParams.yy * transpose(glstate_matrix_projection)[1].xy;
    u_xlat1.xy = mad(transpose(glstate_matrix_projection)[0].xy, _ScreenParams.xx, u_xlat1.xy);
    u_xlat1.xy = abs(u_xlat1.xy) * float2(_ScaleX, _ScaleY);
    u_xlat1.xy = u_xlat2.ww / u_xlat1.xy;
    u_xlat15 = dot(u_xlat1.xy, u_xlat1.xy);
    u_xlat1.xy = mad(float2(_MaskSoftnessX, _MaskSoftnessY), float2(0.25, 0.25), u_xlat1.xy);
    output.TEXCOORD2.zw = float2(0.25, 0.25) / u_xlat1.xy;
    u_xlat15 = rsqrt(u_xlat15);
    u_xlat1.x = abs(input.TEXCOORD1.y) * _GradientScale;
    u_xlat15 = u_xlat15 * u_xlat1.x;
    u_xlat1.x = u_xlat15 * 1.5;
    u_xlat6.x = (-_PerspectiveFilter) + 1.0;
    u_xlat6.x = u_xlat6.x * abs(u_xlat1.x);
    u_xlat15 = mad(u_xlat15, 1.5, (-u_xlat6.x));
    u_xlat10 = mad(abs(u_xlat10), u_xlat15, u_xlat6.x);
    u_xlatb15 = transpose(glstate_matrix_projection)[3].w==0.0;
    u_xlat10 = (u_xlatb15) ? u_xlat10 : u_xlat1.x;
    u_xlat1.xy = float2(_FaceDilate, _OutlineSoftness) * ((float2)(_ScaleRatioA));
    u_xlat15 = mad(u_xlat1.y, u_xlat10, 1.0);
    u_xlat2.x = u_xlat10 / u_xlat15;
    u_xlat10 = _OutlineWidth * _ScaleRatioA;
    u_xlat10 = u_xlat2.x * u_xlat10;
    u_xlat15 = min(u_xlat10, 1.0);
    u_xlat15 = sqrt(u_xlat15);
    u_xlat4.w = input.COLOR0.w * _OutlineColor.w;
    u_xlat4.xyz = u_xlat4.www * _OutlineColor.xyz;
    u_xlat4 = (-u_xlat3) + u_xlat4;
    output.COLOR1 = mad(((float4)(u_xlat15)), u_xlat4, u_xlat3);
    u_xlat3 = max(_ClipRect, float4(-2e+10, -2e+10, -2e+10, -2e+10));
    u_xlat3 = min(u_xlat3, float4(2e+10, 2e+10, 2e+10, 2e+10));
    u_xlat6.xy = u_xlat0.xy + (-u_xlat3.xy);
    u_xlat0.xy = mad(u_xlat0.xy, float2(2.0, 2.0), (-u_xlat3.xy));
    output.TEXCOORD2.xy = (-u_xlat3.zw) + u_xlat0.xy;
    u_xlat0.xy = (-u_xlat3.xy) + u_xlat3.zw;
    output.TEXCOORD0.zw = u_xlat6.xy / u_xlat0.xy;
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    u_xlatb0 = 0.0>=input.TEXCOORD1.y;
    u_xlat0.x = u_xlatb0 ? 1.0 : float(0.0);
    u_xlat5 = (-_WeightNormal) + _WeightBold;
    u_xlat0.x = mad(u_xlat0.x, u_xlat5, _WeightNormal);
    u_xlat0.x = u_xlat0.x / _GradientScale;
    u_xlat0.x = mad(u_xlat1.x, 0.5, u_xlat0.x);
    u_xlat0.x = (-u_xlat0.x) + 0.5;
    u_xlat2.w = mad(u_xlat0.x, u_xlat2.x, -0.5);
    output.TEXCOORD1.xw = u_xlat2.xw;
    output.TEXCOORD1.y = mad((-u_xlat10), 0.5, u_xlat2.w);
    output.TEXCOORD1.z = mad(u_xlat10, 0.5, u_xlat2.w);
    return output;
}



struct RF_3b2266366c11_Input
{
    float4 COLOR0 : COLOR0;
    float4 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
    float4 TEXCOORD2 : TEXCOORD2;
};

struct RF_3b2266366c11_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_3b2266366c11_Output RecoveryFragment(RF_3b2266366c11_Input input)
{
    RF_3b2266366c11_Output output;
    float2 u_xlat0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlat0.xy = (-_ClipRect.xy) + _ClipRect.zw;
    u_xlat0.xy = u_xlat0.xy + -abs(input.TEXCOORD2.xy);
    u_xlat0.xy = u_xlat0.xy * input.TEXCOORD2.zw;
    u_xlat0.xy = clamp(u_xlat0.xy, 0.0f, 1.0f);
    u_xlat0.x = u_xlat0.y * u_xlat0.x;
    u_xlat2 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy).w;
    u_xlat2 = mad(u_xlat2, input.TEXCOORD1.x, (-input.TEXCOORD1.w));
    u_xlat2 = clamp(u_xlat2, 0.0f, 1.0f);
    u_xlat1 = ((float4)(u_xlat2)) * input.COLOR0;
    output.SV_Target0 = u_xlat0.xxxx * u_xlat1;
    return output;
}

#endif
            ENDHLSL
        }
    }
    CustomEditor "TMProOld.EditorUtilities.TMP_SDFShaderGUI"
}
