// Reconstructed from the licensed GOG macOS 1.0.30000 captured Metal programs.
// Generated by tools/shader_reconstruction/shaderlab_generator.py.
// Original serialized Shader SHA256: 36747963fc927ad33b2f37e303798ed57dec627e763e15aad4f7cb04251906fc
// Properties, render states, texture samplers, and retained variants come from the original data.
// Extra keyword combinations select a captured variant; see batch-generation-manifest.json.
Shader "TextMeshPro/Distance Field"
{
    Properties
    {
        _FaceTex ("Face Texture", 2D) = "white" {}
        _FaceUVSpeedX ("Face UV Speed X", Range(-5, 5)) = 0
        _FaceUVSpeedY ("Face UV Speed Y", Range(-5, 5)) = 0
        _FaceColor ("Face Color", Color) = (1, 1, 1, 1)
        _FaceDilate ("Face Dilate", Range(-1, 1)) = 0
        _OutlineColor ("Outline Color", Color) = (0, 0, 0, 1)
        _OutlineTex ("Outline Texture", 2D) = "white" {}
        _OutlineUVSpeedX ("Outline UV Speed X", Range(-5, 5)) = 0
        _OutlineUVSpeedY ("Outline UV Speed Y", Range(-5, 5)) = 0
        _OutlineWidth ("Outline Thickness", Range(0, 1)) = 0
        _OutlineSoftness ("Outline Softness", Range(0, 1)) = 0
        _Bevel ("Bevel", Range(0, 1)) = 0.5
        _BevelOffset ("Bevel Offset", Range(-0.5, 0.5)) = 0
        _BevelWidth ("Bevel Width", Range(-0.5, 0.5)) = 0
        _BevelClamp ("Bevel Clamp", Range(0, 1)) = 0
        _BevelRoundness ("Bevel Roundness", Range(0, 1)) = 0
        _LightAngle ("Light Angle", Range(0, 6.28318548)) = 3.14159989
        _SpecularColor ("Specular", Color) = (1, 1, 1, 1)
        _SpecularPower ("Specular", Range(0, 4)) = 2
        _Reflectivity ("Reflectivity", Range(5, 15)) = 10
        _Diffuse ("Diffuse", Range(0, 1)) = 0.5
        _Ambient ("Ambient", Range(1, 0)) = 0.5
        _BumpMap ("Normal map", 2D) = "bump" {}
        _BumpOutline ("Bump Outline", Range(0, 1)) = 0
        _BumpFace ("Bump Face", Range(0, 1)) = 0
        _ReflectFaceColor ("Reflection Color", Color) = (0, 0, 0, 1)
        _ReflectOutlineColor ("Reflection Color", Color) = (0, 0, 0, 1)
        _Cube ("Reflection Cubemap", Cube) = "black" {}
        _EnvMatrixRotation ("Texture Rotation", Vector) = (0, 0, 0, 0)
        _UnderlayColor ("Border Color", Color) = (0, 0, 0, 0.5)
        _UnderlayOffsetX ("Border OffsetX", Range(-1, 1)) = 0
        _UnderlayOffsetY ("Border OffsetY", Range(-1, 1)) = 0
        _UnderlayDilate ("Border Dilate", Range(-1, 1)) = 0
        _UnderlaySoftness ("Border Softness", Range(0, 1)) = 0
        _GlowColor ("Color", Color) = (0, 1, 0, 0.5)
        _GlowOffset ("Offset", Range(-1, 1)) = 0
        _GlowInner ("Inner", Range(0, 1)) = 0.0500000007
        _GlowOuter ("Outer", Range(0, 1)) = 0.0500000007
        _GlowPower ("Falloff", Range(1, 0)) = 0.75
        _WeightNormal ("Weight Normal", Float) = 0
        _WeightBold ("Weight Bold", Float) = 0.5
        _ShaderFlags ("Flags", Float) = 0
        _ScaleRatioA ("Scale RatioA", Float) = 1
        _ScaleRatioB ("Scale RatioB", Float) = 1
        _ScaleRatioC ("Scale RatioC", Float) = 1
        _MainTex ("Font Atlas", 2D) = "white" {}
        _TextureWidth ("Texture Width", Float) = 512
        _TextureHeight ("Texture Height", Float) = 512
        _GradientScale ("Gradient Scale", Float) = 5
        _ScaleX ("Scale X", Float) = 1
        _ScaleY ("Scale Y", Float) = 1
        _PerspectiveFilter ("Perspective Correction", Range(0, 1)) = 0.875
        _VertexOffsetX ("Vertex OffsetX", Float) = 0
        _VertexOffsetY ("Vertex OffsetY", Float) = 0
        _MaskCoord ("Mask Coordinates", Vector) = (0, 0, 10000, 10000)
        _ClipRect ("Clip Rect", Vector) = (-10000, -10000, 10000, 10000)
        _MaskSoftnessX ("Mask SoftnessX", Float) = 0
        _MaskSoftnessY ("Mask SoftnessY", Float) = 0
        _StencilComp ("Stencil Comparison", Float) = 8
        _Stencil ("Stencil ID", Float) = 0
        _StencilOp ("Stencil Operation", Float) = 0
        _StencilWriteMask ("Stencil Write Mask", Float) = 255
        _StencilReadMask ("Stencil Read Mask", Float) = 255
        _ColorMask ("Color Mask", Float) = 15
    }
    SubShader
    {
        Tags { "IGNOREPROJECTOR"="true" "QUEUE"="Transparent" "RenderType"="Transparent" }
        Pass
        {
            Tags { "IGNOREPROJECTOR"="true" "QUEUE"="Transparent" "RenderType"="Transparent" }
            Cull [_CullMode]
            ZClip On
            ZTest [unity_GUIZTestMode]
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend One OneMinusSrcAlpha
            BlendOp Add
            ColorMask [_ColorMask]
            Stencil
            {
                Ref [_Stencil]
                ReadMask [_StencilReadMask]
                WriteMask [_StencilWriteMask]
                Comp [_StencilComp]
                Pass [_StencilOp]
                Fail Keep
                ZFail Keep
            }
            Fog { Mode Off }
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#pragma multi_compile __ GLOW_ON
#pragma multi_compile __ UNDERLAY_ON
#if (defined(GLOW_ON) && defined(UNDERLAY_ON))
            // Original Metal program SHA256: vertex 085e5b3b1055042e71eae85e3dba3e422326ae83db04a38e33fe9ddb3b8684c1; fragment 30f764111b4f164fda4f14611e763db499938dd7305f9ece85f004639dfd3401.
#include "UnityCG.cginc"

float4 _ClipRect;

float4x4 _EnvMatrix;

float4 _FaceColor;

float _FaceDilate;

Texture2D<float4> _FaceTex;

float _FaceUVSpeedX;

float _FaceUVSpeedY;

float4 _GlowColor;

float _GlowInner;

float _GlowOffset;

float _GlowOuter;

float _GlowPower;

float _GradientScale;

Texture2D<float4> _MainTex;

float _MaskSoftnessX;

float _MaskSoftnessY;

float4 _OutlineColor;

float _OutlineSoftness;

Texture2D<float4> _OutlineTex;

float _OutlineUVSpeedX;

float _OutlineUVSpeedY;

float _OutlineWidth;

float _PerspectiveFilter;

float _ScaleRatioA;

float _ScaleRatioB;

float _ScaleRatioC;

float _ScaleX;

float _ScaleY;

float _TextureHeight;

float _TextureWidth;

float4 _UnderlayColor;

float _UnderlayDilate;

float _UnderlayOffsetX;

float _UnderlayOffsetY;

float _UnderlaySoftness;

float _VertexOffsetX;

float _VertexOffsetY;

float _WeightBold;

float _WeightNormal;

SamplerState sampler_FaceTex;

SamplerState sampler_MainTex;

SamplerState sampler_OutlineTex;



struct RV_085e5b3b1055_Input
{
    float4 POSITION0 : POSITION0;
    float3 NORMAL0 : NORMAL0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RV_085e5b3b1055_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float4 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
    float4 TEXCOORD2 : TEXCOORD2;
    float3 TEXCOORD3 : TEXCOORD3;
    float4 TEXCOORD4 : TEXCOORD4;
    float4 COLOR1 : COLOR1;
};

RV_085e5b3b1055_Output RecoveryVertex(RV_085e5b3b1055_Input input)
{
    RV_085e5b3b1055_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float4 u_xlat3;
    float u_xlat4;
    float3 u_xlat6;
    float2 u_xlat8;
    float u_xlat12;
    float u_xlat13;
    bool u_xlatb13;
    u_xlat0.xy = input.POSITION0.xy + float2(_VertexOffsetX, _VertexOffsetY);
    u_xlat1 = u_xlat0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat1 = mad(transpose(unity_ObjectToWorld)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat1);
    u_xlat2 = u_xlat1 + transpose(unity_ObjectToWorld)[3];
    u_xlat1.xyz = mad(transpose(unity_ObjectToWorld)[3].xyz, input.POSITION0.www, u_xlat1.xyz);
    u_xlat1.xyz = (-u_xlat1.xyz) + _WorldSpaceCameraPos.xyzx.xyz;
    u_xlat3 = u_xlat2.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat3 = mad(transpose(unity_MatrixVP)[0], u_xlat2.xxxx, u_xlat3);
    u_xlat3 = mad(transpose(unity_MatrixVP)[2], u_xlat2.zzzz, u_xlat3);
    u_xlat2 = mad(transpose(unity_MatrixVP)[3], u_xlat2.wwww, u_xlat3);
    output.mtl_Position = u_xlat2;
    output.COLOR0 = input.COLOR0;
    u_xlat8.x = input.TEXCOORD1.x * 0.000244140625;
    u_xlat8.x = floor(u_xlat8.x);
    u_xlat8.y = mad((-u_xlat8.x), 4096.0, input.TEXCOORD1.x);
    output.TEXCOORD0.zw = u_xlat8.xy * float2(0.001953125, 0.001953125);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    u_xlat8.x = mad((-_OutlineWidth), _ScaleRatioA, 1.0);
    u_xlat8.x = mad((-_OutlineSoftness), _ScaleRatioA, u_xlat8.x);
    u_xlat12 = mad((-_GlowOffset), _ScaleRatioB, 1.0);
    u_xlat12 = mad((-_GlowOuter), _ScaleRatioB, u_xlat12);
    u_xlat8.x = min(u_xlat12, u_xlat8.x);
    u_xlat2.x = dot(input.NORMAL0.xyz, transpose(unity_WorldToObject)[0].xyz);
    u_xlat2.y = dot(input.NORMAL0.xyz, transpose(unity_WorldToObject)[1].xyz);
    u_xlat2.z = dot(input.NORMAL0.xyz, transpose(unity_WorldToObject)[2].xyz);
    u_xlat12 = dot(u_xlat2.xyz, u_xlat2.xyz);
    u_xlat12 = rsqrt(u_xlat12);
    u_xlat2.xyz = ((float3)(u_xlat12)) * u_xlat2.xyz;
    u_xlat12 = dot(u_xlat1.xyz, u_xlat1.xyz);
    u_xlat12 = rsqrt(u_xlat12);
    u_xlat3.xyz = ((float3)(u_xlat12)) * u_xlat1.xyz;
    u_xlat12 = dot(u_xlat2.xyz, u_xlat3.xyz);
    u_xlat2.xy = _ScreenParams.yy * transpose(glstate_matrix_projection)[1].xy;
    u_xlat2.xy = mad(transpose(glstate_matrix_projection)[0].xy, _ScreenParams.xx, u_xlat2.xy);
    u_xlat2.xy = abs(u_xlat2.xy) * float2(_ScaleX, _ScaleY);
    u_xlat2.xy = u_xlat2.ww / u_xlat2.xy;
    u_xlat13 = dot(u_xlat2.xy, u_xlat2.xy);
    u_xlat2.xy = mad(float2(_MaskSoftnessX, _MaskSoftnessY), float2(0.25, 0.25), u_xlat2.xy);
    output.TEXCOORD2.zw = float2(0.25, 0.25) / u_xlat2.xy;
    u_xlat13 = rsqrt(u_xlat13);
    u_xlat2.x = abs(input.TEXCOORD1.y) * _GradientScale;
    u_xlat13 = u_xlat13 * u_xlat2.x;
    u_xlat2.x = u_xlat13 * 1.5;
    u_xlat6.x = (-_PerspectiveFilter) + 1.0;
    u_xlat6.x = u_xlat6.x * abs(u_xlat2.x);
    u_xlat13 = mad(u_xlat13, 1.5, (-u_xlat6.x));
    u_xlat12 = mad(abs(u_xlat12), u_xlat13, u_xlat6.x);
    u_xlatb13 = transpose(glstate_matrix_projection)[3].w==0.0;
    u_xlat6.x = (u_xlatb13) ? u_xlat12 : u_xlat2.x;
    u_xlat12 = 0.5 / u_xlat6.x;
    u_xlat8.x = mad(u_xlat8.x, 0.5, (-u_xlat12));
    u_xlatb13 = 0.0>=input.TEXCOORD1.y;
    u_xlat13 = u_xlatb13 ? 1.0 : float(0.0);
    u_xlat2.x = (-_WeightNormal) + _WeightBold;
    u_xlat13 = mad(u_xlat13, u_xlat2.x, _WeightNormal);
    u_xlat13 = u_xlat13 / _GradientScale;
    u_xlat2.x = _FaceDilate * _ScaleRatioA;
    u_xlat6.z = mad(u_xlat2.x, 0.5, u_xlat13);
    output.TEXCOORD1.x = u_xlat8.x + (-u_xlat6.z);
    output.TEXCOORD1.yw = u_xlat6.xz;
    u_xlat8.x = (-u_xlat6.z) + 0.5;
    output.TEXCOORD1.z = u_xlat12 + u_xlat8.x;
    u_xlat3 = max(_ClipRect, float4(-2e+10, -2e+10, -2e+10, -2e+10));
    u_xlat3 = min(u_xlat3, float4(2e+10, 2e+10, 2e+10, 2e+10));
    u_xlat0.xy = mad(u_xlat0.xy, float2(2.0, 2.0), (-u_xlat3.xy));
    output.TEXCOORD2.xy = (-u_xlat3.zw) + u_xlat0.xy;
    u_xlat0.xyw = u_xlat1.yyy * transpose(_EnvMatrix)[1].xyz;
    u_xlat0.xyw = mad(transpose(_EnvMatrix)[0].xyz, u_xlat1.xxx, u_xlat0.xyw);
    output.TEXCOORD3.xyz = mad(transpose(_EnvMatrix)[2].xyz, u_xlat1.zzz, u_xlat0.xyw);
    u_xlat1 = float4(_UnderlaySoftness, _UnderlayDilate, _UnderlayOffsetX, _UnderlayOffsetY) * ((float4)(_ScaleRatioC));
    u_xlat0.x = mad(u_xlat1.x, u_xlat6.x, 1.0);
    u_xlat0.x = u_xlat6.x / u_xlat0.x;
    u_xlat4 = mad(u_xlat8.x, u_xlat0.x, -0.5);
    u_xlat8.x = u_xlat0.x * u_xlat1.y;
    u_xlat1.xy = (-u_xlat1.zw) * ((float2)(_GradientScale));
    u_xlat1.xy = u_xlat1.xy / float2(_TextureWidth, _TextureHeight);
    output.TEXCOORD4.xy = u_xlat1.xy + input.TEXCOORD0.xy;
    output.TEXCOORD4.z = u_xlat0.x;
    output.TEXCOORD4.w = mad((-u_xlat8.x), 0.5, u_xlat4);
    output.COLOR1.xyz = _UnderlayColor.www * _UnderlayColor.xyz;
    output.COLOR1.w = _UnderlayColor.w;
    return output;
}



struct RF_30f764111b4f_Input
{
    float4 COLOR0 : COLOR0;
    float4 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
    float4 TEXCOORD2 : TEXCOORD2;
    float4 TEXCOORD4 : TEXCOORD4;
    float4 COLOR1 : COLOR1;
};

struct RF_30f764111b4f_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_30f764111b4f_Output RecoveryFragment(RF_30f764111b4f_Input input)
{
    RF_30f764111b4f_Output output;
    float4 u_xlat0;
    float3 u_xlat1;
    float4 u_xlat2;
    float4 u_xlat3;
    float u_xlat4;
    float2 u_xlat5;
    bool u_xlatb5;
    float2 u_xlat9;
    float u_xlat13;
    u_xlat0.xy = mad(float2(_OutlineUVSpeedX, _OutlineUVSpeedY), _Time.yy, input.TEXCOORD0.zw);
    u_xlat0 = _OutlineTex.Sample(sampler_OutlineTex, u_xlat0.xy);
    u_xlat0 = u_xlat0 * _OutlineColor;
    u_xlat0.xyz = u_xlat0.www * u_xlat0.xyz;
    u_xlat1.xyz = input.COLOR0.xyz * _FaceColor.xyz;
    u_xlat2.xy = mad(float2(_FaceUVSpeedX, _FaceUVSpeedY), _Time.yy, input.TEXCOORD0.zw);
    u_xlat2 = _FaceTex.Sample(sampler_FaceTex, u_xlat2.xy);
    u_xlat1.xyz = u_xlat1.xyz * u_xlat2.xyz;
    u_xlat2.w = u_xlat2.w * _FaceColor.w;
    u_xlat2.xyz = u_xlat1.xyz * u_xlat2.www;
    u_xlat0 = u_xlat0 + (-u_xlat2);
    u_xlat1.x = _OutlineWidth * _ScaleRatioA;
    u_xlat1.x = u_xlat1.x * input.TEXCOORD1.y;
    u_xlat5.x = min(u_xlat1.x, 1.0);
    u_xlat1.x = u_xlat1.x * 0.5;
    u_xlat5.x = sqrt(u_xlat5.x);
    u_xlat9.x = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy).w;
    u_xlat5.y = (-u_xlat9.x) + input.TEXCOORD1.z;
    u_xlat13 = mad(u_xlat5.y, input.TEXCOORD1.y, u_xlat1.x);
    u_xlat13 = clamp(u_xlat13, 0.0f, 1.0f);
    u_xlat1.x = mad(u_xlat5.y, input.TEXCOORD1.y, (-u_xlat1.x));
    u_xlat5.x = u_xlat5.x * u_xlat13;
    u_xlat0 = mad(u_xlat5.xxxx, u_xlat0, u_xlat2);
    u_xlat5.x = _OutlineSoftness * _ScaleRatioA;
    u_xlat9.xy = u_xlat5.yx * input.TEXCOORD1.yy;
    u_xlat5.x = mad(u_xlat5.x, input.TEXCOORD1.y, 1.0);
    u_xlat1.x = mad(u_xlat9.y, 0.5, u_xlat1.x);
    u_xlat1.x = u_xlat1.x / u_xlat5.x;
    u_xlat1.x = clamp(u_xlat1.x, 0.0f, 1.0f);
    u_xlat1.x = (-u_xlat1.x) + 1.0;
    u_xlat2 = u_xlat0 * u_xlat1.xxxx;
    u_xlat0.x = mad((-u_xlat0.w), u_xlat1.x, 1.0);
    u_xlat4 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD4.xy).w;
    u_xlat4 = mad(u_xlat4, input.TEXCOORD4.z, (-input.TEXCOORD4.w));
    u_xlat4 = clamp(u_xlat4, 0.0f, 1.0f);
    u_xlat3 = ((float4)(u_xlat4)) * input.COLOR1;
    u_xlat0 = mad(u_xlat3, u_xlat0.xxxx, u_xlat2);
    u_xlat1.x = _GlowOffset * _ScaleRatioB;
    u_xlat1.x = u_xlat1.x * input.TEXCOORD1.y;
    u_xlat1.x = mad((-u_xlat1.x), 0.5, u_xlat9.x);
    u_xlatb5 = u_xlat1.x>=0.0;
    u_xlat5.x = u_xlatb5 ? 1.0 : float(0.0);
    u_xlat9.x = mad(_GlowOuter, _ScaleRatioB, (-_GlowInner));
    u_xlat5.x = mad(u_xlat5.x, u_xlat9.x, _GlowInner);
    u_xlat5.x = u_xlat5.x * input.TEXCOORD1.y;
    u_xlat9.x = mad(u_xlat5.x, 0.5, 1.0);
    u_xlat5.x = u_xlat5.x * 0.5;
    u_xlat5.x = min(u_xlat5.x, 1.0);
    u_xlat5.x = sqrt(u_xlat5.x);
    u_xlat1.x = u_xlat1.x / u_xlat9.x;
    u_xlat1.x = min(abs(u_xlat1.x), 1.0);
    u_xlat1.x = log2(u_xlat1.x);
    u_xlat1.x = u_xlat1.x * _GlowPower;
    u_xlat1.x = exp2(u_xlat1.x);
    u_xlat1.x = (-u_xlat1.x) + 1.0;
    u_xlat1.x = u_xlat5.x * u_xlat1.x;
    u_xlat1.x = dot(_GlowColor.ww, u_xlat1.xx);
    u_xlat1.x = clamp(u_xlat1.x, 0.0f, 1.0f);
    u_xlat0.xyz = mad(_GlowColor.xyz, u_xlat1.xxx, u_xlat0.xyz);
    u_xlat1.xy = (-_ClipRect.xy) + _ClipRect.zw;
    u_xlat1.xy = u_xlat1.xy + -abs(input.TEXCOORD2.xy);
    u_xlat1.xy = u_xlat1.xy * input.TEXCOORD2.zw;
    u_xlat1.xy = clamp(u_xlat1.xy, 0.0f, 1.0f);
    u_xlat1.x = u_xlat1.y * u_xlat1.x;
    u_xlat0 = u_xlat0 * u_xlat1.xxxx;
    output.SV_Target0 = u_xlat0 * input.COLOR0.wwww;
    return output;
}

#elif (!defined(GLOW_ON) && !defined(UNDERLAY_ON))
            // Original Metal program SHA256: vertex 40482df73e2ae1fec766b588c03e0ec53741720cadd21f76de9995ed730508e2; fragment 2cbedfae1d0eb84cb75f8d7017c54cef162677c88823dce77195923b65ae786e.
#include "UnityCG.cginc"

float4 _ClipRect;

float4x4 _EnvMatrix;

float4 _FaceColor;

float _FaceDilate;

Texture2D<float4> _FaceTex;

float _FaceUVSpeedX;

float _FaceUVSpeedY;

float _GradientScale;

Texture2D<float4> _MainTex;

float _MaskSoftnessX;

float _MaskSoftnessY;

float4 _OutlineColor;

float _OutlineSoftness;

Texture2D<float4> _OutlineTex;

float _OutlineUVSpeedX;

float _OutlineUVSpeedY;

float _OutlineWidth;

float _PerspectiveFilter;

float _ScaleRatioA;

float _ScaleX;

float _ScaleY;

float _VertexOffsetX;

float _VertexOffsetY;

float _WeightBold;

float _WeightNormal;

SamplerState sampler_FaceTex;

SamplerState sampler_MainTex;

SamplerState sampler_OutlineTex;



struct RV_40482df73e2a_Input
{
    float4 POSITION0 : POSITION0;
    float3 NORMAL0 : NORMAL0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RV_40482df73e2a_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float4 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
    float4 TEXCOORD2 : TEXCOORD2;
    float3 TEXCOORD3 : TEXCOORD3;
};

RV_40482df73e2a_Output RecoveryVertex(RV_40482df73e2a_Input input)
{
    RV_40482df73e2a_Output output;
    float3 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float4 u_xlat3;
    float3 u_xlat6;
    float2 u_xlat8;
    bool u_xlatb8;
    float u_xlat12;
    bool u_xlatb12;
    float u_xlat13;
    u_xlat0.xy = input.POSITION0.xy + float2(_VertexOffsetX, _VertexOffsetY);
    u_xlat1 = u_xlat0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat1 = mad(transpose(unity_ObjectToWorld)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat1);
    u_xlat2 = u_xlat1 + transpose(unity_ObjectToWorld)[3];
    u_xlat1.xyz = mad(transpose(unity_ObjectToWorld)[3].xyz, input.POSITION0.www, u_xlat1.xyz);
    u_xlat1.xyz = (-u_xlat1.xyz) + _WorldSpaceCameraPos.xyzx.xyz;
    u_xlat3 = u_xlat2.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat3 = mad(transpose(unity_MatrixVP)[0], u_xlat2.xxxx, u_xlat3);
    u_xlat3 = mad(transpose(unity_MatrixVP)[2], u_xlat2.zzzz, u_xlat3);
    u_xlat2 = mad(transpose(unity_MatrixVP)[3], u_xlat2.wwww, u_xlat3);
    output.mtl_Position = u_xlat2;
    output.COLOR0 = input.COLOR0;
    u_xlat8.x = input.TEXCOORD1.x * 0.000244140625;
    u_xlat8.x = floor(u_xlat8.x);
    u_xlat8.y = mad((-u_xlat8.x), 4096.0, input.TEXCOORD1.x);
    output.TEXCOORD0.zw = u_xlat8.xy * float2(0.001953125, 0.001953125);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    u_xlat2.x = dot(input.NORMAL0.xyz, transpose(unity_WorldToObject)[0].xyz);
    u_xlat2.y = dot(input.NORMAL0.xyz, transpose(unity_WorldToObject)[1].xyz);
    u_xlat2.z = dot(input.NORMAL0.xyz, transpose(unity_WorldToObject)[2].xyz);
    u_xlat8.x = dot(u_xlat2.xyz, u_xlat2.xyz);
    u_xlat8.x = rsqrt(u_xlat8.x);
    u_xlat2.xyz = u_xlat8.xxx * u_xlat2.xyz;
    u_xlat8.x = dot(u_xlat1.xyz, u_xlat1.xyz);
    u_xlat8.x = rsqrt(u_xlat8.x);
    u_xlat3.xyz = u_xlat8.xxx * u_xlat1.xyz;
    u_xlat8.x = dot(u_xlat2.xyz, u_xlat3.xyz);
    u_xlat2.xy = _ScreenParams.yy * transpose(glstate_matrix_projection)[1].xy;
    u_xlat2.xy = mad(transpose(glstate_matrix_projection)[0].xy, _ScreenParams.xx, u_xlat2.xy);
    u_xlat2.xy = abs(u_xlat2.xy) * float2(_ScaleX, _ScaleY);
    u_xlat2.xy = u_xlat2.ww / u_xlat2.xy;
    u_xlat12 = dot(u_xlat2.xy, u_xlat2.xy);
    u_xlat2.xy = mad(float2(_MaskSoftnessX, _MaskSoftnessY), float2(0.25, 0.25), u_xlat2.xy);
    output.TEXCOORD2.zw = float2(0.25, 0.25) / u_xlat2.xy;
    u_xlat12 = rsqrt(u_xlat12);
    u_xlat13 = abs(input.TEXCOORD1.y) * _GradientScale;
    u_xlat12 = u_xlat12 * u_xlat13;
    u_xlat13 = u_xlat12 * 1.5;
    u_xlat2.x = (-_PerspectiveFilter) + 1.0;
    u_xlat2.x = abs(u_xlat13) * u_xlat2.x;
    u_xlat12 = mad(u_xlat12, 1.5, (-u_xlat2.x));
    u_xlat8.x = mad(abs(u_xlat8.x), u_xlat12, u_xlat2.x);
    u_xlatb12 = transpose(glstate_matrix_projection)[3].w==0.0;
    u_xlat6.x = (u_xlatb12) ? u_xlat8.x : u_xlat13;
    u_xlatb8 = 0.0>=input.TEXCOORD1.y;
    u_xlat8.x = u_xlatb8 ? 1.0 : float(0.0);
    u_xlat12 = (-_WeightNormal) + _WeightBold;
    u_xlat8.x = mad(u_xlat8.x, u_xlat12, _WeightNormal);
    u_xlat8.x = u_xlat8.x / _GradientScale;
    u_xlat12 = _FaceDilate * _ScaleRatioA;
    u_xlat6.z = mad(u_xlat12, 0.5, u_xlat8.x);
    output.TEXCOORD1.yw = u_xlat6.xz;
    u_xlat8.x = 0.5 / u_xlat6.x;
    u_xlat12 = mad((-_OutlineWidth), _ScaleRatioA, 1.0);
    u_xlat12 = mad((-_OutlineSoftness), _ScaleRatioA, u_xlat12);
    u_xlat12 = mad(u_xlat12, 0.5, (-u_xlat8.x));
    output.TEXCOORD1.x = (-u_xlat6.z) + u_xlat12;
    u_xlat12 = (-u_xlat6.z) + 0.5;
    output.TEXCOORD1.z = u_xlat8.x + u_xlat12;
    u_xlat2 = max(_ClipRect, float4(-2e+10, -2e+10, -2e+10, -2e+10));
    u_xlat2 = min(u_xlat2, float4(2e+10, 2e+10, 2e+10, 2e+10));
    u_xlat0.xy = mad(u_xlat0.xy, float2(2.0, 2.0), (-u_xlat2.xy));
    output.TEXCOORD2.xy = (-u_xlat2.zw) + u_xlat0.xy;
    u_xlat0.xyz = u_xlat1.yyy * transpose(_EnvMatrix)[1].xyz;
    u_xlat0.xyz = mad(transpose(_EnvMatrix)[0].xyz, u_xlat1.xxx, u_xlat0.xyz);
    output.TEXCOORD3.xyz = mad(transpose(_EnvMatrix)[2].xyz, u_xlat1.zzz, u_xlat0.xyz);
    return output;
}



struct RF_2cbedfae1d0e_Input
{
    float4 COLOR0 : COLOR0;
    float4 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
    float4 TEXCOORD2 : TEXCOORD2;
};

struct RF_2cbedfae1d0e_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_2cbedfae1d0e_Output RecoveryFragment(RF_2cbedfae1d0e_Input input)
{
    RF_2cbedfae1d0e_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float3 u_xlat2;
    float4 u_xlat3;
    float u_xlat4;
    bool u_xlatb4;
    float2 u_xlat8;
    float u_xlat12;
    u_xlat0.x = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy).w;
    u_xlat4 = u_xlat0.x + (-input.TEXCOORD1.x);
    u_xlat0.x = (-u_xlat0.x) + input.TEXCOORD1.z;
    u_xlatb4 = u_xlat4<0.0;
    if(((int(u_xlatb4) * int(0xffffffffu)))!=0){discard;}
    u_xlat4 = _OutlineWidth * _ScaleRatioA;
    u_xlat4 = u_xlat4 * input.TEXCOORD1.y;
    u_xlat8.x = min(u_xlat4, 1.0);
    u_xlat4 = u_xlat4 * 0.5;
    u_xlat8.x = sqrt(u_xlat8.x);
    u_xlat12 = mad(u_xlat0.x, input.TEXCOORD1.y, u_xlat4);
    u_xlat12 = clamp(u_xlat12, 0.0f, 1.0f);
    u_xlat0.x = mad(u_xlat0.x, input.TEXCOORD1.y, (-u_xlat4));
    u_xlat4 = u_xlat8.x * u_xlat12;
    u_xlat8.xy = mad(float2(_OutlineUVSpeedX, _OutlineUVSpeedY), _Time.yy, input.TEXCOORD0.zw);
    u_xlat1 = _OutlineTex.Sample(sampler_OutlineTex, u_xlat8.xy);
    u_xlat1 = u_xlat1 * _OutlineColor;
    u_xlat1.xyz = u_xlat1.www * u_xlat1.xyz;
    u_xlat2.xyz = input.COLOR0.xyz * _FaceColor.xyz;
    u_xlat8.xy = mad(float2(_FaceUVSpeedX, _FaceUVSpeedY), _Time.yy, input.TEXCOORD0.zw);
    u_xlat3 = _FaceTex.Sample(sampler_FaceTex, u_xlat8.xy);
    u_xlat2.xyz = u_xlat2.xyz * u_xlat3.xyz;
    u_xlat3.w = u_xlat3.w * _FaceColor.w;
    u_xlat3.xyz = u_xlat2.xyz * u_xlat3.www;
    u_xlat1 = u_xlat1 + (-u_xlat3);
    u_xlat1 = mad(((float4)(u_xlat4)), u_xlat1, u_xlat3);
    u_xlat4 = _OutlineSoftness * _ScaleRatioA;
    u_xlat8.x = u_xlat4 * input.TEXCOORD1.y;
    u_xlat4 = mad(u_xlat4, input.TEXCOORD1.y, 1.0);
    u_xlat0.x = mad(u_xlat8.x, 0.5, u_xlat0.x);
    u_xlat0.x = u_xlat0.x / u_xlat4;
    u_xlat0.x = clamp(u_xlat0.x, 0.0f, 1.0f);
    u_xlat0.x = (-u_xlat0.x) + 1.0;
    u_xlat0 = u_xlat0.xxxx * u_xlat1;
    u_xlat1.xy = (-_ClipRect.xy) + _ClipRect.zw;
    u_xlat1.xy = u_xlat1.xy + -abs(input.TEXCOORD2.xy);
    u_xlat1.xy = u_xlat1.xy * input.TEXCOORD2.zw;
    u_xlat1.xy = clamp(u_xlat1.xy, 0.0f, 1.0f);
    u_xlat1.x = u_xlat1.y * u_xlat1.x;
    u_xlat0 = u_xlat0 * u_xlat1.xxxx;
    output.SV_Target0 = u_xlat0 * input.COLOR0.wwww;
    return output;
}

#elif (!defined(GLOW_ON) && defined(UNDERLAY_ON))
            // Original Metal program SHA256: vertex a46bcbe2699f5abf9c16b74f1104419bba4f1fb773494ebffa6966b772c96607; fragment 7c54a05c073787b85e403568afe61d72b825ce57fdf2f7cc7aede9ddf51b45e1.
#include "UnityCG.cginc"

float4 _ClipRect;

float4x4 _EnvMatrix;

float4 _FaceColor;

float _FaceDilate;

Texture2D<float4> _FaceTex;

float _FaceUVSpeedX;

float _FaceUVSpeedY;

float _GradientScale;

Texture2D<float4> _MainTex;

float _MaskSoftnessX;

float _MaskSoftnessY;

float4 _OutlineColor;

float _OutlineSoftness;

Texture2D<float4> _OutlineTex;

float _OutlineUVSpeedX;

float _OutlineUVSpeedY;

float _OutlineWidth;

float _PerspectiveFilter;

float _ScaleRatioA;

float _ScaleRatioC;

float _ScaleX;

float _ScaleY;

float _TextureHeight;

float _TextureWidth;

float4 _UnderlayColor;

float _UnderlayDilate;

float _UnderlayOffsetX;

float _UnderlayOffsetY;

float _UnderlaySoftness;

float _VertexOffsetX;

float _VertexOffsetY;

float _WeightBold;

float _WeightNormal;

SamplerState sampler_FaceTex;

SamplerState sampler_MainTex;

SamplerState sampler_OutlineTex;



struct RV_a46bcbe2699f_Input
{
    float4 POSITION0 : POSITION0;
    float3 NORMAL0 : NORMAL0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RV_a46bcbe2699f_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float4 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
    float4 TEXCOORD2 : TEXCOORD2;
    float3 TEXCOORD3 : TEXCOORD3;
    float4 TEXCOORD4 : TEXCOORD4;
    float4 COLOR1 : COLOR1;
};

RV_a46bcbe2699f_Output RecoveryVertex(RV_a46bcbe2699f_Input input)
{
    RV_a46bcbe2699f_Output output;
    float3 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float4 u_xlat3;
    float u_xlat4;
    float3 u_xlat6;
    float2 u_xlat8;
    bool u_xlatb8;
    float u_xlat12;
    bool u_xlatb12;
    float u_xlat13;
    u_xlat0.xy = input.POSITION0.xy + float2(_VertexOffsetX, _VertexOffsetY);
    u_xlat1 = u_xlat0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat1 = mad(transpose(unity_ObjectToWorld)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat1);
    u_xlat2 = u_xlat1 + transpose(unity_ObjectToWorld)[3];
    u_xlat1.xyz = mad(transpose(unity_ObjectToWorld)[3].xyz, input.POSITION0.www, u_xlat1.xyz);
    u_xlat1.xyz = (-u_xlat1.xyz) + _WorldSpaceCameraPos.xyzx.xyz;
    u_xlat3 = u_xlat2.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat3 = mad(transpose(unity_MatrixVP)[0], u_xlat2.xxxx, u_xlat3);
    u_xlat3 = mad(transpose(unity_MatrixVP)[2], u_xlat2.zzzz, u_xlat3);
    u_xlat2 = mad(transpose(unity_MatrixVP)[3], u_xlat2.wwww, u_xlat3);
    output.mtl_Position = u_xlat2;
    output.COLOR0 = input.COLOR0;
    u_xlat8.x = input.TEXCOORD1.x * 0.000244140625;
    u_xlat8.x = floor(u_xlat8.x);
    u_xlat8.y = mad((-u_xlat8.x), 4096.0, input.TEXCOORD1.x);
    output.TEXCOORD0.zw = u_xlat8.xy * float2(0.001953125, 0.001953125);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    u_xlat2.x = dot(input.NORMAL0.xyz, transpose(unity_WorldToObject)[0].xyz);
    u_xlat2.y = dot(input.NORMAL0.xyz, transpose(unity_WorldToObject)[1].xyz);
    u_xlat2.z = dot(input.NORMAL0.xyz, transpose(unity_WorldToObject)[2].xyz);
    u_xlat8.x = dot(u_xlat2.xyz, u_xlat2.xyz);
    u_xlat8.x = rsqrt(u_xlat8.x);
    u_xlat2.xyz = u_xlat8.xxx * u_xlat2.xyz;
    u_xlat8.x = dot(u_xlat1.xyz, u_xlat1.xyz);
    u_xlat8.x = rsqrt(u_xlat8.x);
    u_xlat3.xyz = u_xlat8.xxx * u_xlat1.xyz;
    u_xlat8.x = dot(u_xlat2.xyz, u_xlat3.xyz);
    u_xlat2.xy = _ScreenParams.yy * transpose(glstate_matrix_projection)[1].xy;
    u_xlat2.xy = mad(transpose(glstate_matrix_projection)[0].xy, _ScreenParams.xx, u_xlat2.xy);
    u_xlat2.xy = abs(u_xlat2.xy) * float2(_ScaleX, _ScaleY);
    u_xlat2.xy = u_xlat2.ww / u_xlat2.xy;
    u_xlat12 = dot(u_xlat2.xy, u_xlat2.xy);
    u_xlat2.xy = mad(float2(_MaskSoftnessX, _MaskSoftnessY), float2(0.25, 0.25), u_xlat2.xy);
    output.TEXCOORD2.zw = float2(0.25, 0.25) / u_xlat2.xy;
    u_xlat12 = rsqrt(u_xlat12);
    u_xlat13 = abs(input.TEXCOORD1.y) * _GradientScale;
    u_xlat12 = u_xlat12 * u_xlat13;
    u_xlat13 = u_xlat12 * 1.5;
    u_xlat2.x = (-_PerspectiveFilter) + 1.0;
    u_xlat2.x = abs(u_xlat13) * u_xlat2.x;
    u_xlat12 = mad(u_xlat12, 1.5, (-u_xlat2.x));
    u_xlat8.x = mad(abs(u_xlat8.x), u_xlat12, u_xlat2.x);
    u_xlatb12 = transpose(glstate_matrix_projection)[3].w==0.0;
    u_xlat6.x = (u_xlatb12) ? u_xlat8.x : u_xlat13;
    u_xlatb8 = 0.0>=input.TEXCOORD1.y;
    u_xlat8.x = u_xlatb8 ? 1.0 : float(0.0);
    u_xlat12 = (-_WeightNormal) + _WeightBold;
    u_xlat8.x = mad(u_xlat8.x, u_xlat12, _WeightNormal);
    u_xlat8.x = u_xlat8.x / _GradientScale;
    u_xlat12 = _FaceDilate * _ScaleRatioA;
    u_xlat6.z = mad(u_xlat12, 0.5, u_xlat8.x);
    output.TEXCOORD1.yw = u_xlat6.xz;
    u_xlat8.x = 0.5 / u_xlat6.x;
    u_xlat12 = mad((-_OutlineWidth), _ScaleRatioA, 1.0);
    u_xlat12 = mad((-_OutlineSoftness), _ScaleRatioA, u_xlat12);
    u_xlat12 = mad(u_xlat12, 0.5, (-u_xlat8.x));
    output.TEXCOORD1.x = (-u_xlat6.z) + u_xlat12;
    u_xlat12 = (-u_xlat6.z) + 0.5;
    output.TEXCOORD1.z = u_xlat8.x + u_xlat12;
    u_xlat3 = max(_ClipRect, float4(-2e+10, -2e+10, -2e+10, -2e+10));
    u_xlat3 = min(u_xlat3, float4(2e+10, 2e+10, 2e+10, 2e+10));
    u_xlat0.xy = mad(u_xlat0.xy, float2(2.0, 2.0), (-u_xlat3.xy));
    output.TEXCOORD2.xy = (-u_xlat3.zw) + u_xlat0.xy;
    u_xlat0.xyz = u_xlat1.yyy * transpose(_EnvMatrix)[1].xyz;
    u_xlat0.xyz = mad(transpose(_EnvMatrix)[0].xyz, u_xlat1.xxx, u_xlat0.xyz);
    output.TEXCOORD3.xyz = mad(transpose(_EnvMatrix)[2].xyz, u_xlat1.zzz, u_xlat0.xyz);
    u_xlat1 = float4(_UnderlaySoftness, _UnderlayDilate, _UnderlayOffsetX, _UnderlayOffsetY) * ((float4)(_ScaleRatioC));
    u_xlat0.x = mad(u_xlat1.x, u_xlat6.x, 1.0);
    u_xlat0.x = u_xlat6.x / u_xlat0.x;
    u_xlat4 = mad(u_xlat12, u_xlat0.x, -0.5);
    u_xlat8.x = u_xlat0.x * u_xlat1.y;
    u_xlat1.xy = (-u_xlat1.zw) * ((float2)(_GradientScale));
    u_xlat1.xy = u_xlat1.xy / float2(_TextureWidth, _TextureHeight);
    output.TEXCOORD4.xy = u_xlat1.xy + input.TEXCOORD0.xy;
    output.TEXCOORD4.z = u_xlat0.x;
    output.TEXCOORD4.w = mad((-u_xlat8.x), 0.5, u_xlat4);
    output.COLOR1.xyz = _UnderlayColor.www * _UnderlayColor.xyz;
    output.COLOR1.w = _UnderlayColor.w;
    return output;
}



struct RF_7c54a05c0737_Input
{
    float4 COLOR0 : COLOR0;
    float4 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
    float4 TEXCOORD2 : TEXCOORD2;
    float4 TEXCOORD4 : TEXCOORD4;
    float4 COLOR1 : COLOR1;
};

struct RF_7c54a05c0737_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_7c54a05c0737_Output RecoveryFragment(RF_7c54a05c0737_Input input)
{
    RF_7c54a05c0737_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float u_xlat3;
    float u_xlat4;
    float u_xlat7;
    float u_xlat10;
    u_xlat0.xy = mad(float2(_OutlineUVSpeedX, _OutlineUVSpeedY), _Time.yy, input.TEXCOORD0.zw);
    u_xlat0 = _OutlineTex.Sample(sampler_OutlineTex, u_xlat0.xy);
    u_xlat0 = u_xlat0 * _OutlineColor;
    u_xlat0.xyz = u_xlat0.www * u_xlat0.xyz;
    u_xlat1.xyz = input.COLOR0.xyz * _FaceColor.xyz;
    u_xlat2.xy = mad(float2(_FaceUVSpeedX, _FaceUVSpeedY), _Time.yy, input.TEXCOORD0.zw);
    u_xlat2 = _FaceTex.Sample(sampler_FaceTex, u_xlat2.xy);
    u_xlat1.xyz = u_xlat1.xyz * u_xlat2.xyz;
    u_xlat2.w = u_xlat2.w * _FaceColor.w;
    u_xlat2.xyz = u_xlat1.xyz * u_xlat2.www;
    u_xlat0 = u_xlat0 + (-u_xlat2);
    u_xlat1.x = _OutlineWidth * _ScaleRatioA;
    u_xlat1.x = u_xlat1.x * input.TEXCOORD1.y;
    u_xlat4 = min(u_xlat1.x, 1.0);
    u_xlat1.x = u_xlat1.x * 0.5;
    u_xlat4 = sqrt(u_xlat4);
    u_xlat7 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy).w;
    u_xlat7 = (-u_xlat7) + input.TEXCOORD1.z;
    u_xlat10 = mad(u_xlat7, input.TEXCOORD1.y, u_xlat1.x);
    u_xlat10 = clamp(u_xlat10, 0.0f, 1.0f);
    u_xlat1.x = mad(u_xlat7, input.TEXCOORD1.y, (-u_xlat1.x));
    u_xlat4 = u_xlat4 * u_xlat10;
    u_xlat0 = mad(((float4)(u_xlat4)), u_xlat0, u_xlat2);
    u_xlat4 = _OutlineSoftness * _ScaleRatioA;
    u_xlat7 = u_xlat4 * input.TEXCOORD1.y;
    u_xlat4 = mad(u_xlat4, input.TEXCOORD1.y, 1.0);
    u_xlat1.x = mad(u_xlat7, 0.5, u_xlat1.x);
    u_xlat1.x = u_xlat1.x / u_xlat4;
    u_xlat1.x = clamp(u_xlat1.x, 0.0f, 1.0f);
    u_xlat1.x = (-u_xlat1.x) + 1.0;
    u_xlat2 = u_xlat0 * u_xlat1.xxxx;
    u_xlat0.x = mad((-u_xlat0.w), u_xlat1.x, 1.0);
    u_xlat3 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD4.xy).w;
    u_xlat3 = mad(u_xlat3, input.TEXCOORD4.z, (-input.TEXCOORD4.w));
    u_xlat3 = clamp(u_xlat3, 0.0f, 1.0f);
    u_xlat1 = ((float4)(u_xlat3)) * input.COLOR1;
    u_xlat0 = mad(u_xlat1, u_xlat0.xxxx, u_xlat2);
    u_xlat1.xy = (-_ClipRect.xy) + _ClipRect.zw;
    u_xlat1.xy = u_xlat1.xy + -abs(input.TEXCOORD2.xy);
    u_xlat1.xy = u_xlat1.xy * input.TEXCOORD2.zw;
    u_xlat1.xy = clamp(u_xlat1.xy, 0.0f, 1.0f);
    u_xlat1.x = u_xlat1.y * u_xlat1.x;
    u_xlat0 = u_xlat0 * u_xlat1.xxxx;
    output.SV_Target0 = u_xlat0 * input.COLOR0.wwww;
    return output;
}

#else
            // Original Metal program SHA256: vertex f412afe1ae1a396879f681452ab4d06aff6989542a248cfe082ea7d622b0f268; fragment 26a75d1d15465b448d501353517b75fa15fee884241403750ddfa22482f99887.
#include "UnityCG.cginc"

float4 _ClipRect;

float4x4 _EnvMatrix;

float4 _FaceColor;

float _FaceDilate;

Texture2D<float4> _FaceTex;

float _FaceUVSpeedX;

float _FaceUVSpeedY;

float4 _GlowColor;

float _GlowInner;

float _GlowOffset;

float _GlowOuter;

float _GlowPower;

float _GradientScale;

Texture2D<float4> _MainTex;

float _MaskSoftnessX;

float _MaskSoftnessY;

float4 _OutlineColor;

float _OutlineSoftness;

Texture2D<float4> _OutlineTex;

float _OutlineUVSpeedX;

float _OutlineUVSpeedY;

float _OutlineWidth;

float _PerspectiveFilter;

float _ScaleRatioA;

float _ScaleRatioB;

float _ScaleX;

float _ScaleY;

float _VertexOffsetX;

float _VertexOffsetY;

float _WeightBold;

float _WeightNormal;

SamplerState sampler_FaceTex;

SamplerState sampler_MainTex;

SamplerState sampler_OutlineTex;



struct RV_f412afe1ae1a_Input
{
    float4 POSITION0 : POSITION0;
    float3 NORMAL0 : NORMAL0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RV_f412afe1ae1a_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float4 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
    float4 TEXCOORD2 : TEXCOORD2;
    float3 TEXCOORD3 : TEXCOORD3;
};

RV_f412afe1ae1a_Output RecoveryVertex(RV_f412afe1ae1a_Input input)
{
    RV_f412afe1ae1a_Output output;
    float3 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float4 u_xlat3;
    float3 u_xlat6;
    float2 u_xlat8;
    bool u_xlatb8;
    float u_xlat12;
    bool u_xlatb12;
    float u_xlat13;
    u_xlat0.xy = input.POSITION0.xy + float2(_VertexOffsetX, _VertexOffsetY);
    u_xlat1 = u_xlat0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat1 = mad(transpose(unity_ObjectToWorld)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat1);
    u_xlat2 = u_xlat1 + transpose(unity_ObjectToWorld)[3];
    u_xlat1.xyz = mad(transpose(unity_ObjectToWorld)[3].xyz, input.POSITION0.www, u_xlat1.xyz);
    u_xlat1.xyz = (-u_xlat1.xyz) + _WorldSpaceCameraPos.xyzx.xyz;
    u_xlat3 = u_xlat2.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat3 = mad(transpose(unity_MatrixVP)[0], u_xlat2.xxxx, u_xlat3);
    u_xlat3 = mad(transpose(unity_MatrixVP)[2], u_xlat2.zzzz, u_xlat3);
    u_xlat2 = mad(transpose(unity_MatrixVP)[3], u_xlat2.wwww, u_xlat3);
    output.mtl_Position = u_xlat2;
    output.COLOR0 = input.COLOR0;
    u_xlat8.x = input.TEXCOORD1.x * 0.000244140625;
    u_xlat8.x = floor(u_xlat8.x);
    u_xlat8.y = mad((-u_xlat8.x), 4096.0, input.TEXCOORD1.x);
    output.TEXCOORD0.zw = u_xlat8.xy * float2(0.001953125, 0.001953125);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    u_xlat2.x = dot(input.NORMAL0.xyz, transpose(unity_WorldToObject)[0].xyz);
    u_xlat2.y = dot(input.NORMAL0.xyz, transpose(unity_WorldToObject)[1].xyz);
    u_xlat2.z = dot(input.NORMAL0.xyz, transpose(unity_WorldToObject)[2].xyz);
    u_xlat8.x = dot(u_xlat2.xyz, u_xlat2.xyz);
    u_xlat8.x = rsqrt(u_xlat8.x);
    u_xlat2.xyz = u_xlat8.xxx * u_xlat2.xyz;
    u_xlat8.x = dot(u_xlat1.xyz, u_xlat1.xyz);
    u_xlat8.x = rsqrt(u_xlat8.x);
    u_xlat3.xyz = u_xlat8.xxx * u_xlat1.xyz;
    u_xlat8.x = dot(u_xlat2.xyz, u_xlat3.xyz);
    u_xlat2.xy = _ScreenParams.yy * transpose(glstate_matrix_projection)[1].xy;
    u_xlat2.xy = mad(transpose(glstate_matrix_projection)[0].xy, _ScreenParams.xx, u_xlat2.xy);
    u_xlat2.xy = abs(u_xlat2.xy) * float2(_ScaleX, _ScaleY);
    u_xlat2.xy = u_xlat2.ww / u_xlat2.xy;
    u_xlat12 = dot(u_xlat2.xy, u_xlat2.xy);
    u_xlat2.xy = mad(float2(_MaskSoftnessX, _MaskSoftnessY), float2(0.25, 0.25), u_xlat2.xy);
    output.TEXCOORD2.zw = float2(0.25, 0.25) / u_xlat2.xy;
    u_xlat12 = rsqrt(u_xlat12);
    u_xlat13 = abs(input.TEXCOORD1.y) * _GradientScale;
    u_xlat12 = u_xlat12 * u_xlat13;
    u_xlat13 = u_xlat12 * 1.5;
    u_xlat2.x = (-_PerspectiveFilter) + 1.0;
    u_xlat2.x = abs(u_xlat13) * u_xlat2.x;
    u_xlat12 = mad(u_xlat12, 1.5, (-u_xlat2.x));
    u_xlat8.x = mad(abs(u_xlat8.x), u_xlat12, u_xlat2.x);
    u_xlatb12 = transpose(glstate_matrix_projection)[3].w==0.0;
    u_xlat6.x = (u_xlatb12) ? u_xlat8.x : u_xlat13;
    u_xlatb8 = 0.0>=input.TEXCOORD1.y;
    u_xlat8.x = u_xlatb8 ? 1.0 : float(0.0);
    u_xlat12 = (-_WeightNormal) + _WeightBold;
    u_xlat8.x = mad(u_xlat8.x, u_xlat12, _WeightNormal);
    u_xlat8.x = u_xlat8.x / _GradientScale;
    u_xlat12 = _FaceDilate * _ScaleRatioA;
    u_xlat6.z = mad(u_xlat12, 0.5, u_xlat8.x);
    output.TEXCOORD1.yw = u_xlat6.xz;
    u_xlat8.x = 0.5 / u_xlat6.x;
    u_xlat12 = mad((-_OutlineWidth), _ScaleRatioA, 1.0);
    u_xlat12 = mad((-_OutlineSoftness), _ScaleRatioA, u_xlat12);
    u_xlat13 = mad((-_GlowOffset), _ScaleRatioB, 1.0);
    u_xlat13 = mad((-_GlowOuter), _ScaleRatioB, u_xlat13);
    u_xlat12 = min(u_xlat12, u_xlat13);
    u_xlat12 = mad(u_xlat12, 0.5, (-u_xlat8.x));
    output.TEXCOORD1.x = (-u_xlat6.z) + u_xlat12;
    u_xlat12 = (-u_xlat6.z) + 0.5;
    output.TEXCOORD1.z = u_xlat8.x + u_xlat12;
    u_xlat2 = max(_ClipRect, float4(-2e+10, -2e+10, -2e+10, -2e+10));
    u_xlat2 = min(u_xlat2, float4(2e+10, 2e+10, 2e+10, 2e+10));
    u_xlat0.xy = mad(u_xlat0.xy, float2(2.0, 2.0), (-u_xlat2.xy));
    output.TEXCOORD2.xy = (-u_xlat2.zw) + u_xlat0.xy;
    u_xlat0.xyz = u_xlat1.yyy * transpose(_EnvMatrix)[1].xyz;
    u_xlat0.xyz = mad(transpose(_EnvMatrix)[0].xyz, u_xlat1.xxx, u_xlat0.xyz);
    output.TEXCOORD3.xyz = mad(transpose(_EnvMatrix)[2].xyz, u_xlat1.zzz, u_xlat0.xyz);
    return output;
}



struct RF_26a75d1d1546_Input
{
    float4 COLOR0 : COLOR0;
    float4 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
    float4 TEXCOORD2 : TEXCOORD2;
};

struct RF_26a75d1d1546_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_26a75d1d1546_Output RecoveryFragment(RF_26a75d1d1546_Input input)
{
    RF_26a75d1d1546_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float3 u_xlat3;
    bool u_xlatb3;
    float u_xlat6;
    float u_xlat9;
    u_xlat0.x = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy).w;
    u_xlat3.x = u_xlat0.x + (-input.TEXCOORD1.x);
    u_xlat0.x = (-u_xlat0.x) + input.TEXCOORD1.z;
    u_xlatb3 = u_xlat3.x<0.0;
    if(((int(u_xlatb3) * int(0xffffffffu)))!=0){discard;}
    u_xlat3.xy = mad(float2(_OutlineUVSpeedX, _OutlineUVSpeedY), _Time.yy, input.TEXCOORD0.zw);
    u_xlat1 = _OutlineTex.Sample(sampler_OutlineTex, u_xlat3.xy);
    u_xlat1 = u_xlat1 * _OutlineColor;
    u_xlat1.xyz = u_xlat1.www * u_xlat1.xyz;
    u_xlat3.xyz = input.COLOR0.xyz * _FaceColor.xyz;
    u_xlat2.xy = mad(float2(_FaceUVSpeedX, _FaceUVSpeedY), _Time.yy, input.TEXCOORD0.zw);
    u_xlat2 = _FaceTex.Sample(sampler_FaceTex, u_xlat2.xy);
    u_xlat3.xyz = u_xlat3.xyz * u_xlat2.xyz;
    u_xlat2.w = u_xlat2.w * _FaceColor.w;
    u_xlat2.xyz = u_xlat3.xyz * u_xlat2.www;
    u_xlat1 = u_xlat1 + (-u_xlat2);
    u_xlat3.x = _OutlineWidth * _ScaleRatioA;
    u_xlat3.x = u_xlat3.x * input.TEXCOORD1.y;
    u_xlat6 = min(u_xlat3.x, 1.0);
    u_xlat3.x = u_xlat3.x * 0.5;
    u_xlat6 = sqrt(u_xlat6);
    u_xlat9 = mad(u_xlat0.x, input.TEXCOORD1.y, u_xlat3.x);
    u_xlat9 = clamp(u_xlat9, 0.0f, 1.0f);
    u_xlat3.x = mad(u_xlat0.x, input.TEXCOORD1.y, (-u_xlat3.x));
    u_xlat6 = u_xlat6 * u_xlat9;
    u_xlat1 = mad(((float4)(u_xlat6)), u_xlat1, u_xlat2);
    u_xlat0.z = _OutlineSoftness * _ScaleRatioA;
    u_xlat0.xw = u_xlat0.xz * input.TEXCOORD1.yy;
    u_xlat6 = mad(u_xlat0.z, input.TEXCOORD1.y, 1.0);
    u_xlat3.x = mad(u_xlat0.w, 0.5, u_xlat3.x);
    u_xlat3.x = u_xlat3.x / u_xlat6;
    u_xlat3.x = clamp(u_xlat3.x, 0.0f, 1.0f);
    u_xlat3.x = (-u_xlat3.x) + 1.0;
    u_xlat1 = u_xlat3.xxxx * u_xlat1;
    u_xlat3.x = _GlowOffset * _ScaleRatioB;
    u_xlat3.x = u_xlat3.x * input.TEXCOORD1.y;
    u_xlat0.x = mad((-u_xlat3.x), 0.5, u_xlat0.x);
    u_xlatb3 = u_xlat0.x>=0.0;
    u_xlat3.x = u_xlatb3 ? 1.0 : float(0.0);
    u_xlat6 = mad(_GlowOuter, _ScaleRatioB, (-_GlowInner));
    u_xlat3.x = mad(u_xlat3.x, u_xlat6, _GlowInner);
    u_xlat3.x = u_xlat3.x * input.TEXCOORD1.y;
    u_xlat6 = mad(u_xlat3.x, 0.5, 1.0);
    u_xlat3.x = u_xlat3.x * 0.5;
    u_xlat3.x = min(u_xlat3.x, 1.0);
    u_xlat3.x = sqrt(u_xlat3.x);
    u_xlat0.x = u_xlat0.x / u_xlat6;
    u_xlat0.x = min(abs(u_xlat0.x), 1.0);
    u_xlat0.x = log2(u_xlat0.x);
    u_xlat0.x = u_xlat0.x * _GlowPower;
    u_xlat0.x = exp2(u_xlat0.x);
    u_xlat0.x = (-u_xlat0.x) + 1.0;
    u_xlat0.x = u_xlat3.x * u_xlat0.x;
    u_xlat0.x = dot(_GlowColor.ww, u_xlat0.xx);
    u_xlat0.x = clamp(u_xlat0.x, 0.0f, 1.0f);
    u_xlat1.xyz = mad(_GlowColor.xyz, u_xlat0.xxx, u_xlat1.xyz);
    u_xlat0.xy = (-_ClipRect.xy) + _ClipRect.zw;
    u_xlat0.xy = u_xlat0.xy + -abs(input.TEXCOORD2.xy);
    u_xlat0.xy = u_xlat0.xy * input.TEXCOORD2.zw;
    u_xlat0.xy = clamp(u_xlat0.xy, 0.0f, 1.0f);
    u_xlat0.x = u_xlat0.y * u_xlat0.x;
    u_xlat0 = u_xlat0.xxxx * u_xlat1;
    output.SV_Target0 = u_xlat0 * input.COLOR0.wwww;
    return output;
}

#endif
            ENDHLSL
        }
    }
    Fallback "TextMeshPro/Mobile/Distance Field"
    CustomEditor "TMProOld.EditorUtilities.TMP_SDFShaderGUI"
}
