// Reconstructed from the licensed GOG macOS 1.0.30000 captured Metal programs.
// Generated by tools/shader_reconstruction/shaderlab_generator.py.
// Original serialized Shader SHA256: 5a663a3b49185cfb96bf00f33dfea125021647efe28feef256d0ab6138ef10e5
// Properties, render states, texture samplers, and retained variants come from the original data.
// Extra keyword combinations select a captured variant; see batch-generation-manifest.json.
Shader "UI/Blur/UIBlur Camera"
{
    Properties
    {
        _MainTex ("Base (RGB)", 2D) = "white" {}
        _Size ("Spacing", Range(0, 200)) = 5
        _Vibrancy ("Vibrancy", Range(0, 2)) = 0.200000003
        [Toggle(USE_MASK)] _UseMask ("Use Mask", Float) = 0
        _MaskLerp ("Mask Lerp", Range(0, 1)) = 1
        _Mask ("Mask", 2D) = "white" {}
    }
    SubShader
    {
        Pass
        {
            Name "VERTICAL"
            Tags { "LIGHTMODE"="ALWAYS" }
            Cull Off
            ZClip On
            ZTest Off
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend One Zero
            BlendOp Add
            ColorMask RGBA
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#pragma multi_compile __ USE_MASK
#if (!defined(USE_MASK))
            // Original Metal program SHA256: vertex 33e08d1304667188776ce4403e1ba75e4d847c2ee12955ac463f44443feeeddd; fragment baa80d99728a37f5f347832e33af626c0f59774207b3502cc0ab4d8e0e9b1130.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

float _Size;

SamplerState sampler_MainTex;



struct RV_33e08d130466_Input
{
    float4 POSITION0 : POSITION0;
};

struct RV_33e08d130466_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 TEXCOORD0 : TEXCOORD0;
};

RV_33e08d130466_Output RecoveryVertex(RV_33e08d130466_Input input)
{
    RV_33e08d130466_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.mtl_Position = u_xlat0;
    u_xlat0.xy = mad(u_xlat0.xy, float2(1.0, -1.0), u_xlat0.ww);
    output.TEXCOORD0.zw = u_xlat0.zw;
    output.TEXCOORD0.xy = u_xlat0.xy * float2(0.5, 0.5);
    return output;
}



struct RF_baa80d99728a_Input
{
    float4 TEXCOORD0 : TEXCOORD0;
};

struct RF_baa80d99728a_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_baa80d99728a_Output RecoveryFragment(RF_baa80d99728a_Input input)
{
    RF_baa80d99728a_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float4 u_xlat3;
    u_xlat0.xz = input.TEXCOORD0.xx;
    u_xlat1.x = _MainTex_TexelSize.y * _Size;
    u_xlat2 = mad(u_xlat1.xxxx, float4(-6.44000006, -3.22000003, -4.82999992, -1.61000001), input.TEXCOORD0.yyyy);
    u_xlat1 = mad(u_xlat1.xxxx, float4(1.61000001, 4.82999992, 3.22000003, 6.44000006), input.TEXCOORD0.yyyy);
    u_xlat0.yw = u_xlat2.xz;
    u_xlat0 = u_xlat0 / input.TEXCOORD0.wwww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat0.zw);
    u_xlat0 = _MainTex.Sample(sampler_MainTex, u_xlat0.xy);
    u_xlat3 = u_xlat3 * float4(0.0900000036, 0.0900000036, 0.0900000036, 0.0900000036);
    u_xlat0 = mad(u_xlat0, float4(0.0500000007, 0.0500000007, 0.0500000007, 0.0500000007), u_xlat3);
    u_xlat2.xz = input.TEXCOORD0.xx;
    u_xlat2 = u_xlat2 / input.TEXCOORD0.wwww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat2.xy);
    u_xlat2 = _MainTex.Sample(sampler_MainTex, u_xlat2.zw);
    u_xlat0 = mad(u_xlat3, float4(0.119999997, 0.119999997, 0.119999997, 0.119999997), u_xlat0);
    u_xlat0 = mad(u_xlat2, float4(0.150000006, 0.150000006, 0.150000006, 0.150000006), u_xlat0);
    u_xlat2.xy = input.TEXCOORD0.xy / input.TEXCOORD0.ww;
    u_xlat2 = _MainTex.Sample(sampler_MainTex, u_xlat2.xy);
    u_xlat0 = mad(u_xlat2, float4(0.180000007, 0.180000007, 0.180000007, 0.180000007), u_xlat0);
    u_xlat2.yw = u_xlat1.xz;
    u_xlat2.xz = input.TEXCOORD0.xx;
    u_xlat2 = u_xlat2 / input.TEXCOORD0.wwww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat2.xy);
    u_xlat2 = _MainTex.Sample(sampler_MainTex, u_xlat2.zw);
    u_xlat0 = mad(u_xlat3, float4(0.150000006, 0.150000006, 0.150000006, 0.150000006), u_xlat0);
    u_xlat0 = mad(u_xlat2, float4(0.119999997, 0.119999997, 0.119999997, 0.119999997), u_xlat0);
    u_xlat1.xz = input.TEXCOORD0.xx;
    u_xlat1 = u_xlat1 / input.TEXCOORD0.wwww;
    u_xlat2 = _MainTex.Sample(sampler_MainTex, u_xlat1.xy);
    u_xlat1 = _MainTex.Sample(sampler_MainTex, u_xlat1.zw);
    u_xlat0 = mad(u_xlat2, float4(0.0900000036, 0.0900000036, 0.0900000036, 0.0900000036), u_xlat0);
    output.SV_Target0 = mad(u_xlat1, float4(0.0500000007, 0.0500000007, 0.0500000007, 0.0500000007), u_xlat0);
    return output;
}

#else
            // Original Metal program SHA256: vertex e1fa8462e3444c6a651fd04a9ccc5451d5ee7e04920ed80c01c35d6eb9f5677a; fragment 9873e30908616c8491c223577680b735b24edce7ebd43c3cd9828f0902ec9aa6.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

Texture2D<float4> _Mask;

float _MaskLerp;

float4 _Mask_ST;

float _Size;

SamplerState sampler_MainTex;

SamplerState sampler_Mask;



struct RV_e1fa8462e344_Input
{
    float4 POSITION0 : POSITION0;
};

struct RV_e1fa8462e344_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_e1fa8462e344_Output RecoveryVertex(RV_e1fa8462e344_Input input)
{
    RV_e1fa8462e344_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.mtl_Position = u_xlat0;
    u_xlat0.xy = mad(u_xlat0.xy, float2(1.0, -1.0), u_xlat0.ww);
    u_xlat0.xy = u_xlat0.xy * float2(0.5, 0.5);
    output.TEXCOORD0.xy = mad(u_xlat0.xy, _Mask_ST.xy, _Mask_ST.zw);
    output.TEXCOORD1 = u_xlat0;
    return output;
}



struct RF_9873e3090861_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_9873e3090861_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_9873e3090861_Output RecoveryFragment(RF_9873e3090861_Input input)
{
    RF_9873e3090861_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float4 u_xlat3;
    u_xlat0.x = _Mask.Sample(sampler_Mask, input.TEXCOORD0.xy).x;
    u_xlat0.x = mad(_Size, u_xlat0.x, (-_Size));
    u_xlat0.x = mad(_MaskLerp, u_xlat0.x, _Size);
    u_xlat0.x = u_xlat0.x * _MainTex_TexelSize.y;
    u_xlat1 = mad(u_xlat0.xxxx, float4(-6.44000006, -3.22000003, -4.82999992, -1.61000001), input.TEXCOORD1.yyyy);
    u_xlat0 = mad(u_xlat0.xxxx, float4(1.61000001, 4.82999992, 3.22000003, 6.44000006), input.TEXCOORD1.yyyy);
    u_xlat2.yw = u_xlat1.xz;
    u_xlat2.xz = input.TEXCOORD1.xx;
    u_xlat2 = u_xlat2 / input.TEXCOORD1.wwww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat2.zw);
    u_xlat2 = _MainTex.Sample(sampler_MainTex, u_xlat2.xy);
    u_xlat3 = u_xlat3 * float4(0.0900000036, 0.0900000036, 0.0900000036, 0.0900000036);
    u_xlat2 = mad(u_xlat2, float4(0.0500000007, 0.0500000007, 0.0500000007, 0.0500000007), u_xlat3);
    u_xlat1.xz = input.TEXCOORD1.xx;
    u_xlat1 = u_xlat1 / input.TEXCOORD1.wwww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat1.xy);
    u_xlat1 = _MainTex.Sample(sampler_MainTex, u_xlat1.zw);
    u_xlat2 = mad(u_xlat3, float4(0.119999997, 0.119999997, 0.119999997, 0.119999997), u_xlat2);
    u_xlat1 = mad(u_xlat1, float4(0.150000006, 0.150000006, 0.150000006, 0.150000006), u_xlat2);
    u_xlat2.xy = input.TEXCOORD1.xy / input.TEXCOORD1.ww;
    u_xlat2 = _MainTex.Sample(sampler_MainTex, u_xlat2.xy);
    u_xlat1 = mad(u_xlat2, float4(0.180000007, 0.180000007, 0.180000007, 0.180000007), u_xlat1);
    u_xlat2.yw = u_xlat0.xz;
    u_xlat2.xz = input.TEXCOORD1.xx;
    u_xlat2 = u_xlat2 / input.TEXCOORD1.wwww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat2.xy);
    u_xlat2 = _MainTex.Sample(sampler_MainTex, u_xlat2.zw);
    u_xlat1 = mad(u_xlat3, float4(0.150000006, 0.150000006, 0.150000006, 0.150000006), u_xlat1);
    u_xlat1 = mad(u_xlat2, float4(0.119999997, 0.119999997, 0.119999997, 0.119999997), u_xlat1);
    u_xlat0.xz = input.TEXCOORD1.xx;
    u_xlat0 = u_xlat0 / input.TEXCOORD1.wwww;
    u_xlat2 = _MainTex.Sample(sampler_MainTex, u_xlat0.xy);
    u_xlat0 = _MainTex.Sample(sampler_MainTex, u_xlat0.zw);
    u_xlat1 = mad(u_xlat2, float4(0.0900000036, 0.0900000036, 0.0900000036, 0.0900000036), u_xlat1);
    output.SV_Target0 = mad(u_xlat0, float4(0.0500000007, 0.0500000007, 0.0500000007, 0.0500000007), u_xlat1);
    return output;
}

#endif
            ENDHLSL
        }
        Pass
        {
            Name "HORIZONTAL"
            Tags { "LIGHTMODE"="ALWAYS" }
            Cull Off
            ZClip On
            ZTest Off
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend One Zero
            BlendOp Add
            ColorMask RGBA
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#pragma multi_compile __ USE_MASK
#if (!defined(USE_MASK))
            // Original Metal program SHA256: vertex 33e08d1304667188776ce4403e1ba75e4d847c2ee12955ac463f44443feeeddd; fragment 0c464fc6d1c17d76cc21a58615245907a49fbc0183213314a58c2fafb0f05eb5.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

float _Size;

SamplerState sampler_MainTex;



struct RV_33e08d130466_Input
{
    float4 POSITION0 : POSITION0;
};

struct RV_33e08d130466_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 TEXCOORD0 : TEXCOORD0;
};

RV_33e08d130466_Output RecoveryVertex(RV_33e08d130466_Input input)
{
    RV_33e08d130466_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.mtl_Position = u_xlat0;
    u_xlat0.xy = mad(u_xlat0.xy, float2(1.0, -1.0), u_xlat0.ww);
    output.TEXCOORD0.zw = u_xlat0.zw;
    output.TEXCOORD0.xy = u_xlat0.xy * float2(0.5, 0.5);
    return output;
}



struct RF_0c464fc6d1c1_Input
{
    float4 TEXCOORD0 : TEXCOORD0;
};

struct RF_0c464fc6d1c1_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_0c464fc6d1c1_Output RecoveryFragment(RF_0c464fc6d1c1_Input input)
{
    RF_0c464fc6d1c1_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float4 u_xlat3;
    u_xlat0.yw = input.TEXCOORD0.yy;
    u_xlat1.x = _MainTex_TexelSize.x * _Size;
    u_xlat2 = mad(u_xlat1.xxxx, float4(-3.22000003, -6.44000006, -1.61000001, -4.82999992), input.TEXCOORD0.xxxx);
    u_xlat1 = mad(u_xlat1.xxxx, float4(4.82999992, 1.61000001, 6.44000006, 3.22000003), input.TEXCOORD0.xxxx);
    u_xlat0.xz = u_xlat2.yw;
    u_xlat0 = u_xlat0 / input.TEXCOORD0.wwww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat0.zw);
    u_xlat0 = _MainTex.Sample(sampler_MainTex, u_xlat0.xy);
    u_xlat3 = u_xlat3 * float4(0.0900000036, 0.0900000036, 0.0900000036, 0.0900000036);
    u_xlat0 = mad(u_xlat0, float4(0.0500000007, 0.0500000007, 0.0500000007, 0.0500000007), u_xlat3);
    u_xlat2.yw = input.TEXCOORD0.yy;
    u_xlat2 = u_xlat2 / input.TEXCOORD0.wwww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat2.xy);
    u_xlat2 = _MainTex.Sample(sampler_MainTex, u_xlat2.zw);
    u_xlat0 = mad(u_xlat3, float4(0.119999997, 0.119999997, 0.119999997, 0.119999997), u_xlat0);
    u_xlat0 = mad(u_xlat2, float4(0.150000006, 0.150000006, 0.150000006, 0.150000006), u_xlat0);
    u_xlat2.xy = input.TEXCOORD0.xy / input.TEXCOORD0.ww;
    u_xlat2 = _MainTex.Sample(sampler_MainTex, u_xlat2.xy);
    u_xlat0 = mad(u_xlat2, float4(0.180000007, 0.180000007, 0.180000007, 0.180000007), u_xlat0);
    u_xlat2.xz = u_xlat1.yw;
    u_xlat2.yw = input.TEXCOORD0.yy;
    u_xlat2 = u_xlat2 / input.TEXCOORD0.wwww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat2.xy);
    u_xlat2 = _MainTex.Sample(sampler_MainTex, u_xlat2.zw);
    u_xlat0 = mad(u_xlat3, float4(0.150000006, 0.150000006, 0.150000006, 0.150000006), u_xlat0);
    u_xlat0 = mad(u_xlat2, float4(0.119999997, 0.119999997, 0.119999997, 0.119999997), u_xlat0);
    u_xlat1.yw = input.TEXCOORD0.yy;
    u_xlat1 = u_xlat1 / input.TEXCOORD0.wwww;
    u_xlat2 = _MainTex.Sample(sampler_MainTex, u_xlat1.xy);
    u_xlat1 = _MainTex.Sample(sampler_MainTex, u_xlat1.zw);
    u_xlat0 = mad(u_xlat2, float4(0.0900000036, 0.0900000036, 0.0900000036, 0.0900000036), u_xlat0);
    output.SV_Target0 = mad(u_xlat1, float4(0.0500000007, 0.0500000007, 0.0500000007, 0.0500000007), u_xlat0);
    return output;
}

#else
            // Original Metal program SHA256: vertex e1fa8462e3444c6a651fd04a9ccc5451d5ee7e04920ed80c01c35d6eb9f5677a; fragment d86aa2b28930f0ec5035638c4e9b14189273646daf2cad35ed786cfeb6a7a39e.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

Texture2D<float4> _Mask;

float _MaskLerp;

float4 _Mask_ST;

float _Size;

SamplerState sampler_MainTex;

SamplerState sampler_Mask;



struct RV_e1fa8462e344_Input
{
    float4 POSITION0 : POSITION0;
};

struct RV_e1fa8462e344_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_e1fa8462e344_Output RecoveryVertex(RV_e1fa8462e344_Input input)
{
    RV_e1fa8462e344_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.mtl_Position = u_xlat0;
    u_xlat0.xy = mad(u_xlat0.xy, float2(1.0, -1.0), u_xlat0.ww);
    u_xlat0.xy = u_xlat0.xy * float2(0.5, 0.5);
    output.TEXCOORD0.xy = mad(u_xlat0.xy, _Mask_ST.xy, _Mask_ST.zw);
    output.TEXCOORD1 = u_xlat0;
    return output;
}



struct RF_d86aa2b28930_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_d86aa2b28930_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_d86aa2b28930_Output RecoveryFragment(RF_d86aa2b28930_Input input)
{
    RF_d86aa2b28930_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float4 u_xlat3;
    u_xlat0.x = _Mask.Sample(sampler_Mask, input.TEXCOORD0.xy).x;
    u_xlat0.x = mad(_Size, u_xlat0.x, (-_Size));
    u_xlat0.x = mad(_MaskLerp, u_xlat0.x, _Size);
    u_xlat0.x = u_xlat0.x * _MainTex_TexelSize.x;
    u_xlat1 = mad(u_xlat0.xxxx, float4(-3.22000003, -6.44000006, -1.61000001, -4.82999992), input.TEXCOORD1.xxxx);
    u_xlat0 = mad(u_xlat0.xxxx, float4(4.82999992, 1.61000001, 6.44000006, 3.22000003), input.TEXCOORD1.xxxx);
    u_xlat2.xz = u_xlat1.yw;
    u_xlat2.yw = input.TEXCOORD1.yy;
    u_xlat2 = u_xlat2 / input.TEXCOORD1.wwww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat2.zw);
    u_xlat2 = _MainTex.Sample(sampler_MainTex, u_xlat2.xy);
    u_xlat3 = u_xlat3 * float4(0.0900000036, 0.0900000036, 0.0900000036, 0.0900000036);
    u_xlat2 = mad(u_xlat2, float4(0.0500000007, 0.0500000007, 0.0500000007, 0.0500000007), u_xlat3);
    u_xlat1.yw = input.TEXCOORD1.yy;
    u_xlat1 = u_xlat1 / input.TEXCOORD1.wwww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat1.xy);
    u_xlat1 = _MainTex.Sample(sampler_MainTex, u_xlat1.zw);
    u_xlat2 = mad(u_xlat3, float4(0.119999997, 0.119999997, 0.119999997, 0.119999997), u_xlat2);
    u_xlat1 = mad(u_xlat1, float4(0.150000006, 0.150000006, 0.150000006, 0.150000006), u_xlat2);
    u_xlat2.xy = input.TEXCOORD1.xy / input.TEXCOORD1.ww;
    u_xlat2 = _MainTex.Sample(sampler_MainTex, u_xlat2.xy);
    u_xlat1 = mad(u_xlat2, float4(0.180000007, 0.180000007, 0.180000007, 0.180000007), u_xlat1);
    u_xlat2.xz = u_xlat0.yw;
    u_xlat2.yw = input.TEXCOORD1.yy;
    u_xlat2 = u_xlat2 / input.TEXCOORD1.wwww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat2.xy);
    u_xlat2 = _MainTex.Sample(sampler_MainTex, u_xlat2.zw);
    u_xlat1 = mad(u_xlat3, float4(0.150000006, 0.150000006, 0.150000006, 0.150000006), u_xlat1);
    u_xlat1 = mad(u_xlat2, float4(0.119999997, 0.119999997, 0.119999997, 0.119999997), u_xlat1);
    u_xlat0.yw = input.TEXCOORD1.yy;
    u_xlat0 = u_xlat0 / input.TEXCOORD1.wwww;
    u_xlat2 = _MainTex.Sample(sampler_MainTex, u_xlat0.xy);
    u_xlat0 = _MainTex.Sample(sampler_MainTex, u_xlat0.zw);
    u_xlat1 = mad(u_xlat2, float4(0.0900000036, 0.0900000036, 0.0900000036, 0.0900000036), u_xlat1);
    output.SV_Target0 = mad(u_xlat0, float4(0.0500000007, 0.0500000007, 0.0500000007, 0.0500000007), u_xlat1);
    return output;
}

#endif
            ENDHLSL
        }
        Pass
        {
            Name "VERTICAL"
            Tags { "LIGHTMODE"="ALWAYS" }
            Cull Off
            ZClip On
            ZTest Off
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend One Zero
            BlendOp Add
            ColorMask RGBA
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#pragma multi_compile __ USE_MASK
#if (!defined(USE_MASK))
            // Original Metal program SHA256: vertex 33e08d1304667188776ce4403e1ba75e4d847c2ee12955ac463f44443feeeddd; fragment 1e6ceea3a081564c9f60eb9df4fc565ee79f59d730332d87de6c64a901ca3b79.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

float _Size;

SamplerState sampler_MainTex;



struct RV_33e08d130466_Input
{
    float4 POSITION0 : POSITION0;
};

struct RV_33e08d130466_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 TEXCOORD0 : TEXCOORD0;
};

RV_33e08d130466_Output RecoveryVertex(RV_33e08d130466_Input input)
{
    RV_33e08d130466_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.mtl_Position = u_xlat0;
    u_xlat0.xy = mad(u_xlat0.xy, float2(1.0, -1.0), u_xlat0.ww);
    output.TEXCOORD0.zw = u_xlat0.zw;
    output.TEXCOORD0.xy = u_xlat0.xy * float2(0.5, 0.5);
    return output;
}



struct RF_1e6ceea3a081_Input
{
    float4 TEXCOORD0 : TEXCOORD0;
};

struct RF_1e6ceea3a081_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_1e6ceea3a081_Output RecoveryFragment(RF_1e6ceea3a081_Input input)
{
    RF_1e6ceea3a081_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float4 u_xlat3;
    float4 u_xlat4;
    float2 u_xlat6;
    u_xlat0.xz = input.TEXCOORD0.xx;
    u_xlat1.x = _MainTex_TexelSize.y * _Size;
    u_xlat2 = mad(u_xlat1.xxxx, float4(-4.0, 3.0, -3.0, -2.0), input.TEXCOORD0.yyyy);
    u_xlat0.yw = u_xlat2.xz;
    u_xlat0 = u_xlat0 / input.TEXCOORD0.wwww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat0.zw);
    u_xlat0 = _MainTex.Sample(sampler_MainTex, u_xlat0.xy);
    u_xlat3 = u_xlat3 * float4(0.0900000036, 0.0900000036, 0.0900000036, 0.0900000036);
    u_xlat0 = mad(u_xlat0, float4(0.0500000007, 0.0500000007, 0.0500000007, 0.0500000007), u_xlat3);
    u_xlat3.y = u_xlat2.w;
    u_xlat3.xz = input.TEXCOORD0.xx;
    u_xlat6.xy = u_xlat3.xy / input.TEXCOORD0.ww;
    u_xlat4 = _MainTex.Sample(sampler_MainTex, u_xlat6.xy);
    u_xlat0 = mad(u_xlat4, float4(0.119999997, 0.119999997, 0.119999997, 0.119999997), u_xlat0);
    u_xlat3.w = mad((-_MainTex_TexelSize.y), _Size, input.TEXCOORD0.y);
    u_xlat6.xy = u_xlat3.zw / input.TEXCOORD0.ww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat6.xy);
    u_xlat0 = mad(u_xlat3, float4(0.150000006, 0.150000006, 0.150000006, 0.150000006), u_xlat0);
    u_xlat6.xy = input.TEXCOORD0.xy / input.TEXCOORD0.ww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat6.xy);
    u_xlat0 = mad(u_xlat3, float4(0.180000007, 0.180000007, 0.180000007, 0.180000007), u_xlat0);
    u_xlat3.y = mad(_MainTex_TexelSize.y, _Size, input.TEXCOORD0.y);
    u_xlat3.xz = input.TEXCOORD0.xx;
    u_xlat6.xy = u_xlat3.xy / input.TEXCOORD0.ww;
    u_xlat4 = _MainTex.Sample(sampler_MainTex, u_xlat6.xy);
    u_xlat0 = mad(u_xlat4, float4(0.150000006, 0.150000006, 0.150000006, 0.150000006), u_xlat0);
    u_xlat3.w = mad(u_xlat1.x, 2.0, input.TEXCOORD0.y);
    u_xlat2.w = mad(u_xlat1.x, 4.0, input.TEXCOORD0.y);
    u_xlat1.xy = u_xlat3.zw / input.TEXCOORD0.ww;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, u_xlat1.xy);
    u_xlat0 = mad(u_xlat1, float4(0.119999997, 0.119999997, 0.119999997, 0.119999997), u_xlat0);
    u_xlat2.xz = input.TEXCOORD0.xx;
    u_xlat1 = u_xlat2 / input.TEXCOORD0.wwww;
    u_xlat2 = _MainTex.Sample(sampler_MainTex, u_xlat1.zw);
    u_xlat1 = _MainTex.Sample(sampler_MainTex, u_xlat1.xy);
    u_xlat0 = mad(u_xlat1, float4(0.0900000036, 0.0900000036, 0.0900000036, 0.0900000036), u_xlat0);
    output.SV_Target0 = mad(u_xlat2, float4(0.0500000007, 0.0500000007, 0.0500000007, 0.0500000007), u_xlat0);
    return output;
}

#else
            // Original Metal program SHA256: vertex e1fa8462e3444c6a651fd04a9ccc5451d5ee7e04920ed80c01c35d6eb9f5677a; fragment 4f5d87453822d4ac40e23af1fd28d023d07712c0dbd8d9b34f65bcb86ec7b3b2.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

Texture2D<float4> _Mask;

float _MaskLerp;

float4 _Mask_ST;

float _Size;

SamplerState sampler_MainTex;

SamplerState sampler_Mask;



struct RV_e1fa8462e344_Input
{
    float4 POSITION0 : POSITION0;
};

struct RV_e1fa8462e344_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_e1fa8462e344_Output RecoveryVertex(RV_e1fa8462e344_Input input)
{
    RV_e1fa8462e344_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.mtl_Position = u_xlat0;
    u_xlat0.xy = mad(u_xlat0.xy, float2(1.0, -1.0), u_xlat0.ww);
    u_xlat0.xy = u_xlat0.xy * float2(0.5, 0.5);
    output.TEXCOORD0.xy = mad(u_xlat0.xy, _Mask_ST.xy, _Mask_ST.zw);
    output.TEXCOORD1 = u_xlat0;
    return output;
}



struct RF_4f5d87453822_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_4f5d87453822_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_4f5d87453822_Output RecoveryFragment(RF_4f5d87453822_Input input)
{
    RF_4f5d87453822_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float4 u_xlat3;
    float4 u_xlat4;
    float u_xlat6;
    float2 u_xlat11;
    u_xlat0.xz = input.TEXCOORD1.xx;
    u_xlat1.x = _Mask.Sample(sampler_Mask, input.TEXCOORD0.xy).x;
    u_xlat1.x = mad(_Size, u_xlat1.x, (-_Size));
    u_xlat1.x = mad(_MaskLerp, u_xlat1.x, _Size);
    u_xlat6 = u_xlat1.x * _MainTex_TexelSize.y;
    u_xlat2 = mad(((float4)(u_xlat6)), float4(-4.0, 3.0, -3.0, -2.0), input.TEXCOORD1.yyyy);
    u_xlat0.yw = u_xlat2.xz;
    u_xlat0 = u_xlat0 / input.TEXCOORD1.wwww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat0.zw);
    u_xlat0 = _MainTex.Sample(sampler_MainTex, u_xlat0.xy);
    u_xlat3 = u_xlat3 * float4(0.0900000036, 0.0900000036, 0.0900000036, 0.0900000036);
    u_xlat0 = mad(u_xlat0, float4(0.0500000007, 0.0500000007, 0.0500000007, 0.0500000007), u_xlat3);
    u_xlat3.y = u_xlat2.w;
    u_xlat3.xz = input.TEXCOORD1.xx;
    u_xlat11.xy = u_xlat3.xy / input.TEXCOORD1.ww;
    u_xlat4 = _MainTex.Sample(sampler_MainTex, u_xlat11.xy);
    u_xlat0 = mad(u_xlat4, float4(0.119999997, 0.119999997, 0.119999997, 0.119999997), u_xlat0);
    u_xlat3.w = mad((-_MainTex_TexelSize.y), u_xlat1.x, input.TEXCOORD1.y);
    u_xlat4.y = mad(_MainTex_TexelSize.y, u_xlat1.x, input.TEXCOORD1.y);
    u_xlat1.xz = u_xlat3.zw / input.TEXCOORD1.ww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat1.xz);
    u_xlat0 = mad(u_xlat3, float4(0.150000006, 0.150000006, 0.150000006, 0.150000006), u_xlat0);
    u_xlat1.xz = input.TEXCOORD1.xy / input.TEXCOORD1.ww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat1.xz);
    u_xlat0 = mad(u_xlat3, float4(0.180000007, 0.180000007, 0.180000007, 0.180000007), u_xlat0);
    u_xlat4.xz = input.TEXCOORD1.xx;
    u_xlat1.xz = u_xlat4.xy / input.TEXCOORD1.ww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat1.xz);
    u_xlat0 = mad(u_xlat3, float4(0.150000006, 0.150000006, 0.150000006, 0.150000006), u_xlat0);
    u_xlat4.w = mad(u_xlat6, 2.0, input.TEXCOORD1.y);
    u_xlat2.w = mad(u_xlat6, 4.0, input.TEXCOORD1.y);
    u_xlat1.xy = u_xlat4.zw / input.TEXCOORD1.ww;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, u_xlat1.xy);
    u_xlat0 = mad(u_xlat1, float4(0.119999997, 0.119999997, 0.119999997, 0.119999997), u_xlat0);
    u_xlat2.xz = input.TEXCOORD1.xx;
    u_xlat1 = u_xlat2 / input.TEXCOORD1.wwww;
    u_xlat2 = _MainTex.Sample(sampler_MainTex, u_xlat1.zw);
    u_xlat1 = _MainTex.Sample(sampler_MainTex, u_xlat1.xy);
    u_xlat0 = mad(u_xlat1, float4(0.0900000036, 0.0900000036, 0.0900000036, 0.0900000036), u_xlat0);
    output.SV_Target0 = mad(u_xlat2, float4(0.0500000007, 0.0500000007, 0.0500000007, 0.0500000007), u_xlat0);
    return output;
}

#endif
            ENDHLSL
        }
        Pass
        {
            Name "HORIZONTAL"
            Tags { "LIGHTMODE"="ALWAYS" }
            Cull Off
            ZClip On
            ZTest Off
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend One Zero
            BlendOp Add
            ColorMask RGBA
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#pragma multi_compile __ USE_MASK
#if (!defined(USE_MASK))
            // Original Metal program SHA256: vertex 33e08d1304667188776ce4403e1ba75e4d847c2ee12955ac463f44443feeeddd; fragment 8add7a6da2d8dbaba986a0c48935fbbdb7a34409837765e21635bc088ff431f6.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

float _Size;

SamplerState sampler_MainTex;



struct RV_33e08d130466_Input
{
    float4 POSITION0 : POSITION0;
};

struct RV_33e08d130466_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 TEXCOORD0 : TEXCOORD0;
};

RV_33e08d130466_Output RecoveryVertex(RV_33e08d130466_Input input)
{
    RV_33e08d130466_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.mtl_Position = u_xlat0;
    u_xlat0.xy = mad(u_xlat0.xy, float2(1.0, -1.0), u_xlat0.ww);
    output.TEXCOORD0.zw = u_xlat0.zw;
    output.TEXCOORD0.xy = u_xlat0.xy * float2(0.5, 0.5);
    return output;
}



struct RF_8add7a6da2d8_Input
{
    float4 TEXCOORD0 : TEXCOORD0;
};

struct RF_8add7a6da2d8_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_8add7a6da2d8_Output RecoveryFragment(RF_8add7a6da2d8_Input input)
{
    RF_8add7a6da2d8_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float4 u_xlat3;
    float4 u_xlat4;
    float2 u_xlat6;
    u_xlat0.yw = input.TEXCOORD0.yy;
    u_xlat1.x = _MainTex_TexelSize.x * _Size;
    u_xlat2 = mad(u_xlat1.xxxx, float4(3.0, -4.0, -3.0, -2.0), input.TEXCOORD0.xxxx);
    u_xlat0.xz = u_xlat2.yz;
    u_xlat0 = u_xlat0 / input.TEXCOORD0.wwww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat0.zw);
    u_xlat0 = _MainTex.Sample(sampler_MainTex, u_xlat0.xy);
    u_xlat3 = u_xlat3 * float4(0.0900000036, 0.0900000036, 0.0900000036, 0.0900000036);
    u_xlat0 = mad(u_xlat0, float4(0.0500000007, 0.0500000007, 0.0500000007, 0.0500000007), u_xlat3);
    u_xlat3.x = u_xlat2.w;
    u_xlat3.yw = input.TEXCOORD0.yy;
    u_xlat6.xy = u_xlat3.xy / input.TEXCOORD0.ww;
    u_xlat4 = _MainTex.Sample(sampler_MainTex, u_xlat6.xy);
    u_xlat0 = mad(u_xlat4, float4(0.119999997, 0.119999997, 0.119999997, 0.119999997), u_xlat0);
    u_xlat3.z = mad((-_MainTex_TexelSize.x), _Size, input.TEXCOORD0.x);
    u_xlat6.xy = u_xlat3.zw / input.TEXCOORD0.ww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat6.xy);
    u_xlat0 = mad(u_xlat3, float4(0.150000006, 0.150000006, 0.150000006, 0.150000006), u_xlat0);
    u_xlat6.xy = input.TEXCOORD0.xy / input.TEXCOORD0.ww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat6.xy);
    u_xlat0 = mad(u_xlat3, float4(0.180000007, 0.180000007, 0.180000007, 0.180000007), u_xlat0);
    u_xlat3.x = mad(_MainTex_TexelSize.x, _Size, input.TEXCOORD0.x);
    u_xlat3.yw = input.TEXCOORD0.yy;
    u_xlat6.xy = u_xlat3.xy / input.TEXCOORD0.ww;
    u_xlat4 = _MainTex.Sample(sampler_MainTex, u_xlat6.xy);
    u_xlat0 = mad(u_xlat4, float4(0.150000006, 0.150000006, 0.150000006, 0.150000006), u_xlat0);
    u_xlat3.z = mad(u_xlat1.x, 2.0, input.TEXCOORD0.x);
    u_xlat2.z = mad(u_xlat1.x, 4.0, input.TEXCOORD0.x);
    u_xlat1.xy = u_xlat3.zw / input.TEXCOORD0.ww;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, u_xlat1.xy);
    u_xlat0 = mad(u_xlat1, float4(0.119999997, 0.119999997, 0.119999997, 0.119999997), u_xlat0);
    u_xlat2.yw = input.TEXCOORD0.yy;
    u_xlat1 = u_xlat2 / input.TEXCOORD0.wwww;
    u_xlat2 = _MainTex.Sample(sampler_MainTex, u_xlat1.zw);
    u_xlat1 = _MainTex.Sample(sampler_MainTex, u_xlat1.xy);
    u_xlat0 = mad(u_xlat1, float4(0.0900000036, 0.0900000036, 0.0900000036, 0.0900000036), u_xlat0);
    output.SV_Target0 = mad(u_xlat2, float4(0.0500000007, 0.0500000007, 0.0500000007, 0.0500000007), u_xlat0);
    return output;
}

#else
            // Original Metal program SHA256: vertex e1fa8462e3444c6a651fd04a9ccc5451d5ee7e04920ed80c01c35d6eb9f5677a; fragment ac13a8f27a849bc90c3e3ce5fe9fdfa8eecf8b1cac36db5b73c7383f4ce555af.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

Texture2D<float4> _Mask;

float _MaskLerp;

float4 _Mask_ST;

float _Size;

SamplerState sampler_MainTex;

SamplerState sampler_Mask;



struct RV_e1fa8462e344_Input
{
    float4 POSITION0 : POSITION0;
};

struct RV_e1fa8462e344_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_e1fa8462e344_Output RecoveryVertex(RV_e1fa8462e344_Input input)
{
    RV_e1fa8462e344_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.mtl_Position = u_xlat0;
    u_xlat0.xy = mad(u_xlat0.xy, float2(1.0, -1.0), u_xlat0.ww);
    u_xlat0.xy = u_xlat0.xy * float2(0.5, 0.5);
    output.TEXCOORD0.xy = mad(u_xlat0.xy, _Mask_ST.xy, _Mask_ST.zw);
    output.TEXCOORD1 = u_xlat0;
    return output;
}



struct RF_ac13a8f27a84_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_ac13a8f27a84_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_ac13a8f27a84_Output RecoveryFragment(RF_ac13a8f27a84_Input input)
{
    RF_ac13a8f27a84_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float4 u_xlat3;
    float4 u_xlat4;
    float u_xlat6;
    float2 u_xlat11;
    u_xlat0.yw = input.TEXCOORD1.yy;
    u_xlat1.x = _Mask.Sample(sampler_Mask, input.TEXCOORD0.xy).x;
    u_xlat1.x = mad(_Size, u_xlat1.x, (-_Size));
    u_xlat1.x = mad(_MaskLerp, u_xlat1.x, _Size);
    u_xlat6 = u_xlat1.x * _MainTex_TexelSize.x;
    u_xlat2 = mad(((float4)(u_xlat6)), float4(3.0, -4.0, -3.0, -2.0), input.TEXCOORD1.xxxx);
    u_xlat0.xz = u_xlat2.yz;
    u_xlat0 = u_xlat0 / input.TEXCOORD1.wwww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat0.zw);
    u_xlat0 = _MainTex.Sample(sampler_MainTex, u_xlat0.xy);
    u_xlat3 = u_xlat3 * float4(0.0900000036, 0.0900000036, 0.0900000036, 0.0900000036);
    u_xlat0 = mad(u_xlat0, float4(0.0500000007, 0.0500000007, 0.0500000007, 0.0500000007), u_xlat3);
    u_xlat3.x = u_xlat2.w;
    u_xlat3.yw = input.TEXCOORD1.yy;
    u_xlat11.xy = u_xlat3.xy / input.TEXCOORD1.ww;
    u_xlat4 = _MainTex.Sample(sampler_MainTex, u_xlat11.xy);
    u_xlat0 = mad(u_xlat4, float4(0.119999997, 0.119999997, 0.119999997, 0.119999997), u_xlat0);
    u_xlat3.z = mad((-_MainTex_TexelSize.x), u_xlat1.x, input.TEXCOORD1.x);
    u_xlat4.x = mad(_MainTex_TexelSize.x, u_xlat1.x, input.TEXCOORD1.x);
    u_xlat1.xz = u_xlat3.zw / input.TEXCOORD1.ww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat1.xz);
    u_xlat0 = mad(u_xlat3, float4(0.150000006, 0.150000006, 0.150000006, 0.150000006), u_xlat0);
    u_xlat1.xz = input.TEXCOORD1.xy / input.TEXCOORD1.ww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat1.xz);
    u_xlat0 = mad(u_xlat3, float4(0.180000007, 0.180000007, 0.180000007, 0.180000007), u_xlat0);
    u_xlat4.yw = input.TEXCOORD1.yy;
    u_xlat1.xz = u_xlat4.xy / input.TEXCOORD1.ww;
    u_xlat3 = _MainTex.Sample(sampler_MainTex, u_xlat1.xz);
    u_xlat0 = mad(u_xlat3, float4(0.150000006, 0.150000006, 0.150000006, 0.150000006), u_xlat0);
    u_xlat4.z = mad(u_xlat6, 2.0, input.TEXCOORD1.x);
    u_xlat2.z = mad(u_xlat6, 4.0, input.TEXCOORD1.x);
    u_xlat1.xy = u_xlat4.zw / input.TEXCOORD1.ww;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, u_xlat1.xy);
    u_xlat0 = mad(u_xlat1, float4(0.119999997, 0.119999997, 0.119999997, 0.119999997), u_xlat0);
    u_xlat2.yw = input.TEXCOORD1.yy;
    u_xlat1 = u_xlat2 / input.TEXCOORD1.wwww;
    u_xlat2 = _MainTex.Sample(sampler_MainTex, u_xlat1.zw);
    u_xlat1 = _MainTex.Sample(sampler_MainTex, u_xlat1.xy);
    u_xlat0 = mad(u_xlat1, float4(0.0900000036, 0.0900000036, 0.0900000036, 0.0900000036), u_xlat0);
    output.SV_Target0 = mad(u_xlat2, float4(0.0500000007, 0.0500000007, 0.0500000007, 0.0500000007), u_xlat0);
    return output;
}

#endif
            ENDHLSL
        }
        Pass
        {
            Tags { "LIGHTMODE"="ALWAYS" }
            Cull Off
            ZClip On
            ZTest Off
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend One Zero
            BlendOp Add
            ColorMask RGBA
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#pragma multi_compile __ USE_MASK
#if (!defined(USE_MASK))
            // Original Metal program SHA256: vertex 33e08d1304667188776ce4403e1ba75e4d847c2ee12955ac463f44443feeeddd; fragment 1f443606235ee11883d3f86673b5a3dedeb0d83b489129ae8a3a724ce348e28b.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float _Vibrancy;

SamplerState sampler_MainTex;



struct RV_33e08d130466_Input
{
    float4 POSITION0 : POSITION0;
};

struct RV_33e08d130466_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 TEXCOORD0 : TEXCOORD0;
};

RV_33e08d130466_Output RecoveryVertex(RV_33e08d130466_Input input)
{
    RV_33e08d130466_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.mtl_Position = u_xlat0;
    u_xlat0.xy = mad(u_xlat0.xy, float2(1.0, -1.0), u_xlat0.ww);
    output.TEXCOORD0.zw = u_xlat0.zw;
    output.TEXCOORD0.xy = u_xlat0.xy * float2(0.5, 0.5);
    return output;
}



struct RF_1f443606235e_Input
{
    float4 TEXCOORD0 : TEXCOORD0;
};

struct RF_1f443606235e_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_1f443606235e_Output RecoveryFragment(RF_1f443606235e_Input input)
{
    RF_1f443606235e_Output output;
    float u_xlat0;
    float4 u_xlat1;
    float2 u_xlat2;
    u_xlat0 = _Vibrancy + 1.0;
    u_xlat2.xy = input.TEXCOORD0.xy / input.TEXCOORD0.ww;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, u_xlat2.xy);
    output.SV_Target0.xyz = ((float3)(u_xlat0)) * u_xlat1.xyz;
    output.SV_Target0.w = u_xlat1.w;
    return output;
}

#else
            // Original Metal program SHA256: vertex e1fa8462e3444c6a651fd04a9ccc5451d5ee7e04920ed80c01c35d6eb9f5677a; fragment c1f57ad540049fbf67a92cac4c53e9f130c71d9685ef5506ad257e466df88017.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

Texture2D<float4> _Mask;

float _MaskLerp;

float4 _Mask_ST;

float _Vibrancy;

SamplerState sampler_MainTex;

SamplerState sampler_Mask;



struct RV_e1fa8462e344_Input
{
    float4 POSITION0 : POSITION0;
};

struct RV_e1fa8462e344_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_e1fa8462e344_Output RecoveryVertex(RV_e1fa8462e344_Input input)
{
    RV_e1fa8462e344_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.mtl_Position = u_xlat0;
    u_xlat0.xy = mad(u_xlat0.xy, float2(1.0, -1.0), u_xlat0.ww);
    u_xlat0.xy = u_xlat0.xy * float2(0.5, 0.5);
    output.TEXCOORD0.xy = mad(u_xlat0.xy, _Mask_ST.xy, _Mask_ST.zw);
    output.TEXCOORD1 = u_xlat0;
    return output;
}



struct RF_c1f57ad54004_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_c1f57ad54004_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_c1f57ad54004_Output RecoveryFragment(RF_c1f57ad54004_Input input)
{
    RF_c1f57ad54004_Output output;
    float u_xlat0;
    float4 u_xlat1;
    float2 u_xlat2;
    u_xlat0 = _Mask.Sample(sampler_Mask, input.TEXCOORD0.xy).x;
    u_xlat0 = mad(_Vibrancy, u_xlat0, (-_Vibrancy));
    u_xlat0 = mad(_MaskLerp, u_xlat0, _Vibrancy);
    u_xlat0 = u_xlat0 + 1.0;
    u_xlat2.xy = input.TEXCOORD1.xy / input.TEXCOORD1.ww;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, u_xlat2.xy);
    output.SV_Target0.xyz = ((float3)(u_xlat0)) * u_xlat1.xyz;
    output.SV_Target0.w = u_xlat1.w;
    return output;
}

#endif
            ENDHLSL
        }
    }
    Fallback Off
}
