// Reconstructed from the licensed GOG macOS 1.0.30000 captured Metal programs.
// Generated by tools/shader_reconstruction/shaderlab_generator.py.
// Original serialized Shader SHA256: 6f1448721fe4e4c2ab80a19f45647146b5334f91cedead81d48030fa5837d2dd
// Properties, render states, texture samplers, and retained variants come from the original data.
// Extra keyword combinations select a captured variant; see batch-generation-manifest.json.
Shader "Sprites/Cherry-Default-HueShift"
{
    Properties
    {
        [PerRendererData] _MainTex ("Sprite Texture", 2D) = "white" {}
        _Color ("Tint", Color) = (1, 1, 1, 1)
        [MaterialToggle] PixelSnap ("Pixel snap", Float) = 0
        _HueShift ("Hue Shift", Range(-1, 1)) = 0
    }
    SubShader
    {
        Tags { "CanUseSpriteAtlas"="true" "IGNOREPROJECTOR"="true" "PreviewType"="Plane" "QUEUE"="Transparent" "RenderType"="Transparent" }
        Pass
        {
            Tags { "CanUseSpriteAtlas"="true" "IGNOREPROJECTOR"="true" "PreviewType"="Plane" "QUEUE"="Transparent" "RenderType"="Transparent" }
            Cull Off
            ZClip On
            ZTest LEqual
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend One OneMinusSrcAlpha
            BlendOp Add
            ColorMask RGBA
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#pragma multi_compile __ PIXELSNAP_ON
#if (defined(PIXELSNAP_ON))
            // Original Metal program SHA256: vertex 41cd6bd0f0343bc71996009a612b3849d5cb9991381b704b19840a5c27ca3043; fragment ab040749e787503170d8bbc7e95d417f3b4dd2d5104bd316c80ddb44f252fb0b.
#include "UnityCG.cginc"

float4 _Color;

float _HueShift;

Texture2D<float4> _MainTex;

SamplerState sampler_MainTex;



struct RV_41cd6bd0f034_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_41cd6bd0f034_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

RV_41cd6bd0f034_Output RecoveryVertex(RV_41cd6bd0f034_Input input)
{
    RV_41cd6bd0f034_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlat0.xy = u_xlat0.xy / u_xlat0.ww;
    u_xlat1.xy = _ScreenParams.xy * float2(0.5, 0.5);
    u_xlat0.xy = u_xlat0.xy * u_xlat1.xy;
    u_xlat0.xy = round(u_xlat0.xy);
    u_xlat0.xy = u_xlat0.xy / u_xlat1.xy;
    output.mtl_Position.xy = u_xlat0.ww * u_xlat0.xy;
    output.mtl_Position.zw = u_xlat0.zw;
    output.COLOR0 = input.COLOR0 * _Color;
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_ab040749e787_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RF_ab040749e787_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_ab040749e787_Output RecoveryFragment(RF_ab040749e787_Input input)
{
    RF_ab040749e787_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float u_xlat3;
    bool u_xlatb3;
    float u_xlat4;
    float u_xlat5;
    u_xlat0.z = float(-1.0);
    u_xlat0.w = float(0.666666687);
    u_xlat1.z = float(1.0);
    u_xlat1.w = float(-1.0);
    u_xlat2 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlatb3 = u_xlat2.y>=u_xlat2.z;
    u_xlat3 = u_xlatb3 ? 1.0 : float(0.0);
    u_xlat0.xy = u_xlat2.zy;
    u_xlat1.xy = (-u_xlat0.xy) + u_xlat2.yz;
    u_xlat0 = mad(((float4)(u_xlat3)), u_xlat1.xywz, u_xlat0.xywz);
    u_xlat1.z = u_xlat0.w;
    u_xlatb3 = u_xlat2.x>=u_xlat0.x;
    u_xlat3 = u_xlatb3 ? 1.0 : float(0.0);
    u_xlat0.w = u_xlat2.x;
    u_xlat1.xyw = u_xlat0.wyx;
    u_xlat1 = (-u_xlat0) + u_xlat1;
    u_xlat0 = mad(((float4)(u_xlat3)), u_xlat1.yxzw, u_xlat0.yxzw);
    u_xlat1.x = min(u_xlat0.x, u_xlat0.w);
    u_xlat1.x = u_xlat0.y + (-u_xlat1.x);
    u_xlat5 = mad(u_xlat1.x, 6.0, 1.00000001e-10);
    u_xlat0.x = (-u_xlat0.x) + u_xlat0.w;
    u_xlat0.x = u_xlat0.x / u_xlat5;
    u_xlat0.x = u_xlat0.x + u_xlat0.z;
    u_xlat0.x = abs(u_xlat0.x) + _HueShift;
    u_xlat0.xzw = u_xlat0.xxx + float3(1.0, 0.666666687, 0.333333343);
    u_xlat0.xzw = frac(u_xlat0.xzw);
    u_xlat0.xzw = mad(u_xlat0.xzw, float3(6.0, 6.0, 6.0), float3(-3.0, -3.0, -3.0));
    u_xlat0.xzw = abs(u_xlat0.xzw) + float3(-1.0, -1.0, -1.0);
    u_xlat0.xzw = clamp(u_xlat0.xzw, 0.0f, 1.0f);
    u_xlat0.xzw = u_xlat0.xzw + float3(-1.0, -1.0, -1.0);
    u_xlat5 = u_xlat0.y + 1.00000001e-10;
    u_xlat4 = u_xlat0.y;
    u_xlat4 = clamp(u_xlat4, 0.0f, 1.0f);
    u_xlat1.x = u_xlat1.x / u_xlat5;
    u_xlat1.x = clamp(u_xlat1.x, 0.0f, 1.0f);
    u_xlat0.xzw = mad(u_xlat1.xxx, u_xlat0.xzw, float3(1.0, 1.0, 1.0));
    u_xlat2.xyz = u_xlat0.xzw * ((float3)(u_xlat4));
    u_xlat0 = u_xlat2 * input.COLOR0;
    output.SV_Target0.xyz = u_xlat0.www * u_xlat0.xyz;
    output.SV_Target0.w = u_xlat0.w;
    return output;
}

#else
            // Original Metal program SHA256: vertex 4c427b1893dd1578a0cd519683fa421379edda04c9eb362bf2198edee4f8c2f7; fragment ab040749e787503170d8bbc7e95d417f3b4dd2d5104bd316c80ddb44f252fb0b.
#include "UnityCG.cginc"

float4 _Color;

float _HueShift;

Texture2D<float4> _MainTex;

SamplerState sampler_MainTex;



struct RV_4c427b1893dd_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_4c427b1893dd_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

RV_4c427b1893dd_Output RecoveryVertex(RV_4c427b1893dd_Input input)
{
    RV_4c427b1893dd_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.COLOR0 = input.COLOR0 * _Color;
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_ab040749e787_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RF_ab040749e787_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_ab040749e787_Output RecoveryFragment(RF_ab040749e787_Input input)
{
    RF_ab040749e787_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float u_xlat3;
    bool u_xlatb3;
    float u_xlat4;
    float u_xlat5;
    u_xlat0.z = float(-1.0);
    u_xlat0.w = float(0.666666687);
    u_xlat1.z = float(1.0);
    u_xlat1.w = float(-1.0);
    u_xlat2 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlatb3 = u_xlat2.y>=u_xlat2.z;
    u_xlat3 = u_xlatb3 ? 1.0 : float(0.0);
    u_xlat0.xy = u_xlat2.zy;
    u_xlat1.xy = (-u_xlat0.xy) + u_xlat2.yz;
    u_xlat0 = mad(((float4)(u_xlat3)), u_xlat1.xywz, u_xlat0.xywz);
    u_xlat1.z = u_xlat0.w;
    u_xlatb3 = u_xlat2.x>=u_xlat0.x;
    u_xlat3 = u_xlatb3 ? 1.0 : float(0.0);
    u_xlat0.w = u_xlat2.x;
    u_xlat1.xyw = u_xlat0.wyx;
    u_xlat1 = (-u_xlat0) + u_xlat1;
    u_xlat0 = mad(((float4)(u_xlat3)), u_xlat1.yxzw, u_xlat0.yxzw);
    u_xlat1.x = min(u_xlat0.x, u_xlat0.w);
    u_xlat1.x = u_xlat0.y + (-u_xlat1.x);
    u_xlat5 = mad(u_xlat1.x, 6.0, 1.00000001e-10);
    u_xlat0.x = (-u_xlat0.x) + u_xlat0.w;
    u_xlat0.x = u_xlat0.x / u_xlat5;
    u_xlat0.x = u_xlat0.x + u_xlat0.z;
    u_xlat0.x = abs(u_xlat0.x) + _HueShift;
    u_xlat0.xzw = u_xlat0.xxx + float3(1.0, 0.666666687, 0.333333343);
    u_xlat0.xzw = frac(u_xlat0.xzw);
    u_xlat0.xzw = mad(u_xlat0.xzw, float3(6.0, 6.0, 6.0), float3(-3.0, -3.0, -3.0));
    u_xlat0.xzw = abs(u_xlat0.xzw) + float3(-1.0, -1.0, -1.0);
    u_xlat0.xzw = clamp(u_xlat0.xzw, 0.0f, 1.0f);
    u_xlat0.xzw = u_xlat0.xzw + float3(-1.0, -1.0, -1.0);
    u_xlat5 = u_xlat0.y + 1.00000001e-10;
    u_xlat4 = u_xlat0.y;
    u_xlat4 = clamp(u_xlat4, 0.0f, 1.0f);
    u_xlat1.x = u_xlat1.x / u_xlat5;
    u_xlat1.x = clamp(u_xlat1.x, 0.0f, 1.0f);
    u_xlat0.xzw = mad(u_xlat1.xxx, u_xlat0.xzw, float3(1.0, 1.0, 1.0));
    u_xlat2.xyz = u_xlat0.xzw * ((float3)(u_xlat4));
    u_xlat0 = u_xlat2 * input.COLOR0;
    output.SV_Target0.xyz = u_xlat0.www * u_xlat0.xyz;
    output.SV_Target0.w = u_xlat0.w;
    return output;
}

#endif
            ENDHLSL
        }
    }
}
