// Reconstructed from the licensed GOG macOS 1.0.30000 captured Metal programs.
// Generated by tools/shader_reconstruction/shaderlab_generator.py.
// Original serialized Shader SHA256: 6ef63eab070d58481b693ab51d15435adde1dab9a8358fc21b5ed59b856e1f3c
// Properties, render states, texture samplers, and retained variants come from the original data.
// Extra keyword combinations select a captured variant; see batch-generation-manifest.json.
Shader "Custom/Contrast Effect"
{
    Properties
    {
        _Contrast ("Contrast", Float) = 1
        _Mask ("Mask", 2D) = "white" {}
        [Toggle(CAN_DESATURATE)] _CanDesaturate ("Can Desaturate", Float) = 0
        _Desaturation ("Desaturation", Range(0, 1)) = 0
    }
    SubShader
    {
        Tags { "QUEUE"="Transparent" "RenderType"="Opaque" }
        GrabPass
        {
            Name "BASE"
            Tags { "LIGHTMODE"="ALWAYS" }
        }
        Pass
        {
            Name "BASE"
            Tags { "LIGHTMODE"="ALWAYS" "QUEUE"="Transparent" "RenderType"="Opaque" }
            Cull Back
            ZClip On
            ZTest LEqual
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend One Zero
            BlendOp Add
            ColorMask RGBA
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#pragma multi_compile __ CAN_DESATURATE
#if (defined(CAN_DESATURATE))
            // Original Metal program SHA256: vertex cbd2748c8b4041b2adfe647b648540b3191a82fc59fd6910b01de31aa0d2ba44; fragment 692e3622bf498fb7459a2daa5512c9a46f4aca0d9a04c83c3bcf16be708e9fc4.
#include "UnityCG.cginc"

float _Contrast;

float _Desaturation;

Texture2D<float4> _GrabTexture;

Texture2D<float4> _Mask;

float4 _Mask_ST;

SamplerState sampler_GrabTexture;

SamplerState sampler_Mask;



struct RV_cbd2748c8b40_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_cbd2748c8b40_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_cbd2748c8b40_Output RecoveryVertex(RV_cbd2748c8b40_Input input)
{
    RV_cbd2748c8b40_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.mtl_Position = u_xlat0;
    u_xlat0.xy = mad(u_xlat0.xy, float2(1.0, -1.0), u_xlat0.ww);
    output.TEXCOORD0.zw = u_xlat0.zw;
    output.TEXCOORD0.xy = u_xlat0.xy * float2(0.5, 0.5);
    output.TEXCOORD1.xy = mad(input.TEXCOORD0.xy, _Mask_ST.xy, _Mask_ST.zw);
    return output;
}



struct RF_692e3622bf49_Input
{
    float4 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_692e3622bf49_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_692e3622bf49_Output RecoveryFragment(RF_692e3622bf49_Input input)
{
    RF_692e3622bf49_Output output;
    float3 u_xlat0;
    float4 u_xlat1;
    float3 u_xlat2;
    float u_xlat6;
    u_xlat0.x = _Mask.Sample(sampler_Mask, input.TEXCOORD1.xy).x;
    u_xlat2.xy = input.TEXCOORD0.xy / input.TEXCOORD0.ww;
    u_xlat1 = _GrabTexture.Sample(sampler_GrabTexture, u_xlat2.xy);
    u_xlat2.xyz = u_xlat1.xyz + float3(-0.217637643, -0.217637643, -0.217637643);
    u_xlat2.xyz = mad(u_xlat2.xyz, ((float3)(_Contrast)), float3(0.217637643, 0.217637643, 0.217637643));
    u_xlat2.xyz = (-u_xlat1.xyz) + u_xlat2.xyz;
    u_xlat0.xyz = mad(u_xlat0.xxx, u_xlat2.xyz, u_xlat1.xyz);
    output.SV_Target0.w = u_xlat1.w;
    u_xlat6 = dot(u_xlat0.xyz, float3(0.219999999, 0.707000017, 0.0710000023));
    u_xlat6 = clamp(u_xlat6, 0.0f, 1.0f);
    u_xlat1.xyz = (-u_xlat0.xyz) + ((float3)(u_xlat6));
    output.SV_Target0.xyz = mad(((float3)(_Desaturation)), u_xlat1.xyz, u_xlat0.xyz);
    return output;
}

#else
            // Original Metal program SHA256: vertex cbd2748c8b4041b2adfe647b648540b3191a82fc59fd6910b01de31aa0d2ba44; fragment 8eaffbde7556356f30b2cab4f77f9f0500426cbe189ec9dd683c01e0c4471f33.
#include "UnityCG.cginc"

float _Contrast;

Texture2D<float4> _GrabTexture;

Texture2D<float4> _Mask;

float4 _Mask_ST;

SamplerState sampler_GrabTexture;

SamplerState sampler_Mask;



struct RV_cbd2748c8b40_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_cbd2748c8b40_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_cbd2748c8b40_Output RecoveryVertex(RV_cbd2748c8b40_Input input)
{
    RV_cbd2748c8b40_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.mtl_Position = u_xlat0;
    u_xlat0.xy = mad(u_xlat0.xy, float2(1.0, -1.0), u_xlat0.ww);
    output.TEXCOORD0.zw = u_xlat0.zw;
    output.TEXCOORD0.xy = u_xlat0.xy * float2(0.5, 0.5);
    output.TEXCOORD1.xy = mad(input.TEXCOORD0.xy, _Mask_ST.xy, _Mask_ST.zw);
    return output;
}



struct RF_8eaffbde7556_Input
{
    float4 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_8eaffbde7556_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_8eaffbde7556_Output RecoveryFragment(RF_8eaffbde7556_Input input)
{
    RF_8eaffbde7556_Output output;
    float u_xlat0;
    float4 u_xlat1;
    float3 u_xlat2;
    u_xlat0 = _Mask.Sample(sampler_Mask, input.TEXCOORD1.xy).x;
    u_xlat2.xy = input.TEXCOORD0.xy / input.TEXCOORD0.ww;
    u_xlat1 = _GrabTexture.Sample(sampler_GrabTexture, u_xlat2.xy);
    u_xlat2.xyz = u_xlat1.xyz + float3(-0.217637643, -0.217637643, -0.217637643);
    u_xlat2.xyz = mad(u_xlat2.xyz, ((float3)(_Contrast)), float3(0.217637643, 0.217637643, 0.217637643));
    u_xlat2.xyz = (-u_xlat1.xyz) + u_xlat2.xyz;
    output.SV_Target0.xyz = mad(((float3)(u_xlat0)), u_xlat2.xyz, u_xlat1.xyz);
    output.SV_Target0.w = u_xlat1.w;
    return output;
}

#endif
            ENDHLSL
        }
    }
}
