// Reconstructed from the licensed GOG macOS 1.0.30000 captured Metal programs.
// Generated by tools/shader_reconstruction/shaderlab_generator.py.
// Original serialized Shader SHA256: 02ab67596185d66ed7149e42371554a3b406b0b968e7b96a7e506bb3e9d71e1b
// Properties, render states, texture samplers, and retained variants come from the original data.
// Extra keyword combinations select a captured variant; see batch-generation-manifest.json.
Shader "Custom/ScrollTexture"
{
    Properties
    {
        _Color ("Color", Color) = (1, 1, 1, 1)
        _MainTex ("Texture", 2D) = "white" {}
        _SpeedX ("Flow Rate X", Float) = 1
        _SpeedY ("Flow Rate Y", Float) = 1
        [Toggle(USE_SECONDARY)] _UseSecondary ("Use Secondary", Float) = 0
        _SecondaryColor ("Secondary Color", Color) = (1, 1, 1, 1)
        _SecondaryTex ("Secondary Texture", 2D) = "white" {}
        _SecondarySpeedX ("Secondary Flow Rate X", Float) = 1
        _SecondarySpeedY ("Secondary Flow Rate Y", Float) = 1
        [Space] [Toggle(USE_OBJECT_SCALE)] _UseObjectScale ("Use Object Scale", Float) = 0
        [Space] [Toggle(USE_WORLD_OFFSET)] _UseWorldOffset ("Use World Offset", Float) = 0
        _WorldOffsetX ("World Offset X Amount", Float) = 0
        _WorldOffsetY ("World Offset Y Amount", Float) = 0
        _WorldOffsetZ ("World Offset Z Amount", Float) = 0
        [Toggle(USE_MASK)] _UseMask ("Use Mask", Float) = 0
        _MaskTex ("Mask Texture", 2D) = "white" {}
        [PerRendererData] _TintColor ("Tint Color", Color) = (1, 1, 1, 1)
        _StencilRef ("Stencil Ref", Range(0, 255)) = 255
        [Toggle(USE_COLOR_FLASH)] _UseColorFlash ("Use Color Flash", Float) = 0
        _FlashColor ("Flash Color", Color) = (1, 1, 1, 1)
        _FlashAmount ("Flash Amount", Range(0, 1)) = 0
    }
    SubShader
    {
        LOD 100
        Tags { "DisableBatching"="true" "IGNOREPROJECTOR"="true" "QUEUE"="Transparent" "RenderType"="Transparent" }
        Pass
        {
            Tags { "DisableBatching"="true" "IGNOREPROJECTOR"="true" "QUEUE"="Transparent" "RenderType"="Transparent" }
            Cull Back
            ZClip On
            ZTest LEqual
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend One OneMinusSrcAlpha
            BlendOp Add
            ColorMask RGBA
            Stencil
            {
                Ref [_StencilRef]
                ReadMask 255
                WriteMask 255
                Comp GEqual
                Pass Keep
                Fail Keep
                ZFail Keep
            }
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#pragma multi_compile __ USE_COLOR_FLASH USE_MASK USE_OBJECT_SCALE
#pragma multi_compile __ USE_SECONDARY
#pragma multi_compile __ USE_WORLD_OFFSET
#pragma multi_compile_instancing
#if (!defined(INSTANCING_ON) && defined(USE_MASK) && !defined(USE_SECONDARY) && !defined(USE_WORLD_OFFSET))
            // Original Metal program SHA256: vertex 1ab1134ff477f911d40b31e88bf826d683777326f5f1b32e438d8e6131c2882a; fragment 11b4b85c8b46cdc5dd456bf2f87be2b91145e2deada3eea34ada1ec10f7985ef.
#include "UnityCG.cginc"

float4 _Color;

Texture2D<float4> _MainTex;

float4 _MainTex_ST;

Texture2D<float4> _MaskTex;

float4 _MaskTex_ST;

float _SpeedX;

float _SpeedY;

float4 _TintColor;

SamplerState sampler_MainTex;

SamplerState sampler_MaskTex;



struct RV_1ab1134ff477_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 COLOR0 : COLOR0;
};

struct RV_1ab1134ff477_Output
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
};

RV_1ab1134ff477_Output RecoveryVertex(RV_1ab1134ff477_Input input)
{
    RV_1ab1134ff477_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.xy = mad(float2(_SpeedX, _SpeedY), _Time.yy, input.TEXCOORD0.xy);
    output.TEXCOORD0.xy = mad(u_xlat0.xy, _MainTex_ST.xy, _MainTex_ST.zw);
    output.TEXCOORD1.xy = mad(input.TEXCOORD0.xy, _MaskTex_ST.xy, _MaskTex_ST.zw);
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.COLOR0 = input.COLOR0 * _TintColor;
    return output;
}



struct RF_11b4b85c8b46_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
    float4 COLOR0 : COLOR0;
};

struct RF_11b4b85c8b46_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_11b4b85c8b46_Output RecoveryFragment(RF_11b4b85c8b46_Input input)
{
    RF_11b4b85c8b46_Output output;
    float4 u_xlat0;
    float u_xlat1;
    float u_xlat6;
    u_xlat0 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat0 = u_xlat0 * _Color;
    u_xlat0 = u_xlat0 * input.COLOR0;
    u_xlat1 = _MaskTex.Sample(sampler_MaskTex, input.TEXCOORD1.xy).x;
    u_xlat6 = u_xlat0.w * u_xlat1;
    output.SV_Target0.xyz = ((float3)(u_xlat6)) * u_xlat0.xyz;
    output.SV_Target0.w = u_xlat6;
    return output;
}

#elif (defined(INSTANCING_ON) && defined(USE_MASK) && !defined(USE_SECONDARY) && defined(USE_WORLD_OFFSET))
            // Original Metal program SHA256: vertex 3a89c6ba5f096cc743422601164bf6a7485f6c1ce0e996ea8f75ff415a44e9a7; fragment 2aec5dd8a76273af8ea778bb5d500f67d945fd199733217328d952e9245f1a00.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float4 _MainTex_ST;

Texture2D<float4> _MaskTex;

float4 _MaskTex_ST;

float _WorldOffsetX;

float _WorldOffsetY;

float _WorldOffsetZ;

UNITY_INSTANCING_BUFFER_START(Props)
    UNITY_DEFINE_INSTANCED_PROP(float4, _Color)
    UNITY_DEFINE_INSTANCED_PROP(float4, _TintColor)
    UNITY_DEFINE_INSTANCED_PROP(float, _SpeedX)
    UNITY_DEFINE_INSTANCED_PROP(float, _SpeedY)
UNITY_INSTANCING_BUFFER_END(Props)

SamplerState sampler_MainTex;

SamplerState sampler_MaskTex;



struct RV_3a89c6ba5f09_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 COLOR0 : COLOR0;
    uint recovered_InstanceID : SV_InstanceID;
};

struct RV_3a89c6ba5f09_Output
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    uint SV_InstanceID0 : TEXCOORD13;
};

RV_3a89c6ba5f09_Output RecoveryVertex(RV_3a89c6ba5f09_Input input)
{

    RV_3a89c6ba5f09_Output output;
    float4 u_xlat0;
    int u_xlati0;
    float4 u_xlat1;
    int u_xlati2;
    float2 u_xlat4;
    output.TEXCOORD1.xy = mad(input.TEXCOORD0.xy, _MaskTex_ST.xy, _MaskTex_ST.zw);
    u_xlati0 = int(input.recovered_InstanceID) + unity_BaseInstanceID;
    u_xlati2 = u_xlati0 * 0x3;
    u_xlati0 = u_xlati0 << 0x3;
    u_xlat4.x = dot(transpose(unity_Builtins0Array[u_xlati0 / 8].unity_ObjectToWorldArray)[3].yxz, float3(_WorldOffsetY, _WorldOffsetX, _WorldOffsetZ));
    u_xlat4.x = u_xlat4.x + _Time.y;
    u_xlat4.xy = mad(float2(PropsArray[u_xlati2 / 3]._SpeedX, PropsArray[u_xlati2 / 3]._SpeedY), u_xlat4.xx, input.TEXCOORD0.xy);
    output.COLOR0 = input.COLOR0 * PropsArray[u_xlati2 / 3]._TintColor;
    output.TEXCOORD0.xy = mad(u_xlat4.xy, _MainTex_ST.xy, _MainTex_ST.zw);
    u_xlat1 = input.POSITION0.yyyy * transpose(unity_Builtins0Array[u_xlati0 / 8].unity_ObjectToWorldArray)[1];
    u_xlat1 = mad(transpose(unity_Builtins0Array[u_xlati0 / 8].unity_ObjectToWorldArray)[0], input.POSITION0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_Builtins0Array[u_xlati0 / 8].unity_ObjectToWorldArray)[2], input.POSITION0.zzzz, u_xlat1);
    u_xlat0 = u_xlat1 + transpose(unity_Builtins0Array[u_xlati0 / 8].unity_ObjectToWorldArray)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.SV_InstanceID0 = input.recovered_InstanceID;
    return output;
}



struct RF_2aec5dd8a762_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
    float4 COLOR0 : COLOR0;
    nointerpolation uint SV_InstanceID0 : TEXCOORD13;
};

struct RF_2aec5dd8a762_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_2aec5dd8a762_Output RecoveryFragment(RF_2aec5dd8a762_Input input)
{
    RF_2aec5dd8a762_Output output;
    float4 u_xlat0;
    int u_xlati0;
    float4 u_xlat1;
    float u_xlat6;
    u_xlati0 = int(input.SV_InstanceID0) + unity_BaseInstanceID;
    u_xlati0 = u_xlati0 * 0x3;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat0 = u_xlat1 * PropsArray[u_xlati0 / 3]._Color;
    u_xlat0 = u_xlat0 * input.COLOR0;
    u_xlat1.x = _MaskTex.Sample(sampler_MaskTex, input.TEXCOORD1.xy).x;
    u_xlat6 = u_xlat0.w * u_xlat1.x;
    output.SV_Target0.xyz = ((float3)(u_xlat6)) * u_xlat0.xyz;
    output.SV_Target0.w = u_xlat6;
    return output;
}

#elif (defined(INSTANCING_ON) && defined(USE_MASK) && !defined(USE_SECONDARY) && !defined(USE_WORLD_OFFSET))
            // Original Metal program SHA256: vertex 715f6194044c793a5bf60c4507d085fe5f4957ef9d99994ac97d55f54df62d08; fragment 2aec5dd8a76273af8ea778bb5d500f67d945fd199733217328d952e9245f1a00.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float4 _MainTex_ST;

Texture2D<float4> _MaskTex;

float4 _MaskTex_ST;

UNITY_INSTANCING_BUFFER_START(Props)
    UNITY_DEFINE_INSTANCED_PROP(float4, _Color)
    UNITY_DEFINE_INSTANCED_PROP(float4, _TintColor)
    UNITY_DEFINE_INSTANCED_PROP(float, _SpeedX)
    UNITY_DEFINE_INSTANCED_PROP(float, _SpeedY)
UNITY_INSTANCING_BUFFER_END(Props)

SamplerState sampler_MainTex;

SamplerState sampler_MaskTex;



struct RV_715f6194044c_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 COLOR0 : COLOR0;
    uint recovered_InstanceID : SV_InstanceID;
};

struct RV_715f6194044c_Output
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    uint SV_InstanceID0 : TEXCOORD13;
};

RV_715f6194044c_Output RecoveryVertex(RV_715f6194044c_Input input)
{

    RV_715f6194044c_Output output;
    float4 u_xlat0;
    int u_xlati0;
    float4 u_xlat1;
    int u_xlati2;
    float2 u_xlat4;
    output.TEXCOORD1.xy = mad(input.TEXCOORD0.xy, _MaskTex_ST.xy, _MaskTex_ST.zw);
    u_xlati0 = int(input.recovered_InstanceID) + unity_BaseInstanceID;
    u_xlati2 = u_xlati0 * 0x3;
    u_xlati0 = u_xlati0 << 0x3;
    u_xlat4.xy = mad(float2(PropsArray[u_xlati2 / 3]._SpeedX, PropsArray[u_xlati2 / 3]._SpeedY), _Time.yy, input.TEXCOORD0.xy);
    output.COLOR0 = input.COLOR0 * PropsArray[u_xlati2 / 3]._TintColor;
    output.TEXCOORD0.xy = mad(u_xlat4.xy, _MainTex_ST.xy, _MainTex_ST.zw);
    u_xlat1 = input.POSITION0.yyyy * transpose(unity_Builtins0Array[u_xlati0 / 8].unity_ObjectToWorldArray)[1];
    u_xlat1 = mad(transpose(unity_Builtins0Array[u_xlati0 / 8].unity_ObjectToWorldArray)[0], input.POSITION0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_Builtins0Array[u_xlati0 / 8].unity_ObjectToWorldArray)[2], input.POSITION0.zzzz, u_xlat1);
    u_xlat0 = u_xlat1 + transpose(unity_Builtins0Array[u_xlati0 / 8].unity_ObjectToWorldArray)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.SV_InstanceID0 = input.recovered_InstanceID;
    return output;
}



struct RF_2aec5dd8a762_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
    float4 COLOR0 : COLOR0;
    nointerpolation uint SV_InstanceID0 : TEXCOORD13;
};

struct RF_2aec5dd8a762_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_2aec5dd8a762_Output RecoveryFragment(RF_2aec5dd8a762_Input input)
{
    RF_2aec5dd8a762_Output output;
    float4 u_xlat0;
    int u_xlati0;
    float4 u_xlat1;
    float u_xlat6;
    u_xlati0 = int(input.SV_InstanceID0) + unity_BaseInstanceID;
    u_xlati0 = u_xlati0 * 0x3;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat0 = u_xlat1 * PropsArray[u_xlati0 / 3]._Color;
    u_xlat0 = u_xlat0 * input.COLOR0;
    u_xlat1.x = _MaskTex.Sample(sampler_MaskTex, input.TEXCOORD1.xy).x;
    u_xlat6 = u_xlat0.w * u_xlat1.x;
    output.SV_Target0.xyz = ((float3)(u_xlat6)) * u_xlat0.xyz;
    output.SV_Target0.w = u_xlat6;
    return output;
}

#elif (!defined(INSTANCING_ON) && defined(USE_MASK) && !defined(USE_SECONDARY) && defined(USE_WORLD_OFFSET))
            // Original Metal program SHA256: vertex 827e5583dc3d8e0c11b1d5c3ba10955ec62186c5e900e4e959ef2c607111fb5c; fragment 11b4b85c8b46cdc5dd456bf2f87be2b91145e2deada3eea34ada1ec10f7985ef.
#include "UnityCG.cginc"

float4 _Color;

Texture2D<float4> _MainTex;

float4 _MainTex_ST;

Texture2D<float4> _MaskTex;

float4 _MaskTex_ST;

float _SpeedX;

float _SpeedY;

float4 _TintColor;

float _WorldOffsetX;

float _WorldOffsetY;

float _WorldOffsetZ;

SamplerState sampler_MainTex;

SamplerState sampler_MaskTex;



struct RV_827e5583dc3d_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 COLOR0 : COLOR0;
};

struct RV_827e5583dc3d_Output
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
};

RV_827e5583dc3d_Output RecoveryVertex(RV_827e5583dc3d_Input input)
{
    RV_827e5583dc3d_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.x = dot(transpose(unity_ObjectToWorld)[3].yxz, float3(_WorldOffsetY, _WorldOffsetX, _WorldOffsetZ));
    u_xlat0.x = u_xlat0.x + _Time.y;
    u_xlat0.xy = mad(float2(_SpeedX, _SpeedY), u_xlat0.xx, input.TEXCOORD0.xy);
    output.TEXCOORD0.xy = mad(u_xlat0.xy, _MainTex_ST.xy, _MainTex_ST.zw);
    output.TEXCOORD1.xy = mad(input.TEXCOORD0.xy, _MaskTex_ST.xy, _MaskTex_ST.zw);
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.COLOR0 = input.COLOR0 * _TintColor;
    return output;
}



struct RF_11b4b85c8b46_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
    float4 COLOR0 : COLOR0;
};

struct RF_11b4b85c8b46_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_11b4b85c8b46_Output RecoveryFragment(RF_11b4b85c8b46_Input input)
{
    RF_11b4b85c8b46_Output output;
    float4 u_xlat0;
    float u_xlat1;
    float u_xlat6;
    u_xlat0 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat0 = u_xlat0 * _Color;
    u_xlat0 = u_xlat0 * input.COLOR0;
    u_xlat1 = _MaskTex.Sample(sampler_MaskTex, input.TEXCOORD1.xy).x;
    u_xlat6 = u_xlat0.w * u_xlat1;
    output.SV_Target0.xyz = ((float3)(u_xlat6)) * u_xlat0.xyz;
    output.SV_Target0.w = u_xlat6;
    return output;
}

#elif (!defined(INSTANCING_ON) && defined(USE_MASK) && defined(USE_SECONDARY))
            // Original Metal program SHA256: vertex 7408ec9e7cc8690737035b286261057c1482c7264d14cb5952c00653ad1637ad; fragment c1d090420f7aa55519317500bbbe47198a38b177e2275fcdbac3c09c0054d5da.
#include "UnityCG.cginc"

float4 _Color;

Texture2D<float4> _MainTex;

float4 _MainTex_ST;

Texture2D<float4> _MaskTex;

float4 _MaskTex_ST;

float4 _SecondaryColor;

float _SecondarySpeedX;

float _SecondarySpeedY;

Texture2D<float4> _SecondaryTex;

float4 _SecondaryTex_ST;

float _SpeedX;

float _SpeedY;

float4 _TintColor;

SamplerState sampler_MainTex;

SamplerState sampler_MaskTex;

SamplerState sampler_SecondaryTex;



struct RV_7408ec9e7cc8_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 COLOR0 : COLOR0;
};

struct RV_7408ec9e7cc8_Output
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
    float2 TEXCOORD2 : TEXCOORD2;
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
};

RV_7408ec9e7cc8_Output RecoveryVertex(RV_7408ec9e7cc8_Input input)
{
    RV_7408ec9e7cc8_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.xy = mad(float2(_SpeedX, _SpeedY), _Time.yy, input.TEXCOORD0.xy);
    output.TEXCOORD0.xy = mad(u_xlat0.xy, _MainTex_ST.xy, _MainTex_ST.zw);
    output.TEXCOORD1.xy = mad(input.TEXCOORD0.xy, _MaskTex_ST.xy, _MaskTex_ST.zw);
    u_xlat0.xy = mad(float2(_SecondarySpeedX, _SecondarySpeedY), _Time.yy, input.TEXCOORD0.xy);
    output.TEXCOORD2.xy = mad(u_xlat0.xy, _SecondaryTex_ST.xy, _SecondaryTex_ST.zw);
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.COLOR0 = input.COLOR0 * _TintColor;
    return output;
}



struct RF_c1d090420f7a_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
    float2 TEXCOORD2 : TEXCOORD2;
    float4 COLOR0 : COLOR0;
};

struct RF_c1d090420f7a_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_c1d090420f7a_Output RecoveryFragment(RF_c1d090420f7a_Input input)
{
    RF_c1d090420f7a_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float u_xlat6;
    u_xlat0 = _SecondaryTex.Sample(sampler_SecondaryTex, input.TEXCOORD2.xy);
    u_xlat0 = u_xlat0 * _SecondaryColor;
    u_xlat0 = u_xlat0 * input.COLOR0;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat1 = u_xlat1 * _Color;
    u_xlat0 = mad(u_xlat1, input.COLOR0, u_xlat0);
    u_xlat1.x = _MaskTex.Sample(sampler_MaskTex, input.TEXCOORD1.xy).x;
    u_xlat6 = u_xlat0.w * u_xlat1.x;
    output.SV_Target0.xyz = ((float3)(u_xlat6)) * u_xlat0.xyz;
    output.SV_Target0.w = u_xlat6;
    return output;
}

#elif (defined(INSTANCING_ON) && defined(USE_MASK) && defined(USE_SECONDARY))
            // Original Metal program SHA256: vertex 980439b28be4d6d2a09ba54e0300dde2dc60ec9f5b973c1c35052e178a5a1fa2; fragment 3888e172f9c23709af84615cf62b7331ab463f3d8e7c79de1ded88f3561898c3.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float4 _MainTex_ST;

Texture2D<float4> _MaskTex;

float4 _MaskTex_ST;

Texture2D<float4> _SecondaryTex;

float4 _SecondaryTex_ST;

UNITY_INSTANCING_BUFFER_START(Props)
    UNITY_DEFINE_INSTANCED_PROP(float4, _Color)
    UNITY_DEFINE_INSTANCED_PROP(float4, _TintColor)
    UNITY_DEFINE_INSTANCED_PROP(float, _SpeedX)
    UNITY_DEFINE_INSTANCED_PROP(float, _SpeedY)
UNITY_INSTANCING_BUFFER_END(Props)

UNITY_INSTANCING_BUFFER_START(SecondaryProps)
    UNITY_DEFINE_INSTANCED_PROP(float4, _SecondaryColor)
    UNITY_DEFINE_INSTANCED_PROP(float, _SecondarySpeedX)
    UNITY_DEFINE_INSTANCED_PROP(float, _SecondarySpeedY)
UNITY_INSTANCING_BUFFER_END(SecondaryProps)

SamplerState sampler_MainTex;

SamplerState sampler_MaskTex;

SamplerState sampler_SecondaryTex;



struct RV_980439b28be4_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 COLOR0 : COLOR0;
    uint recovered_InstanceID : SV_InstanceID;
};

struct RV_980439b28be4_Output
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
    float2 TEXCOORD2 : TEXCOORD2;
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    uint SV_InstanceID0 : TEXCOORD13;
};

RV_980439b28be4_Output RecoveryVertex(RV_980439b28be4_Input input)
{

    RV_980439b28be4_Output output;
    float4 u_xlat0;
    int3 u_xlati0;
    float4 u_xlat1;
    float2 u_xlat2;
    int u_xlati2;
    output.TEXCOORD1.xy = mad(input.TEXCOORD0.xy, _MaskTex_ST.xy, _MaskTex_ST.zw);
    u_xlati0.x = int(input.recovered_InstanceID) + unity_BaseInstanceID;
    u_xlati2 = u_xlati0.x * 0x3;
    u_xlati0.xz = u_xlati0.xx << int2(0x3, 0x1);
    u_xlat1.xy = mad(float2(PropsArray[u_xlati2 / 3]._SpeedX, PropsArray[u_xlati2 / 3]._SpeedY), _Time.yy, input.TEXCOORD0.xy);
    output.COLOR0 = input.COLOR0 * PropsArray[u_xlati2 / 3]._TintColor;
    output.TEXCOORD0.xy = mad(u_xlat1.xy, _MainTex_ST.xy, _MainTex_ST.zw);
    u_xlat2.xy = mad(float2(SecondaryPropsArray[u_xlati0.z / 2]._SecondarySpeedX, SecondaryPropsArray[u_xlati0.z / 2]._SecondarySpeedY), _Time.yy, input.TEXCOORD0.xy);
    output.TEXCOORD2.xy = mad(u_xlat2.xy, _SecondaryTex_ST.xy, _SecondaryTex_ST.zw);
    u_xlat1 = input.POSITION0.yyyy * transpose(unity_Builtins0Array[u_xlati0.x / 8].unity_ObjectToWorldArray)[1];
    u_xlat1 = mad(transpose(unity_Builtins0Array[u_xlati0.x / 8].unity_ObjectToWorldArray)[0], input.POSITION0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_Builtins0Array[u_xlati0.x / 8].unity_ObjectToWorldArray)[2], input.POSITION0.zzzz, u_xlat1);
    u_xlat0 = u_xlat1 + transpose(unity_Builtins0Array[u_xlati0.x / 8].unity_ObjectToWorldArray)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.SV_InstanceID0 = input.recovered_InstanceID;
    return output;
}



struct RF_3888e172f9c2_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
    float2 TEXCOORD2 : TEXCOORD2;
    float4 COLOR0 : COLOR0;
    nointerpolation uint SV_InstanceID0 : TEXCOORD13;
};

struct RF_3888e172f9c2_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_3888e172f9c2_Output RecoveryFragment(RF_3888e172f9c2_Input input)
{
    RF_3888e172f9c2_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    int u_xlati1;
    float4 u_xlat2;
    int u_xlati4;
    float u_xlat9;
    u_xlat0 = _SecondaryTex.Sample(sampler_SecondaryTex, input.TEXCOORD2.xy);
    u_xlati1 = int(input.SV_InstanceID0) + unity_BaseInstanceID;
    u_xlati4 = u_xlati1 << 0x1;
    u_xlati1 = u_xlati1 * 0x3;
    u_xlat0 = u_xlat0 * SecondaryPropsArray[u_xlati4 / 2]._SecondaryColor;
    u_xlat0 = u_xlat0 * input.COLOR0;
    u_xlat2 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat1 = u_xlat2 * PropsArray[u_xlati1 / 3]._Color;
    u_xlat0 = mad(u_xlat1, input.COLOR0, u_xlat0);
    u_xlat1.x = _MaskTex.Sample(sampler_MaskTex, input.TEXCOORD1.xy).x;
    u_xlat9 = u_xlat0.w * u_xlat1.x;
    output.SV_Target0.xyz = ((float3)(u_xlat9)) * u_xlat0.xyz;
    output.SV_Target0.w = u_xlat9;
    return output;
}

#elif (defined(INSTANCING_ON) && defined(USE_OBJECT_SCALE) && defined(USE_SECONDARY)) || (defined(INSTANCING_ON) && defined(USE_OBJECT_SCALE) && defined(USE_WORLD_OFFSET)) || (defined(INSTANCING_ON) && !defined(USE_COLOR_FLASH) && !defined(USE_MASK) && defined(USE_SECONDARY) && defined(USE_WORLD_OFFSET))
            // Original Metal program SHA256: vertex 164cd638913d0504046c849a8d87b5e30c280d95e0d035775dc347b703da0364; fragment 95d868211a26799dfcc2d1b0d537f0f9453a4c573b918c23030e24cca2d7bd2a.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float4 _MainTex_ST;

Texture2D<float4> _SecondaryTex;

float4 _SecondaryTex_ST;

float _WorldOffsetX;

float _WorldOffsetY;

float _WorldOffsetZ;

UNITY_INSTANCING_BUFFER_START(Props)
    UNITY_DEFINE_INSTANCED_PROP(float4, _Color)
    UNITY_DEFINE_INSTANCED_PROP(float4, _TintColor)
    UNITY_DEFINE_INSTANCED_PROP(float, _SpeedX)
    UNITY_DEFINE_INSTANCED_PROP(float, _SpeedY)
    UNITY_DEFINE_INSTANCED_PROP(float3, _ObjectScale)
UNITY_INSTANCING_BUFFER_END(Props)

UNITY_INSTANCING_BUFFER_START(SecondaryProps)
    UNITY_DEFINE_INSTANCED_PROP(float4, _SecondaryColor)
    UNITY_DEFINE_INSTANCED_PROP(float, _SecondarySpeedX)
    UNITY_DEFINE_INSTANCED_PROP(float, _SecondarySpeedY)
UNITY_INSTANCING_BUFFER_END(SecondaryProps)

SamplerState sampler_MainTex;

SamplerState sampler_SecondaryTex;



struct RV_164cd638913d_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 COLOR0 : COLOR0;
    uint recovered_InstanceID : SV_InstanceID;
};

struct RV_164cd638913d_Output
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD2 : TEXCOORD2;
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    uint SV_InstanceID0 : TEXCOORD13;
};

RV_164cd638913d_Output RecoveryVertex(RV_164cd638913d_Input input)
{

    RV_164cd638913d_Output output;
    float4 u_xlat0;
    int3 u_xlati0;
    float4 u_xlat1;
    float2 u_xlat4;
    float2 u_xlat5;
    float u_xlat6;
    u_xlati0.x = int(input.recovered_InstanceID) + unity_BaseInstanceID;
    u_xlati0.xyz = u_xlati0.xxx << int3(0x3, 0x2, 0x1);
    u_xlat6 = dot(transpose(unity_Builtins0Array[u_xlati0.x / 8].unity_ObjectToWorldArray)[3].yxz, float3(_WorldOffsetY, _WorldOffsetX, _WorldOffsetZ));
    u_xlat6 = u_xlat6 + _Time.y;
    u_xlat1.xy = input.TEXCOORD0.xy * PropsArray[u_xlati0.y / 4]._ObjectScale.xyzx.xy;
    u_xlat5.xy = mad(float2(PropsArray[u_xlati0.y / 4]._SpeedX, PropsArray[u_xlati0.y / 4]._SpeedY), ((float2)(u_xlat6)), u_xlat1.xy);
    u_xlat4.xy = mad(float2(SecondaryPropsArray[u_xlati0.z / 2]._SecondarySpeedX, SecondaryPropsArray[u_xlati0.z / 2]._SecondarySpeedY), ((float2)(u_xlat6)), u_xlat1.xy);
    output.TEXCOORD2.xy = mad(u_xlat4.xy, _SecondaryTex_ST.xy, _SecondaryTex_ST.zw);
    output.TEXCOORD0.xy = mad(u_xlat5.xy, _MainTex_ST.xy, _MainTex_ST.zw);
    u_xlat1 = input.POSITION0.yyyy * transpose(unity_Builtins0Array[u_xlati0.x / 8].unity_ObjectToWorldArray)[1];
    u_xlat1 = mad(transpose(unity_Builtins0Array[u_xlati0.x / 8].unity_ObjectToWorldArray)[0], input.POSITION0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_Builtins0Array[u_xlati0.x / 8].unity_ObjectToWorldArray)[2], input.POSITION0.zzzz, u_xlat1);
    u_xlat1 = u_xlat1 + transpose(unity_Builtins0Array[u_xlati0.x / 8].unity_ObjectToWorldArray)[3];
    output.COLOR0 = input.COLOR0 * PropsArray[u_xlati0.y / 4]._TintColor;
    u_xlat0 = u_xlat1.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat0 = mad(transpose(unity_MatrixVP)[0], u_xlat1.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_MatrixVP)[2], u_xlat1.zzzz, u_xlat0);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat1.wwww, u_xlat0);
    output.SV_InstanceID0 = input.recovered_InstanceID;
    return output;
}



struct RF_95d868211a26_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD2 : TEXCOORD2;
    float4 COLOR0 : COLOR0;
    nointerpolation uint SV_InstanceID0 : TEXCOORD13;
};

struct RF_95d868211a26_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_95d868211a26_Output RecoveryFragment(RF_95d868211a26_Input input)
{
    RF_95d868211a26_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    int2 u_xlati1;
    float4 u_xlat2;
    u_xlat0 = _SecondaryTex.Sample(sampler_SecondaryTex, input.TEXCOORD2.xy);
    u_xlati1.x = int(input.SV_InstanceID0) + unity_BaseInstanceID;
    u_xlati1.xy = u_xlati1.xx << int2(0x2, 0x1);
    u_xlat0 = u_xlat0 * SecondaryPropsArray[u_xlati1.y / 2]._SecondaryColor;
    u_xlat0 = u_xlat0 * input.COLOR0;
    u_xlat2 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat1 = u_xlat2 * PropsArray[u_xlati1.x / 4]._Color;
    u_xlat0 = mad(u_xlat1, input.COLOR0, u_xlat0);
    output.SV_Target0.xyz = u_xlat0.www * u_xlat0.xyz;
    output.SV_Target0.w = u_xlat0.w;
    return output;
}

#elif (defined(INSTANCING_ON) && defined(USE_COLOR_FLASH))
            // Original Metal program SHA256: vertex 172a51091ecf59a0254b3d817e6f2aadec093e8b0da2fe7a4dad78c680df552a; fragment cd51f01c76627b11d6d9d1d405c0c49c9cd161a20244cffc1617a5ac13875378.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float4 _MainTex_ST;

UNITY_INSTANCING_BUFFER_START(Props)
    UNITY_DEFINE_INSTANCED_PROP(float4, _Color)
    UNITY_DEFINE_INSTANCED_PROP(float4, _TintColor)
    UNITY_DEFINE_INSTANCED_PROP(float, _SpeedX)
    UNITY_DEFINE_INSTANCED_PROP(float, _SpeedY)
    UNITY_DEFINE_INSTANCED_PROP(float4, _FlashColor)
    UNITY_DEFINE_INSTANCED_PROP(float, _FlashAmount)
UNITY_INSTANCING_BUFFER_END(Props)

SamplerState sampler_MainTex;



struct RV_172a51091ecf_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 COLOR0 : COLOR0;
    uint recovered_InstanceID : SV_InstanceID;
};

struct RV_172a51091ecf_Output
{
    float2 TEXCOORD0 : TEXCOORD0;
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    uint SV_InstanceID0 : TEXCOORD13;
};

RV_172a51091ecf_Output RecoveryVertex(RV_172a51091ecf_Input input)
{

    RV_172a51091ecf_Output output;
    float4 u_xlat0;
    int u_xlati0;
    float4 u_xlat1;
    int u_xlati2;
    float2 u_xlat4;
    u_xlati0 = int(input.recovered_InstanceID) + unity_BaseInstanceID;
    u_xlati2 = u_xlati0 * 0x5;
    u_xlati0 = u_xlati0 << 0x3;
    u_xlat4.xy = mad(float2(PropsArray[u_xlati2 / 5]._SpeedX, PropsArray[u_xlati2 / 5]._SpeedY), _Time.yy, input.TEXCOORD0.xy);
    output.COLOR0 = input.COLOR0 * PropsArray[u_xlati2 / 5]._TintColor;
    output.TEXCOORD0.xy = mad(u_xlat4.xy, _MainTex_ST.xy, _MainTex_ST.zw);
    u_xlat1 = input.POSITION0.yyyy * transpose(unity_Builtins0Array[u_xlati0 / 8].unity_ObjectToWorldArray)[1];
    u_xlat1 = mad(transpose(unity_Builtins0Array[u_xlati0 / 8].unity_ObjectToWorldArray)[0], input.POSITION0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_Builtins0Array[u_xlati0 / 8].unity_ObjectToWorldArray)[2], input.POSITION0.zzzz, u_xlat1);
    u_xlat0 = u_xlat1 + transpose(unity_Builtins0Array[u_xlati0 / 8].unity_ObjectToWorldArray)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.SV_InstanceID0 = input.recovered_InstanceID;
    return output;
}



struct RF_cd51f01c7662_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float4 COLOR0 : COLOR0;
    nointerpolation uint SV_InstanceID0 : TEXCOORD13;
};

struct RF_cd51f01c7662_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_cd51f01c7662_Output RecoveryFragment(RF_cd51f01c7662_Input input)
{
    RF_cd51f01c7662_Output output;
    float4 u_xlat0;
    int u_xlati1;
    float3 u_xlat3;
    u_xlat0 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlati1 = int(input.SV_InstanceID0) + unity_BaseInstanceID;
    u_xlati1 = u_xlati1 * 0x5;
    u_xlat0 = u_xlat0 * PropsArray[u_xlati1 / 5]._Color;
    u_xlat3.xyz = mad((-u_xlat0.xyz), input.COLOR0.xyz, PropsArray[u_xlati1 / 5]._FlashColor.xyz);
    u_xlat0 = u_xlat0 * input.COLOR0;
    u_xlat0.xyz = mad(((float3)(PropsArray[u_xlati1 / 5]._FlashAmount)), u_xlat3.xyz, u_xlat0.xyz);
    output.SV_Target0.xyz = u_xlat0.www * u_xlat0.xyz;
    output.SV_Target0.w = u_xlat0.w;
    return output;
}

#elif (!defined(INSTANCING_ON) && defined(USE_OBJECT_SCALE) && defined(USE_SECONDARY)) || (!defined(INSTANCING_ON) && defined(USE_OBJECT_SCALE) && defined(USE_WORLD_OFFSET)) || (!defined(INSTANCING_ON) && !defined(USE_COLOR_FLASH) && !defined(USE_MASK) && defined(USE_SECONDARY) && defined(USE_WORLD_OFFSET))
            // Original Metal program SHA256: vertex 41f8c29e890d152650f41811231f500e4ffe0efdcf63d11f6a3c891f7d1a064d; fragment 4e0eb74b2ebf586f32ae04c7132903f4238391cdfe41af2e27f477e4c76d7658.
#include "UnityCG.cginc"

float4 _Color;

Texture2D<float4> _MainTex;

float4 _MainTex_ST;

float3 _ObjectScale;

float4 _SecondaryColor;

float _SecondarySpeedX;

float _SecondarySpeedY;

Texture2D<float4> _SecondaryTex;

float4 _SecondaryTex_ST;

float _SpeedX;

float _SpeedY;

float4 _TintColor;

float _WorldOffsetX;

float _WorldOffsetY;

float _WorldOffsetZ;

SamplerState sampler_MainTex;

SamplerState sampler_SecondaryTex;



struct RV_41f8c29e890d_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 COLOR0 : COLOR0;
};

struct RV_41f8c29e890d_Output
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD2 : TEXCOORD2;
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
};

RV_41f8c29e890d_Output RecoveryVertex(RV_41f8c29e890d_Input input)
{
    RV_41f8c29e890d_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float2 u_xlat2;
    u_xlat0.x = dot(transpose(unity_ObjectToWorld)[3].yxz, float3(_WorldOffsetY, _WorldOffsetX, _WorldOffsetZ));
    u_xlat0.x = u_xlat0.x + _Time.y;
    u_xlat2.xy = input.TEXCOORD0.xy * _ObjectScale.xyzx.xy;
    u_xlat1.xy = mad(float2(_SpeedX, _SpeedY), u_xlat0.xx, u_xlat2.xy);
    u_xlat0.xy = mad(float2(_SecondarySpeedX, _SecondarySpeedY), u_xlat0.xx, u_xlat2.xy);
    output.TEXCOORD2.xy = mad(u_xlat0.xy, _SecondaryTex_ST.xy, _SecondaryTex_ST.zw);
    output.TEXCOORD0.xy = mad(u_xlat1.xy, _MainTex_ST.xy, _MainTex_ST.zw);
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.COLOR0 = input.COLOR0 * _TintColor;
    return output;
}



struct RF_4e0eb74b2ebf_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD2 : TEXCOORD2;
    float4 COLOR0 : COLOR0;
};

struct RF_4e0eb74b2ebf_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_4e0eb74b2ebf_Output RecoveryFragment(RF_4e0eb74b2ebf_Input input)
{
    RF_4e0eb74b2ebf_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = _SecondaryTex.Sample(sampler_SecondaryTex, input.TEXCOORD2.xy);
    u_xlat0 = u_xlat0 * _SecondaryColor;
    u_xlat0 = u_xlat0 * input.COLOR0;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat1 = u_xlat1 * _Color;
    u_xlat0 = mad(u_xlat1, input.COLOR0, u_xlat0);
    output.SV_Target0.xyz = u_xlat0.www * u_xlat0.xyz;
    output.SV_Target0.w = u_xlat0.w;
    return output;
}

#elif (defined(INSTANCING_ON) && !defined(USE_COLOR_FLASH) && !defined(USE_MASK) && !defined(USE_OBJECT_SCALE) && !defined(USE_SECONDARY)) || (defined(INSTANCING_ON) && defined(USE_OBJECT_SCALE) && !defined(USE_SECONDARY) && !defined(USE_WORLD_OFFSET)) || (defined(INSTANCING_ON) && !defined(USE_COLOR_FLASH) && !defined(USE_MASK) && !defined(USE_OBJECT_SCALE) && !defined(USE_WORLD_OFFSET))
            // Original Metal program SHA256: vertex 97ee9eb6b9b1c63c9f692452a7f6251e4f5d3c07eae5b9c4dc829fef018110d4; fragment 866f9bb1cdbce42fb148356f0066e8908943cda3cb2cacc7827d72895381c930.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float4 _MainTex_ST;

UNITY_INSTANCING_BUFFER_START(Props)
    UNITY_DEFINE_INSTANCED_PROP(float4, _Color)
    UNITY_DEFINE_INSTANCED_PROP(float4, _TintColor)
    UNITY_DEFINE_INSTANCED_PROP(float, _SpeedX)
    UNITY_DEFINE_INSTANCED_PROP(float, _SpeedY)
UNITY_INSTANCING_BUFFER_END(Props)

SamplerState sampler_MainTex;



struct RV_97ee9eb6b9b1_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 COLOR0 : COLOR0;
    uint recovered_InstanceID : SV_InstanceID;
};

struct RV_97ee9eb6b9b1_Output
{
    float2 TEXCOORD0 : TEXCOORD0;
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    uint SV_InstanceID0 : TEXCOORD13;
};

RV_97ee9eb6b9b1_Output RecoveryVertex(RV_97ee9eb6b9b1_Input input)
{

    RV_97ee9eb6b9b1_Output output;
    float4 u_xlat0;
    int u_xlati0;
    float4 u_xlat1;
    int u_xlati2;
    float2 u_xlat4;
    u_xlati0 = int(input.recovered_InstanceID) + unity_BaseInstanceID;
    u_xlati2 = u_xlati0 * 0x3;
    u_xlati0 = u_xlati0 << 0x3;
    u_xlat4.xy = mad(float2(PropsArray[u_xlati2 / 3]._SpeedX, PropsArray[u_xlati2 / 3]._SpeedY), _Time.yy, input.TEXCOORD0.xy);
    output.COLOR0 = input.COLOR0 * PropsArray[u_xlati2 / 3]._TintColor;
    output.TEXCOORD0.xy = mad(u_xlat4.xy, _MainTex_ST.xy, _MainTex_ST.zw);
    u_xlat1 = input.POSITION0.yyyy * transpose(unity_Builtins0Array[u_xlati0 / 8].unity_ObjectToWorldArray)[1];
    u_xlat1 = mad(transpose(unity_Builtins0Array[u_xlati0 / 8].unity_ObjectToWorldArray)[0], input.POSITION0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_Builtins0Array[u_xlati0 / 8].unity_ObjectToWorldArray)[2], input.POSITION0.zzzz, u_xlat1);
    u_xlat0 = u_xlat1 + transpose(unity_Builtins0Array[u_xlati0 / 8].unity_ObjectToWorldArray)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.SV_InstanceID0 = input.recovered_InstanceID;
    return output;
}



struct RF_866f9bb1cdbc_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float4 COLOR0 : COLOR0;
    nointerpolation uint SV_InstanceID0 : TEXCOORD13;
};

struct RF_866f9bb1cdbc_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_866f9bb1cdbc_Output RecoveryFragment(RF_866f9bb1cdbc_Input input)
{
    RF_866f9bb1cdbc_Output output;
    float4 u_xlat0;
    int u_xlati0;
    float4 u_xlat1;
    u_xlati0 = int(input.SV_InstanceID0) + unity_BaseInstanceID;
    u_xlati0 = u_xlati0 * 0x3;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat0 = u_xlat1 * PropsArray[u_xlati0 / 3]._Color;
    u_xlat0 = u_xlat0 * input.COLOR0;
    output.SV_Target0.xyz = u_xlat0.www * u_xlat0.xyz;
    output.SV_Target0.w = u_xlat0.w;
    return output;
}

#elif (!defined(INSTANCING_ON) && defined(USE_COLOR_FLASH))
            // Original Metal program SHA256: vertex be5aadff7a14c4d17d3fa9313f3fa91bd2d8ec9a159e39cb9f6ed5b63ba07666; fragment 1f232d6bf2108c4235edebaa7915e2f62d8ce7e77db6c5ec84789836cab38857.
#include "UnityCG.cginc"

float4 _Color;

float _FlashAmount;

float4 _FlashColor;

Texture2D<float4> _MainTex;

float4 _MainTex_ST;

float _SpeedX;

float _SpeedY;

float4 _TintColor;

SamplerState sampler_MainTex;



struct RV_be5aadff7a14_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 COLOR0 : COLOR0;
};

struct RV_be5aadff7a14_Output
{
    float2 TEXCOORD0 : TEXCOORD0;
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
};

RV_be5aadff7a14_Output RecoveryVertex(RV_be5aadff7a14_Input input)
{
    RV_be5aadff7a14_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.xy = mad(float2(_SpeedX, _SpeedY), _Time.yy, input.TEXCOORD0.xy);
    output.TEXCOORD0.xy = mad(u_xlat0.xy, _MainTex_ST.xy, _MainTex_ST.zw);
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.COLOR0 = input.COLOR0 * _TintColor;
    return output;
}



struct RF_1f232d6bf210_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float4 COLOR0 : COLOR0;
};

struct RF_1f232d6bf210_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_1f232d6bf210_Output RecoveryFragment(RF_1f232d6bf210_Input input)
{
    RF_1f232d6bf210_Output output;
    float4 u_xlat0;
    float3 u_xlat1;
    u_xlat0 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat0 = u_xlat0 * _Color;
    u_xlat1.xyz = mad((-u_xlat0.xyz), input.COLOR0.xyz, _FlashColor.xyz);
    u_xlat0 = u_xlat0 * input.COLOR0;
    u_xlat0.xyz = mad(((float3)(_FlashAmount)), u_xlat1.xyz, u_xlat0.xyz);
    output.SV_Target0.xyz = u_xlat0.www * u_xlat0.xyz;
    output.SV_Target0.w = u_xlat0.w;
    return output;
}

#else
            // Original Metal program SHA256: vertex e8116f3e8b37b7937560afe68c71aeb896c85a78887b6dd070713519ebd725a0; fragment 9e2d10ad6e777c3f5d967fde7b7d654066b5ccda7c4c2e8d010771816b3f38ff.
#include "UnityCG.cginc"

float4 _Color;

Texture2D<float4> _MainTex;

float4 _MainTex_ST;

float _SpeedX;

float _SpeedY;

float4 _TintColor;

SamplerState sampler_MainTex;



struct RV_e8116f3e8b37_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 COLOR0 : COLOR0;
};

struct RV_e8116f3e8b37_Output
{
    float2 TEXCOORD0 : TEXCOORD0;
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
};

RV_e8116f3e8b37_Output RecoveryVertex(RV_e8116f3e8b37_Input input)
{
    RV_e8116f3e8b37_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.xy = mad(float2(_SpeedX, _SpeedY), _Time.yy, input.TEXCOORD0.xy);
    output.TEXCOORD0.xy = mad(u_xlat0.xy, _MainTex_ST.xy, _MainTex_ST.zw);
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.COLOR0 = input.COLOR0 * _TintColor;
    return output;
}



struct RF_9e2d10ad6e77_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float4 COLOR0 : COLOR0;
};

struct RF_9e2d10ad6e77_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_9e2d10ad6e77_Output RecoveryFragment(RF_9e2d10ad6e77_Input input)
{
    RF_9e2d10ad6e77_Output output;
    float4 u_xlat0;
    u_xlat0 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat0 = u_xlat0 * _Color;
    u_xlat0 = u_xlat0 * input.COLOR0;
    output.SV_Target0.xyz = u_xlat0.www * u_xlat0.xyz;
    output.SV_Target0.w = u_xlat0.w;
    return output;
}

#endif
            ENDHLSL
        }
    }
}
