// Reconstructed from the licensed GOG macOS 1.0.30000 captured Metal programs.
// Generated by tools/shader_reconstruction/shaderlab_generator.py.
// Original serialized Shader SHA256: c13cc90dec74a660376e961590b00d7162f7d8d54453ce345a7eca53c42a6e14
// Properties, render states, texture samplers, and retained variants come from the original data.
// Extra keyword combinations select a captured variant; see batch-generation-manifest.json.
Shader "Sprites/Screen"
{
    Properties
    {
        [PerRendererData] _MainTex ("Sprite Texture", 2D) = "white" {}
        _Color ("Tint", Color) = (1, 1, 1, 1)
        [MaterialToggle] PixelSnap ("Pixel snap", Float) = 0
        [HideInInspector] _RendererColor ("RendererColor", Color) = (1, 1, 1, 1)
        [HideInInspector] _Flip ("Flip", Vector) = (1, 1, 1, 1)
        [PerRendererData] _AlphaTex ("External Alpha", 2D) = "white" {}
        [PerRendererData] _EnableExternalAlpha ("Enable External Alpha", Float) = 0
    }
    SubShader
    {
        Tags { "CanUseSpriteAtlas"="true" "IGNOREPROJECTOR"="true" "PreviewType"="Plane" "QUEUE"="Transparent" "RenderType"="Transparent" }
        GrabPass
        {
        }
        Pass
        {
            Tags { "CanUseSpriteAtlas"="true" "IGNOREPROJECTOR"="true" "PreviewType"="Plane" "QUEUE"="Transparent" "RenderType"="Transparent" }
            Cull Off
            ZClip On
            ZTest LEqual
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend SrcAlpha OneMinusSrcAlpha
            BlendOp Add
            ColorMask RGBA
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#pragma multi_compile __ DITHERING_NOISE
#pragma multi_compile __ ETC1_EXTERNAL_ALPHA
#pragma multi_compile __ PIXELSNAP_ON
#if (!defined(DITHERING_NOISE) && !defined(ETC1_EXTERNAL_ALPHA) && !defined(PIXELSNAP_ON))
            // Original Metal program SHA256: vertex 24cb19e59128409aec6f5b006f3c2a9321e7f242cc5fa73088d50a178f2685ba; fragment 4b47a8b933befeaaaeb34b51fcdbb47b4a0596bc123eb05cfac3da1789b65cd5.
#include "UnityCG.cginc"

float4 _Color;

Texture2D<float4> _GrabTexture;

Texture2D<float4> _MainTex;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_GrabTexture;

SamplerState sampler_MainTex;



struct RV_24cb19e59128_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_24cb19e59128_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_24cb19e59128_Output RecoveryVertex(RV_24cb19e59128_Input input)
{
    RV_24cb19e59128_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.xy = input.POSITION0.xy * _Flip.xyxx.xy;
    u_xlat1 = u_xlat0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlat0 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat0 * _RendererColor;
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlat0.y = u_xlat0.y * _ProjectionParams.x;
    u_xlat1.xzw = u_xlat0.xwy * float3(0.5, 0.5, 0.5);
    output.TEXCOORD1.zw = u_xlat0.zw;
    output.TEXCOORD1.xy = u_xlat1.zz + u_xlat1.xw;
    return output;
}



struct RF_4b47a8b933be_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_4b47a8b933be_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_4b47a8b933be_Output RecoveryFragment(RF_4b47a8b933be_Input input)
{
    RF_4b47a8b933be_Output output;
    float4 u_xlat0;
    bool3 u_xlatb0;
    float3 u_xlat1;
    float3 u_xlat2;
    float3 u_xlat3;
    u_xlat0 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat1.xyz = mad(u_xlat0.xyz, input.COLOR0.xyz, float3(-0.5, -0.5, -0.5));
    u_xlat0 = u_xlat0 * input.COLOR0;
    u_xlat1.xyz = mad((-u_xlat1.xyz), float3(2.0, 2.0, 2.0), float3(1.0, 1.0, 1.0));
    u_xlat2.xy = input.TEXCOORD1.xy / input.TEXCOORD1.ww;
    u_xlat2.xyz = _GrabTexture.Sample(sampler_GrabTexture, u_xlat2.xy).xyz;
    u_xlat1.xyz = u_xlat2.xyz / u_xlat1.xyz;
    u_xlat2.xyz = (-u_xlat2.xyz) + float3(1.0, 1.0, 1.0);
    u_xlat3.xyz = u_xlat0.xyz + u_xlat0.xyz;
    u_xlat2.xyz = u_xlat2.xyz / u_xlat3.xyz;
    u_xlat2.xyz = (-u_xlat2.xyz) + float3(1.0, 1.0, 1.0);
    u_xlatb0.xyz = (float3(0.5, 0.5, 0.5)<u_xlat0.xyz);
    output.SV_Target0.w = u_xlat0.w;
    output.SV_Target0.x = (u_xlatb0.x) ? u_xlat1.x : u_xlat2.x;
    output.SV_Target0.y = (u_xlatb0.y) ? u_xlat1.y : u_xlat2.y;
    output.SV_Target0.z = (u_xlatb0.z) ? u_xlat1.z : u_xlat2.z;
    return output;
}

#elif (defined(DITHERING_NOISE) && !defined(ETC1_EXTERNAL_ALPHA) && !defined(PIXELSNAP_ON))
            // Original Metal program SHA256: vertex 24cb19e59128409aec6f5b006f3c2a9321e7f242cc5fa73088d50a178f2685ba; fragment 66ccc0a6dc2f6a362b90498559cffd6a847623df52e71c8c563b60a9b934628a.
#include "UnityCG.cginc"

float4 _Color;

Texture2D<float4> _GrabTexture;

Texture2D<float4> _MainTex;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_GrabTexture;

SamplerState sampler_MainTex;



struct RV_24cb19e59128_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_24cb19e59128_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_24cb19e59128_Output RecoveryVertex(RV_24cb19e59128_Input input)
{
    RV_24cb19e59128_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.xy = input.POSITION0.xy * _Flip.xyxx.xy;
    u_xlat1 = u_xlat0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlat0 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat0 * _RendererColor;
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlat0.y = u_xlat0.y * _ProjectionParams.x;
    u_xlat1.xzw = u_xlat0.xwy * float3(0.5, 0.5, 0.5);
    output.TEXCOORD1.zw = u_xlat0.zw;
    output.TEXCOORD1.xy = u_xlat1.zz + u_xlat1.xw;
    return output;
}



struct RF_66ccc0a6dc2f_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_66ccc0a6dc2f_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_66ccc0a6dc2f_Output RecoveryFragment(RF_66ccc0a6dc2f_Input input, float4 mtl_FragCoord : SV_POSITION)
{
    RF_66ccc0a6dc2f_Output output;
    float4 hlslcc_FragCoord = float4(mtl_FragCoord.xyz, 1.0/mtl_FragCoord.w);
    float4 u_xlat0;
    float3 u_xlat1;
    float3 u_xlat2;
    float3 u_xlat3;
    bool3 u_xlatb3;
    u_xlat0 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat1.xyz = mad(u_xlat0.xyz, input.COLOR0.xyz, float3(-0.5, -0.5, -0.5));
    u_xlat0 = u_xlat0 * input.COLOR0;
    u_xlat1.xyz = mad((-u_xlat1.xyz), float3(2.0, 2.0, 2.0), float3(1.0, 1.0, 1.0));
    u_xlat2.xy = input.TEXCOORD1.xy / input.TEXCOORD1.ww;
    u_xlat2.xyz = _GrabTexture.Sample(sampler_GrabTexture, u_xlat2.xy).xyz;
    u_xlat1.xyz = u_xlat2.xyz / u_xlat1.xyz;
    u_xlat2.xyz = (-u_xlat2.xyz) + float3(1.0, 1.0, 1.0);
    u_xlat3.xyz = u_xlat0.xyz + u_xlat0.xyz;
    u_xlat2.xyz = u_xlat2.xyz / u_xlat3.xyz;
    u_xlat2.xyz = (-u_xlat2.xyz) + float3(1.0, 1.0, 1.0);
    u_xlatb3.xyz = (float3(0.5, 0.5, 0.5)<u_xlat0.xyz);
    u_xlat0.x = (u_xlatb3.x) ? u_xlat1.x : u_xlat2.x;
    u_xlat0.y = (u_xlatb3.y) ? u_xlat1.y : u_xlat2.y;
    u_xlat0.z = (u_xlatb3.z) ? u_xlat1.z : u_xlat2.z;
    u_xlat1.x = dot(hlslcc_FragCoord.xy, float2(0.0671105608, 0.00583714992));
    u_xlat1.x = frac(u_xlat1.x);
    u_xlat1.x = u_xlat1.x * 52.9829178;
    u_xlat1.x = frac(u_xlat1.x);
    u_xlat1.x = mad(u_xlat1.x, 0.00392156886, -0.00196078443);
    output.SV_Target0 = u_xlat0 + u_xlat1.xxxx;
    return output;
}

#elif (defined(DITHERING_NOISE) && defined(ETC1_EXTERNAL_ALPHA) && !defined(PIXELSNAP_ON))
            // Original Metal program SHA256: vertex 24cb19e59128409aec6f5b006f3c2a9321e7f242cc5fa73088d50a178f2685ba; fragment 6f0a37ee3618043d5af41d9c5fb8fa5e2f596bb3414cd80d3398678f7e2ef549.
#include "UnityCG.cginc"

Texture2D<float4> _AlphaTex;

float4 _Color;

Texture2D<float4> _GrabTexture;

Texture2D<float4> _MainTex;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_AlphaTex;

SamplerState sampler_GrabTexture;

SamplerState sampler_MainTex;



struct RV_24cb19e59128_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_24cb19e59128_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_24cb19e59128_Output RecoveryVertex(RV_24cb19e59128_Input input)
{
    RV_24cb19e59128_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.xy = input.POSITION0.xy * _Flip.xyxx.xy;
    u_xlat1 = u_xlat0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlat0 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat0 * _RendererColor;
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlat0.y = u_xlat0.y * _ProjectionParams.x;
    u_xlat1.xzw = u_xlat0.xwy * float3(0.5, 0.5, 0.5);
    output.TEXCOORD1.zw = u_xlat0.zw;
    output.TEXCOORD1.xy = u_xlat1.zz + u_xlat1.xw;
    return output;
}



struct RF_6f0a37ee3618_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_6f0a37ee3618_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_6f0a37ee3618_Output RecoveryFragment(RF_6f0a37ee3618_Input input, float4 mtl_FragCoord : SV_POSITION)
{
    RF_6f0a37ee3618_Output output;
    float4 hlslcc_FragCoord = float4(mtl_FragCoord.xyz, 1.0/mtl_FragCoord.w);
    float3 u_xlat0;
    float3 u_xlat1;
    float4 u_xlat2;
    bool3 u_xlatb2;
    float4 u_xlat3;
    float u_xlat12;
    u_xlat0.xy = input.TEXCOORD1.xy / input.TEXCOORD1.ww;
    u_xlat0.xyz = _GrabTexture.Sample(sampler_GrabTexture, u_xlat0.xy).xyz;
    u_xlat1.xyz = (-u_xlat0.xyz) + float3(1.0, 1.0, 1.0);
    u_xlat12 = _AlphaTex.Sample(sampler_AlphaTex, input.TEXCOORD0.xy).x;
    u_xlat2 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat12 = u_xlat12 + (-u_xlat2.w);
    u_xlat2.w = mad(_EnableExternalAlpha, u_xlat12, u_xlat2.w);
    u_xlat3 = u_xlat2 * input.COLOR0;
    u_xlat2.xyz = mad(u_xlat2.xyz, input.COLOR0.xyz, float3(-0.5, -0.5, -0.5));
    u_xlat2.xyz = mad((-u_xlat2.xyz), float3(2.0, 2.0, 2.0), float3(1.0, 1.0, 1.0));
    u_xlat0.xyz = u_xlat0.xyz / u_xlat2.xyz;
    u_xlat2.xyz = u_xlat3.xyz + u_xlat3.xyz;
    u_xlat1.xyz = u_xlat1.xyz / u_xlat2.xyz;
    u_xlat1.xyz = (-u_xlat1.xyz) + float3(1.0, 1.0, 1.0);
    u_xlatb2.xyz = (float3(0.5, 0.5, 0.5)<u_xlat3.xyz);
    u_xlat3.x = (u_xlatb2.x) ? u_xlat0.x : u_xlat1.x;
    u_xlat3.y = (u_xlatb2.y) ? u_xlat0.y : u_xlat1.y;
    u_xlat3.z = (u_xlatb2.z) ? u_xlat0.z : u_xlat1.z;
    u_xlat0.x = dot(hlslcc_FragCoord.xy, float2(0.0671105608, 0.00583714992));
    u_xlat0.x = frac(u_xlat0.x);
    u_xlat0.x = u_xlat0.x * 52.9829178;
    u_xlat0.x = frac(u_xlat0.x);
    u_xlat0.x = mad(u_xlat0.x, 0.00392156886, -0.00196078443);
    output.SV_Target0 = u_xlat0.xxxx + u_xlat3;
    return output;
}

#elif (!defined(DITHERING_NOISE) && defined(ETC1_EXTERNAL_ALPHA) && !defined(PIXELSNAP_ON))
            // Original Metal program SHA256: vertex 24cb19e59128409aec6f5b006f3c2a9321e7f242cc5fa73088d50a178f2685ba; fragment b330ccda84006368d71a47b180d63f43543ecc76c4fb409adfd611e040a5caa6.
#include "UnityCG.cginc"

Texture2D<float4> _AlphaTex;

float4 _Color;

Texture2D<float4> _GrabTexture;

Texture2D<float4> _MainTex;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_AlphaTex;

SamplerState sampler_GrabTexture;

SamplerState sampler_MainTex;



struct RV_24cb19e59128_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_24cb19e59128_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_24cb19e59128_Output RecoveryVertex(RV_24cb19e59128_Input input)
{
    RV_24cb19e59128_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.xy = input.POSITION0.xy * _Flip.xyxx.xy;
    u_xlat1 = u_xlat0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlat0 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat0 * _RendererColor;
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlat0.y = u_xlat0.y * _ProjectionParams.x;
    u_xlat1.xzw = u_xlat0.xwy * float3(0.5, 0.5, 0.5);
    output.TEXCOORD1.zw = u_xlat0.zw;
    output.TEXCOORD1.xy = u_xlat1.zz + u_xlat1.xw;
    return output;
}



struct RF_b330ccda8400_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_b330ccda8400_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_b330ccda8400_Output RecoveryFragment(RF_b330ccda8400_Input input)
{
    RF_b330ccda8400_Output output;
    float3 u_xlat0;
    float3 u_xlat1;
    float4 u_xlat2;
    bool3 u_xlatb2;
    float4 u_xlat3;
    float u_xlat12;
    u_xlat0.xy = input.TEXCOORD1.xy / input.TEXCOORD1.ww;
    u_xlat0.xyz = _GrabTexture.Sample(sampler_GrabTexture, u_xlat0.xy).xyz;
    u_xlat1.xyz = (-u_xlat0.xyz) + float3(1.0, 1.0, 1.0);
    u_xlat12 = _AlphaTex.Sample(sampler_AlphaTex, input.TEXCOORD0.xy).x;
    u_xlat2 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat12 = u_xlat12 + (-u_xlat2.w);
    u_xlat2.w = mad(_EnableExternalAlpha, u_xlat12, u_xlat2.w);
    u_xlat3 = u_xlat2 * input.COLOR0;
    u_xlat2.xyz = mad(u_xlat2.xyz, input.COLOR0.xyz, float3(-0.5, -0.5, -0.5));
    u_xlat2.xyz = mad((-u_xlat2.xyz), float3(2.0, 2.0, 2.0), float3(1.0, 1.0, 1.0));
    u_xlat0.xyz = u_xlat0.xyz / u_xlat2.xyz;
    u_xlat2.xyz = u_xlat3.xyz + u_xlat3.xyz;
    u_xlat1.xyz = u_xlat1.xyz / u_xlat2.xyz;
    u_xlat1.xyz = (-u_xlat1.xyz) + float3(1.0, 1.0, 1.0);
    u_xlatb2.xyz = (float3(0.5, 0.5, 0.5)<u_xlat3.xyz);
    output.SV_Target0.w = u_xlat3.w;
    output.SV_Target0.x = (u_xlatb2.x) ? u_xlat0.x : u_xlat1.x;
    output.SV_Target0.y = (u_xlatb2.y) ? u_xlat0.y : u_xlat1.y;
    output.SV_Target0.z = (u_xlatb2.z) ? u_xlat0.z : u_xlat1.z;
    return output;
}

#elif (!defined(DITHERING_NOISE) && !defined(ETC1_EXTERNAL_ALPHA) && defined(PIXELSNAP_ON))
            // Original Metal program SHA256: vertex 47c247524031f60b4bc18e6f82bd2c78fe2dac250414a15c05629d4095d109ac; fragment 4b47a8b933befeaaaeb34b51fcdbb47b4a0596bc123eb05cfac3da1789b65cd5.
#include "UnityCG.cginc"

float4 _Color;

Texture2D<float4> _GrabTexture;

Texture2D<float4> _MainTex;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_GrabTexture;

SamplerState sampler_MainTex;



struct RV_47c247524031_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_47c247524031_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_47c247524031_Output RecoveryVertex(RV_47c247524031_Input input)
{
    RV_47c247524031_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.xy = input.POSITION0.xy * _Flip.xyxx.xy;
    u_xlat1 = u_xlat0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlat0.xy = u_xlat0.xy / u_xlat0.ww;
    u_xlat1.xy = _ScreenParams.xy * float2(0.5, 0.5);
    u_xlat0.xy = u_xlat0.xy * u_xlat1.xy;
    u_xlat0.xy = round(u_xlat0.xy);
    u_xlat0.xy = u_xlat0.xy / u_xlat1.xy;
    output.mtl_Position.xy = u_xlat0.ww * u_xlat0.xy;
    output.mtl_Position.zw = u_xlat0.zw;
    u_xlat0 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat0 * _RendererColor;
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlat0.y = u_xlat0.y * _ProjectionParams.x;
    u_xlat1.xzw = u_xlat0.xwy * float3(0.5, 0.5, 0.5);
    output.TEXCOORD1.zw = u_xlat0.zw;
    output.TEXCOORD1.xy = u_xlat1.zz + u_xlat1.xw;
    return output;
}



struct RF_4b47a8b933be_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_4b47a8b933be_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_4b47a8b933be_Output RecoveryFragment(RF_4b47a8b933be_Input input)
{
    RF_4b47a8b933be_Output output;
    float4 u_xlat0;
    bool3 u_xlatb0;
    float3 u_xlat1;
    float3 u_xlat2;
    float3 u_xlat3;
    u_xlat0 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat1.xyz = mad(u_xlat0.xyz, input.COLOR0.xyz, float3(-0.5, -0.5, -0.5));
    u_xlat0 = u_xlat0 * input.COLOR0;
    u_xlat1.xyz = mad((-u_xlat1.xyz), float3(2.0, 2.0, 2.0), float3(1.0, 1.0, 1.0));
    u_xlat2.xy = input.TEXCOORD1.xy / input.TEXCOORD1.ww;
    u_xlat2.xyz = _GrabTexture.Sample(sampler_GrabTexture, u_xlat2.xy).xyz;
    u_xlat1.xyz = u_xlat2.xyz / u_xlat1.xyz;
    u_xlat2.xyz = (-u_xlat2.xyz) + float3(1.0, 1.0, 1.0);
    u_xlat3.xyz = u_xlat0.xyz + u_xlat0.xyz;
    u_xlat2.xyz = u_xlat2.xyz / u_xlat3.xyz;
    u_xlat2.xyz = (-u_xlat2.xyz) + float3(1.0, 1.0, 1.0);
    u_xlatb0.xyz = (float3(0.5, 0.5, 0.5)<u_xlat0.xyz);
    output.SV_Target0.w = u_xlat0.w;
    output.SV_Target0.x = (u_xlatb0.x) ? u_xlat1.x : u_xlat2.x;
    output.SV_Target0.y = (u_xlatb0.y) ? u_xlat1.y : u_xlat2.y;
    output.SV_Target0.z = (u_xlatb0.z) ? u_xlat1.z : u_xlat2.z;
    return output;
}

#elif (defined(DITHERING_NOISE) && !defined(ETC1_EXTERNAL_ALPHA) && defined(PIXELSNAP_ON))
            // Original Metal program SHA256: vertex 47c247524031f60b4bc18e6f82bd2c78fe2dac250414a15c05629d4095d109ac; fragment 66ccc0a6dc2f6a362b90498559cffd6a847623df52e71c8c563b60a9b934628a.
#include "UnityCG.cginc"

float4 _Color;

Texture2D<float4> _GrabTexture;

Texture2D<float4> _MainTex;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_GrabTexture;

SamplerState sampler_MainTex;



struct RV_47c247524031_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_47c247524031_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_47c247524031_Output RecoveryVertex(RV_47c247524031_Input input)
{
    RV_47c247524031_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.xy = input.POSITION0.xy * _Flip.xyxx.xy;
    u_xlat1 = u_xlat0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlat0.xy = u_xlat0.xy / u_xlat0.ww;
    u_xlat1.xy = _ScreenParams.xy * float2(0.5, 0.5);
    u_xlat0.xy = u_xlat0.xy * u_xlat1.xy;
    u_xlat0.xy = round(u_xlat0.xy);
    u_xlat0.xy = u_xlat0.xy / u_xlat1.xy;
    output.mtl_Position.xy = u_xlat0.ww * u_xlat0.xy;
    output.mtl_Position.zw = u_xlat0.zw;
    u_xlat0 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat0 * _RendererColor;
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlat0.y = u_xlat0.y * _ProjectionParams.x;
    u_xlat1.xzw = u_xlat0.xwy * float3(0.5, 0.5, 0.5);
    output.TEXCOORD1.zw = u_xlat0.zw;
    output.TEXCOORD1.xy = u_xlat1.zz + u_xlat1.xw;
    return output;
}



struct RF_66ccc0a6dc2f_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_66ccc0a6dc2f_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_66ccc0a6dc2f_Output RecoveryFragment(RF_66ccc0a6dc2f_Input input, float4 mtl_FragCoord : SV_POSITION)
{
    RF_66ccc0a6dc2f_Output output;
    float4 hlslcc_FragCoord = float4(mtl_FragCoord.xyz, 1.0/mtl_FragCoord.w);
    float4 u_xlat0;
    float3 u_xlat1;
    float3 u_xlat2;
    float3 u_xlat3;
    bool3 u_xlatb3;
    u_xlat0 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat1.xyz = mad(u_xlat0.xyz, input.COLOR0.xyz, float3(-0.5, -0.5, -0.5));
    u_xlat0 = u_xlat0 * input.COLOR0;
    u_xlat1.xyz = mad((-u_xlat1.xyz), float3(2.0, 2.0, 2.0), float3(1.0, 1.0, 1.0));
    u_xlat2.xy = input.TEXCOORD1.xy / input.TEXCOORD1.ww;
    u_xlat2.xyz = _GrabTexture.Sample(sampler_GrabTexture, u_xlat2.xy).xyz;
    u_xlat1.xyz = u_xlat2.xyz / u_xlat1.xyz;
    u_xlat2.xyz = (-u_xlat2.xyz) + float3(1.0, 1.0, 1.0);
    u_xlat3.xyz = u_xlat0.xyz + u_xlat0.xyz;
    u_xlat2.xyz = u_xlat2.xyz / u_xlat3.xyz;
    u_xlat2.xyz = (-u_xlat2.xyz) + float3(1.0, 1.0, 1.0);
    u_xlatb3.xyz = (float3(0.5, 0.5, 0.5)<u_xlat0.xyz);
    u_xlat0.x = (u_xlatb3.x) ? u_xlat1.x : u_xlat2.x;
    u_xlat0.y = (u_xlatb3.y) ? u_xlat1.y : u_xlat2.y;
    u_xlat0.z = (u_xlatb3.z) ? u_xlat1.z : u_xlat2.z;
    u_xlat1.x = dot(hlslcc_FragCoord.xy, float2(0.0671105608, 0.00583714992));
    u_xlat1.x = frac(u_xlat1.x);
    u_xlat1.x = u_xlat1.x * 52.9829178;
    u_xlat1.x = frac(u_xlat1.x);
    u_xlat1.x = mad(u_xlat1.x, 0.00392156886, -0.00196078443);
    output.SV_Target0 = u_xlat0 + u_xlat1.xxxx;
    return output;
}

#elif (defined(DITHERING_NOISE) && defined(ETC1_EXTERNAL_ALPHA) && defined(PIXELSNAP_ON))
            // Original Metal program SHA256: vertex 47c247524031f60b4bc18e6f82bd2c78fe2dac250414a15c05629d4095d109ac; fragment 6f0a37ee3618043d5af41d9c5fb8fa5e2f596bb3414cd80d3398678f7e2ef549.
#include "UnityCG.cginc"

Texture2D<float4> _AlphaTex;

float4 _Color;

Texture2D<float4> _GrabTexture;

Texture2D<float4> _MainTex;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_AlphaTex;

SamplerState sampler_GrabTexture;

SamplerState sampler_MainTex;



struct RV_47c247524031_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_47c247524031_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_47c247524031_Output RecoveryVertex(RV_47c247524031_Input input)
{
    RV_47c247524031_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.xy = input.POSITION0.xy * _Flip.xyxx.xy;
    u_xlat1 = u_xlat0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlat0.xy = u_xlat0.xy / u_xlat0.ww;
    u_xlat1.xy = _ScreenParams.xy * float2(0.5, 0.5);
    u_xlat0.xy = u_xlat0.xy * u_xlat1.xy;
    u_xlat0.xy = round(u_xlat0.xy);
    u_xlat0.xy = u_xlat0.xy / u_xlat1.xy;
    output.mtl_Position.xy = u_xlat0.ww * u_xlat0.xy;
    output.mtl_Position.zw = u_xlat0.zw;
    u_xlat0 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat0 * _RendererColor;
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlat0.y = u_xlat0.y * _ProjectionParams.x;
    u_xlat1.xzw = u_xlat0.xwy * float3(0.5, 0.5, 0.5);
    output.TEXCOORD1.zw = u_xlat0.zw;
    output.TEXCOORD1.xy = u_xlat1.zz + u_xlat1.xw;
    return output;
}



struct RF_6f0a37ee3618_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_6f0a37ee3618_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_6f0a37ee3618_Output RecoveryFragment(RF_6f0a37ee3618_Input input, float4 mtl_FragCoord : SV_POSITION)
{
    RF_6f0a37ee3618_Output output;
    float4 hlslcc_FragCoord = float4(mtl_FragCoord.xyz, 1.0/mtl_FragCoord.w);
    float3 u_xlat0;
    float3 u_xlat1;
    float4 u_xlat2;
    bool3 u_xlatb2;
    float4 u_xlat3;
    float u_xlat12;
    u_xlat0.xy = input.TEXCOORD1.xy / input.TEXCOORD1.ww;
    u_xlat0.xyz = _GrabTexture.Sample(sampler_GrabTexture, u_xlat0.xy).xyz;
    u_xlat1.xyz = (-u_xlat0.xyz) + float3(1.0, 1.0, 1.0);
    u_xlat12 = _AlphaTex.Sample(sampler_AlphaTex, input.TEXCOORD0.xy).x;
    u_xlat2 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat12 = u_xlat12 + (-u_xlat2.w);
    u_xlat2.w = mad(_EnableExternalAlpha, u_xlat12, u_xlat2.w);
    u_xlat3 = u_xlat2 * input.COLOR0;
    u_xlat2.xyz = mad(u_xlat2.xyz, input.COLOR0.xyz, float3(-0.5, -0.5, -0.5));
    u_xlat2.xyz = mad((-u_xlat2.xyz), float3(2.0, 2.0, 2.0), float3(1.0, 1.0, 1.0));
    u_xlat0.xyz = u_xlat0.xyz / u_xlat2.xyz;
    u_xlat2.xyz = u_xlat3.xyz + u_xlat3.xyz;
    u_xlat1.xyz = u_xlat1.xyz / u_xlat2.xyz;
    u_xlat1.xyz = (-u_xlat1.xyz) + float3(1.0, 1.0, 1.0);
    u_xlatb2.xyz = (float3(0.5, 0.5, 0.5)<u_xlat3.xyz);
    u_xlat3.x = (u_xlatb2.x) ? u_xlat0.x : u_xlat1.x;
    u_xlat3.y = (u_xlatb2.y) ? u_xlat0.y : u_xlat1.y;
    u_xlat3.z = (u_xlatb2.z) ? u_xlat0.z : u_xlat1.z;
    u_xlat0.x = dot(hlslcc_FragCoord.xy, float2(0.0671105608, 0.00583714992));
    u_xlat0.x = frac(u_xlat0.x);
    u_xlat0.x = u_xlat0.x * 52.9829178;
    u_xlat0.x = frac(u_xlat0.x);
    u_xlat0.x = mad(u_xlat0.x, 0.00392156886, -0.00196078443);
    output.SV_Target0 = u_xlat0.xxxx + u_xlat3;
    return output;
}

#else
            // Original Metal program SHA256: vertex 47c247524031f60b4bc18e6f82bd2c78fe2dac250414a15c05629d4095d109ac; fragment b330ccda84006368d71a47b180d63f43543ecc76c4fb409adfd611e040a5caa6.
#include "UnityCG.cginc"

Texture2D<float4> _AlphaTex;

float4 _Color;

Texture2D<float4> _GrabTexture;

Texture2D<float4> _MainTex;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_AlphaTex;

SamplerState sampler_GrabTexture;

SamplerState sampler_MainTex;



struct RV_47c247524031_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_47c247524031_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_47c247524031_Output RecoveryVertex(RV_47c247524031_Input input)
{
    RV_47c247524031_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.xy = input.POSITION0.xy * _Flip.xyxx.xy;
    u_xlat1 = u_xlat0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlat0.xy = u_xlat0.xy / u_xlat0.ww;
    u_xlat1.xy = _ScreenParams.xy * float2(0.5, 0.5);
    u_xlat0.xy = u_xlat0.xy * u_xlat1.xy;
    u_xlat0.xy = round(u_xlat0.xy);
    u_xlat0.xy = u_xlat0.xy / u_xlat1.xy;
    output.mtl_Position.xy = u_xlat0.ww * u_xlat0.xy;
    output.mtl_Position.zw = u_xlat0.zw;
    u_xlat0 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat0 * _RendererColor;
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlat0.y = u_xlat0.y * _ProjectionParams.x;
    u_xlat1.xzw = u_xlat0.xwy * float3(0.5, 0.5, 0.5);
    output.TEXCOORD1.zw = u_xlat0.zw;
    output.TEXCOORD1.xy = u_xlat1.zz + u_xlat1.xw;
    return output;
}



struct RF_b330ccda8400_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_b330ccda8400_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_b330ccda8400_Output RecoveryFragment(RF_b330ccda8400_Input input)
{
    RF_b330ccda8400_Output output;
    float3 u_xlat0;
    float3 u_xlat1;
    float4 u_xlat2;
    bool3 u_xlatb2;
    float4 u_xlat3;
    float u_xlat12;
    u_xlat0.xy = input.TEXCOORD1.xy / input.TEXCOORD1.ww;
    u_xlat0.xyz = _GrabTexture.Sample(sampler_GrabTexture, u_xlat0.xy).xyz;
    u_xlat1.xyz = (-u_xlat0.xyz) + float3(1.0, 1.0, 1.0);
    u_xlat12 = _AlphaTex.Sample(sampler_AlphaTex, input.TEXCOORD0.xy).x;
    u_xlat2 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat12 = u_xlat12 + (-u_xlat2.w);
    u_xlat2.w = mad(_EnableExternalAlpha, u_xlat12, u_xlat2.w);
    u_xlat3 = u_xlat2 * input.COLOR0;
    u_xlat2.xyz = mad(u_xlat2.xyz, input.COLOR0.xyz, float3(-0.5, -0.5, -0.5));
    u_xlat2.xyz = mad((-u_xlat2.xyz), float3(2.0, 2.0, 2.0), float3(1.0, 1.0, 1.0));
    u_xlat0.xyz = u_xlat0.xyz / u_xlat2.xyz;
    u_xlat2.xyz = u_xlat3.xyz + u_xlat3.xyz;
    u_xlat1.xyz = u_xlat1.xyz / u_xlat2.xyz;
    u_xlat1.xyz = (-u_xlat1.xyz) + float3(1.0, 1.0, 1.0);
    u_xlatb2.xyz = (float3(0.5, 0.5, 0.5)<u_xlat3.xyz);
    output.SV_Target0.w = u_xlat3.w;
    output.SV_Target0.x = (u_xlatb2.x) ? u_xlat0.x : u_xlat1.x;
    output.SV_Target0.y = (u_xlatb2.y) ? u_xlat0.y : u_xlat1.y;
    output.SV_Target0.z = (u_xlatb2.z) ? u_xlat0.z : u_xlat1.z;
    return output;
}

#endif
            ENDHLSL
        }
    }
}
