// Reconstructed from the licensed GOG macOS 1.0.30000 captured Metal programs.
// Generated by tools/shader_reconstruction/shaderlab_generator.py.
// Original serialized Shader SHA256: 408a5b1958f240fd90490e10cbd5f03c0136bc7e31c0b5e766bdc66e6ce1d30a
// Properties, render states, texture samplers, and retained variants come from the original data.
// Extra keyword combinations select a captured variant; see batch-generation-manifest.json.
Shader "Sprites/Tiled Masked"
{
    Properties
    {
        [PerRendererData] _MainTex ("Sprite Texture", 2D) = "white" {}
        _Color ("Tint", Color) = (1, 1, 1, 1)
        [MaterialToggle] PixelSnap ("Pixel snap", Float) = 0
        [HideInInspector] _RendererColor ("RendererColor", Color) = (1, 1, 1, 1)
        [HideInInspector] _Flip ("Flip", Vector) = (1, 1, 1, 1)
        [PerRendererData] _AlphaTex ("External Alpha", 2D) = "white" {}
        [PerRendererData] _EnableExternalAlpha ("Enable External Alpha", Float) = 0
        _ScrollTex ("Texture", 2D) = "white" {}
        [PerRendererData] _FogRotation ("Fog Rotation", Float) = 0
        [Toggle(WORLD_SCALE_FLIP)] _EnableWorldScaleFlip ("Enable World Scale Flip", Float) = 1
        [Toggle(SILHOUETTE)] _EnableSilhouette ("Is Silhouette", Float) = 0
    }
    SubShader
    {
        Tags { "CanUseSpriteAtlas"="true" "DisableBatching"="true" "IGNOREPROJECTOR"="true" "PreviewType"="Plane" "QUEUE"="Transparent" "RenderType"="Transparent" }
        Pass
        {
            Tags { "CanUseSpriteAtlas"="true" "DisableBatching"="true" "IGNOREPROJECTOR"="true" "PreviewType"="Plane" "QUEUE"="Transparent" "RenderType"="Transparent" }
            Cull Off
            ZClip On
            ZTest LEqual
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend One OneMinusSrcAlpha
            BlendOp Add
            ColorMask RGBA
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#pragma multi_compile __ DITHERING_NOISE
#pragma multi_compile __ ETC1_EXTERNAL_ALPHA
#pragma multi_compile __ PIXELSNAP_ON
#pragma multi_compile __ WORLD_SCALE_FLIP
#if (!defined(DITHERING_NOISE) && defined(ETC1_EXTERNAL_ALPHA) && defined(PIXELSNAP_ON) && !defined(WORLD_SCALE_FLIP))
            // Original Metal program SHA256: vertex 2dffb3439cf7c8d98ef9094ff6b86736e40195914fb0832e53dcfdcbbdbddb72; fragment 001e632eb975959f823420c0bc8d307c652e55b482e08dfae5e7c82957c60c6f.
#include "UnityCG.cginc"

Texture2D<float4> _AlphaTex;

float4 _Color;

float _FogRotation;

Texture2D<float4> _MainTex;

Texture2D<float4> _ScrollTex;

float4 _ScrollTex_ST;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_AlphaTex;

SamplerState sampler_MainTex;

SamplerState sampler_ScrollTex;



struct RV_2dffb3439cf7_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_2dffb3439cf7_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_2dffb3439cf7_Output RecoveryVertex(RV_2dffb3439cf7_Input input)
{
    RV_2dffb3439cf7_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float3 u_xlat3;
    float2 u_xlat8;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat1 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat0.xy = mad(transpose(unity_ObjectToWorld)[3].xy, input.POSITION0.ww, u_xlat0.xy);
    u_xlat2 = u_xlat1.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat2 = mad(transpose(unity_MatrixVP)[0], u_xlat1.xxxx, u_xlat2);
    u_xlat2 = mad(transpose(unity_MatrixVP)[2], u_xlat1.zzzz, u_xlat2);
    u_xlat1 = mad(transpose(unity_MatrixVP)[3], u_xlat1.wwww, u_xlat2);
    u_xlat8.xy = u_xlat1.xy / u_xlat1.ww;
    u_xlat1.xy = _ScreenParams.xy * float2(0.5, 0.5);
    u_xlat8.xy = u_xlat8.xy * u_xlat1.xy;
    u_xlat8.xy = round(u_xlat8.xy);
    u_xlat8.xy = u_xlat8.xy / u_xlat1.xy;
    output.mtl_Position.xy = u_xlat1.ww * u_xlat8.xy;
    output.mtl_Position.zw = u_xlat1.zw;
    u_xlat1 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat1 * _RendererColor;
    u_xlat1.x = sin(_FogRotation);
    u_xlat2.x = cos(_FogRotation);
    u_xlat3.z = u_xlat1.x;
    u_xlat3.y = u_xlat2.x;
    u_xlat3.x = (-u_xlat1.x);
    u_xlat8.y = dot(u_xlat0.xy, u_xlat3.xy);
    u_xlat8.x = dot(u_xlat0.xy, u_xlat3.yz);
    output.TEXCOORD1.xy = mad(u_xlat8.xy, _ScrollTex_ST.xy, _ScrollTex_ST.zw);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_001e632eb975_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_001e632eb975_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_001e632eb975_Output RecoveryFragment(RF_001e632eb975_Input input)
{
    RF_001e632eb975_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.x = _AlphaTex.Sample(sampler_AlphaTex, input.TEXCOORD0.xy).x;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy).wxyz;
    u_xlat0.x = u_xlat0.x + (-u_xlat1.x);
    u_xlat1.x = mad(_EnableExternalAlpha, u_xlat0.x, u_xlat1.x);
    u_xlat0 = u_xlat1 * input.COLOR0.wxyz;
    u_xlat1 = _ScrollTex.Sample(sampler_ScrollTex, input.TEXCOORD1.xy);
    u_xlat0 = u_xlat0 * u_xlat1.wxyz;
    output.SV_Target0.xyz = u_xlat0.xxx * u_xlat0.yzw;
    output.SV_Target0.w = u_xlat0.x;
    return output;
}

#elif (!defined(DITHERING_NOISE) && !defined(ETC1_EXTERNAL_ALPHA) && defined(PIXELSNAP_ON) && !defined(WORLD_SCALE_FLIP))
            // Original Metal program SHA256: vertex 2dffb3439cf7c8d98ef9094ff6b86736e40195914fb0832e53dcfdcbbdbddb72; fragment 3e3b76cf4a711e23c60e239e9fefefeb3936823cfb2c6b76b0b0ca473f148b77.
#include "UnityCG.cginc"

float4 _Color;

float _FogRotation;

Texture2D<float4> _MainTex;

Texture2D<float4> _ScrollTex;

float4 _ScrollTex_ST;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_MainTex;

SamplerState sampler_ScrollTex;



struct RV_2dffb3439cf7_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_2dffb3439cf7_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_2dffb3439cf7_Output RecoveryVertex(RV_2dffb3439cf7_Input input)
{
    RV_2dffb3439cf7_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float3 u_xlat3;
    float2 u_xlat8;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat1 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat0.xy = mad(transpose(unity_ObjectToWorld)[3].xy, input.POSITION0.ww, u_xlat0.xy);
    u_xlat2 = u_xlat1.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat2 = mad(transpose(unity_MatrixVP)[0], u_xlat1.xxxx, u_xlat2);
    u_xlat2 = mad(transpose(unity_MatrixVP)[2], u_xlat1.zzzz, u_xlat2);
    u_xlat1 = mad(transpose(unity_MatrixVP)[3], u_xlat1.wwww, u_xlat2);
    u_xlat8.xy = u_xlat1.xy / u_xlat1.ww;
    u_xlat1.xy = _ScreenParams.xy * float2(0.5, 0.5);
    u_xlat8.xy = u_xlat8.xy * u_xlat1.xy;
    u_xlat8.xy = round(u_xlat8.xy);
    u_xlat8.xy = u_xlat8.xy / u_xlat1.xy;
    output.mtl_Position.xy = u_xlat1.ww * u_xlat8.xy;
    output.mtl_Position.zw = u_xlat1.zw;
    u_xlat1 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat1 * _RendererColor;
    u_xlat1.x = sin(_FogRotation);
    u_xlat2.x = cos(_FogRotation);
    u_xlat3.z = u_xlat1.x;
    u_xlat3.y = u_xlat2.x;
    u_xlat3.x = (-u_xlat1.x);
    u_xlat8.y = dot(u_xlat0.xy, u_xlat3.xy);
    u_xlat8.x = dot(u_xlat0.xy, u_xlat3.yz);
    output.TEXCOORD1.xy = mad(u_xlat8.xy, _ScrollTex_ST.xy, _ScrollTex_ST.zw);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_3e3b76cf4a71_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_3e3b76cf4a71_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_3e3b76cf4a71_Output RecoveryFragment(RF_3e3b76cf4a71_Input input)
{
    RF_3e3b76cf4a71_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat0 = u_xlat0.wxyz * input.COLOR0.wxyz;
    u_xlat1 = _ScrollTex.Sample(sampler_ScrollTex, input.TEXCOORD1.xy);
    u_xlat0 = u_xlat0 * u_xlat1.wxyz;
    output.SV_Target0.xyz = u_xlat0.xxx * u_xlat0.yzw;
    output.SV_Target0.w = u_xlat0.x;
    return output;
}

#elif (defined(DITHERING_NOISE) && !defined(ETC1_EXTERNAL_ALPHA) && defined(PIXELSNAP_ON) && !defined(WORLD_SCALE_FLIP))
            // Original Metal program SHA256: vertex 2dffb3439cf7c8d98ef9094ff6b86736e40195914fb0832e53dcfdcbbdbddb72; fragment 4e122f45757dc279ed74c433a11d1ac5f81a50e905f0d064cecdde1dc29cf0c9.
#include "UnityCG.cginc"

float4 _Color;

float _FogRotation;

Texture2D<float4> _MainTex;

Texture2D<float4> _ScrollTex;

float4 _ScrollTex_ST;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_MainTex;

SamplerState sampler_ScrollTex;



struct RV_2dffb3439cf7_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_2dffb3439cf7_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_2dffb3439cf7_Output RecoveryVertex(RV_2dffb3439cf7_Input input)
{
    RV_2dffb3439cf7_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float3 u_xlat3;
    float2 u_xlat8;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat1 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat0.xy = mad(transpose(unity_ObjectToWorld)[3].xy, input.POSITION0.ww, u_xlat0.xy);
    u_xlat2 = u_xlat1.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat2 = mad(transpose(unity_MatrixVP)[0], u_xlat1.xxxx, u_xlat2);
    u_xlat2 = mad(transpose(unity_MatrixVP)[2], u_xlat1.zzzz, u_xlat2);
    u_xlat1 = mad(transpose(unity_MatrixVP)[3], u_xlat1.wwww, u_xlat2);
    u_xlat8.xy = u_xlat1.xy / u_xlat1.ww;
    u_xlat1.xy = _ScreenParams.xy * float2(0.5, 0.5);
    u_xlat8.xy = u_xlat8.xy * u_xlat1.xy;
    u_xlat8.xy = round(u_xlat8.xy);
    u_xlat8.xy = u_xlat8.xy / u_xlat1.xy;
    output.mtl_Position.xy = u_xlat1.ww * u_xlat8.xy;
    output.mtl_Position.zw = u_xlat1.zw;
    u_xlat1 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat1 * _RendererColor;
    u_xlat1.x = sin(_FogRotation);
    u_xlat2.x = cos(_FogRotation);
    u_xlat3.z = u_xlat1.x;
    u_xlat3.y = u_xlat2.x;
    u_xlat3.x = (-u_xlat1.x);
    u_xlat8.y = dot(u_xlat0.xy, u_xlat3.xy);
    u_xlat8.x = dot(u_xlat0.xy, u_xlat3.yz);
    output.TEXCOORD1.xy = mad(u_xlat8.xy, _ScrollTex_ST.xy, _ScrollTex_ST.zw);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_4e122f45757d_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_4e122f45757d_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_4e122f45757d_Output RecoveryFragment(RF_4e122f45757d_Input input, float4 mtl_FragCoord : SV_POSITION)
{
    RF_4e122f45757d_Output output;
    float4 hlslcc_FragCoord = float4(mtl_FragCoord.xyz, 1.0/mtl_FragCoord.w);
    float u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    u_xlat0 = dot(hlslcc_FragCoord.xy, float2(0.0671105608, 0.00583714992));
    u_xlat0 = frac(u_xlat0);
    u_xlat0 = u_xlat0 * 52.9829178;
    u_xlat0 = frac(u_xlat0);
    u_xlat0 = mad(u_xlat0, 0.00392156886, -0.00196078443);
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat1 = u_xlat1.wxyz * input.COLOR0.wxyz;
    u_xlat2 = _ScrollTex.Sample(sampler_ScrollTex, input.TEXCOORD1.xy);
    u_xlat1 = u_xlat1.yzwx * u_xlat2;
    u_xlat1.xyz = u_xlat1.www * u_xlat1.xyz;
    output.SV_Target0 = ((float4)(u_xlat0)) + u_xlat1;
    return output;
}

#elif (defined(DITHERING_NOISE) && defined(ETC1_EXTERNAL_ALPHA) && defined(PIXELSNAP_ON) && !defined(WORLD_SCALE_FLIP))
            // Original Metal program SHA256: vertex 2dffb3439cf7c8d98ef9094ff6b86736e40195914fb0832e53dcfdcbbdbddb72; fragment 93dfb571babbc1fa3218dd540b495f3afc6888ba95befc2ffc963cbb9724c5f0.
#include "UnityCG.cginc"

Texture2D<float4> _AlphaTex;

float4 _Color;

float _FogRotation;

Texture2D<float4> _MainTex;

Texture2D<float4> _ScrollTex;

float4 _ScrollTex_ST;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_AlphaTex;

SamplerState sampler_MainTex;

SamplerState sampler_ScrollTex;



struct RV_2dffb3439cf7_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_2dffb3439cf7_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_2dffb3439cf7_Output RecoveryVertex(RV_2dffb3439cf7_Input input)
{
    RV_2dffb3439cf7_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float3 u_xlat3;
    float2 u_xlat8;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat1 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat0.xy = mad(transpose(unity_ObjectToWorld)[3].xy, input.POSITION0.ww, u_xlat0.xy);
    u_xlat2 = u_xlat1.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat2 = mad(transpose(unity_MatrixVP)[0], u_xlat1.xxxx, u_xlat2);
    u_xlat2 = mad(transpose(unity_MatrixVP)[2], u_xlat1.zzzz, u_xlat2);
    u_xlat1 = mad(transpose(unity_MatrixVP)[3], u_xlat1.wwww, u_xlat2);
    u_xlat8.xy = u_xlat1.xy / u_xlat1.ww;
    u_xlat1.xy = _ScreenParams.xy * float2(0.5, 0.5);
    u_xlat8.xy = u_xlat8.xy * u_xlat1.xy;
    u_xlat8.xy = round(u_xlat8.xy);
    u_xlat8.xy = u_xlat8.xy / u_xlat1.xy;
    output.mtl_Position.xy = u_xlat1.ww * u_xlat8.xy;
    output.mtl_Position.zw = u_xlat1.zw;
    u_xlat1 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat1 * _RendererColor;
    u_xlat1.x = sin(_FogRotation);
    u_xlat2.x = cos(_FogRotation);
    u_xlat3.z = u_xlat1.x;
    u_xlat3.y = u_xlat2.x;
    u_xlat3.x = (-u_xlat1.x);
    u_xlat8.y = dot(u_xlat0.xy, u_xlat3.xy);
    u_xlat8.x = dot(u_xlat0.xy, u_xlat3.yz);
    output.TEXCOORD1.xy = mad(u_xlat8.xy, _ScrollTex_ST.xy, _ScrollTex_ST.zw);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_93dfb571babb_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_93dfb571babb_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_93dfb571babb_Output RecoveryFragment(RF_93dfb571babb_Input input, float4 mtl_FragCoord : SV_POSITION)
{
    RF_93dfb571babb_Output output;
    float4 hlslcc_FragCoord = float4(mtl_FragCoord.xyz, 1.0/mtl_FragCoord.w);
    float u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float u_xlat3;
    u_xlat0 = dot(hlslcc_FragCoord.xy, float2(0.0671105608, 0.00583714992));
    u_xlat0 = frac(u_xlat0);
    u_xlat0 = u_xlat0 * 52.9829178;
    u_xlat0 = frac(u_xlat0);
    u_xlat0 = mad(u_xlat0, 0.00392156886, -0.00196078443);
    u_xlat3 = _AlphaTex.Sample(sampler_AlphaTex, input.TEXCOORD0.xy).x;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy).wxyz;
    u_xlat3 = u_xlat3 + (-u_xlat1.x);
    u_xlat1.x = mad(_EnableExternalAlpha, u_xlat3, u_xlat1.x);
    u_xlat1 = u_xlat1 * input.COLOR0.wxyz;
    u_xlat2 = _ScrollTex.Sample(sampler_ScrollTex, input.TEXCOORD1.xy);
    u_xlat1 = u_xlat1.yzwx * u_xlat2;
    u_xlat1.xyz = u_xlat1.www * u_xlat1.xyz;
    output.SV_Target0 = ((float4)(u_xlat0)) + u_xlat1;
    return output;
}

#elif (!defined(DITHERING_NOISE) && defined(ETC1_EXTERNAL_ALPHA) && !defined(PIXELSNAP_ON) && defined(WORLD_SCALE_FLIP))
            // Original Metal program SHA256: vertex b41aa9dd816507bd816cb7d74cf6b08ab8d3e9be84f6e70595dfff81010b0ada; fragment 001e632eb975959f823420c0bc8d307c652e55b482e08dfae5e7c82957c60c6f.
#include "UnityCG.cginc"

Texture2D<float4> _AlphaTex;

float4 _Color;

float _FogRotation;

Texture2D<float4> _MainTex;

Texture2D<float4> _ScrollTex;

float4 _ScrollTex_ST;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_AlphaTex;

SamplerState sampler_MainTex;

SamplerState sampler_ScrollTex;



struct RV_b41aa9dd8165_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_b41aa9dd8165_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_b41aa9dd8165_Output RecoveryVertex(RV_b41aa9dd8165_Input input)
{
    RV_b41aa9dd8165_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    int2 u_xlati1;
    float4 u_xlat2;
    float3 u_xlat3;
    float2 u_xlat8;
    int2 u_xlati8;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat1 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat0.xy = mad(transpose(unity_ObjectToWorld)[3].xy, input.POSITION0.ww, u_xlat0.xy);
    u_xlat2 = u_xlat1.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat2 = mad(transpose(unity_MatrixVP)[0], u_xlat1.xxxx, u_xlat2);
    u_xlat2 = mad(transpose(unity_MatrixVP)[2], u_xlat1.zzzz, u_xlat2);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat1.wwww, u_xlat2);
    u_xlat1 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat1 * _RendererColor;
    u_xlat8.xy = transpose(unity_ObjectToWorld)[0].xy + transpose(unity_ObjectToWorld)[1].xy;
    u_xlat8.xy = u_xlat8.xy + transpose(unity_ObjectToWorld)[2].xy;
    u_xlati1.xy = ((int2)(((uint2)((float2(0.0, 0.0)<u_xlat8.xy))) * 0xFFFFFFFFu));
    u_xlati8.xy = ((int2)(((uint2)((u_xlat8.xy<float2(0.0, 0.0)))) * 0xFFFFFFFFu));
    u_xlati8.xy = (-u_xlati1.xy) + u_xlati8.xy;
    u_xlat8.xy = ((float2)(u_xlati8.xy));
    u_xlat0.xy = u_xlat8.xy * u_xlat0.xy;
    u_xlat1.x = sin(_FogRotation);
    u_xlat2.x = cos(_FogRotation);
    u_xlat3.z = u_xlat1.x;
    u_xlat3.y = u_xlat2.x;
    u_xlat3.x = (-u_xlat1.x);
    u_xlat8.y = dot(u_xlat0.xy, u_xlat3.xy);
    u_xlat8.x = dot(u_xlat0.xy, u_xlat3.yz);
    output.TEXCOORD1.xy = mad(u_xlat8.xy, _ScrollTex_ST.xy, _ScrollTex_ST.zw);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_001e632eb975_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_001e632eb975_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_001e632eb975_Output RecoveryFragment(RF_001e632eb975_Input input)
{
    RF_001e632eb975_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.x = _AlphaTex.Sample(sampler_AlphaTex, input.TEXCOORD0.xy).x;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy).wxyz;
    u_xlat0.x = u_xlat0.x + (-u_xlat1.x);
    u_xlat1.x = mad(_EnableExternalAlpha, u_xlat0.x, u_xlat1.x);
    u_xlat0 = u_xlat1 * input.COLOR0.wxyz;
    u_xlat1 = _ScrollTex.Sample(sampler_ScrollTex, input.TEXCOORD1.xy);
    u_xlat0 = u_xlat0 * u_xlat1.wxyz;
    output.SV_Target0.xyz = u_xlat0.xxx * u_xlat0.yzw;
    output.SV_Target0.w = u_xlat0.x;
    return output;
}

#elif (!defined(DITHERING_NOISE) && !defined(ETC1_EXTERNAL_ALPHA) && !defined(PIXELSNAP_ON) && defined(WORLD_SCALE_FLIP))
            // Original Metal program SHA256: vertex b41aa9dd816507bd816cb7d74cf6b08ab8d3e9be84f6e70595dfff81010b0ada; fragment 3e3b76cf4a711e23c60e239e9fefefeb3936823cfb2c6b76b0b0ca473f148b77.
#include "UnityCG.cginc"

float4 _Color;

float _FogRotation;

Texture2D<float4> _MainTex;

Texture2D<float4> _ScrollTex;

float4 _ScrollTex_ST;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_MainTex;

SamplerState sampler_ScrollTex;



struct RV_b41aa9dd8165_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_b41aa9dd8165_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_b41aa9dd8165_Output RecoveryVertex(RV_b41aa9dd8165_Input input)
{
    RV_b41aa9dd8165_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    int2 u_xlati1;
    float4 u_xlat2;
    float3 u_xlat3;
    float2 u_xlat8;
    int2 u_xlati8;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat1 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat0.xy = mad(transpose(unity_ObjectToWorld)[3].xy, input.POSITION0.ww, u_xlat0.xy);
    u_xlat2 = u_xlat1.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat2 = mad(transpose(unity_MatrixVP)[0], u_xlat1.xxxx, u_xlat2);
    u_xlat2 = mad(transpose(unity_MatrixVP)[2], u_xlat1.zzzz, u_xlat2);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat1.wwww, u_xlat2);
    u_xlat1 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat1 * _RendererColor;
    u_xlat8.xy = transpose(unity_ObjectToWorld)[0].xy + transpose(unity_ObjectToWorld)[1].xy;
    u_xlat8.xy = u_xlat8.xy + transpose(unity_ObjectToWorld)[2].xy;
    u_xlati1.xy = ((int2)(((uint2)((float2(0.0, 0.0)<u_xlat8.xy))) * 0xFFFFFFFFu));
    u_xlati8.xy = ((int2)(((uint2)((u_xlat8.xy<float2(0.0, 0.0)))) * 0xFFFFFFFFu));
    u_xlati8.xy = (-u_xlati1.xy) + u_xlati8.xy;
    u_xlat8.xy = ((float2)(u_xlati8.xy));
    u_xlat0.xy = u_xlat8.xy * u_xlat0.xy;
    u_xlat1.x = sin(_FogRotation);
    u_xlat2.x = cos(_FogRotation);
    u_xlat3.z = u_xlat1.x;
    u_xlat3.y = u_xlat2.x;
    u_xlat3.x = (-u_xlat1.x);
    u_xlat8.y = dot(u_xlat0.xy, u_xlat3.xy);
    u_xlat8.x = dot(u_xlat0.xy, u_xlat3.yz);
    output.TEXCOORD1.xy = mad(u_xlat8.xy, _ScrollTex_ST.xy, _ScrollTex_ST.zw);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_3e3b76cf4a71_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_3e3b76cf4a71_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_3e3b76cf4a71_Output RecoveryFragment(RF_3e3b76cf4a71_Input input)
{
    RF_3e3b76cf4a71_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat0 = u_xlat0.wxyz * input.COLOR0.wxyz;
    u_xlat1 = _ScrollTex.Sample(sampler_ScrollTex, input.TEXCOORD1.xy);
    u_xlat0 = u_xlat0 * u_xlat1.wxyz;
    output.SV_Target0.xyz = u_xlat0.xxx * u_xlat0.yzw;
    output.SV_Target0.w = u_xlat0.x;
    return output;
}

#elif (defined(DITHERING_NOISE) && !defined(ETC1_EXTERNAL_ALPHA) && !defined(PIXELSNAP_ON) && defined(WORLD_SCALE_FLIP))
            // Original Metal program SHA256: vertex b41aa9dd816507bd816cb7d74cf6b08ab8d3e9be84f6e70595dfff81010b0ada; fragment 4e122f45757dc279ed74c433a11d1ac5f81a50e905f0d064cecdde1dc29cf0c9.
#include "UnityCG.cginc"

float4 _Color;

float _FogRotation;

Texture2D<float4> _MainTex;

Texture2D<float4> _ScrollTex;

float4 _ScrollTex_ST;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_MainTex;

SamplerState sampler_ScrollTex;



struct RV_b41aa9dd8165_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_b41aa9dd8165_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_b41aa9dd8165_Output RecoveryVertex(RV_b41aa9dd8165_Input input)
{
    RV_b41aa9dd8165_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    int2 u_xlati1;
    float4 u_xlat2;
    float3 u_xlat3;
    float2 u_xlat8;
    int2 u_xlati8;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat1 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat0.xy = mad(transpose(unity_ObjectToWorld)[3].xy, input.POSITION0.ww, u_xlat0.xy);
    u_xlat2 = u_xlat1.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat2 = mad(transpose(unity_MatrixVP)[0], u_xlat1.xxxx, u_xlat2);
    u_xlat2 = mad(transpose(unity_MatrixVP)[2], u_xlat1.zzzz, u_xlat2);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat1.wwww, u_xlat2);
    u_xlat1 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat1 * _RendererColor;
    u_xlat8.xy = transpose(unity_ObjectToWorld)[0].xy + transpose(unity_ObjectToWorld)[1].xy;
    u_xlat8.xy = u_xlat8.xy + transpose(unity_ObjectToWorld)[2].xy;
    u_xlati1.xy = ((int2)(((uint2)((float2(0.0, 0.0)<u_xlat8.xy))) * 0xFFFFFFFFu));
    u_xlati8.xy = ((int2)(((uint2)((u_xlat8.xy<float2(0.0, 0.0)))) * 0xFFFFFFFFu));
    u_xlati8.xy = (-u_xlati1.xy) + u_xlati8.xy;
    u_xlat8.xy = ((float2)(u_xlati8.xy));
    u_xlat0.xy = u_xlat8.xy * u_xlat0.xy;
    u_xlat1.x = sin(_FogRotation);
    u_xlat2.x = cos(_FogRotation);
    u_xlat3.z = u_xlat1.x;
    u_xlat3.y = u_xlat2.x;
    u_xlat3.x = (-u_xlat1.x);
    u_xlat8.y = dot(u_xlat0.xy, u_xlat3.xy);
    u_xlat8.x = dot(u_xlat0.xy, u_xlat3.yz);
    output.TEXCOORD1.xy = mad(u_xlat8.xy, _ScrollTex_ST.xy, _ScrollTex_ST.zw);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_4e122f45757d_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_4e122f45757d_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_4e122f45757d_Output RecoveryFragment(RF_4e122f45757d_Input input, float4 mtl_FragCoord : SV_POSITION)
{
    RF_4e122f45757d_Output output;
    float4 hlslcc_FragCoord = float4(mtl_FragCoord.xyz, 1.0/mtl_FragCoord.w);
    float u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    u_xlat0 = dot(hlslcc_FragCoord.xy, float2(0.0671105608, 0.00583714992));
    u_xlat0 = frac(u_xlat0);
    u_xlat0 = u_xlat0 * 52.9829178;
    u_xlat0 = frac(u_xlat0);
    u_xlat0 = mad(u_xlat0, 0.00392156886, -0.00196078443);
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat1 = u_xlat1.wxyz * input.COLOR0.wxyz;
    u_xlat2 = _ScrollTex.Sample(sampler_ScrollTex, input.TEXCOORD1.xy);
    u_xlat1 = u_xlat1.yzwx * u_xlat2;
    u_xlat1.xyz = u_xlat1.www * u_xlat1.xyz;
    output.SV_Target0 = ((float4)(u_xlat0)) + u_xlat1;
    return output;
}

#elif (defined(DITHERING_NOISE) && defined(ETC1_EXTERNAL_ALPHA) && !defined(PIXELSNAP_ON) && defined(WORLD_SCALE_FLIP))
            // Original Metal program SHA256: vertex b41aa9dd816507bd816cb7d74cf6b08ab8d3e9be84f6e70595dfff81010b0ada; fragment 93dfb571babbc1fa3218dd540b495f3afc6888ba95befc2ffc963cbb9724c5f0.
#include "UnityCG.cginc"

Texture2D<float4> _AlphaTex;

float4 _Color;

float _FogRotation;

Texture2D<float4> _MainTex;

Texture2D<float4> _ScrollTex;

float4 _ScrollTex_ST;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_AlphaTex;

SamplerState sampler_MainTex;

SamplerState sampler_ScrollTex;



struct RV_b41aa9dd8165_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_b41aa9dd8165_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_b41aa9dd8165_Output RecoveryVertex(RV_b41aa9dd8165_Input input)
{
    RV_b41aa9dd8165_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    int2 u_xlati1;
    float4 u_xlat2;
    float3 u_xlat3;
    float2 u_xlat8;
    int2 u_xlati8;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat1 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat0.xy = mad(transpose(unity_ObjectToWorld)[3].xy, input.POSITION0.ww, u_xlat0.xy);
    u_xlat2 = u_xlat1.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat2 = mad(transpose(unity_MatrixVP)[0], u_xlat1.xxxx, u_xlat2);
    u_xlat2 = mad(transpose(unity_MatrixVP)[2], u_xlat1.zzzz, u_xlat2);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat1.wwww, u_xlat2);
    u_xlat1 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat1 * _RendererColor;
    u_xlat8.xy = transpose(unity_ObjectToWorld)[0].xy + transpose(unity_ObjectToWorld)[1].xy;
    u_xlat8.xy = u_xlat8.xy + transpose(unity_ObjectToWorld)[2].xy;
    u_xlati1.xy = ((int2)(((uint2)((float2(0.0, 0.0)<u_xlat8.xy))) * 0xFFFFFFFFu));
    u_xlati8.xy = ((int2)(((uint2)((u_xlat8.xy<float2(0.0, 0.0)))) * 0xFFFFFFFFu));
    u_xlati8.xy = (-u_xlati1.xy) + u_xlati8.xy;
    u_xlat8.xy = ((float2)(u_xlati8.xy));
    u_xlat0.xy = u_xlat8.xy * u_xlat0.xy;
    u_xlat1.x = sin(_FogRotation);
    u_xlat2.x = cos(_FogRotation);
    u_xlat3.z = u_xlat1.x;
    u_xlat3.y = u_xlat2.x;
    u_xlat3.x = (-u_xlat1.x);
    u_xlat8.y = dot(u_xlat0.xy, u_xlat3.xy);
    u_xlat8.x = dot(u_xlat0.xy, u_xlat3.yz);
    output.TEXCOORD1.xy = mad(u_xlat8.xy, _ScrollTex_ST.xy, _ScrollTex_ST.zw);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_93dfb571babb_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_93dfb571babb_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_93dfb571babb_Output RecoveryFragment(RF_93dfb571babb_Input input, float4 mtl_FragCoord : SV_POSITION)
{
    RF_93dfb571babb_Output output;
    float4 hlslcc_FragCoord = float4(mtl_FragCoord.xyz, 1.0/mtl_FragCoord.w);
    float u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float u_xlat3;
    u_xlat0 = dot(hlslcc_FragCoord.xy, float2(0.0671105608, 0.00583714992));
    u_xlat0 = frac(u_xlat0);
    u_xlat0 = u_xlat0 * 52.9829178;
    u_xlat0 = frac(u_xlat0);
    u_xlat0 = mad(u_xlat0, 0.00392156886, -0.00196078443);
    u_xlat3 = _AlphaTex.Sample(sampler_AlphaTex, input.TEXCOORD0.xy).x;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy).wxyz;
    u_xlat3 = u_xlat3 + (-u_xlat1.x);
    u_xlat1.x = mad(_EnableExternalAlpha, u_xlat3, u_xlat1.x);
    u_xlat1 = u_xlat1 * input.COLOR0.wxyz;
    u_xlat2 = _ScrollTex.Sample(sampler_ScrollTex, input.TEXCOORD1.xy);
    u_xlat1 = u_xlat1.yzwx * u_xlat2;
    u_xlat1.xyz = u_xlat1.www * u_xlat1.xyz;
    output.SV_Target0 = ((float4)(u_xlat0)) + u_xlat1;
    return output;
}

#elif (!defined(DITHERING_NOISE) && defined(ETC1_EXTERNAL_ALPHA) && defined(PIXELSNAP_ON) && defined(WORLD_SCALE_FLIP))
            // Original Metal program SHA256: vertex ba7e6bcee2c68d55850eac652257090ea881c7e4f9388b9a8c324b42e7aa16da; fragment 001e632eb975959f823420c0bc8d307c652e55b482e08dfae5e7c82957c60c6f.
#include "UnityCG.cginc"

Texture2D<float4> _AlphaTex;

float4 _Color;

float _FogRotation;

Texture2D<float4> _MainTex;

Texture2D<float4> _ScrollTex;

float4 _ScrollTex_ST;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_AlphaTex;

SamplerState sampler_MainTex;

SamplerState sampler_ScrollTex;



struct RV_ba7e6bcee2c6_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_ba7e6bcee2c6_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_ba7e6bcee2c6_Output RecoveryVertex(RV_ba7e6bcee2c6_Input input)
{
    RV_ba7e6bcee2c6_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    int2 u_xlati1;
    float4 u_xlat2;
    float3 u_xlat3;
    float2 u_xlat8;
    int2 u_xlati8;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat1 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat0.xy = mad(transpose(unity_ObjectToWorld)[3].xy, input.POSITION0.ww, u_xlat0.xy);
    u_xlat2 = u_xlat1.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat2 = mad(transpose(unity_MatrixVP)[0], u_xlat1.xxxx, u_xlat2);
    u_xlat2 = mad(transpose(unity_MatrixVP)[2], u_xlat1.zzzz, u_xlat2);
    u_xlat1 = mad(transpose(unity_MatrixVP)[3], u_xlat1.wwww, u_xlat2);
    u_xlat8.xy = u_xlat1.xy / u_xlat1.ww;
    u_xlat1.xy = _ScreenParams.xy * float2(0.5, 0.5);
    u_xlat8.xy = u_xlat8.xy * u_xlat1.xy;
    u_xlat8.xy = round(u_xlat8.xy);
    u_xlat8.xy = u_xlat8.xy / u_xlat1.xy;
    output.mtl_Position.xy = u_xlat1.ww * u_xlat8.xy;
    output.mtl_Position.zw = u_xlat1.zw;
    u_xlat1 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat1 * _RendererColor;
    u_xlat8.xy = transpose(unity_ObjectToWorld)[0].xy + transpose(unity_ObjectToWorld)[1].xy;
    u_xlat8.xy = u_xlat8.xy + transpose(unity_ObjectToWorld)[2].xy;
    u_xlati1.xy = ((int2)(((uint2)((float2(0.0, 0.0)<u_xlat8.xy))) * 0xFFFFFFFFu));
    u_xlati8.xy = ((int2)(((uint2)((u_xlat8.xy<float2(0.0, 0.0)))) * 0xFFFFFFFFu));
    u_xlati8.xy = (-u_xlati1.xy) + u_xlati8.xy;
    u_xlat8.xy = ((float2)(u_xlati8.xy));
    u_xlat0.xy = u_xlat8.xy * u_xlat0.xy;
    u_xlat1.x = sin(_FogRotation);
    u_xlat2.x = cos(_FogRotation);
    u_xlat3.z = u_xlat1.x;
    u_xlat3.y = u_xlat2.x;
    u_xlat3.x = (-u_xlat1.x);
    u_xlat8.y = dot(u_xlat0.xy, u_xlat3.xy);
    u_xlat8.x = dot(u_xlat0.xy, u_xlat3.yz);
    output.TEXCOORD1.xy = mad(u_xlat8.xy, _ScrollTex_ST.xy, _ScrollTex_ST.zw);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_001e632eb975_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_001e632eb975_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_001e632eb975_Output RecoveryFragment(RF_001e632eb975_Input input)
{
    RF_001e632eb975_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.x = _AlphaTex.Sample(sampler_AlphaTex, input.TEXCOORD0.xy).x;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy).wxyz;
    u_xlat0.x = u_xlat0.x + (-u_xlat1.x);
    u_xlat1.x = mad(_EnableExternalAlpha, u_xlat0.x, u_xlat1.x);
    u_xlat0 = u_xlat1 * input.COLOR0.wxyz;
    u_xlat1 = _ScrollTex.Sample(sampler_ScrollTex, input.TEXCOORD1.xy);
    u_xlat0 = u_xlat0 * u_xlat1.wxyz;
    output.SV_Target0.xyz = u_xlat0.xxx * u_xlat0.yzw;
    output.SV_Target0.w = u_xlat0.x;
    return output;
}

#elif (!defined(DITHERING_NOISE) && !defined(ETC1_EXTERNAL_ALPHA) && defined(PIXELSNAP_ON) && defined(WORLD_SCALE_FLIP))
            // Original Metal program SHA256: vertex ba7e6bcee2c68d55850eac652257090ea881c7e4f9388b9a8c324b42e7aa16da; fragment 3e3b76cf4a711e23c60e239e9fefefeb3936823cfb2c6b76b0b0ca473f148b77.
#include "UnityCG.cginc"

float4 _Color;

float _FogRotation;

Texture2D<float4> _MainTex;

Texture2D<float4> _ScrollTex;

float4 _ScrollTex_ST;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_MainTex;

SamplerState sampler_ScrollTex;



struct RV_ba7e6bcee2c6_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_ba7e6bcee2c6_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_ba7e6bcee2c6_Output RecoveryVertex(RV_ba7e6bcee2c6_Input input)
{
    RV_ba7e6bcee2c6_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    int2 u_xlati1;
    float4 u_xlat2;
    float3 u_xlat3;
    float2 u_xlat8;
    int2 u_xlati8;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat1 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat0.xy = mad(transpose(unity_ObjectToWorld)[3].xy, input.POSITION0.ww, u_xlat0.xy);
    u_xlat2 = u_xlat1.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat2 = mad(transpose(unity_MatrixVP)[0], u_xlat1.xxxx, u_xlat2);
    u_xlat2 = mad(transpose(unity_MatrixVP)[2], u_xlat1.zzzz, u_xlat2);
    u_xlat1 = mad(transpose(unity_MatrixVP)[3], u_xlat1.wwww, u_xlat2);
    u_xlat8.xy = u_xlat1.xy / u_xlat1.ww;
    u_xlat1.xy = _ScreenParams.xy * float2(0.5, 0.5);
    u_xlat8.xy = u_xlat8.xy * u_xlat1.xy;
    u_xlat8.xy = round(u_xlat8.xy);
    u_xlat8.xy = u_xlat8.xy / u_xlat1.xy;
    output.mtl_Position.xy = u_xlat1.ww * u_xlat8.xy;
    output.mtl_Position.zw = u_xlat1.zw;
    u_xlat1 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat1 * _RendererColor;
    u_xlat8.xy = transpose(unity_ObjectToWorld)[0].xy + transpose(unity_ObjectToWorld)[1].xy;
    u_xlat8.xy = u_xlat8.xy + transpose(unity_ObjectToWorld)[2].xy;
    u_xlati1.xy = ((int2)(((uint2)((float2(0.0, 0.0)<u_xlat8.xy))) * 0xFFFFFFFFu));
    u_xlati8.xy = ((int2)(((uint2)((u_xlat8.xy<float2(0.0, 0.0)))) * 0xFFFFFFFFu));
    u_xlati8.xy = (-u_xlati1.xy) + u_xlati8.xy;
    u_xlat8.xy = ((float2)(u_xlati8.xy));
    u_xlat0.xy = u_xlat8.xy * u_xlat0.xy;
    u_xlat1.x = sin(_FogRotation);
    u_xlat2.x = cos(_FogRotation);
    u_xlat3.z = u_xlat1.x;
    u_xlat3.y = u_xlat2.x;
    u_xlat3.x = (-u_xlat1.x);
    u_xlat8.y = dot(u_xlat0.xy, u_xlat3.xy);
    u_xlat8.x = dot(u_xlat0.xy, u_xlat3.yz);
    output.TEXCOORD1.xy = mad(u_xlat8.xy, _ScrollTex_ST.xy, _ScrollTex_ST.zw);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_3e3b76cf4a71_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_3e3b76cf4a71_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_3e3b76cf4a71_Output RecoveryFragment(RF_3e3b76cf4a71_Input input)
{
    RF_3e3b76cf4a71_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat0 = u_xlat0.wxyz * input.COLOR0.wxyz;
    u_xlat1 = _ScrollTex.Sample(sampler_ScrollTex, input.TEXCOORD1.xy);
    u_xlat0 = u_xlat0 * u_xlat1.wxyz;
    output.SV_Target0.xyz = u_xlat0.xxx * u_xlat0.yzw;
    output.SV_Target0.w = u_xlat0.x;
    return output;
}

#elif (defined(DITHERING_NOISE) && !defined(ETC1_EXTERNAL_ALPHA) && defined(PIXELSNAP_ON) && defined(WORLD_SCALE_FLIP))
            // Original Metal program SHA256: vertex ba7e6bcee2c68d55850eac652257090ea881c7e4f9388b9a8c324b42e7aa16da; fragment 4e122f45757dc279ed74c433a11d1ac5f81a50e905f0d064cecdde1dc29cf0c9.
#include "UnityCG.cginc"

float4 _Color;

float _FogRotation;

Texture2D<float4> _MainTex;

Texture2D<float4> _ScrollTex;

float4 _ScrollTex_ST;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_MainTex;

SamplerState sampler_ScrollTex;



struct RV_ba7e6bcee2c6_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_ba7e6bcee2c6_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_ba7e6bcee2c6_Output RecoveryVertex(RV_ba7e6bcee2c6_Input input)
{
    RV_ba7e6bcee2c6_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    int2 u_xlati1;
    float4 u_xlat2;
    float3 u_xlat3;
    float2 u_xlat8;
    int2 u_xlati8;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat1 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat0.xy = mad(transpose(unity_ObjectToWorld)[3].xy, input.POSITION0.ww, u_xlat0.xy);
    u_xlat2 = u_xlat1.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat2 = mad(transpose(unity_MatrixVP)[0], u_xlat1.xxxx, u_xlat2);
    u_xlat2 = mad(transpose(unity_MatrixVP)[2], u_xlat1.zzzz, u_xlat2);
    u_xlat1 = mad(transpose(unity_MatrixVP)[3], u_xlat1.wwww, u_xlat2);
    u_xlat8.xy = u_xlat1.xy / u_xlat1.ww;
    u_xlat1.xy = _ScreenParams.xy * float2(0.5, 0.5);
    u_xlat8.xy = u_xlat8.xy * u_xlat1.xy;
    u_xlat8.xy = round(u_xlat8.xy);
    u_xlat8.xy = u_xlat8.xy / u_xlat1.xy;
    output.mtl_Position.xy = u_xlat1.ww * u_xlat8.xy;
    output.mtl_Position.zw = u_xlat1.zw;
    u_xlat1 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat1 * _RendererColor;
    u_xlat8.xy = transpose(unity_ObjectToWorld)[0].xy + transpose(unity_ObjectToWorld)[1].xy;
    u_xlat8.xy = u_xlat8.xy + transpose(unity_ObjectToWorld)[2].xy;
    u_xlati1.xy = ((int2)(((uint2)((float2(0.0, 0.0)<u_xlat8.xy))) * 0xFFFFFFFFu));
    u_xlati8.xy = ((int2)(((uint2)((u_xlat8.xy<float2(0.0, 0.0)))) * 0xFFFFFFFFu));
    u_xlati8.xy = (-u_xlati1.xy) + u_xlati8.xy;
    u_xlat8.xy = ((float2)(u_xlati8.xy));
    u_xlat0.xy = u_xlat8.xy * u_xlat0.xy;
    u_xlat1.x = sin(_FogRotation);
    u_xlat2.x = cos(_FogRotation);
    u_xlat3.z = u_xlat1.x;
    u_xlat3.y = u_xlat2.x;
    u_xlat3.x = (-u_xlat1.x);
    u_xlat8.y = dot(u_xlat0.xy, u_xlat3.xy);
    u_xlat8.x = dot(u_xlat0.xy, u_xlat3.yz);
    output.TEXCOORD1.xy = mad(u_xlat8.xy, _ScrollTex_ST.xy, _ScrollTex_ST.zw);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_4e122f45757d_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_4e122f45757d_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_4e122f45757d_Output RecoveryFragment(RF_4e122f45757d_Input input, float4 mtl_FragCoord : SV_POSITION)
{
    RF_4e122f45757d_Output output;
    float4 hlslcc_FragCoord = float4(mtl_FragCoord.xyz, 1.0/mtl_FragCoord.w);
    float u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    u_xlat0 = dot(hlslcc_FragCoord.xy, float2(0.0671105608, 0.00583714992));
    u_xlat0 = frac(u_xlat0);
    u_xlat0 = u_xlat0 * 52.9829178;
    u_xlat0 = frac(u_xlat0);
    u_xlat0 = mad(u_xlat0, 0.00392156886, -0.00196078443);
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat1 = u_xlat1.wxyz * input.COLOR0.wxyz;
    u_xlat2 = _ScrollTex.Sample(sampler_ScrollTex, input.TEXCOORD1.xy);
    u_xlat1 = u_xlat1.yzwx * u_xlat2;
    u_xlat1.xyz = u_xlat1.www * u_xlat1.xyz;
    output.SV_Target0 = ((float4)(u_xlat0)) + u_xlat1;
    return output;
}

#elif (defined(DITHERING_NOISE) && defined(ETC1_EXTERNAL_ALPHA) && defined(PIXELSNAP_ON) && defined(WORLD_SCALE_FLIP))
            // Original Metal program SHA256: vertex ba7e6bcee2c68d55850eac652257090ea881c7e4f9388b9a8c324b42e7aa16da; fragment 93dfb571babbc1fa3218dd540b495f3afc6888ba95befc2ffc963cbb9724c5f0.
#include "UnityCG.cginc"

Texture2D<float4> _AlphaTex;

float4 _Color;

float _FogRotation;

Texture2D<float4> _MainTex;

Texture2D<float4> _ScrollTex;

float4 _ScrollTex_ST;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_AlphaTex;

SamplerState sampler_MainTex;

SamplerState sampler_ScrollTex;



struct RV_ba7e6bcee2c6_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_ba7e6bcee2c6_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_ba7e6bcee2c6_Output RecoveryVertex(RV_ba7e6bcee2c6_Input input)
{
    RV_ba7e6bcee2c6_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    int2 u_xlati1;
    float4 u_xlat2;
    float3 u_xlat3;
    float2 u_xlat8;
    int2 u_xlati8;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat1 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat0.xy = mad(transpose(unity_ObjectToWorld)[3].xy, input.POSITION0.ww, u_xlat0.xy);
    u_xlat2 = u_xlat1.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat2 = mad(transpose(unity_MatrixVP)[0], u_xlat1.xxxx, u_xlat2);
    u_xlat2 = mad(transpose(unity_MatrixVP)[2], u_xlat1.zzzz, u_xlat2);
    u_xlat1 = mad(transpose(unity_MatrixVP)[3], u_xlat1.wwww, u_xlat2);
    u_xlat8.xy = u_xlat1.xy / u_xlat1.ww;
    u_xlat1.xy = _ScreenParams.xy * float2(0.5, 0.5);
    u_xlat8.xy = u_xlat8.xy * u_xlat1.xy;
    u_xlat8.xy = round(u_xlat8.xy);
    u_xlat8.xy = u_xlat8.xy / u_xlat1.xy;
    output.mtl_Position.xy = u_xlat1.ww * u_xlat8.xy;
    output.mtl_Position.zw = u_xlat1.zw;
    u_xlat1 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat1 * _RendererColor;
    u_xlat8.xy = transpose(unity_ObjectToWorld)[0].xy + transpose(unity_ObjectToWorld)[1].xy;
    u_xlat8.xy = u_xlat8.xy + transpose(unity_ObjectToWorld)[2].xy;
    u_xlati1.xy = ((int2)(((uint2)((float2(0.0, 0.0)<u_xlat8.xy))) * 0xFFFFFFFFu));
    u_xlati8.xy = ((int2)(((uint2)((u_xlat8.xy<float2(0.0, 0.0)))) * 0xFFFFFFFFu));
    u_xlati8.xy = (-u_xlati1.xy) + u_xlati8.xy;
    u_xlat8.xy = ((float2)(u_xlati8.xy));
    u_xlat0.xy = u_xlat8.xy * u_xlat0.xy;
    u_xlat1.x = sin(_FogRotation);
    u_xlat2.x = cos(_FogRotation);
    u_xlat3.z = u_xlat1.x;
    u_xlat3.y = u_xlat2.x;
    u_xlat3.x = (-u_xlat1.x);
    u_xlat8.y = dot(u_xlat0.xy, u_xlat3.xy);
    u_xlat8.x = dot(u_xlat0.xy, u_xlat3.yz);
    output.TEXCOORD1.xy = mad(u_xlat8.xy, _ScrollTex_ST.xy, _ScrollTex_ST.zw);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_93dfb571babb_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_93dfb571babb_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_93dfb571babb_Output RecoveryFragment(RF_93dfb571babb_Input input, float4 mtl_FragCoord : SV_POSITION)
{
    RF_93dfb571babb_Output output;
    float4 hlslcc_FragCoord = float4(mtl_FragCoord.xyz, 1.0/mtl_FragCoord.w);
    float u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float u_xlat3;
    u_xlat0 = dot(hlslcc_FragCoord.xy, float2(0.0671105608, 0.00583714992));
    u_xlat0 = frac(u_xlat0);
    u_xlat0 = u_xlat0 * 52.9829178;
    u_xlat0 = frac(u_xlat0);
    u_xlat0 = mad(u_xlat0, 0.00392156886, -0.00196078443);
    u_xlat3 = _AlphaTex.Sample(sampler_AlphaTex, input.TEXCOORD0.xy).x;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy).wxyz;
    u_xlat3 = u_xlat3 + (-u_xlat1.x);
    u_xlat1.x = mad(_EnableExternalAlpha, u_xlat3, u_xlat1.x);
    u_xlat1 = u_xlat1 * input.COLOR0.wxyz;
    u_xlat2 = _ScrollTex.Sample(sampler_ScrollTex, input.TEXCOORD1.xy);
    u_xlat1 = u_xlat1.yzwx * u_xlat2;
    u_xlat1.xyz = u_xlat1.www * u_xlat1.xyz;
    output.SV_Target0 = ((float4)(u_xlat0)) + u_xlat1;
    return output;
}

#elif (!defined(DITHERING_NOISE) && defined(ETC1_EXTERNAL_ALPHA) && !defined(PIXELSNAP_ON) && !defined(WORLD_SCALE_FLIP))
            // Original Metal program SHA256: vertex bd6703a1ae3c1d8cf807ce0b01a67757a60b4efeec494edd8131e66a09d4f66e; fragment 001e632eb975959f823420c0bc8d307c652e55b482e08dfae5e7c82957c60c6f.
#include "UnityCG.cginc"

Texture2D<float4> _AlphaTex;

float4 _Color;

float _FogRotation;

Texture2D<float4> _MainTex;

Texture2D<float4> _ScrollTex;

float4 _ScrollTex_ST;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_AlphaTex;

SamplerState sampler_MainTex;

SamplerState sampler_ScrollTex;



struct RV_bd6703a1ae3c_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_bd6703a1ae3c_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_bd6703a1ae3c_Output RecoveryVertex(RV_bd6703a1ae3c_Input input)
{
    RV_bd6703a1ae3c_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float3 u_xlat3;
    float2 u_xlat8;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat1 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat0.xy = mad(transpose(unity_ObjectToWorld)[3].xy, input.POSITION0.ww, u_xlat0.xy);
    u_xlat2 = u_xlat1.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat2 = mad(transpose(unity_MatrixVP)[0], u_xlat1.xxxx, u_xlat2);
    u_xlat2 = mad(transpose(unity_MatrixVP)[2], u_xlat1.zzzz, u_xlat2);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat1.wwww, u_xlat2);
    u_xlat1 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat1 * _RendererColor;
    u_xlat1.x = sin(_FogRotation);
    u_xlat2.x = cos(_FogRotation);
    u_xlat3.z = u_xlat1.x;
    u_xlat3.y = u_xlat2.x;
    u_xlat3.x = (-u_xlat1.x);
    u_xlat8.y = dot(u_xlat0.xy, u_xlat3.xy);
    u_xlat8.x = dot(u_xlat0.xy, u_xlat3.yz);
    output.TEXCOORD1.xy = mad(u_xlat8.xy, _ScrollTex_ST.xy, _ScrollTex_ST.zw);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_001e632eb975_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_001e632eb975_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_001e632eb975_Output RecoveryFragment(RF_001e632eb975_Input input)
{
    RF_001e632eb975_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.x = _AlphaTex.Sample(sampler_AlphaTex, input.TEXCOORD0.xy).x;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy).wxyz;
    u_xlat0.x = u_xlat0.x + (-u_xlat1.x);
    u_xlat1.x = mad(_EnableExternalAlpha, u_xlat0.x, u_xlat1.x);
    u_xlat0 = u_xlat1 * input.COLOR0.wxyz;
    u_xlat1 = _ScrollTex.Sample(sampler_ScrollTex, input.TEXCOORD1.xy);
    u_xlat0 = u_xlat0 * u_xlat1.wxyz;
    output.SV_Target0.xyz = u_xlat0.xxx * u_xlat0.yzw;
    output.SV_Target0.w = u_xlat0.x;
    return output;
}

#elif (!defined(DITHERING_NOISE) && !defined(ETC1_EXTERNAL_ALPHA) && !defined(PIXELSNAP_ON) && !defined(WORLD_SCALE_FLIP))
            // Original Metal program SHA256: vertex bd6703a1ae3c1d8cf807ce0b01a67757a60b4efeec494edd8131e66a09d4f66e; fragment 3e3b76cf4a711e23c60e239e9fefefeb3936823cfb2c6b76b0b0ca473f148b77.
#include "UnityCG.cginc"

float4 _Color;

float _FogRotation;

Texture2D<float4> _MainTex;

Texture2D<float4> _ScrollTex;

float4 _ScrollTex_ST;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_MainTex;

SamplerState sampler_ScrollTex;



struct RV_bd6703a1ae3c_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_bd6703a1ae3c_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_bd6703a1ae3c_Output RecoveryVertex(RV_bd6703a1ae3c_Input input)
{
    RV_bd6703a1ae3c_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float3 u_xlat3;
    float2 u_xlat8;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat1 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat0.xy = mad(transpose(unity_ObjectToWorld)[3].xy, input.POSITION0.ww, u_xlat0.xy);
    u_xlat2 = u_xlat1.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat2 = mad(transpose(unity_MatrixVP)[0], u_xlat1.xxxx, u_xlat2);
    u_xlat2 = mad(transpose(unity_MatrixVP)[2], u_xlat1.zzzz, u_xlat2);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat1.wwww, u_xlat2);
    u_xlat1 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat1 * _RendererColor;
    u_xlat1.x = sin(_FogRotation);
    u_xlat2.x = cos(_FogRotation);
    u_xlat3.z = u_xlat1.x;
    u_xlat3.y = u_xlat2.x;
    u_xlat3.x = (-u_xlat1.x);
    u_xlat8.y = dot(u_xlat0.xy, u_xlat3.xy);
    u_xlat8.x = dot(u_xlat0.xy, u_xlat3.yz);
    output.TEXCOORD1.xy = mad(u_xlat8.xy, _ScrollTex_ST.xy, _ScrollTex_ST.zw);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_3e3b76cf4a71_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_3e3b76cf4a71_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_3e3b76cf4a71_Output RecoveryFragment(RF_3e3b76cf4a71_Input input)
{
    RF_3e3b76cf4a71_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat0 = u_xlat0.wxyz * input.COLOR0.wxyz;
    u_xlat1 = _ScrollTex.Sample(sampler_ScrollTex, input.TEXCOORD1.xy);
    u_xlat0 = u_xlat0 * u_xlat1.wxyz;
    output.SV_Target0.xyz = u_xlat0.xxx * u_xlat0.yzw;
    output.SV_Target0.w = u_xlat0.x;
    return output;
}

#elif (defined(DITHERING_NOISE) && !defined(ETC1_EXTERNAL_ALPHA) && !defined(PIXELSNAP_ON) && !defined(WORLD_SCALE_FLIP))
            // Original Metal program SHA256: vertex bd6703a1ae3c1d8cf807ce0b01a67757a60b4efeec494edd8131e66a09d4f66e; fragment 4e122f45757dc279ed74c433a11d1ac5f81a50e905f0d064cecdde1dc29cf0c9.
#include "UnityCG.cginc"

float4 _Color;

float _FogRotation;

Texture2D<float4> _MainTex;

Texture2D<float4> _ScrollTex;

float4 _ScrollTex_ST;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_MainTex;

SamplerState sampler_ScrollTex;



struct RV_bd6703a1ae3c_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_bd6703a1ae3c_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_bd6703a1ae3c_Output RecoveryVertex(RV_bd6703a1ae3c_Input input)
{
    RV_bd6703a1ae3c_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float3 u_xlat3;
    float2 u_xlat8;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat1 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat0.xy = mad(transpose(unity_ObjectToWorld)[3].xy, input.POSITION0.ww, u_xlat0.xy);
    u_xlat2 = u_xlat1.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat2 = mad(transpose(unity_MatrixVP)[0], u_xlat1.xxxx, u_xlat2);
    u_xlat2 = mad(transpose(unity_MatrixVP)[2], u_xlat1.zzzz, u_xlat2);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat1.wwww, u_xlat2);
    u_xlat1 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat1 * _RendererColor;
    u_xlat1.x = sin(_FogRotation);
    u_xlat2.x = cos(_FogRotation);
    u_xlat3.z = u_xlat1.x;
    u_xlat3.y = u_xlat2.x;
    u_xlat3.x = (-u_xlat1.x);
    u_xlat8.y = dot(u_xlat0.xy, u_xlat3.xy);
    u_xlat8.x = dot(u_xlat0.xy, u_xlat3.yz);
    output.TEXCOORD1.xy = mad(u_xlat8.xy, _ScrollTex_ST.xy, _ScrollTex_ST.zw);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_4e122f45757d_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_4e122f45757d_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_4e122f45757d_Output RecoveryFragment(RF_4e122f45757d_Input input, float4 mtl_FragCoord : SV_POSITION)
{
    RF_4e122f45757d_Output output;
    float4 hlslcc_FragCoord = float4(mtl_FragCoord.xyz, 1.0/mtl_FragCoord.w);
    float u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    u_xlat0 = dot(hlslcc_FragCoord.xy, float2(0.0671105608, 0.00583714992));
    u_xlat0 = frac(u_xlat0);
    u_xlat0 = u_xlat0 * 52.9829178;
    u_xlat0 = frac(u_xlat0);
    u_xlat0 = mad(u_xlat0, 0.00392156886, -0.00196078443);
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat1 = u_xlat1.wxyz * input.COLOR0.wxyz;
    u_xlat2 = _ScrollTex.Sample(sampler_ScrollTex, input.TEXCOORD1.xy);
    u_xlat1 = u_xlat1.yzwx * u_xlat2;
    u_xlat1.xyz = u_xlat1.www * u_xlat1.xyz;
    output.SV_Target0 = ((float4)(u_xlat0)) + u_xlat1;
    return output;
}

#else
            // Original Metal program SHA256: vertex bd6703a1ae3c1d8cf807ce0b01a67757a60b4efeec494edd8131e66a09d4f66e; fragment 93dfb571babbc1fa3218dd540b495f3afc6888ba95befc2ffc963cbb9724c5f0.
#include "UnityCG.cginc"

Texture2D<float4> _AlphaTex;

float4 _Color;

float _FogRotation;

Texture2D<float4> _MainTex;

Texture2D<float4> _ScrollTex;

float4 _ScrollTex_ST;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_AlphaTex;

SamplerState sampler_MainTex;

SamplerState sampler_ScrollTex;



struct RV_bd6703a1ae3c_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_bd6703a1ae3c_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_bd6703a1ae3c_Output RecoveryVertex(RV_bd6703a1ae3c_Input input)
{
    RV_bd6703a1ae3c_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float3 u_xlat3;
    float2 u_xlat8;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat1 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat0.xy = mad(transpose(unity_ObjectToWorld)[3].xy, input.POSITION0.ww, u_xlat0.xy);
    u_xlat2 = u_xlat1.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat2 = mad(transpose(unity_MatrixVP)[0], u_xlat1.xxxx, u_xlat2);
    u_xlat2 = mad(transpose(unity_MatrixVP)[2], u_xlat1.zzzz, u_xlat2);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat1.wwww, u_xlat2);
    u_xlat1 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat1 * _RendererColor;
    u_xlat1.x = sin(_FogRotation);
    u_xlat2.x = cos(_FogRotation);
    u_xlat3.z = u_xlat1.x;
    u_xlat3.y = u_xlat2.x;
    u_xlat3.x = (-u_xlat1.x);
    u_xlat8.y = dot(u_xlat0.xy, u_xlat3.xy);
    u_xlat8.x = dot(u_xlat0.xy, u_xlat3.yz);
    output.TEXCOORD1.xy = mad(u_xlat8.xy, _ScrollTex_ST.xy, _ScrollTex_ST.zw);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_93dfb571babb_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_93dfb571babb_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_93dfb571babb_Output RecoveryFragment(RF_93dfb571babb_Input input, float4 mtl_FragCoord : SV_POSITION)
{
    RF_93dfb571babb_Output output;
    float4 hlslcc_FragCoord = float4(mtl_FragCoord.xyz, 1.0/mtl_FragCoord.w);
    float u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float u_xlat3;
    u_xlat0 = dot(hlslcc_FragCoord.xy, float2(0.0671105608, 0.00583714992));
    u_xlat0 = frac(u_xlat0);
    u_xlat0 = u_xlat0 * 52.9829178;
    u_xlat0 = frac(u_xlat0);
    u_xlat0 = mad(u_xlat0, 0.00392156886, -0.00196078443);
    u_xlat3 = _AlphaTex.Sample(sampler_AlphaTex, input.TEXCOORD0.xy).x;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy).wxyz;
    u_xlat3 = u_xlat3 + (-u_xlat1.x);
    u_xlat1.x = mad(_EnableExternalAlpha, u_xlat3, u_xlat1.x);
    u_xlat1 = u_xlat1 * input.COLOR0.wxyz;
    u_xlat2 = _ScrollTex.Sample(sampler_ScrollTex, input.TEXCOORD1.xy);
    u_xlat1 = u_xlat1.yzwx * u_xlat2;
    u_xlat1.xyz = u_xlat1.www * u_xlat1.xyz;
    output.SV_Target0 = ((float4)(u_xlat0)) + u_xlat1;
    return output;
}

#endif
            ENDHLSL
        }
    }
}
