// Reconstructed from the licensed GOG macOS 1.0.30000 captured Metal programs.
// Generated by tools/shader_reconstruction/shaderlab_generator.py.
// Original serialized Shader SHA256: e57fae8cc092911a888f728dc11d48a3ef07f4dd50eaef241a3544dd4e2252b9
// Properties, render states, texture samplers, and retained variants come from the original data.
// Extra keyword combinations select a captured variant; see batch-generation-manifest.json.
Shader "Custom/Sprites-RefractionGrabber"
{
    Properties
    {
    }
    SubShader
    {
        Tags { "CanUseSpriteAtlas"="true" "IGNOREPROJECTOR"="true" "PreviewType"="Plane" "QUEUE"="Transparent" "RenderType"="Transparent" }
        GrabPass
        {
            "_SpriteRefractionGrab"
        }
        Pass
        {
            Tags { "CanUseSpriteAtlas"="true" "IGNOREPROJECTOR"="true" "PreviewType"="Plane" "QUEUE"="Transparent" "RenderType"="Transparent" }
            Cull Off
            ZClip On
            ZTest LEqual
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend One OneMinusSrcAlpha
            BlendOp Add
            ColorMask RGBA
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#if (1)
            // Original Metal program SHA256: vertex a7a8f8dbdb1fc1050ec9630a545df663e4ddb32d064afdb2ad2a1824c1abda4c; fragment 92b4503c90c55b3d8cf3b639c99946fdac78af98f136e539c618c82c0b1863ca.
#include "UnityCG.cginc"

float4 _Color;

Texture2D<float4> _MainTex;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_MainTex;



struct RV_a7a8f8dbdb1f_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_a7a8f8dbdb1f_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

RV_a7a8f8dbdb1f_Output RecoveryVertex(RV_a7a8f8dbdb1f_Input input)
{
    RV_a7a8f8dbdb1f_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.xy = input.POSITION0.xy * _Flip.xyxx.xy;
    u_xlat1 = u_xlat0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlat0 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat0 * _RendererColor;
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_92b4503c90c5_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RF_92b4503c90c5_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_92b4503c90c5_Output RecoveryFragment(RF_92b4503c90c5_Input input)
{
    RF_92b4503c90c5_Output output;
    float4 u_xlat0;
    u_xlat0 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat0 = u_xlat0 * input.COLOR0;
    output.SV_Target0.xyz = u_xlat0.www * u_xlat0.xyz;
    output.SV_Target0.w = u_xlat0.w;
    return output;
}

#endif
            ENDHLSL
        }
    }
    Fallback "Sprites/Diffuse"
}
