// Reconstructed from the licensed GOG macOS 1.0.30000 captured Metal programs.
// Generated by tools/shader_reconstruction/shaderlab_generator.py.
// Original serialized Shader SHA256: 9a4cb1d0e38f996f0d1f36ed07184172f1a910b454409a73fea312dbc990b2d3
// Properties, render states, texture samplers, and retained variants come from the original data.
// Extra keyword combinations select a captured variant; see batch-generation-manifest.json.
Shader "Custom/Sprites-Refraction"
{
    Properties
    {
        [PerRendererData] _MainTex ("Sprite Texture", 2D) = "white" {}
        _Color ("Tint", Color) = (1, 1, 1, 1)
        [HideInInspector] _RendererColor ("RendererColor", Color) = (1, 1, 1, 1)
        [HideInInspector] _Flip ("Flip", Vector) = (1, 1, 1, 1)
        [PerRendererData] _AlphaTex ("External Alpha", 2D) = "white" {}
        [PerRendererData] _EnableExternalAlpha ("Enable External Alpha", Float) = 0
        _BumpAmt ("Distortion", Range(0, 500)) = 10
        _BumpMap ("Normalmap", 2D) = "bump" {}
        [Toggle(USE_SILHOUETTE)] _UseSilhouette ("Just Use Silhouette", Float) = 0
    }
    SubShader
    {
        Tags { "CanUseSpriteAtlas"="true" "IGNOREPROJECTOR"="true" "PreviewType"="Plane" "QUEUE"="Transparent" "RenderType"="Transparent" }
        Pass
        {
            Tags { "CanUseSpriteAtlas"="true" "IGNOREPROJECTOR"="true" "PreviewType"="Plane" "QUEUE"="Transparent" "RenderType"="Transparent" }
            Cull Off
            ZClip On
            ZTest LEqual
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend One OneMinusSrcAlpha
            BlendOp Add
            ColorMask RGBA
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#pragma multi_compile __ ETC1_EXTERNAL_ALPHA
#pragma multi_compile __ USE_SILHOUETTE
#if (!defined(ETC1_EXTERNAL_ALPHA) && defined(USE_SILHOUETTE))
            // Original Metal program SHA256: vertex 64cd8db7d4e95587336bf9a2d3787f9601a9feaea6e1edea58bc0c5b440c5d27; fragment 2ec6d01af03bf0aca91d97fac4c4f925d27ec51f21647d381bf543289a2b7eb0.
#include "UnityCG.cginc"

float _BumpAmt;

Texture2D<float4> _BumpMap;

float4 _BumpMap_ST;

float4 _Color;

Texture2D<float4> _MainTex;

Texture2D<float4> _SpriteRefractionGrab;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_BumpMap;

SamplerState sampler_MainTex;

SamplerState sampler_SpriteRefractionGrab;



struct RV_64cd8db7d4e9_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_64cd8db7d4e9_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD2 : TEXCOORD2;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_64cd8db7d4e9_Output RecoveryVertex(RV_64cd8db7d4e9_Input input)
{
    RV_64cd8db7d4e9_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.xy = input.POSITION0.xy * _Flip.xyxx.xy;
    u_xlat1 = u_xlat0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.mtl_Position = u_xlat0;
    u_xlat1 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat1 * _RendererColor;
    u_xlat1.xy = input.POSITION0.yy * transpose(unity_ObjectToWorld)[1].xy;
    u_xlat1.xy = mad(transpose(unity_ObjectToWorld)[0].xy, input.POSITION0.xx, u_xlat1.xy);
    u_xlat1.xy = mad(transpose(unity_ObjectToWorld)[2].xy, input.POSITION0.zz, u_xlat1.xy);
    u_xlat1.xy = mad(transpose(unity_ObjectToWorld)[3].xy, input.POSITION0.ww, u_xlat1.xy);
    output.TEXCOORD2.xy = mad(u_xlat1.xy, _BumpMap_ST.xy, _BumpMap_ST.zw);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    u_xlat0.xy = mad(u_xlat0.xy, float2(1.0, -1.0), u_xlat0.ww);
    output.TEXCOORD1.zw = u_xlat0.zw;
    output.TEXCOORD1.xy = u_xlat0.xy * float2(0.5, 0.5);
    return output;
}



struct RF_2ec6d01af03b_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD2 : TEXCOORD2;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_2ec6d01af03b_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_2ec6d01af03b_Output RecoveryFragment(RF_2ec6d01af03b_Input input)
{
    RF_2ec6d01af03b_Output output;
    float3 u_xlat0;
    bool u_xlatb1;
    float u_xlat4;
    float u_xlat6;
    u_xlat0.xyz = _BumpMap.Sample(sampler_BumpMap, input.TEXCOORD2.xy).xyw;
    u_xlat0.x = u_xlat0.z * u_xlat0.x;
    u_xlat0.xy = mad(u_xlat0.xy, float2(2.0, 2.0), float2(-1.0, -1.0));
    u_xlat4 = input.TEXCOORD1.z * _BumpAmt;
    u_xlat4 = u_xlat4 * 0.001953125;
    u_xlat0.xy = mad(u_xlat0.xy, ((float2)(u_xlat4)), input.TEXCOORD1.xy);
    u_xlat0.xy = u_xlat0.xy / input.TEXCOORD1.ww;
    u_xlat0.xyz = _SpriteRefractionGrab.Sample(sampler_SpriteRefractionGrab, u_xlat0.xy).xyz;
    u_xlat6 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy).w;
    u_xlat6 = u_xlat6 * input.COLOR0.w;
    u_xlatb1 = 0.100000001<u_xlat6;
    u_xlat6 = (u_xlatb1) ? 1.0 : u_xlat6;
    output.SV_Target0.xyz = ((float3)(u_xlat6)) * u_xlat0.xyz;
    output.SV_Target0.w = u_xlat6;
    return output;
}

#elif (!defined(ETC1_EXTERNAL_ALPHA) && !defined(USE_SILHOUETTE))
            // Original Metal program SHA256: vertex 64cd8db7d4e95587336bf9a2d3787f9601a9feaea6e1edea58bc0c5b440c5d27; fragment 74293013fd3c59047e1579ffea9a6db151f158c1a411cfd30d6d1e91340fd6c5.
#include "UnityCG.cginc"

float _BumpAmt;

Texture2D<float4> _BumpMap;

float4 _BumpMap_ST;

float4 _Color;

Texture2D<float4> _MainTex;

Texture2D<float4> _SpriteRefractionGrab;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_BumpMap;

SamplerState sampler_MainTex;

SamplerState sampler_SpriteRefractionGrab;



struct RV_64cd8db7d4e9_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_64cd8db7d4e9_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD2 : TEXCOORD2;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_64cd8db7d4e9_Output RecoveryVertex(RV_64cd8db7d4e9_Input input)
{
    RV_64cd8db7d4e9_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.xy = input.POSITION0.xy * _Flip.xyxx.xy;
    u_xlat1 = u_xlat0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.mtl_Position = u_xlat0;
    u_xlat1 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat1 * _RendererColor;
    u_xlat1.xy = input.POSITION0.yy * transpose(unity_ObjectToWorld)[1].xy;
    u_xlat1.xy = mad(transpose(unity_ObjectToWorld)[0].xy, input.POSITION0.xx, u_xlat1.xy);
    u_xlat1.xy = mad(transpose(unity_ObjectToWorld)[2].xy, input.POSITION0.zz, u_xlat1.xy);
    u_xlat1.xy = mad(transpose(unity_ObjectToWorld)[3].xy, input.POSITION0.ww, u_xlat1.xy);
    output.TEXCOORD2.xy = mad(u_xlat1.xy, _BumpMap_ST.xy, _BumpMap_ST.zw);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    u_xlat0.xy = mad(u_xlat0.xy, float2(1.0, -1.0), u_xlat0.ww);
    output.TEXCOORD1.zw = u_xlat0.zw;
    output.TEXCOORD1.xy = u_xlat0.xy * float2(0.5, 0.5);
    return output;
}



struct RF_74293013fd3c_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD2 : TEXCOORD2;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_74293013fd3c_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_74293013fd3c_Output RecoveryFragment(RF_74293013fd3c_Input input)
{
    RF_74293013fd3c_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    bool u_xlatb4;
    float u_xlat6;
    u_xlat0.xyz = _BumpMap.Sample(sampler_BumpMap, input.TEXCOORD2.xy).xyw;
    u_xlat0.x = u_xlat0.z * u_xlat0.x;
    u_xlat0.xy = mad(u_xlat0.xy, float2(2.0, 2.0), float2(-1.0, -1.0));
    u_xlat6 = input.TEXCOORD1.z * _BumpAmt;
    u_xlat6 = u_xlat6 * 0.001953125;
    u_xlat0.xy = mad(u_xlat0.xy, ((float2)(u_xlat6)), input.TEXCOORD1.xy);
    u_xlat0.xy = u_xlat0.xy / input.TEXCOORD1.ww;
    u_xlat0 = _SpriteRefractionGrab.Sample(sampler_SpriteRefractionGrab, u_xlat0.xy);
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat2 = mad(u_xlat1, input.COLOR0, (-u_xlat0));
    u_xlat1.x = u_xlat1.w * input.COLOR0.w;
    u_xlatb4 = 0.100000001<u_xlat1.x;
    u_xlat1.x = (u_xlatb4) ? u_xlat1.x : 1.0;
    u_xlat0 = mad(u_xlat1.xxxx, u_xlat2, u_xlat0);
    output.SV_Target0.xyz = u_xlat0.www * u_xlat0.xyz;
    output.SV_Target0.w = u_xlat0.w;
    return output;
}

#elif (defined(ETC1_EXTERNAL_ALPHA) && defined(USE_SILHOUETTE))
            // Original Metal program SHA256: vertex 64cd8db7d4e95587336bf9a2d3787f9601a9feaea6e1edea58bc0c5b440c5d27; fragment 8ebc1bfb35ba98f0631ece156c1e3b142e8bd1896e62ff58b858d25287ba90b8.
#include "UnityCG.cginc"

Texture2D<float4> _AlphaTex;

float _BumpAmt;

Texture2D<float4> _BumpMap;

float4 _BumpMap_ST;

float4 _Color;

Texture2D<float4> _MainTex;

Texture2D<float4> _SpriteRefractionGrab;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_AlphaTex;

SamplerState sampler_BumpMap;

SamplerState sampler_MainTex;

SamplerState sampler_SpriteRefractionGrab;



struct RV_64cd8db7d4e9_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_64cd8db7d4e9_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD2 : TEXCOORD2;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_64cd8db7d4e9_Output RecoveryVertex(RV_64cd8db7d4e9_Input input)
{
    RV_64cd8db7d4e9_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.xy = input.POSITION0.xy * _Flip.xyxx.xy;
    u_xlat1 = u_xlat0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.mtl_Position = u_xlat0;
    u_xlat1 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat1 * _RendererColor;
    u_xlat1.xy = input.POSITION0.yy * transpose(unity_ObjectToWorld)[1].xy;
    u_xlat1.xy = mad(transpose(unity_ObjectToWorld)[0].xy, input.POSITION0.xx, u_xlat1.xy);
    u_xlat1.xy = mad(transpose(unity_ObjectToWorld)[2].xy, input.POSITION0.zz, u_xlat1.xy);
    u_xlat1.xy = mad(transpose(unity_ObjectToWorld)[3].xy, input.POSITION0.ww, u_xlat1.xy);
    output.TEXCOORD2.xy = mad(u_xlat1.xy, _BumpMap_ST.xy, _BumpMap_ST.zw);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    u_xlat0.xy = mad(u_xlat0.xy, float2(1.0, -1.0), u_xlat0.ww);
    output.TEXCOORD1.zw = u_xlat0.zw;
    output.TEXCOORD1.xy = u_xlat0.xy * float2(0.5, 0.5);
    return output;
}



struct RF_8ebc1bfb35ba_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD2 : TEXCOORD2;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_8ebc1bfb35ba_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_8ebc1bfb35ba_Output RecoveryFragment(RF_8ebc1bfb35ba_Input input)
{
    RF_8ebc1bfb35ba_Output output;
    float3 u_xlat0;
    float u_xlat1;
    bool u_xlatb1;
    float u_xlat4;
    float u_xlat6;
    u_xlat0.xyz = _BumpMap.Sample(sampler_BumpMap, input.TEXCOORD2.xy).xyw;
    u_xlat0.x = u_xlat0.z * u_xlat0.x;
    u_xlat0.xy = mad(u_xlat0.xy, float2(2.0, 2.0), float2(-1.0, -1.0));
    u_xlat4 = input.TEXCOORD1.z * _BumpAmt;
    u_xlat4 = u_xlat4 * 0.001953125;
    u_xlat0.xy = mad(u_xlat0.xy, ((float2)(u_xlat4)), input.TEXCOORD1.xy);
    u_xlat0.xy = u_xlat0.xy / input.TEXCOORD1.ww;
    u_xlat0.xyz = _SpriteRefractionGrab.Sample(sampler_SpriteRefractionGrab, u_xlat0.xy).xyz;
    u_xlat6 = _AlphaTex.Sample(sampler_AlphaTex, input.TEXCOORD0.xy).x;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy).w;
    u_xlat6 = u_xlat6 + (-u_xlat1);
    u_xlat6 = mad(_EnableExternalAlpha, u_xlat6, u_xlat1);
    u_xlat6 = u_xlat6 * input.COLOR0.w;
    u_xlatb1 = 0.100000001<u_xlat6;
    u_xlat6 = (u_xlatb1) ? 1.0 : u_xlat6;
    output.SV_Target0.xyz = ((float3)(u_xlat6)) * u_xlat0.xyz;
    output.SV_Target0.w = u_xlat6;
    return output;
}

#else
            // Original Metal program SHA256: vertex 64cd8db7d4e95587336bf9a2d3787f9601a9feaea6e1edea58bc0c5b440c5d27; fragment e8e0982e2f93b0f9c44e94b836eb858162ee83c5736c7fe141f78fc4079b2369.
#include "UnityCG.cginc"

Texture2D<float4> _AlphaTex;

float _BumpAmt;

Texture2D<float4> _BumpMap;

float4 _BumpMap_ST;

float4 _Color;

Texture2D<float4> _MainTex;

Texture2D<float4> _SpriteRefractionGrab;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_AlphaTex;

SamplerState sampler_BumpMap;

SamplerState sampler_MainTex;

SamplerState sampler_SpriteRefractionGrab;



struct RV_64cd8db7d4e9_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_64cd8db7d4e9_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD2 : TEXCOORD2;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_64cd8db7d4e9_Output RecoveryVertex(RV_64cd8db7d4e9_Input input)
{
    RV_64cd8db7d4e9_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.xy = input.POSITION0.xy * _Flip.xyxx.xy;
    u_xlat1 = u_xlat0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.mtl_Position = u_xlat0;
    u_xlat1 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat1 * _RendererColor;
    u_xlat1.xy = input.POSITION0.yy * transpose(unity_ObjectToWorld)[1].xy;
    u_xlat1.xy = mad(transpose(unity_ObjectToWorld)[0].xy, input.POSITION0.xx, u_xlat1.xy);
    u_xlat1.xy = mad(transpose(unity_ObjectToWorld)[2].xy, input.POSITION0.zz, u_xlat1.xy);
    u_xlat1.xy = mad(transpose(unity_ObjectToWorld)[3].xy, input.POSITION0.ww, u_xlat1.xy);
    output.TEXCOORD2.xy = mad(u_xlat1.xy, _BumpMap_ST.xy, _BumpMap_ST.zw);
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    u_xlat0.xy = mad(u_xlat0.xy, float2(1.0, -1.0), u_xlat0.ww);
    output.TEXCOORD1.zw = u_xlat0.zw;
    output.TEXCOORD1.xy = u_xlat0.xy * float2(0.5, 0.5);
    return output;
}



struct RF_e8e0982e2f93_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD2 : TEXCOORD2;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_e8e0982e2f93_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_e8e0982e2f93_Output RecoveryFragment(RF_e8e0982e2f93_Input input)
{
    RF_e8e0982e2f93_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    bool u_xlatb5;
    float u_xlat6;
    u_xlat0.xyz = _BumpMap.Sample(sampler_BumpMap, input.TEXCOORD2.xy).xyw;
    u_xlat0.x = u_xlat0.z * u_xlat0.x;
    u_xlat0.xy = mad(u_xlat0.xy, float2(2.0, 2.0), float2(-1.0, -1.0));
    u_xlat6 = input.TEXCOORD1.z * _BumpAmt;
    u_xlat6 = u_xlat6 * 0.001953125;
    u_xlat0.xy = mad(u_xlat0.xy, ((float2)(u_xlat6)), input.TEXCOORD1.xy);
    u_xlat0.xy = u_xlat0.xy / input.TEXCOORD1.ww;
    u_xlat0 = _SpriteRefractionGrab.Sample(sampler_SpriteRefractionGrab, u_xlat0.xy);
    u_xlat1.x = _AlphaTex.Sample(sampler_AlphaTex, input.TEXCOORD0.xy).x;
    u_xlat2 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat1.x = u_xlat1.x + (-u_xlat2.w);
    u_xlat2.w = mad(_EnableExternalAlpha, u_xlat1.x, u_xlat2.w);
    u_xlat1 = mad(u_xlat2, input.COLOR0, (-u_xlat0));
    u_xlat2.x = u_xlat2.w * input.COLOR0.w;
    u_xlatb5 = 0.100000001<u_xlat2.x;
    u_xlat2.x = (u_xlatb5) ? u_xlat2.x : 1.0;
    u_xlat0 = mad(u_xlat2.xxxx, u_xlat1, u_xlat0);
    output.SV_Target0.xyz = u_xlat0.www * u_xlat0.xyz;
    output.SV_Target0.w = u_xlat0.w;
    return output;
}

#endif
            ENDHLSL
        }
    }
    Fallback "Sprites/Diffuse"
}
