// Reconstructed from the licensed GOG macOS 1.0.30000 captured Metal programs.
// Generated by tools/shader_reconstruction/shaderlab_generator.py.
// Original serialized Shader SHA256: 7d712a7b5fd094949320f1077058e3258bb63b68a6779fe3dba8d17dec380dbb
// Properties, render states, texture samplers, and retained variants come from the original data.
// Extra keyword combinations select a captured variant; see batch-generation-manifest.json.
Shader "Hidden/UberPostprocess"
{
    Properties
    {
        _MainTex ("Texture", 2D) = "white" {}
    }
    SubShader
    {
        Pass
        {
            Cull Off
            ZClip On
            ZTest Always
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend One Zero
            BlendOp Add
            ColorMask RGBA
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#pragma multi_compile __ BLOOM_ENABLED
#pragma multi_compile __ BRIGHTNESS_EFFECT_ENABLED
#pragma multi_compile __ COLOR_CURVES_ENABLED
#pragma multi_compile __ NOISE_ENABLED
#if (defined(BLOOM_ENABLED) && defined(BRIGHTNESS_EFFECT_ENABLED) && !defined(COLOR_CURVES_ENABLED) && defined(NOISE_ENABLED))
            // Original Metal program SHA256: vertex 7f1c2a31f94e276a25b4e46d091d8668e5be1347b3d7b52d18ec94746d149195; fragment 030764d03ca0ab4f722b58ab0c40ba83f42c62b92d89c98b909c39fe45ad7bce.
#include "UnityCG.cginc"

Texture2D<float4> _Bloom;

float _Brightness;

float _Contrast;

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

float4 _NoiseColor;

float _NoiseStrength;

Texture2D<float4> _NoiseTex;

float _TimeSnap;

SamplerState sampler_Bloom;

SamplerState sampler_MainTex;

SamplerState sampler_NoiseTex;



struct RV_7f1c2a31f94e_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_7f1c2a31f94e_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_7f1c2a31f94e_Output RecoveryVertex(RV_7f1c2a31f94e_Input input)
{
    RV_7f1c2a31f94e_Output output;
    float4 phase0_Output0_1;
    float4 u_xlat0;
    bool u_xlatb0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlatb0 = _MainTex_TexelSize.y<0.0;
    u_xlat2 = (-input.TEXCOORD0.y) + 1.0;
    phase0_Output0_1.y = (u_xlatb0) ? u_xlat2 : input.TEXCOORD0.y;
    phase0_Output0_1.xzw = input.TEXCOORD0.xxy;
    output.TEXCOORD0 = phase0_Output0_1.xy;
    output.TEXCOORD1 = phase0_Output0_1.zw;
    return output;
}



struct RF_030764d03ca0_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_030764d03ca0_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_030764d03ca0_Output RecoveryFragment(RF_030764d03ca0_Input input)
{
    RF_030764d03ca0_Output output;
    float3 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float u_xlat6;
    u_xlat0.xy = _Time.zx / ((float2)(_TimeSnap));
    u_xlat0.xy = round(u_xlat0.xy);
    u_xlat0.xy = u_xlat0.xy * ((float2)(_TimeSnap));
    u_xlat6 = dot(u_xlat0.xy, float2(127.099998, 311.700012));
    u_xlat0.x = dot(u_xlat0.xy, float2(269.5, 183.300003));
    u_xlat0.y = sin(u_xlat0.x);
    u_xlat0.x = sin(u_xlat6);
    u_xlat0.xy = u_xlat0.xy * float2(43758.5469, 43758.5469);
    u_xlat0.xy = frac(u_xlat0.xy);
    u_xlat0.xy = mad(u_xlat0.xy, float2(2.0, 2.0), float2(-1.0, -1.0));
    u_xlat0.xy = mad(u_xlat0.xy, float2(162.184998, 162.184998), input.TEXCOORD0.xy);
    u_xlat0.x = _NoiseTex.Sample(sampler_NoiseTex, u_xlat0.xy).x;
    u_xlat0.x = u_xlat0.x + -0.5;
    u_xlat0.x = u_xlat0.x * _NoiseStrength;
    u_xlat0.xyz = mad(_NoiseColor.xyz, u_xlat0.xxx, float3(1.0, 1.0, 1.0));
    u_xlat1 = _MainTex.SampleLevel(sampler_MainTex, input.TEXCOORD1.xy, 0.0);
    u_xlat2 = _Bloom.Sample(sampler_Bloom, input.TEXCOORD0.xy);
    u_xlat1 = u_xlat1 + u_xlat2;
    u_xlat0.xyz = u_xlat0.xyz * u_xlat1.xyz;
    u_xlat0.xyz = clamp(u_xlat0.xyz, 0.0f, 1.0f);
    output.SV_Target0.w = u_xlat1.w;
    u_xlat0.xyz = mad(u_xlat0.xyz, ((float3)(_Brightness)), float3(-0.5, -0.5, -0.5));
    output.SV_Target0.xyz = mad(u_xlat0.xyz, ((float3)(_Contrast)), float3(0.5, 0.5, 0.5));
    return output;
}

#elif (!defined(BLOOM_ENABLED) && !defined(BRIGHTNESS_EFFECT_ENABLED) && defined(COLOR_CURVES_ENABLED) && defined(NOISE_ENABLED))
            // Original Metal program SHA256: vertex 7f1c2a31f94e276a25b4e46d091d8668e5be1347b3d7b52d18ec94746d149195; fragment 07db9d9d137e947ade8eb880bf31caa356b10f02937b0b538bff1315cbf1d2c8.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

float4 _NoiseColor;

float _NoiseStrength;

Texture2D<float4> _NoiseTex;

Texture2D<float4> _RgbTex;

float _Saturation;

float _TimeSnap;

SamplerState sampler_MainTex;

SamplerState sampler_NoiseTex;

SamplerState sampler_RgbTex;



struct RV_7f1c2a31f94e_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_7f1c2a31f94e_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_7f1c2a31f94e_Output RecoveryVertex(RV_7f1c2a31f94e_Input input)
{
    RV_7f1c2a31f94e_Output output;
    float4 phase0_Output0_1;
    float4 u_xlat0;
    bool u_xlatb0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlatb0 = _MainTex_TexelSize.y<0.0;
    u_xlat2 = (-input.TEXCOORD0.y) + 1.0;
    phase0_Output0_1.y = (u_xlatb0) ? u_xlat2 : input.TEXCOORD0.y;
    phase0_Output0_1.xzw = input.TEXCOORD0.xxy;
    output.TEXCOORD0 = phase0_Output0_1.xy;
    output.TEXCOORD1 = phase0_Output0_1.zw;
    return output;
}



struct RF_07db9d9d137e_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_07db9d9d137e_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_07db9d9d137e_Output RecoveryFragment(RF_07db9d9d137e_Input input)
{
    RF_07db9d9d137e_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float3 u_xlat2;
    float u_xlat6;
    float u_xlat9;
    u_xlat0.xy = _Time.zx / ((float2)(_TimeSnap));
    u_xlat0.xy = round(u_xlat0.xy);
    u_xlat0.xy = u_xlat0.xy * ((float2)(_TimeSnap));
    u_xlat6 = dot(u_xlat0.xy, float2(127.099998, 311.700012));
    u_xlat0.x = dot(u_xlat0.xy, float2(269.5, 183.300003));
    u_xlat0.y = sin(u_xlat0.x);
    u_xlat0.x = sin(u_xlat6);
    u_xlat0.xy = u_xlat0.xy * float2(43758.5469, 43758.5469);
    u_xlat0.xy = frac(u_xlat0.xy);
    u_xlat0.xy = mad(u_xlat0.xy, float2(2.0, 2.0), float2(-1.0, -1.0));
    u_xlat0.xy = mad(u_xlat0.xy, float2(162.184998, 162.184998), input.TEXCOORD0.xy);
    u_xlat0.x = _NoiseTex.Sample(sampler_NoiseTex, u_xlat0.xy).x;
    u_xlat0.x = u_xlat0.x + -0.5;
    u_xlat0.x = u_xlat0.x * _NoiseStrength;
    u_xlat0.xyz = mad(_NoiseColor.xyz, u_xlat0.xxx, float3(1.0, 1.0, 1.0));
    u_xlat1 = _MainTex.SampleLevel(sampler_MainTex, input.TEXCOORD1.xy, 0.0);
    u_xlat0.xyz = u_xlat0.yxz * u_xlat1.yxz;
    u_xlat0.xyz = clamp(u_xlat0.xyz, 0.0f, 1.0f);
    output.SV_Target0.w = u_xlat1.w;
    u_xlat0.w = 0.125;
    u_xlat1.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat0.yw).xyz;
    u_xlat0.y = float(0.375);
    u_xlat0.w = float(0.625);
    u_xlat2.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat0.xy).xyz;
    u_xlat0.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat0.zw).xyz;
    u_xlat2.xyz = u_xlat2.xyz * float3(0.0, 1.0, 0.0);
    u_xlat1.xyz = mad(u_xlat1.xyz, float3(1.0, 0.0, 0.0), u_xlat2.xyz);
    u_xlat0.xyz = mad(u_xlat0.xyz, float3(0.0, 0.0, 1.0), u_xlat1.xyz);
    u_xlat9 = dot(u_xlat0.xyz, float3(0.219999999, 0.707000017, 0.0710000023));
    u_xlat0.xyz = (-((float3)(u_xlat9))) + u_xlat0.xyz;
    output.SV_Target0.xyz = mad(((float3)(_Saturation)), u_xlat0.xyz, ((float3)(u_xlat9)));
    return output;
}

#elif (!defined(BLOOM_ENABLED) && !defined(BRIGHTNESS_EFFECT_ENABLED) && defined(COLOR_CURVES_ENABLED) && !defined(NOISE_ENABLED))
            // Original Metal program SHA256: vertex 7f1c2a31f94e276a25b4e46d091d8668e5be1347b3d7b52d18ec94746d149195; fragment 2d229e54c95f096ab2b492c573428dc909802230c2def50eb89cf832982cf879.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

Texture2D<float4> _RgbTex;

float _Saturation;

SamplerState sampler_MainTex;

SamplerState sampler_RgbTex;



struct RV_7f1c2a31f94e_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_7f1c2a31f94e_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_7f1c2a31f94e_Output RecoveryVertex(RV_7f1c2a31f94e_Input input)
{
    RV_7f1c2a31f94e_Output output;
    float4 phase0_Output0_1;
    float4 u_xlat0;
    bool u_xlatb0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlatb0 = _MainTex_TexelSize.y<0.0;
    u_xlat2 = (-input.TEXCOORD0.y) + 1.0;
    phase0_Output0_1.y = (u_xlatb0) ? u_xlat2 : input.TEXCOORD0.y;
    phase0_Output0_1.xzw = input.TEXCOORD0.xxy;
    output.TEXCOORD0 = phase0_Output0_1.xy;
    output.TEXCOORD1 = phase0_Output0_1.zw;
    return output;
}



struct RF_2d229e54c95f_Input
{
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_2d229e54c95f_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_2d229e54c95f_Output RecoveryFragment(RF_2d229e54c95f_Input input)
{
    RF_2d229e54c95f_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float3 u_xlat2;
    float u_xlat9;
    u_xlat0.y = float(0.125);
    u_xlat0.w = float(0.375);
    u_xlat1 = _MainTex.SampleLevel(sampler_MainTex, input.TEXCOORD1.xy, 0.0).zxyw;
    u_xlat0.xz = u_xlat1.yz;
    u_xlat2.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat0.zw).xyz;
    u_xlat0.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat0.xy).xyz;
    u_xlat2.xyz = u_xlat2.xyz * float3(0.0, 1.0, 0.0);
    u_xlat0.xyz = mad(u_xlat0.xyz, float3(1.0, 0.0, 0.0), u_xlat2.xyz);
    output.SV_Target0.w = u_xlat1.w;
    u_xlat1.y = 0.625;
    u_xlat1.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat1.xy).xyz;
    u_xlat0.xyz = mad(u_xlat1.xyz, float3(0.0, 0.0, 1.0), u_xlat0.xyz);
    u_xlat9 = dot(u_xlat0.xyz, float3(0.219999999, 0.707000017, 0.0710000023));
    u_xlat0.xyz = (-((float3)(u_xlat9))) + u_xlat0.xyz;
    output.SV_Target0.xyz = mad(((float3)(_Saturation)), u_xlat0.xyz, ((float3)(u_xlat9)));
    return output;
}

#elif (defined(BLOOM_ENABLED) && defined(BRIGHTNESS_EFFECT_ENABLED) && defined(COLOR_CURVES_ENABLED) && defined(NOISE_ENABLED))
            // Original Metal program SHA256: vertex 7f1c2a31f94e276a25b4e46d091d8668e5be1347b3d7b52d18ec94746d149195; fragment 5189efaddafe498da2a9c59db815c8fa89f94c9db6b65e2ce73c7d7f2e17474a.
#include "UnityCG.cginc"

Texture2D<float4> _Bloom;

float _Brightness;

float _Contrast;

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

float4 _NoiseColor;

float _NoiseStrength;

Texture2D<float4> _NoiseTex;

Texture2D<float4> _RgbTex;

float _Saturation;

float _TimeSnap;

SamplerState sampler_Bloom;

SamplerState sampler_MainTex;

SamplerState sampler_NoiseTex;

SamplerState sampler_RgbTex;



struct RV_7f1c2a31f94e_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_7f1c2a31f94e_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_7f1c2a31f94e_Output RecoveryVertex(RV_7f1c2a31f94e_Input input)
{
    RV_7f1c2a31f94e_Output output;
    float4 phase0_Output0_1;
    float4 u_xlat0;
    bool u_xlatb0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlatb0 = _MainTex_TexelSize.y<0.0;
    u_xlat2 = (-input.TEXCOORD0.y) + 1.0;
    phase0_Output0_1.y = (u_xlatb0) ? u_xlat2 : input.TEXCOORD0.y;
    phase0_Output0_1.xzw = input.TEXCOORD0.xxy;
    output.TEXCOORD0 = phase0_Output0_1.xy;
    output.TEXCOORD1 = phase0_Output0_1.zw;
    return output;
}



struct RF_5189efaddafe_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_5189efaddafe_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_5189efaddafe_Output RecoveryFragment(RF_5189efaddafe_Input input)
{
    RF_5189efaddafe_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float u_xlat6;
    float u_xlat9;
    u_xlat0.xy = _Time.zx / ((float2)(_TimeSnap));
    u_xlat0.xy = round(u_xlat0.xy);
    u_xlat0.xy = u_xlat0.xy * ((float2)(_TimeSnap));
    u_xlat6 = dot(u_xlat0.xy, float2(127.099998, 311.700012));
    u_xlat0.x = dot(u_xlat0.xy, float2(269.5, 183.300003));
    u_xlat0.y = sin(u_xlat0.x);
    u_xlat0.x = sin(u_xlat6);
    u_xlat0.xy = u_xlat0.xy * float2(43758.5469, 43758.5469);
    u_xlat0.xy = frac(u_xlat0.xy);
    u_xlat0.xy = mad(u_xlat0.xy, float2(2.0, 2.0), float2(-1.0, -1.0));
    u_xlat0.xy = mad(u_xlat0.xy, float2(162.184998, 162.184998), input.TEXCOORD0.xy);
    u_xlat0.x = _NoiseTex.Sample(sampler_NoiseTex, u_xlat0.xy).x;
    u_xlat0.x = u_xlat0.x + -0.5;
    u_xlat0.x = u_xlat0.x * _NoiseStrength;
    u_xlat0.xyz = mad(_NoiseColor.xyz, u_xlat0.xxx, float3(1.0, 1.0, 1.0));
    u_xlat1 = _MainTex.SampleLevel(sampler_MainTex, input.TEXCOORD1.xy, 0.0);
    u_xlat2 = _Bloom.Sample(sampler_Bloom, input.TEXCOORD0.xy);
    u_xlat1 = u_xlat1 + u_xlat2;
    u_xlat0.xyz = u_xlat0.yxz * u_xlat1.yxz;
    u_xlat0.xyz = clamp(u_xlat0.xyz, 0.0f, 1.0f);
    output.SV_Target0.w = u_xlat1.w;
    u_xlat0.w = 0.125;
    u_xlat1.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat0.yw).xyz;
    u_xlat0.y = float(0.375);
    u_xlat0.w = float(0.625);
    u_xlat2.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat0.xy).xyz;
    u_xlat0.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat0.zw).xyz;
    u_xlat2.xyz = u_xlat2.xyz * float3(0.0, 1.0, 0.0);
    u_xlat1.xyz = mad(u_xlat1.xyz, float3(1.0, 0.0, 0.0), u_xlat2.xyz);
    u_xlat0.xyz = mad(u_xlat0.xyz, float3(0.0, 0.0, 1.0), u_xlat1.xyz);
    u_xlat9 = dot(u_xlat0.xyz, float3(0.219999999, 0.707000017, 0.0710000023));
    u_xlat0.xyz = (-((float3)(u_xlat9))) + u_xlat0.xyz;
    u_xlat0.xyz = mad(((float3)(_Saturation)), u_xlat0.xyz, ((float3)(u_xlat9)));
    u_xlat0.xyz = mad(u_xlat0.xyz, ((float3)(_Brightness)), float3(-0.5, -0.5, -0.5));
    output.SV_Target0.xyz = mad(u_xlat0.xyz, ((float3)(_Contrast)), float3(0.5, 0.5, 0.5));
    return output;
}

#elif (defined(BLOOM_ENABLED) && !defined(BRIGHTNESS_EFFECT_ENABLED) && defined(COLOR_CURVES_ENABLED) && !defined(NOISE_ENABLED))
            // Original Metal program SHA256: vertex 7f1c2a31f94e276a25b4e46d091d8668e5be1347b3d7b52d18ec94746d149195; fragment 55f5c5d41b58bdfa7915115b9a8bb294fbe2445367a2ba124cc859c4ab6c5a76.
#include "UnityCG.cginc"

Texture2D<float4> _Bloom;

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

Texture2D<float4> _RgbTex;

float _Saturation;

SamplerState sampler_Bloom;

SamplerState sampler_MainTex;

SamplerState sampler_RgbTex;



struct RV_7f1c2a31f94e_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_7f1c2a31f94e_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_7f1c2a31f94e_Output RecoveryVertex(RV_7f1c2a31f94e_Input input)
{
    RV_7f1c2a31f94e_Output output;
    float4 phase0_Output0_1;
    float4 u_xlat0;
    bool u_xlatb0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlatb0 = _MainTex_TexelSize.y<0.0;
    u_xlat2 = (-input.TEXCOORD0.y) + 1.0;
    phase0_Output0_1.y = (u_xlatb0) ? u_xlat2 : input.TEXCOORD0.y;
    phase0_Output0_1.xzw = input.TEXCOORD0.xxy;
    output.TEXCOORD0 = phase0_Output0_1.xy;
    output.TEXCOORD1 = phase0_Output0_1.zw;
    return output;
}



struct RF_55f5c5d41b58_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_55f5c5d41b58_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_55f5c5d41b58_Output RecoveryFragment(RF_55f5c5d41b58_Input input)
{
    RF_55f5c5d41b58_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float3 u_xlat2;
    float u_xlat9;
    u_xlat0 = _MainTex.SampleLevel(sampler_MainTex, input.TEXCOORD1.xy, 0.0);
    u_xlat1 = _Bloom.Sample(sampler_Bloom, input.TEXCOORD0.xy);
    u_xlat0 = u_xlat0.zxyw + u_xlat1.zxyw;
    u_xlat1.xz = u_xlat0.yz;
    u_xlat1.y = float(0.125);
    u_xlat1.w = float(0.375);
    u_xlat2.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat1.zw).xyz;
    u_xlat1.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat1.xy).xyz;
    u_xlat2.xyz = u_xlat2.xyz * float3(0.0, 1.0, 0.0);
    u_xlat1.xyz = mad(u_xlat1.xyz, float3(1.0, 0.0, 0.0), u_xlat2.xyz);
    output.SV_Target0.w = u_xlat0.w;
    u_xlat0.y = 0.625;
    u_xlat0.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat0.xy).xyz;
    u_xlat0.xyz = mad(u_xlat0.xyz, float3(0.0, 0.0, 1.0), u_xlat1.xyz);
    u_xlat9 = dot(u_xlat0.xyz, float3(0.219999999, 0.707000017, 0.0710000023));
    u_xlat0.xyz = (-((float3)(u_xlat9))) + u_xlat0.xyz;
    output.SV_Target0.xyz = mad(((float3)(_Saturation)), u_xlat0.xyz, ((float3)(u_xlat9)));
    return output;
}

#elif (!defined(BLOOM_ENABLED) && !defined(BRIGHTNESS_EFFECT_ENABLED) && !defined(COLOR_CURVES_ENABLED) && !defined(NOISE_ENABLED))
            // Original Metal program SHA256: vertex 7f1c2a31f94e276a25b4e46d091d8668e5be1347b3d7b52d18ec94746d149195; fragment 564881cdb5a029ee88e7f47f8a475edecd29906d5d5792bd0598f176aaccb180.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

SamplerState sampler_MainTex;



struct RV_7f1c2a31f94e_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_7f1c2a31f94e_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_7f1c2a31f94e_Output RecoveryVertex(RV_7f1c2a31f94e_Input input)
{
    RV_7f1c2a31f94e_Output output;
    float4 phase0_Output0_1;
    float4 u_xlat0;
    bool u_xlatb0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlatb0 = _MainTex_TexelSize.y<0.0;
    u_xlat2 = (-input.TEXCOORD0.y) + 1.0;
    phase0_Output0_1.y = (u_xlatb0) ? u_xlat2 : input.TEXCOORD0.y;
    phase0_Output0_1.xzw = input.TEXCOORD0.xxy;
    output.TEXCOORD0 = phase0_Output0_1.xy;
    output.TEXCOORD1 = phase0_Output0_1.zw;
    return output;
}



struct RF_564881cdb5a0_Input
{
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_564881cdb5a0_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_564881cdb5a0_Output RecoveryFragment(RF_564881cdb5a0_Input input)
{
    RF_564881cdb5a0_Output output;
    output.SV_Target0 = _MainTex.SampleLevel(sampler_MainTex, input.TEXCOORD1.xy, 0.0);
    return output;
}

#elif (!defined(BLOOM_ENABLED) && defined(BRIGHTNESS_EFFECT_ENABLED) && defined(COLOR_CURVES_ENABLED) && defined(NOISE_ENABLED))
            // Original Metal program SHA256: vertex 7f1c2a31f94e276a25b4e46d091d8668e5be1347b3d7b52d18ec94746d149195; fragment 660c9f0749370b4360d559c00a3d1257ba176f2a953b30ffb2d486d8c2e56e4c.
#include "UnityCG.cginc"

float _Brightness;

float _Contrast;

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

float4 _NoiseColor;

float _NoiseStrength;

Texture2D<float4> _NoiseTex;

Texture2D<float4> _RgbTex;

float _Saturation;

float _TimeSnap;

SamplerState sampler_MainTex;

SamplerState sampler_NoiseTex;

SamplerState sampler_RgbTex;



struct RV_7f1c2a31f94e_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_7f1c2a31f94e_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_7f1c2a31f94e_Output RecoveryVertex(RV_7f1c2a31f94e_Input input)
{
    RV_7f1c2a31f94e_Output output;
    float4 phase0_Output0_1;
    float4 u_xlat0;
    bool u_xlatb0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlatb0 = _MainTex_TexelSize.y<0.0;
    u_xlat2 = (-input.TEXCOORD0.y) + 1.0;
    phase0_Output0_1.y = (u_xlatb0) ? u_xlat2 : input.TEXCOORD0.y;
    phase0_Output0_1.xzw = input.TEXCOORD0.xxy;
    output.TEXCOORD0 = phase0_Output0_1.xy;
    output.TEXCOORD1 = phase0_Output0_1.zw;
    return output;
}



struct RF_660c9f074937_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_660c9f074937_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_660c9f074937_Output RecoveryFragment(RF_660c9f074937_Input input)
{
    RF_660c9f074937_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float3 u_xlat2;
    float u_xlat6;
    float u_xlat9;
    u_xlat0.xy = _Time.zx / ((float2)(_TimeSnap));
    u_xlat0.xy = round(u_xlat0.xy);
    u_xlat0.xy = u_xlat0.xy * ((float2)(_TimeSnap));
    u_xlat6 = dot(u_xlat0.xy, float2(127.099998, 311.700012));
    u_xlat0.x = dot(u_xlat0.xy, float2(269.5, 183.300003));
    u_xlat0.y = sin(u_xlat0.x);
    u_xlat0.x = sin(u_xlat6);
    u_xlat0.xy = u_xlat0.xy * float2(43758.5469, 43758.5469);
    u_xlat0.xy = frac(u_xlat0.xy);
    u_xlat0.xy = mad(u_xlat0.xy, float2(2.0, 2.0), float2(-1.0, -1.0));
    u_xlat0.xy = mad(u_xlat0.xy, float2(162.184998, 162.184998), input.TEXCOORD0.xy);
    u_xlat0.x = _NoiseTex.Sample(sampler_NoiseTex, u_xlat0.xy).x;
    u_xlat0.x = u_xlat0.x + -0.5;
    u_xlat0.x = u_xlat0.x * _NoiseStrength;
    u_xlat0.xyz = mad(_NoiseColor.xyz, u_xlat0.xxx, float3(1.0, 1.0, 1.0));
    u_xlat1 = _MainTex.SampleLevel(sampler_MainTex, input.TEXCOORD1.xy, 0.0);
    u_xlat0.xyz = u_xlat0.yxz * u_xlat1.yxz;
    u_xlat0.xyz = clamp(u_xlat0.xyz, 0.0f, 1.0f);
    output.SV_Target0.w = u_xlat1.w;
    u_xlat0.w = 0.125;
    u_xlat1.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat0.yw).xyz;
    u_xlat0.y = float(0.375);
    u_xlat0.w = float(0.625);
    u_xlat2.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat0.xy).xyz;
    u_xlat0.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat0.zw).xyz;
    u_xlat2.xyz = u_xlat2.xyz * float3(0.0, 1.0, 0.0);
    u_xlat1.xyz = mad(u_xlat1.xyz, float3(1.0, 0.0, 0.0), u_xlat2.xyz);
    u_xlat0.xyz = mad(u_xlat0.xyz, float3(0.0, 0.0, 1.0), u_xlat1.xyz);
    u_xlat9 = dot(u_xlat0.xyz, float3(0.219999999, 0.707000017, 0.0710000023));
    u_xlat0.xyz = (-((float3)(u_xlat9))) + u_xlat0.xyz;
    u_xlat0.xyz = mad(((float3)(_Saturation)), u_xlat0.xyz, ((float3)(u_xlat9)));
    u_xlat0.xyz = mad(u_xlat0.xyz, ((float3)(_Brightness)), float3(-0.5, -0.5, -0.5));
    output.SV_Target0.xyz = mad(u_xlat0.xyz, ((float3)(_Contrast)), float3(0.5, 0.5, 0.5));
    return output;
}

#elif (!defined(BLOOM_ENABLED) && defined(BRIGHTNESS_EFFECT_ENABLED) && defined(COLOR_CURVES_ENABLED) && !defined(NOISE_ENABLED))
            // Original Metal program SHA256: vertex 7f1c2a31f94e276a25b4e46d091d8668e5be1347b3d7b52d18ec94746d149195; fragment 6fe489e5060da8c4f926d168e4e76bd9f333553a311dfa1aa08894258aceb479.
#include "UnityCG.cginc"

float _Brightness;

float _Contrast;

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

Texture2D<float4> _RgbTex;

float _Saturation;

SamplerState sampler_MainTex;

SamplerState sampler_RgbTex;



struct RV_7f1c2a31f94e_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_7f1c2a31f94e_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_7f1c2a31f94e_Output RecoveryVertex(RV_7f1c2a31f94e_Input input)
{
    RV_7f1c2a31f94e_Output output;
    float4 phase0_Output0_1;
    float4 u_xlat0;
    bool u_xlatb0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlatb0 = _MainTex_TexelSize.y<0.0;
    u_xlat2 = (-input.TEXCOORD0.y) + 1.0;
    phase0_Output0_1.y = (u_xlatb0) ? u_xlat2 : input.TEXCOORD0.y;
    phase0_Output0_1.xzw = input.TEXCOORD0.xxy;
    output.TEXCOORD0 = phase0_Output0_1.xy;
    output.TEXCOORD1 = phase0_Output0_1.zw;
    return output;
}



struct RF_6fe489e5060d_Input
{
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_6fe489e5060d_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_6fe489e5060d_Output RecoveryFragment(RF_6fe489e5060d_Input input)
{
    RF_6fe489e5060d_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float3 u_xlat2;
    float u_xlat9;
    u_xlat0.y = float(0.125);
    u_xlat0.w = float(0.375);
    u_xlat1 = _MainTex.SampleLevel(sampler_MainTex, input.TEXCOORD1.xy, 0.0).zxyw;
    u_xlat0.xz = u_xlat1.yz;
    u_xlat2.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat0.zw).xyz;
    u_xlat0.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat0.xy).xyz;
    u_xlat2.xyz = u_xlat2.xyz * float3(0.0, 1.0, 0.0);
    u_xlat0.xyz = mad(u_xlat0.xyz, float3(1.0, 0.0, 0.0), u_xlat2.xyz);
    output.SV_Target0.w = u_xlat1.w;
    u_xlat1.y = 0.625;
    u_xlat1.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat1.xy).xyz;
    u_xlat0.xyz = mad(u_xlat1.xyz, float3(0.0, 0.0, 1.0), u_xlat0.xyz);
    u_xlat9 = dot(u_xlat0.xyz, float3(0.219999999, 0.707000017, 0.0710000023));
    u_xlat0.xyz = (-((float3)(u_xlat9))) + u_xlat0.xyz;
    u_xlat0.xyz = mad(((float3)(_Saturation)), u_xlat0.xyz, ((float3)(u_xlat9)));
    u_xlat0.xyz = mad(u_xlat0.xyz, ((float3)(_Brightness)), float3(-0.5, -0.5, -0.5));
    output.SV_Target0.xyz = mad(u_xlat0.xyz, ((float3)(_Contrast)), float3(0.5, 0.5, 0.5));
    return output;
}

#elif (!defined(BLOOM_ENABLED) && defined(BRIGHTNESS_EFFECT_ENABLED) && !defined(COLOR_CURVES_ENABLED) && !defined(NOISE_ENABLED))
            // Original Metal program SHA256: vertex 7f1c2a31f94e276a25b4e46d091d8668e5be1347b3d7b52d18ec94746d149195; fragment 728a58cead36374f00ca653fffc10eb701cd11d6fc41bc3c5ff3e1d60456ce97.
#include "UnityCG.cginc"

float _Brightness;

float _Contrast;

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

SamplerState sampler_MainTex;



struct RV_7f1c2a31f94e_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_7f1c2a31f94e_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_7f1c2a31f94e_Output RecoveryVertex(RV_7f1c2a31f94e_Input input)
{
    RV_7f1c2a31f94e_Output output;
    float4 phase0_Output0_1;
    float4 u_xlat0;
    bool u_xlatb0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlatb0 = _MainTex_TexelSize.y<0.0;
    u_xlat2 = (-input.TEXCOORD0.y) + 1.0;
    phase0_Output0_1.y = (u_xlatb0) ? u_xlat2 : input.TEXCOORD0.y;
    phase0_Output0_1.xzw = input.TEXCOORD0.xxy;
    output.TEXCOORD0 = phase0_Output0_1.xy;
    output.TEXCOORD1 = phase0_Output0_1.zw;
    return output;
}



struct RF_728a58cead36_Input
{
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_728a58cead36_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_728a58cead36_Output RecoveryFragment(RF_728a58cead36_Input input)
{
    RF_728a58cead36_Output output;
    float4 u_xlat0;
    u_xlat0 = _MainTex.SampleLevel(sampler_MainTex, input.TEXCOORD1.xy, 0.0);
    u_xlat0.xyz = mad(u_xlat0.xyz, ((float3)(_Brightness)), float3(-0.5, -0.5, -0.5));
    output.SV_Target0.w = u_xlat0.w;
    output.SV_Target0.xyz = mad(u_xlat0.xyz, ((float3)(_Contrast)), float3(0.5, 0.5, 0.5));
    return output;
}

#elif (defined(BLOOM_ENABLED) && defined(BRIGHTNESS_EFFECT_ENABLED) && !defined(COLOR_CURVES_ENABLED) && !defined(NOISE_ENABLED))
            // Original Metal program SHA256: vertex 7f1c2a31f94e276a25b4e46d091d8668e5be1347b3d7b52d18ec94746d149195; fragment 7a54c660060bf77bc2efaf091f9cb2c860242cc6b8b3f712da31f98c91bbf307.
#include "UnityCG.cginc"

Texture2D<float4> _Bloom;

float _Brightness;

float _Contrast;

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

SamplerState sampler_Bloom;

SamplerState sampler_MainTex;



struct RV_7f1c2a31f94e_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_7f1c2a31f94e_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_7f1c2a31f94e_Output RecoveryVertex(RV_7f1c2a31f94e_Input input)
{
    RV_7f1c2a31f94e_Output output;
    float4 phase0_Output0_1;
    float4 u_xlat0;
    bool u_xlatb0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlatb0 = _MainTex_TexelSize.y<0.0;
    u_xlat2 = (-input.TEXCOORD0.y) + 1.0;
    phase0_Output0_1.y = (u_xlatb0) ? u_xlat2 : input.TEXCOORD0.y;
    phase0_Output0_1.xzw = input.TEXCOORD0.xxy;
    output.TEXCOORD0 = phase0_Output0_1.xy;
    output.TEXCOORD1 = phase0_Output0_1.zw;
    return output;
}



struct RF_7a54c660060b_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_7a54c660060b_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_7a54c660060b_Output RecoveryFragment(RF_7a54c660060b_Input input)
{
    RF_7a54c660060b_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = _MainTex.SampleLevel(sampler_MainTex, input.TEXCOORD1.xy, 0.0);
    u_xlat1 = _Bloom.Sample(sampler_Bloom, input.TEXCOORD0.xy);
    u_xlat0 = u_xlat0 + u_xlat1;
    u_xlat0.xyz = mad(u_xlat0.xyz, ((float3)(_Brightness)), float3(-0.5, -0.5, -0.5));
    output.SV_Target0.w = u_xlat0.w;
    output.SV_Target0.xyz = mad(u_xlat0.xyz, ((float3)(_Contrast)), float3(0.5, 0.5, 0.5));
    return output;
}

#elif (defined(BLOOM_ENABLED) && defined(BRIGHTNESS_EFFECT_ENABLED) && defined(COLOR_CURVES_ENABLED) && !defined(NOISE_ENABLED))
            // Original Metal program SHA256: vertex 7f1c2a31f94e276a25b4e46d091d8668e5be1347b3d7b52d18ec94746d149195; fragment bbb53b80bfabbbceeb7322de97e27c91beb8230595c54713c5b9349908086d27.
#include "UnityCG.cginc"

Texture2D<float4> _Bloom;

float _Brightness;

float _Contrast;

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

Texture2D<float4> _RgbTex;

float _Saturation;

SamplerState sampler_Bloom;

SamplerState sampler_MainTex;

SamplerState sampler_RgbTex;



struct RV_7f1c2a31f94e_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_7f1c2a31f94e_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_7f1c2a31f94e_Output RecoveryVertex(RV_7f1c2a31f94e_Input input)
{
    RV_7f1c2a31f94e_Output output;
    float4 phase0_Output0_1;
    float4 u_xlat0;
    bool u_xlatb0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlatb0 = _MainTex_TexelSize.y<0.0;
    u_xlat2 = (-input.TEXCOORD0.y) + 1.0;
    phase0_Output0_1.y = (u_xlatb0) ? u_xlat2 : input.TEXCOORD0.y;
    phase0_Output0_1.xzw = input.TEXCOORD0.xxy;
    output.TEXCOORD0 = phase0_Output0_1.xy;
    output.TEXCOORD1 = phase0_Output0_1.zw;
    return output;
}



struct RF_bbb53b80bfab_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_bbb53b80bfab_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_bbb53b80bfab_Output RecoveryFragment(RF_bbb53b80bfab_Input input)
{
    RF_bbb53b80bfab_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float3 u_xlat2;
    float u_xlat9;
    u_xlat0 = _MainTex.SampleLevel(sampler_MainTex, input.TEXCOORD1.xy, 0.0);
    u_xlat1 = _Bloom.Sample(sampler_Bloom, input.TEXCOORD0.xy);
    u_xlat0 = u_xlat0.zxyw + u_xlat1.zxyw;
    u_xlat1.xz = u_xlat0.yz;
    u_xlat1.y = float(0.125);
    u_xlat1.w = float(0.375);
    u_xlat2.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat1.zw).xyz;
    u_xlat1.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat1.xy).xyz;
    u_xlat2.xyz = u_xlat2.xyz * float3(0.0, 1.0, 0.0);
    u_xlat1.xyz = mad(u_xlat1.xyz, float3(1.0, 0.0, 0.0), u_xlat2.xyz);
    output.SV_Target0.w = u_xlat0.w;
    u_xlat0.y = 0.625;
    u_xlat0.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat0.xy).xyz;
    u_xlat0.xyz = mad(u_xlat0.xyz, float3(0.0, 0.0, 1.0), u_xlat1.xyz);
    u_xlat9 = dot(u_xlat0.xyz, float3(0.219999999, 0.707000017, 0.0710000023));
    u_xlat0.xyz = (-((float3)(u_xlat9))) + u_xlat0.xyz;
    u_xlat0.xyz = mad(((float3)(_Saturation)), u_xlat0.xyz, ((float3)(u_xlat9)));
    u_xlat0.xyz = mad(u_xlat0.xyz, ((float3)(_Brightness)), float3(-0.5, -0.5, -0.5));
    output.SV_Target0.xyz = mad(u_xlat0.xyz, ((float3)(_Contrast)), float3(0.5, 0.5, 0.5));
    return output;
}

#elif (!defined(BLOOM_ENABLED) && !defined(BRIGHTNESS_EFFECT_ENABLED) && !defined(COLOR_CURVES_ENABLED) && defined(NOISE_ENABLED))
            // Original Metal program SHA256: vertex 7f1c2a31f94e276a25b4e46d091d8668e5be1347b3d7b52d18ec94746d149195; fragment bfa9548e71bf34462961773a0bd62649d214ba18757e871297794a97c7468ca7.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

float4 _NoiseColor;

float _NoiseStrength;

Texture2D<float4> _NoiseTex;

float _TimeSnap;

SamplerState sampler_MainTex;

SamplerState sampler_NoiseTex;



struct RV_7f1c2a31f94e_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_7f1c2a31f94e_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_7f1c2a31f94e_Output RecoveryVertex(RV_7f1c2a31f94e_Input input)
{
    RV_7f1c2a31f94e_Output output;
    float4 phase0_Output0_1;
    float4 u_xlat0;
    bool u_xlatb0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlatb0 = _MainTex_TexelSize.y<0.0;
    u_xlat2 = (-input.TEXCOORD0.y) + 1.0;
    phase0_Output0_1.y = (u_xlatb0) ? u_xlat2 : input.TEXCOORD0.y;
    phase0_Output0_1.xzw = input.TEXCOORD0.xxy;
    output.TEXCOORD0 = phase0_Output0_1.xy;
    output.TEXCOORD1 = phase0_Output0_1.zw;
    return output;
}



struct RF_bfa9548e71bf_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_bfa9548e71bf_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_bfa9548e71bf_Output RecoveryFragment(RF_bfa9548e71bf_Input input)
{
    RF_bfa9548e71bf_Output output;
    float3 u_xlat0;
    float4 u_xlat1;
    float u_xlat4;
    u_xlat0.xy = _Time.zx / ((float2)(_TimeSnap));
    u_xlat0.xy = round(u_xlat0.xy);
    u_xlat0.xy = u_xlat0.xy * ((float2)(_TimeSnap));
    u_xlat4 = dot(u_xlat0.xy, float2(127.099998, 311.700012));
    u_xlat0.x = dot(u_xlat0.xy, float2(269.5, 183.300003));
    u_xlat0.y = sin(u_xlat0.x);
    u_xlat0.x = sin(u_xlat4);
    u_xlat0.xy = u_xlat0.xy * float2(43758.5469, 43758.5469);
    u_xlat0.xy = frac(u_xlat0.xy);
    u_xlat0.xy = mad(u_xlat0.xy, float2(2.0, 2.0), float2(-1.0, -1.0));
    u_xlat0.xy = mad(u_xlat0.xy, float2(162.184998, 162.184998), input.TEXCOORD0.xy);
    u_xlat0.x = _NoiseTex.Sample(sampler_NoiseTex, u_xlat0.xy).x;
    u_xlat0.x = u_xlat0.x + -0.5;
    u_xlat0.x = u_xlat0.x * _NoiseStrength;
    u_xlat0.xyz = mad(_NoiseColor.xyz, u_xlat0.xxx, float3(1.0, 1.0, 1.0));
    u_xlat1 = _MainTex.SampleLevel(sampler_MainTex, input.TEXCOORD1.xy, 0.0);
    output.SV_Target0.xyz = u_xlat0.xyz * u_xlat1.xyz;
    output.SV_Target0.xyz = clamp(output.SV_Target0.xyz, 0.0f, 1.0f);
    output.SV_Target0.w = u_xlat1.w;
    return output;
}

#elif (defined(BLOOM_ENABLED) && !defined(BRIGHTNESS_EFFECT_ENABLED) && !defined(COLOR_CURVES_ENABLED) && defined(NOISE_ENABLED))
            // Original Metal program SHA256: vertex 7f1c2a31f94e276a25b4e46d091d8668e5be1347b3d7b52d18ec94746d149195; fragment c6860784c16217d1a969d2ded5fcd9b7a49e6019dd5c2285ed613c0caa5bd8f9.
#include "UnityCG.cginc"

Texture2D<float4> _Bloom;

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

float4 _NoiseColor;

float _NoiseStrength;

Texture2D<float4> _NoiseTex;

float _TimeSnap;

SamplerState sampler_Bloom;

SamplerState sampler_MainTex;

SamplerState sampler_NoiseTex;



struct RV_7f1c2a31f94e_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_7f1c2a31f94e_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_7f1c2a31f94e_Output RecoveryVertex(RV_7f1c2a31f94e_Input input)
{
    RV_7f1c2a31f94e_Output output;
    float4 phase0_Output0_1;
    float4 u_xlat0;
    bool u_xlatb0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlatb0 = _MainTex_TexelSize.y<0.0;
    u_xlat2 = (-input.TEXCOORD0.y) + 1.0;
    phase0_Output0_1.y = (u_xlatb0) ? u_xlat2 : input.TEXCOORD0.y;
    phase0_Output0_1.xzw = input.TEXCOORD0.xxy;
    output.TEXCOORD0 = phase0_Output0_1.xy;
    output.TEXCOORD1 = phase0_Output0_1.zw;
    return output;
}



struct RF_c6860784c162_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_c6860784c162_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_c6860784c162_Output RecoveryFragment(RF_c6860784c162_Input input)
{
    RF_c6860784c162_Output output;
    float3 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float u_xlat6;
    u_xlat0.xy = _Time.zx / ((float2)(_TimeSnap));
    u_xlat0.xy = round(u_xlat0.xy);
    u_xlat0.xy = u_xlat0.xy * ((float2)(_TimeSnap));
    u_xlat6 = dot(u_xlat0.xy, float2(127.099998, 311.700012));
    u_xlat0.x = dot(u_xlat0.xy, float2(269.5, 183.300003));
    u_xlat0.y = sin(u_xlat0.x);
    u_xlat0.x = sin(u_xlat6);
    u_xlat0.xy = u_xlat0.xy * float2(43758.5469, 43758.5469);
    u_xlat0.xy = frac(u_xlat0.xy);
    u_xlat0.xy = mad(u_xlat0.xy, float2(2.0, 2.0), float2(-1.0, -1.0));
    u_xlat0.xy = mad(u_xlat0.xy, float2(162.184998, 162.184998), input.TEXCOORD0.xy);
    u_xlat0.x = _NoiseTex.Sample(sampler_NoiseTex, u_xlat0.xy).x;
    u_xlat0.x = u_xlat0.x + -0.5;
    u_xlat0.x = u_xlat0.x * _NoiseStrength;
    u_xlat0.xyz = mad(_NoiseColor.xyz, u_xlat0.xxx, float3(1.0, 1.0, 1.0));
    u_xlat1 = _MainTex.SampleLevel(sampler_MainTex, input.TEXCOORD1.xy, 0.0);
    u_xlat2 = _Bloom.Sample(sampler_Bloom, input.TEXCOORD0.xy);
    u_xlat1 = u_xlat1 + u_xlat2;
    output.SV_Target0.xyz = u_xlat0.xyz * u_xlat1.xyz;
    output.SV_Target0.xyz = clamp(output.SV_Target0.xyz, 0.0f, 1.0f);
    output.SV_Target0.w = u_xlat1.w;
    return output;
}

#elif (defined(BLOOM_ENABLED) && !defined(BRIGHTNESS_EFFECT_ENABLED) && defined(COLOR_CURVES_ENABLED) && defined(NOISE_ENABLED))
            // Original Metal program SHA256: vertex 7f1c2a31f94e276a25b4e46d091d8668e5be1347b3d7b52d18ec94746d149195; fragment cef4c346b3678cd641428c576833b489b0ad8a20f72f629e2c7d57f627b9ce1c.
#include "UnityCG.cginc"

Texture2D<float4> _Bloom;

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

float4 _NoiseColor;

float _NoiseStrength;

Texture2D<float4> _NoiseTex;

Texture2D<float4> _RgbTex;

float _Saturation;

float _TimeSnap;

SamplerState sampler_Bloom;

SamplerState sampler_MainTex;

SamplerState sampler_NoiseTex;

SamplerState sampler_RgbTex;



struct RV_7f1c2a31f94e_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_7f1c2a31f94e_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_7f1c2a31f94e_Output RecoveryVertex(RV_7f1c2a31f94e_Input input)
{
    RV_7f1c2a31f94e_Output output;
    float4 phase0_Output0_1;
    float4 u_xlat0;
    bool u_xlatb0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlatb0 = _MainTex_TexelSize.y<0.0;
    u_xlat2 = (-input.TEXCOORD0.y) + 1.0;
    phase0_Output0_1.y = (u_xlatb0) ? u_xlat2 : input.TEXCOORD0.y;
    phase0_Output0_1.xzw = input.TEXCOORD0.xxy;
    output.TEXCOORD0 = phase0_Output0_1.xy;
    output.TEXCOORD1 = phase0_Output0_1.zw;
    return output;
}



struct RF_cef4c346b367_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_cef4c346b367_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_cef4c346b367_Output RecoveryFragment(RF_cef4c346b367_Input input)
{
    RF_cef4c346b367_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float4 u_xlat2;
    float u_xlat6;
    float u_xlat9;
    u_xlat0.xy = _Time.zx / ((float2)(_TimeSnap));
    u_xlat0.xy = round(u_xlat0.xy);
    u_xlat0.xy = u_xlat0.xy * ((float2)(_TimeSnap));
    u_xlat6 = dot(u_xlat0.xy, float2(127.099998, 311.700012));
    u_xlat0.x = dot(u_xlat0.xy, float2(269.5, 183.300003));
    u_xlat0.y = sin(u_xlat0.x);
    u_xlat0.x = sin(u_xlat6);
    u_xlat0.xy = u_xlat0.xy * float2(43758.5469, 43758.5469);
    u_xlat0.xy = frac(u_xlat0.xy);
    u_xlat0.xy = mad(u_xlat0.xy, float2(2.0, 2.0), float2(-1.0, -1.0));
    u_xlat0.xy = mad(u_xlat0.xy, float2(162.184998, 162.184998), input.TEXCOORD0.xy);
    u_xlat0.x = _NoiseTex.Sample(sampler_NoiseTex, u_xlat0.xy).x;
    u_xlat0.x = u_xlat0.x + -0.5;
    u_xlat0.x = u_xlat0.x * _NoiseStrength;
    u_xlat0.xyz = mad(_NoiseColor.xyz, u_xlat0.xxx, float3(1.0, 1.0, 1.0));
    u_xlat1 = _MainTex.SampleLevel(sampler_MainTex, input.TEXCOORD1.xy, 0.0);
    u_xlat2 = _Bloom.Sample(sampler_Bloom, input.TEXCOORD0.xy);
    u_xlat1 = u_xlat1 + u_xlat2;
    u_xlat0.xyz = u_xlat0.yxz * u_xlat1.yxz;
    u_xlat0.xyz = clamp(u_xlat0.xyz, 0.0f, 1.0f);
    output.SV_Target0.w = u_xlat1.w;
    u_xlat0.w = 0.125;
    u_xlat1.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat0.yw).xyz;
    u_xlat0.y = float(0.375);
    u_xlat0.w = float(0.625);
    u_xlat2.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat0.xy).xyz;
    u_xlat0.xyz = _RgbTex.Sample(sampler_RgbTex, u_xlat0.zw).xyz;
    u_xlat2.xyz = u_xlat2.xyz * float3(0.0, 1.0, 0.0);
    u_xlat1.xyz = mad(u_xlat1.xyz, float3(1.0, 0.0, 0.0), u_xlat2.xyz);
    u_xlat0.xyz = mad(u_xlat0.xyz, float3(0.0, 0.0, 1.0), u_xlat1.xyz);
    u_xlat9 = dot(u_xlat0.xyz, float3(0.219999999, 0.707000017, 0.0710000023));
    u_xlat0.xyz = (-((float3)(u_xlat9))) + u_xlat0.xyz;
    output.SV_Target0.xyz = mad(((float3)(_Saturation)), u_xlat0.xyz, ((float3)(u_xlat9)));
    return output;
}

#elif (!defined(BLOOM_ENABLED) && defined(BRIGHTNESS_EFFECT_ENABLED) && !defined(COLOR_CURVES_ENABLED) && defined(NOISE_ENABLED))
            // Original Metal program SHA256: vertex 7f1c2a31f94e276a25b4e46d091d8668e5be1347b3d7b52d18ec94746d149195; fragment db6c53c68b37e446c4e8383a9598164b358f3da988f138c70d279dd2030d795b.
#include "UnityCG.cginc"

float _Brightness;

float _Contrast;

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

float4 _NoiseColor;

float _NoiseStrength;

Texture2D<float4> _NoiseTex;

float _TimeSnap;

SamplerState sampler_MainTex;

SamplerState sampler_NoiseTex;



struct RV_7f1c2a31f94e_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_7f1c2a31f94e_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_7f1c2a31f94e_Output RecoveryVertex(RV_7f1c2a31f94e_Input input)
{
    RV_7f1c2a31f94e_Output output;
    float4 phase0_Output0_1;
    float4 u_xlat0;
    bool u_xlatb0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlatb0 = _MainTex_TexelSize.y<0.0;
    u_xlat2 = (-input.TEXCOORD0.y) + 1.0;
    phase0_Output0_1.y = (u_xlatb0) ? u_xlat2 : input.TEXCOORD0.y;
    phase0_Output0_1.xzw = input.TEXCOORD0.xxy;
    output.TEXCOORD0 = phase0_Output0_1.xy;
    output.TEXCOORD1 = phase0_Output0_1.zw;
    return output;
}



struct RF_db6c53c68b37_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_db6c53c68b37_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_db6c53c68b37_Output RecoveryFragment(RF_db6c53c68b37_Input input)
{
    RF_db6c53c68b37_Output output;
    float3 u_xlat0;
    float4 u_xlat1;
    float u_xlat4;
    u_xlat0.xy = _Time.zx / ((float2)(_TimeSnap));
    u_xlat0.xy = round(u_xlat0.xy);
    u_xlat0.xy = u_xlat0.xy * ((float2)(_TimeSnap));
    u_xlat4 = dot(u_xlat0.xy, float2(127.099998, 311.700012));
    u_xlat0.x = dot(u_xlat0.xy, float2(269.5, 183.300003));
    u_xlat0.y = sin(u_xlat0.x);
    u_xlat0.x = sin(u_xlat4);
    u_xlat0.xy = u_xlat0.xy * float2(43758.5469, 43758.5469);
    u_xlat0.xy = frac(u_xlat0.xy);
    u_xlat0.xy = mad(u_xlat0.xy, float2(2.0, 2.0), float2(-1.0, -1.0));
    u_xlat0.xy = mad(u_xlat0.xy, float2(162.184998, 162.184998), input.TEXCOORD0.xy);
    u_xlat0.x = _NoiseTex.Sample(sampler_NoiseTex, u_xlat0.xy).x;
    u_xlat0.x = u_xlat0.x + -0.5;
    u_xlat0.x = u_xlat0.x * _NoiseStrength;
    u_xlat0.xyz = mad(_NoiseColor.xyz, u_xlat0.xxx, float3(1.0, 1.0, 1.0));
    u_xlat1 = _MainTex.SampleLevel(sampler_MainTex, input.TEXCOORD1.xy, 0.0);
    u_xlat0.xyz = u_xlat0.xyz * u_xlat1.xyz;
    u_xlat0.xyz = clamp(u_xlat0.xyz, 0.0f, 1.0f);
    output.SV_Target0.w = u_xlat1.w;
    u_xlat0.xyz = mad(u_xlat0.xyz, ((float3)(_Brightness)), float3(-0.5, -0.5, -0.5));
    output.SV_Target0.xyz = mad(u_xlat0.xyz, ((float3)(_Contrast)), float3(0.5, 0.5, 0.5));
    return output;
}

#else
            // Original Metal program SHA256: vertex 7f1c2a31f94e276a25b4e46d091d8668e5be1347b3d7b52d18ec94746d149195; fragment e87ba1d5ead7f1ada4b765e40444ed8e066bb78d7e2912bd08891a92f1d8494d.
#include "UnityCG.cginc"

Texture2D<float4> _Bloom;

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

SamplerState sampler_Bloom;

SamplerState sampler_MainTex;



struct RV_7f1c2a31f94e_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_7f1c2a31f94e_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

RV_7f1c2a31f94e_Output RecoveryVertex(RV_7f1c2a31f94e_Input input)
{
    RV_7f1c2a31f94e_Output output;
    float4 phase0_Output0_1;
    float4 u_xlat0;
    bool u_xlatb0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlatb0 = _MainTex_TexelSize.y<0.0;
    u_xlat2 = (-input.TEXCOORD0.y) + 1.0;
    phase0_Output0_1.y = (u_xlatb0) ? u_xlat2 : input.TEXCOORD0.y;
    phase0_Output0_1.xzw = input.TEXCOORD0.xxy;
    output.TEXCOORD0 = phase0_Output0_1.xy;
    output.TEXCOORD1 = phase0_Output0_1.zw;
    return output;
}



struct RF_e87ba1d5ead7_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RF_e87ba1d5ead7_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_e87ba1d5ead7_Output RecoveryFragment(RF_e87ba1d5ead7_Input input)
{
    RF_e87ba1d5ead7_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = _MainTex.SampleLevel(sampler_MainTex, input.TEXCOORD1.xy, 0.0);
    u_xlat1 = _Bloom.Sample(sampler_Bloom, input.TEXCOORD0.xy);
    output.SV_Target0 = u_xlat0 + u_xlat1;
    return output;
}

#endif
            ENDHLSL
        }
    }
}
