// Reconstructed from the licensed GOG macOS 1.0.30000 captured Metal programs.
// Generated by tools/shader_reconstruction/shaderlab_generator.py.
// Original serialized Shader SHA256: 241cbd3dda805089dfd4e305ac45420a09feb51dd2ae5f020962ecca284d0650
// Properties, render states, texture samplers, and retained variants come from the original data.
// Extra keyword combinations select a captured variant; see batch-generation-manifest.json.
Shader "Custom/Tracking Trail"
{
    Properties
    {
        [PerRendererData] _TintColor ("Tint Color", Color) = (1, 1, 1, 1)
        _Color ("Color", Color) = (1, 1, 1, 1)
        _MainTex ("Texture", 2D) = "white" {}
        _SpeedX ("Flow Rate X", Float) = 1
        _SpeedY ("Flow Rate Y", Float) = 1
        _SecondaryColor ("Secondary Color", Color) = (1, 1, 1, 1)
        _SecondaryTex ("Secondary Texture", 2D) = "white" {}
        _SecondarySpeedX ("Secondary Flow Rate X", Float) = 1
        _SecondarySpeedY ("Secondary Flow Rate Y", Float) = 1
        _PointMaskTex ("Point Mask Texture", 2D) = "white" {}
        _PointLightTex ("Point Light Texture", 2D) = "white" {}
    }
    SubShader
    {
        Tags { "DisableBatching"="true" "IGNOREPROJECTOR"="true" "QUEUE"="Transparent" "RenderType"="Transparent" }
        Pass
        {
            Tags { "DisableBatching"="true" "IGNOREPROJECTOR"="true" "QUEUE"="Transparent" "RenderType"="Transparent" }
            Cull Off
            ZClip On
            ZTest LEqual
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend SrcAlpha OneMinusSrcAlpha
            BlendOp Add
            ColorMask RGBA
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#if (1)
            // Original Metal program SHA256: vertex 2740518543aea1208ff9dd0d274c999bf73a6f4920476f261d712fd878198a75; fragment 19896a2f5e7745582a208f76f2d7d012a2e340e012d6351e1ac53c4512f2d877.
#include "UnityCG.cginc"

float4 _Color;

float2 _Cutouts[10];

int _CutoutsCount;

float _HeroPlayMode;

float2 _HeroWorldPos;

Texture2D<float4> _MainTex;

float4 _MainTex_ST;

Texture2D<float4> _PointLightTex;

float4 _PointLightTex_ST;

Texture2D<float4> _PointMaskTex;

float4 _PointMaskTex_ST;

float4 _SecondaryColor;

float _SecondarySpeedX;

float _SecondarySpeedY;

Texture2D<float4> _SecondaryTex;

float4 _SecondaryTex_ST;

float _SpeedX;

float _SpeedY;

float4 _TintColor;

SamplerState sampler_MainTex;

SamplerState sampler_PointLightTex;

SamplerState sampler_PointMaskTex;

SamplerState sampler_SecondaryTex;



struct RV_2740518543ae_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 COLOR0 : COLOR0;
};

struct RV_2740518543ae_Output
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD2 : TEXCOORD2;
    float2 TEXCOORD3 : TEXCOORD3;
    float2 TEXCOORD4 : TEXCOORD4;
    float2 TEXCOORD5 : TEXCOORD5;
    float2 TEXCOORD6 : TEXCOORD6;
    float2 TEXCOORD7 : TEXCOORD7;
    float2 TEXCOORD8 : TEXCOORD8;
    float2 TEXCOORD9 : TEXCOORD9;
    float2 TEXCOORD10 : TEXCOORD10;
    float2 TEXCOORD11 : TEXCOORD11;
    float2 TEXCOORD12 : TEXCOORD12;
};

RV_2740518543ae_Output RecoveryVertex(RV_2740518543ae_Input input)
{
    RV_2740518543ae_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    int u_xlati1;
    float4 u_xlat2;
    int u_xlati4;
    float2 u_xlat6;
    float2 u_xlat7;
    bool u_xlatb7;
    float4 TempArray0[10];
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat1 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat2 = u_xlat1.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat2 = mad(transpose(unity_MatrixVP)[0], u_xlat1.xxxx, u_xlat2);
    u_xlat2 = mad(transpose(unity_MatrixVP)[2], u_xlat1.zzzz, u_xlat2);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat1.wwww, u_xlat2);
    output.COLOR0 = input.COLOR0 * _TintColor;
    u_xlat6.xy = mad(float2(_SpeedX, _SpeedY), _Time.yy, input.TEXCOORD0.xy);
    output.TEXCOORD0.xy = mad(u_xlat6.xy, _MainTex_ST.xy, _MainTex_ST.zw);
    u_xlat6.xy = mad(float2(_SecondarySpeedX, _SecondarySpeedY), _Time.yy, input.TEXCOORD0.xy);
    output.TEXCOORD1.xy = mad(u_xlat6.xy, _SecondaryTex_ST.xy, _SecondaryTex_ST.zw);
    u_xlat6.xy = float2(0.5, 0.5) / _PointMaskTex_ST.xy;
    u_xlat6.xy = u_xlat6.xy + (-_PointMaskTex_ST.zw);
    u_xlati1 = min(_CutoutsCount, 0xa);
    u_xlat0.xy = mad(transpose(unity_ObjectToWorld)[3].xy, input.POSITION0.ww, u_xlat0.xy);
    u_xlati4 = 0x0;
    while(true){
        u_xlatb7 = u_xlati4>=u_xlati1;
        if(u_xlatb7){break;}
        u_xlat7.xy = u_xlat0.xy + (-_Cutouts[u_xlati4].xyxx.xy);
        u_xlat7.xy = u_xlat6.xy + u_xlat7.xy;
        u_xlat7.xy = u_xlat7.xy * _PointMaskTex_ST.xy;
        TempArray0[u_xlati4].xy = u_xlat7.xy;
        u_xlati4 = u_xlati4 + 0x1;
    }
    output.TEXCOORD3.xy = TempArray0[0].xy;
    output.TEXCOORD4.xy = TempArray0[1].xy;
    output.TEXCOORD5.xy = TempArray0[2].xy;
    output.TEXCOORD6.xy = TempArray0[3].xy;
    output.TEXCOORD7.xy = TempArray0[4].xy;
    output.TEXCOORD8.xy = TempArray0[5].xy;
    output.TEXCOORD9.xy = TempArray0[6].xy;
    output.TEXCOORD10.xy = TempArray0[7].xy;
    output.TEXCOORD11.xy = TempArray0[8].xy;
    output.TEXCOORD12.xy = TempArray0[9].xy;
    u_xlat0.xy = u_xlat0.xy + (-_HeroWorldPos.xyxx.xy);
    u_xlat6.xy = float2(0.5, 0.5) / _PointLightTex_ST.xy;
    u_xlat0.xy = u_xlat6.xy + u_xlat0.xy;
    u_xlat0.xy = u_xlat0.xy + (-_PointLightTex_ST.zw);
    output.TEXCOORD2.xy = u_xlat0.xy * _PointLightTex_ST.xy;
    return output;
}



struct RF_19896a2f5e77_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD2 : TEXCOORD2;
    float2 TEXCOORD3 : TEXCOORD3;
    float2 TEXCOORD4 : TEXCOORD4;
    float2 TEXCOORD5 : TEXCOORD5;
    float2 TEXCOORD6 : TEXCOORD6;
    float2 TEXCOORD7 : TEXCOORD7;
    float2 TEXCOORD8 : TEXCOORD8;
    float2 TEXCOORD9 : TEXCOORD9;
    float2 TEXCOORD10 : TEXCOORD10;
    float2 TEXCOORD11 : TEXCOORD11;
    float2 TEXCOORD12 : TEXCOORD12;
};

struct RF_19896a2f5e77_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_19896a2f5e77_Output RecoveryFragment(RF_19896a2f5e77_Input input)
{
    RF_19896a2f5e77_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    bool u_xlatb1;
    int u_xlati3;
    float u_xlat5;
    bool u_xlatb5;
    float4 phase0_Input0_4[10];
    phase0_Input0_4[0].xy = input.TEXCOORD3;
    phase0_Input0_4[1].xy = input.TEXCOORD4;
    phase0_Input0_4[2].xy = input.TEXCOORD5;
    phase0_Input0_4[3].xy = input.TEXCOORD6;
    phase0_Input0_4[4].xy = input.TEXCOORD7;
    phase0_Input0_4[5].xy = input.TEXCOORD8;
    phase0_Input0_4[6].xy = input.TEXCOORD9;
    phase0_Input0_4[7].xy = input.TEXCOORD10;
    phase0_Input0_4[8].xy = input.TEXCOORD11;
    phase0_Input0_4[9].xy = input.TEXCOORD12;
    u_xlat0 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat0 = u_xlat0 * _Color;
    u_xlat1 = _SecondaryTex.Sample(sampler_SecondaryTex, input.TEXCOORD1.xy);
    u_xlat1 = u_xlat1 * _SecondaryColor;
    u_xlat1 = u_xlat1 * input.COLOR0;
    u_xlat0 = mad(u_xlat0.wxyz, input.COLOR0.wxyz, u_xlat1.wxyz);
    u_xlat1.x = float(1.0);
    u_xlati3 = int(0x0);
    while(true){
        u_xlatb5 = u_xlati3>=_CutoutsCount;
        if(u_xlatb5){break;}
        u_xlat5 = _PointMaskTex.Sample(sampler_PointMaskTex, phase0_Input0_4[u_xlati3].xy).x;
        u_xlat1.x = min(u_xlat5, u_xlat1.x);
        u_xlati3 = u_xlati3 + 0x1;
    }
    u_xlat0.x = u_xlat0.x * u_xlat1.x;
    u_xlatb1 = float(0.0)!=_HeroPlayMode;
    if(u_xlatb1){
        u_xlat1.x = _PointLightTex.Sample(sampler_PointLightTex, input.TEXCOORD2.xy).x;
        u_xlat0.x = u_xlat0.x * u_xlat1.x;
    }
    output.SV_Target0 = u_xlat0.yzwx;
    return output;
}

#endif
            ENDHLSL
        }
    }
}
