// Reconstructed from the licensed GOG macOS 1.0.30000 captured Metal programs.
// Generated by tools/shader_reconstruction/shaderlab_generator.py.
// Original serialized Shader SHA256: ea26baaeaa69a6b04b8f1aaa837bbfb1864d0ec7b67c1bc6a40d3908ac053914
// Properties, render states, texture samplers, and retained variants come from the original data.
// Extra keyword combinations select a captured variant; see batch-generation-manifest.json.
Shader "Custom/Screen-Space Blit"
{
    Properties
    {
        _MainTex ("Main Texture", 2D) = "white" {}
    }
    SubShader
    {
        Tags { "IGNOREPROJECTOR"="true" "QUEUE"="Geometry" "RenderType"="Opaque" }
        Pass
        {
            Tags { "IGNOREPROJECTOR"="true" "QUEUE"="Geometry" "RenderType"="Opaque" }
            Cull Off
            ZClip On
            ZTest LEqual
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend One Zero
            BlendOp Add
            ColorMask RGBA
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#pragma multi_compile __ BLUR_PLANE
#if (!defined(BLUR_PLANE))
            // Original Metal program SHA256: vertex ec3bf64221cf4fb11e3b85d1cdf651f6aacc10fc4c6e9f3f5db99bac25419566; fragment 05358817827d99164685e548eb428d7b8d741c11da161e6018789489788fa3cd.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

SamplerState sampler_MainTex;



struct RV_ec3bf64221cf_Input
{
    float4 POSITION0 : POSITION0;
};

struct RV_ec3bf64221cf_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 TEXCOORD0 : TEXCOORD0;
};

RV_ec3bf64221cf_Output RecoveryVertex(RV_ec3bf64221cf_Input input)
{
    RV_ec3bf64221cf_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.mtl_Position = u_xlat0;
    u_xlat0.y = u_xlat0.y * _ProjectionParams.x;
    u_xlat1.xzw = u_xlat0.xwy * float3(0.5, 0.5, 0.5);
    output.TEXCOORD0.zw = u_xlat0.zw;
    output.TEXCOORD0.xy = u_xlat1.zz + u_xlat1.xw;
    return output;
}



struct RF_05358817827d_Input
{
    float4 TEXCOORD0 : TEXCOORD0;
};

struct RF_05358817827d_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_05358817827d_Output RecoveryFragment(RF_05358817827d_Input input)
{
    RF_05358817827d_Output output;
    float2 u_xlat0;
    u_xlat0.xy = input.TEXCOORD0.xy / input.TEXCOORD0.ww;
    output.SV_Target0 = _MainTex.Sample(sampler_MainTex, u_xlat0.xy);
    return output;
}

#else
            // Original Metal program SHA256: vertex ec3bf64221cf4fb11e3b85d1cdf651f6aacc10fc4c6e9f3f5db99bac25419566; fragment ad85ac1cfb332ac9b0a0711ce371bbafd4ee46f147645524df7b8736e6e3f893.
#include "UnityCG.cginc"

float _BlurPlaneVibranceOffset;

Texture2D<float4> _MainTex;

SamplerState sampler_MainTex;



struct RV_ec3bf64221cf_Input
{
    float4 POSITION0 : POSITION0;
};

struct RV_ec3bf64221cf_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 TEXCOORD0 : TEXCOORD0;
};

RV_ec3bf64221cf_Output RecoveryVertex(RV_ec3bf64221cf_Input input)
{
    RV_ec3bf64221cf_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.mtl_Position = u_xlat0;
    u_xlat0.y = u_xlat0.y * _ProjectionParams.x;
    u_xlat1.xzw = u_xlat0.xwy * float3(0.5, 0.5, 0.5);
    output.TEXCOORD0.zw = u_xlat0.zw;
    output.TEXCOORD0.xy = u_xlat1.zz + u_xlat1.xw;
    return output;
}



struct RF_ad85ac1cfb33_Input
{
    float4 TEXCOORD0 : TEXCOORD0;
};

struct RF_ad85ac1cfb33_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_ad85ac1cfb33_Output RecoveryFragment(RF_ad85ac1cfb33_Input input)
{
    RF_ad85ac1cfb33_Output output;
    float u_xlat0;
    float4 u_xlat1;
    float2 u_xlat2;
    u_xlat0 = _BlurPlaneVibranceOffset + 1.0;
    u_xlat2.xy = input.TEXCOORD0.xy / input.TEXCOORD0.ww;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, u_xlat2.xy);
    output.SV_Target0.xyz = ((float3)(u_xlat0)) * u_xlat1.xyz;
    output.SV_Target0.w = u_xlat1.w;
    return output;
}

#endif
            ENDHLSL
        }
    }
}
