// Reconstructed from the licensed GOG macOS 1.0.30000 captured Metal programs.
// Generated by tools/shader_reconstruction/shaderlab_generator.py.
// Original serialized Shader SHA256: 98b3d04c72dd89951990a84496f518456d65d34397bd5bf5bf1c59509cb1f725
// Properties, render states, texture samplers, and retained variants come from the original data.
// Extra keyword combinations select a captured variant; see batch-generation-manifest.json.
Shader "Custom/Sway Grass Sprites-Diffuse"
{
    Properties
    {
        [PerRendererData] _MainTex ("Sprite Texture", 2D) = "white" {}
        _Color ("Tint", Color) = (1, 1, 1, 1)
        [HideInInspector] _RendererColor ("RendererColor", Color) = (1, 1, 1, 1)
        [HideInInspector] _Flip ("Flip", Vector) = (1, 1, 1, 1)
        [PerRendererData] _AlphaTex ("External Alpha", 2D) = "white" {}
        [PerRendererData] _EnableExternalAlpha ("Enable External Alpha", Float) = 0
        _SwaySpeed ("SwaySpeed", Float) = 1
        _SwayAmount ("Sway Amount", Float) = 1
        _WorldOffset ("World Offset", Float) = 1
        _ClampZ ("Clamp Z Position", Float) = 1
        _HeightOffset ("Height Offset", Float) = 0
        [PerRendererData] _PushAmount ("Push Amount (Player)", Float) = 0
    }
    SubShader
    {
        Tags { "CanUseSpriteAtlas"="true" "DisableBatching"="true" "IGNOREPROJECTOR"="true" "PreviewType"="Plane" "QUEUE"="Transparent" "RenderType"="Transparent" }
        Pass
        {
            Tags { "CanUseSpriteAtlas"="true" "DisableBatching"="true" "IGNOREPROJECTOR"="true" "PreviewType"="Plane" "QUEUE"="Transparent" "RenderType"="Transparent" }
            Cull Off
            ZClip On
            ZTest LEqual
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend One OneMinusSrcAlpha
            BlendOp Add
            ColorMask RGBA
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#pragma multi_compile __ ETC1_EXTERNAL_ALPHA
#if (defined(ETC1_EXTERNAL_ALPHA))
            // Original Metal program SHA256: vertex fe7b0b7dc32d5d38bbb599103cbeee121ff7811a085b8c77f04ec42055b9491c; fragment 1dbc166314061ce7e8bae2ccbcdb7ba356a26e0bb1ec5b30f58d4edb9b2dc77d.
#include "UnityCG.cginc"

Texture2D<float4> _AlphaTex;

float _ClampZ;

float4 _Color;

float _HeightOffset;

Texture2D<float4> _MainTex;

float _PushAmount;

float _SwayAmount;

float _SwaySpeed;

float _WorldOffset;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_AlphaTex;

SamplerState sampler_MainTex;



struct RV_fe7b0b7dc32d_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_fe7b0b7dc32d_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

RV_fe7b0b7dc32d_Output RecoveryVertex(RV_fe7b0b7dc32d_Input input)
{
    RV_fe7b0b7dc32d_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlat0.x = transpose(unity_ObjectToWorld)[3].z + transpose(unity_ObjectToWorld)[3].x;
    u_xlat0.x = u_xlat0.x * _WorldOffset;
    u_xlat0.x = mad(_Time.y, _SwaySpeed, u_xlat0.x);
    u_xlat0.x = sin(u_xlat0.x);
    u_xlat0.x = u_xlat0.x * _SwayAmount;
    u_xlat0.x = mad(u_xlat0.x, 1.25, _PushAmount);
    u_xlat2 = transpose(unity_ObjectToWorld)[0].y + transpose(unity_ObjectToWorld)[1].y;
    u_xlat2 = u_xlat2 + transpose(unity_ObjectToWorld)[2].y;
    u_xlat2 = mad(_HeightOffset, u_xlat2, input.POSITION0.y);
    u_xlat0.x = u_xlat2 * u_xlat0.x;
    u_xlat2 = max((-_ClampZ), transpose(unity_ObjectToWorld)[3].z);
    u_xlat2 = min(u_xlat2, _ClampZ);
    u_xlat2 = abs(u_xlat2) + 1.0;
    u_xlat0.x = mad(u_xlat0.x, u_xlat2, input.POSITION0.x);
    u_xlat0.y = input.POSITION0.y;
    u_xlat0.xy = u_xlat0.xy * _Flip.xyxx.xy;
    u_xlat1 = u_xlat0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlat0 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat0 * _RendererColor;
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_1dbc16631406_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RF_1dbc16631406_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_1dbc16631406_Output RecoveryFragment(RF_1dbc16631406_Input input)
{
    RF_1dbc16631406_Output output;
    float4 u_xlat0;
    float u_xlat1;
    float4 u_xlat2;
    u_xlat0.xyz = input.COLOR0.xyz * glstate_lightmodel_ambient.xyz;
    u_xlat0.xyz = u_xlat0.xyz + u_xlat0.xyz;
    u_xlat1 = _AlphaTex.Sample(sampler_AlphaTex, input.TEXCOORD0.xy).x;
    u_xlat2 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat1 = u_xlat1 + (-u_xlat2.w);
    u_xlat2.w = mad(_EnableExternalAlpha, u_xlat1, u_xlat2.w);
    u_xlat0.w = input.COLOR0.w;
    u_xlat0 = u_xlat0 * u_xlat2;
    output.SV_Target0.xyz = u_xlat0.www * u_xlat0.xyz;
    output.SV_Target0.w = u_xlat0.w;
    return output;
}

#else
            // Original Metal program SHA256: vertex fe7b0b7dc32d5d38bbb599103cbeee121ff7811a085b8c77f04ec42055b9491c; fragment 2ef78b5c8a7e2d8e3e95a240b4f295989b800b374ef95c7d1736b78abfb68483.
#include "UnityCG.cginc"

float _ClampZ;

float4 _Color;

float _HeightOffset;

Texture2D<float4> _MainTex;

float _PushAmount;

float _SwayAmount;

float _SwaySpeed;

float _WorldOffset;

CBUFFER_START(UnityPerDrawSprite)
    float4 _RendererColor;
    float2 _Flip;
    float _EnableExternalAlpha;
CBUFFER_END

SamplerState sampler_MainTex;



struct RV_fe7b0b7dc32d_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_fe7b0b7dc32d_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

RV_fe7b0b7dc32d_Output RecoveryVertex(RV_fe7b0b7dc32d_Input input)
{
    RV_fe7b0b7dc32d_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlat0.x = transpose(unity_ObjectToWorld)[3].z + transpose(unity_ObjectToWorld)[3].x;
    u_xlat0.x = u_xlat0.x * _WorldOffset;
    u_xlat0.x = mad(_Time.y, _SwaySpeed, u_xlat0.x);
    u_xlat0.x = sin(u_xlat0.x);
    u_xlat0.x = u_xlat0.x * _SwayAmount;
    u_xlat0.x = mad(u_xlat0.x, 1.25, _PushAmount);
    u_xlat2 = transpose(unity_ObjectToWorld)[0].y + transpose(unity_ObjectToWorld)[1].y;
    u_xlat2 = u_xlat2 + transpose(unity_ObjectToWorld)[2].y;
    u_xlat2 = mad(_HeightOffset, u_xlat2, input.POSITION0.y);
    u_xlat0.x = u_xlat2 * u_xlat0.x;
    u_xlat2 = max((-_ClampZ), transpose(unity_ObjectToWorld)[3].z);
    u_xlat2 = min(u_xlat2, _ClampZ);
    u_xlat2 = abs(u_xlat2) + 1.0;
    u_xlat0.x = mad(u_xlat0.x, u_xlat2, input.POSITION0.x);
    u_xlat0.y = input.POSITION0.y;
    u_xlat0.xy = u_xlat0.xy * _Flip.xyxx.xy;
    u_xlat1 = u_xlat0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlat0 = input.COLOR0 * _Color;
    output.COLOR0 = u_xlat0 * _RendererColor;
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_2ef78b5c8a7e_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RF_2ef78b5c8a7e_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_2ef78b5c8a7e_Output RecoveryFragment(RF_2ef78b5c8a7e_Input input)
{
    RF_2ef78b5c8a7e_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.xyz = input.COLOR0.xyz * glstate_lightmodel_ambient.xyz;
    u_xlat0.xyz = u_xlat0.xyz + u_xlat0.xyz;
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat0.w = input.COLOR0.w;
    u_xlat0 = u_xlat0 * u_xlat1;
    output.SV_Target0.xyz = u_xlat0.www * u_xlat0.xyz;
    output.SV_Target0.w = u_xlat0.w;
    return output;
}

#endif
            ENDHLSL
        }
    }
    Fallback "Transparent/VertexLit"
}
