// Reconstructed from the licensed GOG macOS 1.0.30000 captured Metal programs.
// Generated by tools/shader_reconstruction/shaderlab_generator.py.
// Original serialized Shader SHA256: 567bfcfe38e28b0a371d9bbfb5f8347aba384be27519be5c51d9f232fa595de2
// Properties, render states, texture samplers, and retained variants come from the original data.
// Extra keyword combinations select a captured variant; see batch-generation-manifest.json.
Shader "Sprites/CameraScrollingSpriteTexture"
{
    Properties
    {
        _MainTex ("Sprite Texture", 2D) = "white" {}
        _ColorTex ("Color Texture", 2D) = "white" {}
        _Color ("Tint", Color) = (1, 1, 1, 1)
        _ScrollSpeed ("Scroll Speed", Vector) = (0, 0, 0, 0)
        _Scale ("Scale", Vector) = (1, 1, 0, 0)
    }
    SubShader
    {
        LOD 100
        Tags { "QUEUE"="Transparent" "RenderType"="Transparent" }
        Pass
        {
            Tags { "QUEUE"="Transparent" "RenderType"="Transparent" }
            Cull Off
            ZClip On
            ZTest LEqual
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend SrcAlpha OneMinusSrcAlpha
            BlendOp Add
            ColorMask RGBA
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#if (1)
            // Original Metal program SHA256: vertex d7478f0793fe359d839d067dba6956592aea9117de331b9d0c25c3bc31f95cde; fragment 880906e0afdff8b3a13c6f30ba01038525fd69d82773972ce1723a9fa4e821a1.
#include "UnityCG.cginc"

float4 _Color;

Texture2D<float4> _ColorTex;

Texture2D<float4> _MainTex;

float4 _Scale;

float4 _ScrollSpeed;

SamplerState sampler_ColorTex;

SamplerState sampler_MainTex;



struct RV_d7478f0793fe_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 COLOR0 : COLOR0;
};

struct RV_d7478f0793fe_Output
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
};

RV_d7478f0793fe_Output RecoveryVertex(RV_d7478f0793fe_Input input)
{
    RV_d7478f0793fe_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat1.xy = mad(transpose(unity_ObjectToWorld)[3].xy, input.POSITION0.ww, u_xlat0.xy);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1.xy = u_xlat1.xy + _WorldSpaceCameraPos.xyzx.xy;
    u_xlat1.xy = mad(u_xlat1.xy, _ScrollSpeed.xy, input.TEXCOORD0.xy);
    output.TEXCOORD1.xy = u_xlat1.xy / _Scale.xy;
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.COLOR0 = input.COLOR0 * _Color;
    return output;
}



struct RF_880906e0afdf_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
    float4 COLOR0 : COLOR0;
};

struct RF_880906e0afdf_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_880906e0afdf_Output RecoveryFragment(RF_880906e0afdf_Input input)
{
    RF_880906e0afdf_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0.x = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy).w;
    u_xlat1 = _ColorTex.Sample(sampler_ColorTex, input.TEXCOORD1.xy);
    u_xlat0.y = u_xlat1.w;
    u_xlat1 = u_xlat0.xxxy * u_xlat1;
    u_xlat0 = u_xlat0.yyyx * u_xlat1;
    output.SV_Target0 = u_xlat0 * input.COLOR0;
    return output;
}

#endif
            ENDHLSL
        }
    }
}
