// Reconstructed from the licensed GOG macOS 1.0.30000 captured Metal programs.
// Generated by tools/shader_reconstruction/shaderlab_generator.py.
// Original serialized Shader SHA256: a65fca4427c09b67593eb8b696e24c58ccbfa76db8b712ee76b456ce13115910
// Properties, render states, texture samplers, and retained variants come from the original data.
// Extra keyword combinations select a captured variant; see batch-generation-manifest.json.
Shader "Unlit/Noise New"
{
    Properties
    {
        _MainTex ("Sprite Texture", 2D) = "white" {}
        _NoiseTex ("Noise Texture", 2D) = "white" {}
        _NoiseColor ("Noise Color", Vector) = (1, 1, 1, 1)
        _NoiseStrength ("Noise Strength", Float) = 0.5
        _TimeSnap ("Time Snap", Float) = 0.5
    }
    SubShader
    {
        LOD 100
        Tags { "RenderType"="Opaque" }
        Pass
        {
            Tags { "RenderType"="Opaque" }
            Cull Back
            ZClip On
            ZTest LEqual
            ZWrite On
            Offset 0, 0
            AlphaToMask Off
            Blend One Zero
            BlendOp Add
            ColorMask RGBA
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#if (1)
            // Original Metal program SHA256: vertex 61592c8aa19fff65c9fdc95331afa338916ce0fa6e5852e26a2378e2075dd421; fragment 4d7614fa3fd0290933088eb6cf261ae151cca7ef8e4def27f49977d774bfd75e.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float4 _NoiseColor;

float _NoiseStrength;

Texture2D<float4> _NoiseTex;

float _TimeSnap;

SamplerState sampler_MainTex;

SamplerState sampler_NoiseTex;



struct RV_61592c8aa19f_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_61592c8aa19f_Output
{
    float2 TEXCOORD0 : TEXCOORD0;
    float4 mtl_Position : SV_POSITION;
};

RV_61592c8aa19f_Output RecoveryVertex(RV_61592c8aa19f_Input input)
{
    RV_61592c8aa19f_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    return output;
}



struct RF_4d7614fa3fd0_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RF_4d7614fa3fd0_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_4d7614fa3fd0_Output RecoveryFragment(RF_4d7614fa3fd0_Input input)
{
    RF_4d7614fa3fd0_Output output;
    float3 u_xlat0;
    float4 u_xlat1;
    float u_xlat4;
    u_xlat0.xy = _Time.zx / ((float2)(_TimeSnap));
    u_xlat0.xy = round(u_xlat0.xy);
    u_xlat0.xy = u_xlat0.xy * ((float2)(_TimeSnap));
    u_xlat4 = dot(u_xlat0.xy, float2(127.099998, 311.700012));
    u_xlat0.x = dot(u_xlat0.xy, float2(269.5, 183.300003));
    u_xlat0.y = sin(u_xlat0.x);
    u_xlat0.x = sin(u_xlat4);
    u_xlat0.xy = u_xlat0.xy * float2(43758.5469, 43758.5469);
    u_xlat0.xy = frac(u_xlat0.xy);
    u_xlat0.xy = mad(u_xlat0.xy, float2(2.0, 2.0), float2(-1.0, -1.0));
    u_xlat0.xy = mad(u_xlat0.xy, float2(162.184998, 162.184998), input.TEXCOORD0.xy);
    u_xlat0.x = _NoiseTex.Sample(sampler_NoiseTex, u_xlat0.xy).x;
    u_xlat0.x = u_xlat0.x + -0.5;
    u_xlat0.x = u_xlat0.x * _NoiseStrength;
    u_xlat0.xyz = mad(_NoiseColor.xyz, u_xlat0.xxx, float3(1.0, 1.0, 1.0));
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    output.SV_Target0.xyz = u_xlat0.xyz * u_xlat1.xyz;
    output.SV_Target0.xyz = clamp(output.SV_Target0.xyz, 0.0f, 1.0f);
    output.SV_Target0.w = u_xlat1.w;
    return output;
}

#endif
            ENDHLSL
        }
    }
}
