// Reconstructed from the licensed GOG macOS 1.0.30000 captured Metal programs.
// Generated by tools/shader_reconstruction/shaderlab_generator.py.
// Original serialized Shader SHA256: 51888803b01497547c0511c241599ff8fffee0e4855afe33ce9c1a3fb5543572
// Properties, render states, texture samplers, and retained variants come from the original data.
// Extra keyword combinations select a captured variant; see batch-generation-manifest.json.
Shader "tk2d/BlendVertexColor"
{
    Properties
    {
        _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
    }
    SubShader
    {
        LOD 110
        Tags { "IGNOREPROJECTOR"="true" "QUEUE"="Transparent" "RenderType"="Transparent" }
        Pass
        {
            Tags { "IGNOREPROJECTOR"="true" "QUEUE"="Transparent" "RenderType"="Transparent" }
            Cull Off
            ZClip On
            ZTest LEqual
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend SrcAlpha OneMinusSrcAlpha
            BlendOp Add
            ColorMask RGBA
            Fog { Mode Off }
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#if (1)
            // Original Metal program SHA256: vertex 3d8e76204656a61a6f4fe6535e491caacab63a0fe02ce63f69a3659dba5db487; fragment efb590234c0cdc1d872c53000655cb6175cdcc4564939df2533f7890200c0e03.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

SamplerState sampler_MainTex;



struct RV_3d8e76204656_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_3d8e76204656_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

RV_3d8e76204656_Output RecoveryVertex(RV_3d8e76204656_Input input)
{
    RV_3d8e76204656_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.COLOR0 = input.COLOR0;
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_efb590234c0c_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RF_efb590234c0c_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_efb590234c0c_Output RecoveryFragment(RF_efb590234c0c_Input input)
{
    RF_efb590234c0c_Output output;
    float4 u_xlat0;
    u_xlat0 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    output.SV_Target0 = u_xlat0 * input.COLOR0;
    return output;
}

#endif
            ENDHLSL
        }
    }
}
