// Reconstructed from the licensed GOG macOS 1.0.30000 captured Metal programs.
// Generated by tools/shader_reconstruction/shaderlab_generator.py.
// Original serialized Shader SHA256: 8326e7855f372bb2b46387dbbfc38e50b2d112a51e69eb74ebb5e7eb5d2f8564
// Properties, render states, texture samplers, and retained variants come from the original data.
// Extra keyword combinations select a captured variant; see batch-generation-manifest.json.
Shader "UI/BlendModes/Font/LighterColor"
{
    Properties
    {
        [PerRendererData] _MainTex ("Sprite Texture", 2D) = "white" {}
        _Color ("Tint", Color) = (1, 1, 1, 1)
        _StencilComp ("Stencil Comparison", Float) = 8
        _Stencil ("Stencil ID", Float) = 0
        _StencilOp ("Stencil Operation", Float) = 0
        _StencilWriteMask ("Stencil Write Mask", Float) = 255
        _StencilReadMask ("Stencil Read Mask", Float) = 255
        _ColorMask ("Color Mask", Float) = 15
    }
    SubShader
    {
        Tags { "IGNOREPROJECTOR"="true" "PreviewType"="Plane" "QUEUE"="Transparent" "RenderType"="Transparent" }
        GrabPass
        {
        }
        Pass
        {
            Tags { "IGNOREPROJECTOR"="true" "PreviewType"="Plane" "QUEUE"="Transparent" "RenderType"="Transparent" }
            Cull Off
            ZClip On
            ZTest [unity_GUIZTestMode]
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend SrcAlpha OneMinusSrcAlpha
            BlendOp Add
            ColorMask [_ColorMask]
            Stencil
            {
                Ref [_Stencil]
                ReadMask [_StencilReadMask]
                WriteMask [_StencilWriteMask]
                Comp [_StencilComp]
                Pass [_StencilOp]
                Fail Keep
                ZFail Keep
            }
            Fog { Mode Off }
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#if (1)
            // Original Metal program SHA256: vertex e8a9390e720e488a88e40250c1ba00023b6a0912c1a9c492b33e4eeae6773cf0; fragment 05e214d3b6d987b7389b7b7020c75b6881e9739e7383dfbabdcea672c97cb9ff.
#include "UnityCG.cginc"

float4 _Color;

Texture2D<float4> _GrabTexture;

Texture2D<float4> _MainTex;

SamplerState sampler_GrabTexture;

SamplerState sampler_MainTex;



struct RV_e8a9390e720e_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_e8a9390e720e_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_e8a9390e720e_Output RecoveryVertex(RV_e8a9390e720e_Input input)
{
    RV_e8a9390e720e_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.mtl_Position = u_xlat0;
    output.TEXCOORD1 = u_xlat0;
    output.COLOR0 = input.COLOR0 * _Color;
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_05e214d3b6d9_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_05e214d3b6d9_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_05e214d3b6d9_Output RecoveryFragment(RF_05e214d3b6d9_Input input)
{
    RF_05e214d3b6d9_Output output;
    float3 u_xlat0;
    bool u_xlatb0;
    float u_xlat1;
    float u_xlat2;
    float u_xlat6;
    bool u_xlatb6;
    u_xlat0.x = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy).w;
    u_xlat2 = mad(input.COLOR0.w, u_xlat0.x, -0.00999999978);
    u_xlat0.x = u_xlat0.x * input.COLOR0.w;
    output.SV_Target0.w = u_xlat0.x;
    u_xlatb0 = u_xlat2<0.0;
    if(((int(u_xlatb0) * int(0xffffffffu)))!=0){discard;}
    u_xlat0.xy = input.TEXCOORD1.xy / input.TEXCOORD1.ww;
    u_xlat0.xy = u_xlat0.xy + float2(1.0, 1.0);
    u_xlat0.x = u_xlat0.x * 0.5;
    u_xlat0.z = mad((-u_xlat0.y), 0.5, 1.0);
    u_xlat0.xyz = _GrabTexture.Sample(sampler_GrabTexture, u_xlat0.xz).xyz;
    u_xlat6 = dot(u_xlat0.xyz, float3(0.298999995, 0.587000012, 0.114));
    u_xlat1 = dot(input.COLOR0.xyz, float3(0.298999995, 0.587000012, 0.114));
    u_xlatb6 = u_xlat1<u_xlat6;
    output.SV_Target0.xyz = (bool(u_xlatb6)) ? u_xlat0.xyz : input.COLOR0.xyz;
    return output;
}

#endif
            ENDHLSL
        }
    }
    Fallback "UI/Default Font"
}
