// Reconstructed from the licensed GOG macOS 1.0.30000 captured Metal programs.
// Generated by tools/shader_reconstruction/shaderlab_generator.py.
// Original serialized Shader SHA256: 153bbe72a15bf5d294a74010dc80552aab4741407ba7a3b016e1fed2036883ea
// Properties, render states, texture samplers, and retained variants come from the original data.
// Extra keyword combinations select a captured variant; see batch-generation-manifest.json.
Shader "Hidden/NoiseAndGrain"
{
    Properties
    {
        _MainTex ("Base (RGB)", 2D) = "white" {}
        _NoiseTex ("Noise (RGB)", 2D) = "white" {}
    }
    SubShader
    {
        Pass
        {
            Cull Off
            ZClip On
            ZTest Always
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend One Zero
            BlendOp Add
            ColorMask RGBA
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#if (1)
            // Original Metal program SHA256: vertex c2f8b9dc4efba07715adeccd71ceac4f3da57e6e137aed9e5623a4d4d37e455c; fragment bf7e37483db99597bb497eaab1c9f8f27aef5e4b59b90a95e85ca80682e86d09.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

float3 _MidGrey;

float3 _NoiseAmount;

float3 _NoisePerChannel;

Texture2D<float4> _NoiseTex;

float4 _NoiseTex_TexelSize;

float3 _NoiseTilingPerChannel;

SamplerState sampler_MainTex;

SamplerState sampler_NoiseTex;



struct RV_c2f8b9dc4efb_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RV_c2f8b9dc4efb_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD2 : TEXCOORD2;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_c2f8b9dc4efb_Output RecoveryVertex(RV_c2f8b9dc4efb_Input input)
{
    RV_c2f8b9dc4efb_Output output;
    float4 u_xlat0;
    bool u_xlatb0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlatb0 = _MainTex_TexelSize.y<0.0;
    u_xlat2 = (-input.POSITION0.y) + 1.0;
    output.TEXCOORD0.y = (u_xlatb0) ? u_xlat2 : input.POSITION0.y;
    u_xlat0.xy = input.TEXCOORD1.xy * _NoiseTilingPerChannel.xyzx.zz;
    output.TEXCOORD2.xy = mad(u_xlat0.xy, _NoiseTex_TexelSize.xy, input.TEXCOORD0.xy);
    output.TEXCOORD0.x = input.POSITION0.x;
    u_xlat0 = input.TEXCOORD1.xyxy * _NoiseTilingPerChannel.xyzx.xxyy;
    output.TEXCOORD1 = mad(u_xlat0, _NoiseTex_TexelSize.xyxy, input.TEXCOORD0.xyxy);
    return output;
}



struct RF_bf7e37483db9_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD2 : TEXCOORD2;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_bf7e37483db9_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_bf7e37483db9_Output RecoveryFragment(RF_bf7e37483db9_Input input)
{
    RF_bf7e37483db9_Output output;
    float3 u_xlat0;
    float4 u_xlat1;
    bool3 u_xlatb1;
    float3 u_xlat2;
    float3 u_xlat3;
    float u_xlat12;
    u_xlat0.xyz = _NoiseTex.Sample(sampler_NoiseTex, input.TEXCOORD1.zw).xyz;
    u_xlat0.xyz = u_xlat0.xyz * float3(0.0, 1.0, 0.0);
    u_xlat1.xyz = _NoiseTex.Sample(sampler_NoiseTex, input.TEXCOORD1.xy).xyz;
    u_xlat0.xyz = mad(u_xlat1.xyz, float3(1.0, 0.0, 0.0), u_xlat0.xyz);
    u_xlat1.xyz = _NoiseTex.Sample(sampler_NoiseTex, input.TEXCOORD2.xy).xyz;
    u_xlat0.xyz = mad(u_xlat1.xyz, float3(0.0, 0.0, 1.0), u_xlat0.xyz);
    u_xlat0.xyz = u_xlat0.xyz + float3(-0.5, -0.5, -0.5);
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat12 = dot(u_xlat1.xyz, float3(0.219999999, 0.707000017, 0.0710000023));
    u_xlat12 = u_xlat12 + (-_MidGrey.xyzx.x);
    u_xlat2.xy = ((float2)(u_xlat12)) * _MidGrey.xyzx.yz;
    u_xlat2.xy = clamp(u_xlat2.xy, 0.0f, 1.0f);
    u_xlat12 = dot(_NoiseAmount.xyzx.zy, u_xlat2.xy);
    u_xlat12 = max(u_xlat12, 0.0);
    u_xlat12 = u_xlat12 + _NoiseAmount.xyzx.x;
    u_xlat2.xyz = ((float3)(u_xlat12)) * _NoisePerChannel.xyzx.xyz;
    u_xlat0.xyz = mad(u_xlat2.xyz, u_xlat0.xyz, float3(0.5, 0.5, 0.5));
    u_xlat0.xyz = clamp(u_xlat0.xyz, 0.0f, 1.0f);
    u_xlat2.xyz = (-u_xlat0.xyz) + float3(1.0, 1.0, 1.0);
    u_xlat1.xyz = u_xlat1.xyz;
    u_xlat1.xyz = clamp(u_xlat1.xyz, 0.0f, 1.0f);
    output.SV_Target0.w = u_xlat1.w;
    u_xlat3.xyz = u_xlat1.xyz + float3(-0.5, -0.5, -0.5);
    u_xlat3.xyz = mad((-u_xlat3.xyz), float3(2.0, 2.0, 2.0), float3(1.0, 1.0, 1.0));
    u_xlat2.xyz = mad((-u_xlat3.xyz), u_xlat2.xyz, float3(1.0, 1.0, 1.0));
    u_xlat0.xyz = u_xlat0.xyz * u_xlat1.xyz;
    u_xlatb1.xyz = (u_xlat1.xyz>=float3(0.5, 0.5, 0.5));
    {
        float3 hlslcc_movcTemp = u_xlat0;
        hlslcc_movcTemp.x = (u_xlatb1.x) ? float(0.0) : u_xlat0.x;
        hlslcc_movcTemp.y = (u_xlatb1.y) ? float(0.0) : u_xlat0.y;
        hlslcc_movcTemp.z = (u_xlatb1.z) ? float(0.0) : u_xlat0.z;
        u_xlat0 = hlslcc_movcTemp;
    }
    u_xlat1.xyz = ((((bool3)(u_xlatb1.xyz))) ? (float3(1.0, 1.0, 1.0)) : (float3(0.0, 0.0, 0.0)));
    u_xlat0.xyz = u_xlat0.xyz + u_xlat0.xyz;
    output.SV_Target0.xyz = mad(u_xlat1.xyz, u_xlat2.xyz, u_xlat0.xyz);
    return output;
}

#endif
            ENDHLSL
        }
        Pass
        {
            Cull Off
            ZClip On
            ZTest Always
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend One Zero
            BlendOp Add
            ColorMask RGBA
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#if (1)
            // Original Metal program SHA256: vertex c2f8b9dc4efba07715adeccd71ceac4f3da57e6e137aed9e5623a4d4d37e455c; fragment 9116eeb3bbde16911d85c747a00628c7025b2df23eb2944799ef7a482a4f7d9a.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

Texture2D<float4> _NoiseTex;

float4 _NoiseTex_TexelSize;

float3 _NoiseTilingPerChannel;

SamplerState sampler_MainTex;

SamplerState sampler_NoiseTex;



struct RV_c2f8b9dc4efb_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RV_c2f8b9dc4efb_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD2 : TEXCOORD2;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_c2f8b9dc4efb_Output RecoveryVertex(RV_c2f8b9dc4efb_Input input)
{
    RV_c2f8b9dc4efb_Output output;
    float4 u_xlat0;
    bool u_xlatb0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlatb0 = _MainTex_TexelSize.y<0.0;
    u_xlat2 = (-input.POSITION0.y) + 1.0;
    output.TEXCOORD0.y = (u_xlatb0) ? u_xlat2 : input.POSITION0.y;
    u_xlat0.xy = input.TEXCOORD1.xy * _NoiseTilingPerChannel.xyzx.zz;
    output.TEXCOORD2.xy = mad(u_xlat0.xy, _NoiseTex_TexelSize.xy, input.TEXCOORD0.xy);
    output.TEXCOORD0.x = input.POSITION0.x;
    u_xlat0 = input.TEXCOORD1.xyxy * _NoiseTilingPerChannel.xyzx.xxyy;
    output.TEXCOORD1 = mad(u_xlat0, _NoiseTex_TexelSize.xyxy, input.TEXCOORD0.xyxy);
    return output;
}



struct RF_9116eeb3bbde_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RF_9116eeb3bbde_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_9116eeb3bbde_Output RecoveryFragment(RF_9116eeb3bbde_Input input)
{
    RF_9116eeb3bbde_Output output;
    float3 u_xlat0;
    float3 u_xlat1;
    float4 u_xlat2;
    float3 u_xlat3;
    bool3 u_xlatb3;
    u_xlat0.xyz = _NoiseTex.Sample(sampler_NoiseTex, input.TEXCOORD0.xy).xyz;
    u_xlat1.xyz = (-u_xlat0.xyz) + float3(1.0, 1.0, 1.0);
    u_xlat2 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat2.xyz = u_xlat2.xyz;
    u_xlat2.xyz = clamp(u_xlat2.xyz, 0.0f, 1.0f);
    output.SV_Target0.w = u_xlat2.w;
    u_xlat3.xyz = u_xlat2.xyz + float3(-0.5, -0.5, -0.5);
    u_xlat3.xyz = mad((-u_xlat3.xyz), float3(2.0, 2.0, 2.0), float3(1.0, 1.0, 1.0));
    u_xlat1.xyz = mad((-u_xlat3.xyz), u_xlat1.xyz, float3(1.0, 1.0, 1.0));
    u_xlatb3.xyz = (u_xlat2.xyz>=float3(0.5, 0.5, 0.5));
    {
        float4 hlslcc_movcTemp = u_xlat2;
        hlslcc_movcTemp.x = (u_xlatb3.x) ? float(0.0) : u_xlat2.x;
        hlslcc_movcTemp.y = (u_xlatb3.y) ? float(0.0) : u_xlat2.y;
        hlslcc_movcTemp.z = (u_xlatb3.z) ? float(0.0) : u_xlat2.z;
        u_xlat2 = hlslcc_movcTemp;
    }
    u_xlat3.xyz = ((((bool3)(u_xlatb3.xyz))) ? (float3(1.0, 1.0, 1.0)) : (float3(0.0, 0.0, 0.0)));
    u_xlat0.xyz = u_xlat0.xyz * u_xlat2.xyz;
    u_xlat0.xyz = u_xlat0.xyz + u_xlat0.xyz;
    output.SV_Target0.xyz = mad(u_xlat3.xyz, u_xlat1.xyz, u_xlat0.xyz);
    return output;
}

#endif
            ENDHLSL
        }
        Pass
        {
            Cull Off
            ZClip On
            ZTest Always
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend One Zero
            BlendOp Add
            ColorMask RGBA
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#if (1)
            // Original Metal program SHA256: vertex c2f8b9dc4efba07715adeccd71ceac4f3da57e6e137aed9e5623a4d4d37e455c; fragment 1621659062ba385455d60dda35c2f8516ee0e020f6944ce3af713c797c047efd.
#include "UnityCG.cginc"

Texture2D<float4> _MainTex;

float4 _MainTex_TexelSize;

float3 _MidGrey;

float3 _NoiseAmount;

float3 _NoisePerChannel;

Texture2D<float4> _NoiseTex;

float4 _NoiseTex_TexelSize;

float3 _NoiseTilingPerChannel;

SamplerState sampler_MainTex;

SamplerState sampler_NoiseTex;



struct RV_c2f8b9dc4efb_Input
{
    float4 POSITION0 : POSITION0;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD1 : TEXCOORD1;
};

struct RV_c2f8b9dc4efb_Output
{
    float4 mtl_Position : SV_POSITION;
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD2 : TEXCOORD2;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_c2f8b9dc4efb_Output RecoveryVertex(RV_c2f8b9dc4efb_Input input)
{
    RV_c2f8b9dc4efb_Output output;
    float4 u_xlat0;
    bool u_xlatb0;
    float4 u_xlat1;
    float u_xlat2;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    output.mtl_Position = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    u_xlatb0 = _MainTex_TexelSize.y<0.0;
    u_xlat2 = (-input.POSITION0.y) + 1.0;
    output.TEXCOORD0.y = (u_xlatb0) ? u_xlat2 : input.POSITION0.y;
    u_xlat0.xy = input.TEXCOORD1.xy * _NoiseTilingPerChannel.xyzx.zz;
    output.TEXCOORD2.xy = mad(u_xlat0.xy, _NoiseTex_TexelSize.xy, input.TEXCOORD0.xy);
    output.TEXCOORD0.x = input.POSITION0.x;
    u_xlat0 = input.TEXCOORD1.xyxy * _NoiseTilingPerChannel.xyzx.xxyy;
    output.TEXCOORD1 = mad(u_xlat0, _NoiseTex_TexelSize.xyxy, input.TEXCOORD0.xyxy);
    return output;
}



struct RF_1621659062ba_Input
{
    float2 TEXCOORD0 : TEXCOORD0;
    float2 TEXCOORD2 : TEXCOORD2;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_1621659062ba_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_1621659062ba_Output RecoveryFragment(RF_1621659062ba_Input input)
{
    RF_1621659062ba_Output output;
    float3 u_xlat0;
    float4 u_xlat1;
    float u_xlat6;
    u_xlat0.xyz = _NoiseTex.Sample(sampler_NoiseTex, input.TEXCOORD1.zw).xyz;
    u_xlat0.xyz = u_xlat0.xyz * float3(0.0, 1.0, 0.0);
    u_xlat1.xyz = _NoiseTex.Sample(sampler_NoiseTex, input.TEXCOORD1.xy).xyz;
    u_xlat0.xyz = mad(u_xlat1.xyz, float3(1.0, 0.0, 0.0), u_xlat0.xyz);
    u_xlat1.xyz = _NoiseTex.Sample(sampler_NoiseTex, input.TEXCOORD2.xy).xyz;
    u_xlat0.xyz = mad(u_xlat1.xyz, float3(0.0, 0.0, 1.0), u_xlat0.xyz);
    u_xlat0.xyz = u_xlat0.xyz + float3(-0.5, -0.5, -0.5);
    u_xlat1 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat6 = dot(u_xlat1.xyz, float3(0.219999999, 0.707000017, 0.0710000023));
    output.SV_Target0.w = u_xlat1.w;
    u_xlat6 = u_xlat6 + (-_MidGrey.xyzx.x);
    u_xlat1.xy = ((float2)(u_xlat6)) * _MidGrey.xyzx.yz;
    u_xlat1.xy = clamp(u_xlat1.xy, 0.0f, 1.0f);
    u_xlat6 = dot(_NoiseAmount.xyzx.zy, u_xlat1.xy);
    u_xlat6 = max(u_xlat6, 0.0);
    u_xlat6 = u_xlat6 + _NoiseAmount.xyzx.x;
    u_xlat1.xyz = ((float3)(u_xlat6)) * _NoisePerChannel.xyzx.xyz;
    output.SV_Target0.xyz = mad(u_xlat1.xyz, u_xlat0.xyz, float3(0.5, 0.5, 0.5));
    output.SV_Target0.xyz = clamp(output.SV_Target0.xyz, 0.0f, 1.0f);
    return output;
}

#endif
            ENDHLSL
        }
    }
    Fallback Off
}
