namespace GlobalEnums
{
	public enum MainMenuState
	{
		LOGO = 0,
		MAIN_MENU = 1,
		OPTIONS_MENU = 2,
		GAMEPAD_MENU = 3,
		ADVANCED_GAMEPAD_MENU = 4,
		KEYBOARD_MENU = 5,
		SAVE_PROFILES = 6,
		AUDIO_MENU = 7,
		VIDEO_MENU = 8,
		ADVANCED_VIDEO_MENU = 9,
		EXIT_PROMPT = 10,
		OVERSCAN_MENU = 11,
		GAME_OPTIONS_MENU = 12,
		ACHIEVEMENTS_MENU = 13,
		QUIT_GAME_PROMPT = 14,
		RESOLUTION_PROMPT = 15,
		BRIGHTNESS_MENU = 16,
		PAUSE_MENU = 17,
		PLAY_MODE_MENU = 18,
		EXTRAS_MENU = 19,
		REMAP_GAMEPAD_MENU = 20,
		EXTRAS_CONTENT_MENU = 21,
		ENGAGE_MENU = 22
	}
}
