// Reconstructed from the licensed GOG macOS 1.0.30000 captured Metal programs.
// Generated by tools/shader_reconstruction/shaderlab_generator.py.
// Original serialized Shader SHA256: 218d92ee4146442668463f70f47905ca2195b5e413a01d15fadad3a6f52b10f1
// Properties, render states, texture samplers, and retained variants come from the original data.
// Extra keyword combinations select a captured variant; see batch-generation-manifest.json.
Shader "UI/BlendModes/Optimized/HardLight"
{
    Properties
    {
        [PerRendererData] _MainTex ("Sprite Texture", 2D) = "white" {}
        _Color ("Tint", Color) = (1, 1, 1, 1)
        _StencilComp ("Stencil Comparison", Float) = 8
        _Stencil ("Stencil ID", Float) = 0
        _StencilOp ("Stencil Operation", Float) = 0
        _StencilWriteMask ("Stencil Write Mask", Float) = 255
        _StencilReadMask ("Stencil Read Mask", Float) = 255
        _ColorMask ("Color Mask", Float) = 15
    }
    SubShader
    {
        Tags { "IGNOREPROJECTOR"="true" "PreviewType"="Plane" "QUEUE"="Transparent" "RenderType"="Transparent" }
        GrabPass
        {
            "_GUIBlendingSharedGT"
        }
        Pass
        {
            Tags { "IGNOREPROJECTOR"="true" "PreviewType"="Plane" "QUEUE"="Transparent" "RenderType"="Transparent" }
            Cull Off
            ZClip On
            ZTest [unity_GUIZTestMode]
            ZWrite Off
            Offset 0, 0
            AlphaToMask Off
            Blend SrcAlpha OneMinusSrcAlpha
            BlendOp Add
            ColorMask [_ColorMask]
            Stencil
            {
                Ref [_Stencil]
                ReadMask [_StencilReadMask]
                WriteMask [_StencilWriteMask]
                Comp [_StencilComp]
                Pass [_StencilOp]
                Fail Keep
                ZFail Keep
            }
            Fog { Mode Off }
            HLSLPROGRAM
#pragma target 4.5
#pragma vertex RecoveryVertex
#pragma fragment RecoveryFragment
#if (1)
            // Original Metal program SHA256: vertex e8a9390e720e488a88e40250c1ba00023b6a0912c1a9c492b33e4eeae6773cf0; fragment 0054dfde082167ca03f101bb8ed6d9284f746816603d99c14f64d9fc4b9d2ead.
#include "UnityCG.cginc"

float4 _Color;

Texture2D<float4> _GUIBlendingSharedGT;

Texture2D<float4> _MainTex;

SamplerState sampler_GUIBlendingSharedGT;

SamplerState sampler_MainTex;



struct RV_e8a9390e720e_Input
{
    float4 POSITION0 : POSITION0;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
};

struct RV_e8a9390e720e_Output
{
    float4 mtl_Position : SV_POSITION;
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

RV_e8a9390e720e_Output RecoveryVertex(RV_e8a9390e720e_Input input)
{
    RV_e8a9390e720e_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    u_xlat0 = input.POSITION0.yyyy * transpose(unity_ObjectToWorld)[1];
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[0], input.POSITION0.xxxx, u_xlat0);
    u_xlat0 = mad(transpose(unity_ObjectToWorld)[2], input.POSITION0.zzzz, u_xlat0);
    u_xlat0 = u_xlat0 + transpose(unity_ObjectToWorld)[3];
    u_xlat1 = u_xlat0.yyyy * transpose(unity_MatrixVP)[1];
    u_xlat1 = mad(transpose(unity_MatrixVP)[0], u_xlat0.xxxx, u_xlat1);
    u_xlat1 = mad(transpose(unity_MatrixVP)[2], u_xlat0.zzzz, u_xlat1);
    u_xlat0 = mad(transpose(unity_MatrixVP)[3], u_xlat0.wwww, u_xlat1);
    output.mtl_Position = u_xlat0;
    output.TEXCOORD1 = u_xlat0;
    output.COLOR0 = input.COLOR0 * _Color;
    output.TEXCOORD0.xy = input.TEXCOORD0.xy;
    return output;
}



struct RF_0054dfde0821_Input
{
    float4 COLOR0 : COLOR0;
    float2 TEXCOORD0 : TEXCOORD0;
    float4 TEXCOORD1 : TEXCOORD1;
};

struct RF_0054dfde0821_Output
{
    float4 SV_Target0 : SV_Target0;
};

RF_0054dfde0821_Output RecoveryFragment(RF_0054dfde0821_Input input)
{
    RF_0054dfde0821_Output output;
    float4 u_xlat0;
    float4 u_xlat1;
    bool u_xlatb1;
    float3 u_xlat2;
    float3 u_xlat3;
    bool3 u_xlatb3;
    float2 u_xlat4;
    float3 u_xlat5;
    float u_xlat13;
    u_xlat0 = _MainTex.Sample(sampler_MainTex, input.TEXCOORD0.xy);
    u_xlat1 = mad(u_xlat0.wxyz, input.COLOR0.wxyz, float4(-0.00999999978, -0.5, -0.5, -0.5));
    u_xlat0 = u_xlat0.wxyz * input.COLOR0.wxyz;
    u_xlatb1 = u_xlat1.x<0.0;
    u_xlat5.xyz = mad((-u_xlat1.yzw), float3(2.0, 2.0, 2.0), float3(1.0, 1.0, 1.0));
    if(((int(u_xlatb1) * int(0xffffffffu)))!=0){discard;}
    u_xlat2.xy = input.TEXCOORD1.xy / input.TEXCOORD1.ww;
    u_xlat2.xy = u_xlat2.xy + float2(1.0, 1.0);
    u_xlat2.x = u_xlat2.x * 0.5;
    u_xlat2.z = mad((-u_xlat2.y), 0.5, 1.0);
    u_xlat2.xyz = _GUIBlendingSharedGT.Sample(sampler_GUIBlendingSharedGT, u_xlat2.xz).xyz;
    u_xlat3.xyz = (-u_xlat2.xyz) + float3(1.0, 1.0, 1.0);
    u_xlat1.xyz = mad((-u_xlat3.xyz), u_xlat5.xyz, float3(1.0, 1.0, 1.0));
    u_xlat13 = dot(u_xlat2.xx, u_xlat0.yy);
    u_xlatb3.xyz = (float3(0.5, 0.5, 0.5)<u_xlat0.yzw);
    output.SV_Target0.x = (u_xlatb3.x) ? u_xlat1.x : u_xlat13;
    u_xlat4.x = dot(u_xlat2.yy, u_xlat0.zz);
    u_xlat4.y = dot(u_xlat2.zz, u_xlat0.ww);
    output.SV_Target0.w = u_xlat0.x;
    output.SV_Target0.y = (u_xlatb3.y) ? u_xlat1.y : u_xlat4.x;
    output.SV_Target0.z = (u_xlatb3.z) ? u_xlat1.z : u_xlat4.y;
    return output;
}

#endif
            ENDHLSL
        }
    }
    Fallback "UI/Default"
}
